### ISSUE TITLE
Inconsistent use of UA_malloc/UA_free vs. malloc/free

### ISSUE THREAD

**Issue by asthomas** [open62541/open62541#1000]
Description
===========

There are several places where the code calls malloc, free, calloc and realloc directly instead of calling UA_malloc, UA_free, UA_calloc and UA_realloc.  In some cases memory is allocated with UA_malloc and freed with free.  It would make replacing the malloc implementation easier if all memory management used the UA_* functions.

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version (release number or git tag): 0.2
 - [ ] Operating system: any

**Comment by jpfr** [comment]
Fixed. Thanks for reporting this.
