### ISSUE TITLE
Can not Creating object instances

### ISSUE THREAD

**Issue by sunwenfeng** [open62541/open62541#1025]
Description
===========

I have successfully created the FIELDDEVICE object type, now I try to run the Creating object instances follow the tutorial. I changed my code with reference to the answer of Yangxinyu. After running `gcc -g -std=c99 -Wl,-rpath,'pwd' -I ./include -L . -DUA_ENABLE_METHODCALLS -o pump_instance ./pump_instance.c -lopen62541`, the instance pump1 did not create , can you tell me how you running the code ? What should I do before running? @Yangxinyu

Before this step, My running situation and output is same with  the description in Creating object instances not support inheritance #673, the only difference is that the open62541 version  I used is open62541-0.2-rc2.

THANKS！

**Comment by Pro** [comment]
Hi @sunwenfeng, thanks for your question.

Can you try to use the most current version from git:
https://github.com/open62541/open62541/tree/0.2

Can you also post example code how you are creating the object type and object instances. Even better if you could post a minimum working example code (https://stackoverflow.com/help/mcve)

**Comment by jpfr** [comment]
Hello @sunwenfeng ,

did you add a reference to make the content of the object mandatory?
See also the tutorial here: https://open62541.org/doc/current/tutorial_server_object.html#object-types-type-hierarchies-and-instantiation

**Comment by YangXinyu** [comment]
Hello @sunwenfeng ,
i hope you can try the current version or you can try the released version : 
[https://github.com/open62541/open62541/tree/v0.2.0-RC1](url)

it works, i guess.
