### ISSUE TITLE
Could open62541 communicate with kepserver ?

### ISSUE THREAD

**Issue by Eric-918** [open62541/open62541#1029]
I am new to opc ua , but I have some experience on c/c++, now I want to write a client to communicate with kepserverex 5, could open62541 meet my needs ?
thanks.

**Comment by Pro** [comment]
open62541 implements client functionality so you can definitely use it to communicate with other OPC UA servers. Currently encryption is not supported, but will be added in the next months.
See http://open62541.org/doc/current/tutorial_client_firststeps.html
