### ISSUE TITLE
Crashed at end of lifetime for subscription

### ISSUE THREAD

**Issue by JinGuoGe** [open62541/open62541#1030]
Hi
open62541 version tag - 11b729df23 (https://open62541.org/releases) 
I am using https://github.com/comtel2000/opc-ua-client for OpcUaClient.
I am using twp pcs for test. - One is for comtel2000 OPCUaClient, and then the other is for open62541 based OPCUaServer.
Open62541 is running in Ubuntu environment.

In OPCUaClient side, i sent monitor request

![image](https://cloud.githubusercontent.com/assets/15504060/25769408/936efb78-324b-11e7-8d1d-d3598837e850.png)

Then, i plugged off network of open62541 running pc.
After some times (about 5min), then open62541 is crashed with following gdb track.

```
Starting program: /home/osboxes/Work/OPC_UA/open62541/serverAPI_test 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5c87700 (LWP 29498)]
[New Thread 0x7ffff6488700 (LWP 29497)]
[New Thread 0x7ffff6c89700 (LWP 29496)]
[New Thread 0x7ffff748a700 (LWP 29495)]

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff6c89700 (LWP 29496)]
0x00007ffff74c0267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  0x00007ffff74c0267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff74c1eca in __GI_abort () at abort.c:89
#2  0x00007ffff7503c53 in __libc_message (do_abort=do_abort@entry=1, 
    fmt=fmt@entry=0x7ffff761c1a8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff750c391 in malloc_printerr (ptr=<optimised out>, str=0x7ffff76182dd "corrupted double-linked list", action=1)
    at malloc.c:4965
#4  _int_free (av=0x7fffec000020, p=<optimised out>, have_lock=0) at malloc.c:3981
#5  0x00007ffff750f89c in __GI___libc_free (mem=<optimised out>) at malloc.c:2950
#6  0x00007ffff7a904df in UA_Array_delete (p=0x7fffec0a4ff0, size=145, type=0x7ffff7cd12a0 <UA_TYPES+96>) at open62541.c:5770
#7  0x00007ffff7a90218 in deleteMembers_noInit (p=0x7fffec0f2fe8, type=0x7ffff7cd14e0 <UA_TYPES+672>) at open62541.c:5693
#8  0x00007ffff7a90269 in UA_deleteMembers (p=0x7fffec0f2fe8, type=0x7ffff7cd14e0 <UA_TYPES+672>) at open62541.c:5701
#9  0x00007ffff7a8b92f in UA_ByteString_deleteMembers (p=0x7fffec0f2fe8) at open62541.h:5524
#10 0x00007ffff7ab0ce3 in UA_MoniteredItem_SampleCallback (server=0x2a296e0, monitoredItem=0x7fffec0f2f60) at open62541.c:23669
#11 0x00007ffff7a9f268 in processJob (server=0x2a296e0, job=0x7fffec17f710) at open62541.c:17889
#12 0x00007ffff7a9f58d in processRepeatedJobs (server=0x2a296e0, current=5593478807825, dispatched=0x7ffff6c88ea5)
    at open62541.c:18081
#13 0x00007ffff7a9fc94 in UA_Server_run_iterate (server=0x2a296e0, waitInternal=true) at open62541.c:18423
```

When i used eclipse-milo sdk for opcUaClient, it happened same. 
Looking forward your help.
Thanks.

**Comment by jpfr** [comment]
Hello @JinGuoGe ,

I am unable to run comtel2000/opc-ua-client.

Neither of
- mvn clean install
- mvn clean compile assembly:single

produces a runable jar (Windows, Java 8, current Maven).
What is your setup to reproduce the issue?

**Comment by JinGuoGe** [comment]
Hi,
I just used Eclipse Mars for running comtel2000/opc-ua-client.
Just 3 steps.
1) Importing
![1](https://cloud.githubusercontent.com/assets/15504060/25798604/61324758-3414-11e7-8a9b-ef4960c5f8c9.png)
2)Selecting pom file
![2](https://cloud.githubusercontent.com/assets/15504060/25798605/62706d66-3414-11e7-8b3c-26f73f727381.png)
3)running
![3](https://cloud.githubusercontent.com/assets/15504060/25798648/8ee04290-3414-11e7-8649-5c44210dafb4.png)

**Comment by jpfr** [comment]
Hello @JinGuoGe ,

can you test with the current 0.2 branch?
Should be fixed by the latest commit.

**Comment by JinGuoGe** [comment]
Hi @jpfr 
Thanks for your revision.
It works well.
Very thank you.
