### ISSUE TITLE
Discovery Unit Tests fail on master

### ISSUE THREAD

**Issue by jpfr** [open62541/open62541#1035]
Description
===========

The discovery unit tests fails on the master branch.

https://paste2.org/j2N5bhZe

@Pro Do you have an intuition where this comes from?

Background Information / Reproduction Steps
===========================================

See here for the kinds of information we need to reproduce the bug and how to obtain it:
https://github.com/open62541/open62541/wiki/Writing-Good-Issue-Reports

Checklist
=========
Please provide the following information:

 - [ x] open62541 Version (release number or git tag): master
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ x] Operating system: Linux
 - [ x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
The reported error means `BadServiceUnsupported` so it looks like the code wasn't compiled with the `UA_ENABLE_DISCOVERY_MULTICAST` flag?

**Comment by jpfr** [comment]
Can we surround the unit tests that require `UA_ENABLE_DISCOVERY_MULTICAST` with the same #if macro?
It's not good to have some unit tests fail on travis. That leads to other regressions not being noticed.

**Comment by Pro** [comment]
Yes, that would be a good option, but currently `UA_ENABLE_DISCOVERY_MULTICAST` is always enabled for unit tests on travis:
https://github.com/open62541/open62541/blob/master/tools/travis/travis_linux_script.sh#L167

So that shouldn't be an issue here?

**Comment by jpfr** [comment]
Unit tests should never fail.
Independently of whether they are run on travis or locally.

**Comment by Pro** [comment]
Fixed in https://github.com/open62541/open62541/commit/cd665efcf34d5570731f3617e25f9c02d58172e4
