### ISSUE TITLE
Adding variable node fails when namespace index != 1

### ISSUE THREAD

**Issue by aleks-f** [open62541/open62541#1048]
Description
===========

Trying to add a variable node with namespace index different than `1` fails with
```
BadNodeIdInvalid: The syntax of the node id is not valid.
```

Background Information / Reproduction Steps
===========================================

Using the [server example](https://github.com/open62541/open62541/blob/v0.2/examples/server.cpp#L46), if I try to create a variable node with namespace index != 1, it will fail with the above error.

Am I missing something here?

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): 0.2
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: ubuntu 16.04
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Stasik0** [comment]
You need to call UA_Server_addNamespace

**Comment by aleks-f** [comment]
yes, that was it, thanks.
