### ISSUE TITLE
Links to single pair of header and source files need to be updated to 0.2

### ISSUE THREAD

**Issue by escherstair** [open62541/open62541#1059]
The official release 0.2 can be downloaded from [https://open62541.org/](https://open62541.org/) both as whole package and single-file distribution.
The links to download the single pair of header and source files are available on [https://github.com/open62541/open62541#open62541](https://github.com/open62541/open62541#open62541) too, but they point to the old v0.2.0-RC1 release.
I think these links need to be updated to official 0.2 release.

**Comment by jpfr** [comment]
Fixed via #1060 .
