### ISSUE TITLE
When unit tests dont compile, travis is all green.

### ISSUE THREAD

**Issue by Infinity95** [open62541/open62541#1063]
Description
===========

As the title says, travis is green, when the unit tests don't compile.
This can bee seen in PR #1003. This also happens in my [local repository on a pull request](https://travis-ci.org/Infinity95/open62541/builds/238804478?utm_source=github_status&utm_medium=notification)(see [here](https://travis-ci.org/Infinity95/open62541/jobs/238804479#L4805)), and also in my local branch.
I'd assume theres something wrong with the travis configuration maybe?

Background Information / Reproduction Steps
===========================================

Make a unit test not compile. Travis will (probably) stay green.

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): 6b3186ab5d6750f9ec6b2451b631d6b95abb7c63
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
Interesting...
I'll have a look at it in the following days. It definitely worked before that failed unit tests also caused failed travis builds.

**Comment by Infinity95** [comment]
Cool. Tell me if you need anything else concerning this.

**Comment by Pro** [comment]
Fixed in #1066
