### ISSUE TITLE
How to browse server

### ISSUE THREAD

**Issue by aleks-f** [open62541/open62541#1099]
Description
===========

I'm trying to find the proper (or simplest) way to browse the server.

Background Information / Reproduction Steps
===========================================

Looking at example, there are two ways:

- iterative, using `UA_Client_Service_browse()`
- callback, using `UA_Client_forEachChildNodeCall()`

However, the example will only display the top-level object nodes, it does not descend into lower levels (folders) to browse all nodes. The callback does not receive the client handle, so it seems that a combination of iteration and callback would be the way to go, but I'm wondering if there is a simpler way?

Thanks.

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): 0.2
 - [ ] Other OPC UA SDKs used (client or server):
 - [ ] Operating system: Linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Both `UA_Client_Service_browse` and `UA_Client_forEachChildNodeCall` only go level deep. That is, you see only the direct references of the current node.

There is a special `Query` service defined in the OPC UA standard. It provides more SQL like querying capabilities. But I am not aware of any vendor supporting it.
We have plans for making an implementation. But this will only happen in the long term.

Currently, you will have to iterate through several browse calls. Same as everybody else.
