### ISSUE TITLE
NodeSet compiler does not read custom references

### ISSUE THREAD

**Issue by XB32Z** [open62541/open62541#1105]
Description
===========
Hi All, 

I designed a model using UAModeler and exported as XML then used the code generator to compile it with the stack (on [master](https://github.com/open62541/open62541/tree/master)).
My model contained References from a custom ReferenceType but those were not exported from the xml to the nodeset. Are custom references handles by the compiler?  

The referenceType itself is exported, so I can construct the reference programmatically between the objects afterward. 

Thx for your help

Checklist
=========
Please provide the following information:

 - [master] open62541 Version ():
 - [ ] Other OPC UA SDKs used (client or server): 
 - [Windows] Operating system: Windows
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Stasik0** [comment]
could you just attach a minimal xml file?
