### ISSUE TITLE
Added types in datatypes_minimal.txt then got ACK message failed

### ISSUE THREAD

**Issue by averitas** [open62541/open62541#1108]
Description
===========
I am trying to add simple history access function into release 0.2. But when I add history related datatypes into **datatypes_minimal.txt**, all example run successfully except server.c. When I use example client connecting to it, I got:
in server side:
```
[07/11/2017 06:55:19.758] info/network  TCP network layer listening on opc.tcp://cloud:16664
[07/11/2017 06:55:23.754] info/network  Connection 4 | New connection over TCP from 127.0.0.1:60245
Segmentation fault (core dumped)
```
in client side:
```
[07/11/2017 06:55:23.873] info/network  Receiving ACK message failed
```
When I remove **loadCertificate** function in **server.c**, it works fine.

How can I fix it?

Background Information / Reproduction Steps
===========================================
Add 
```
HistoryReadValueId
HistoryReadResult
HistoryReadDetails
ReadEventDetails
ReadRawModifiedDetails
ReadProcessedDetails
ReadAtTimeDetails
HistoryData
ModificationInfo
HistoryModifiedData
HistoryEvent
HistoryReadRequest
HistoryReadResponse
HistoryUpdateDetails
HistoryUpdateType
PerformUpdateType
UpdateDataDetails
UpdateStructureDataDetails
UpdateEventDetails
DeleteRawModifiedDetails
DeleteAtTimeDetails
DeleteEventDetails
HistoryUpdateResult
HistoryUpdateRequest
HistoryUpdateResponse
EventFilter
AggregateConfiguration
AggregateFilter
MonitoringFilterResult
EventFilterResult
AggregateFilterResult
HistoryEventFieldList
Annotation
```
At the end of file **datatypes_minimal.txt**.

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): 0.2
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [x] Critical issue

**Comment by Pro** [comment]
@averitas can you verify if this still happens on master?

If yes can you use a debugger (e.g., gdb) to post the stacktrace of the Segmentation Fault?
