### ISSUE TITLE
Extend access control to allow encryption

### ISSUE THREAD

**Issue by mlgiraud** [open62541/open62541#1112]
Description
===========
The CTT fails on test 10, Secuirty User Name Password:
![grafik](https://user-images.githubusercontent.com/1338425/28213867-38299be0-68a8-11e7-91b2-b4fd877867ca.png)

The expected result is Bad_IdentityTokenInvalid, since the encryption algorithm is expected to be null, but a garbage algorithmUri is supplied.

I think this plugin will need some reworking, as soon as we have the first security policy.

Background Information / Reproduction Steps
===========================================
Checkout 20440bcd6b73a92270e3a4a85b493641558c0037 and run the ctt.

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): 20440bcd6b73a92270e3a4a85b493641558c0037
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Windows 10
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Infinity95** [comment]
#1113 is a quick fix of this. This will only work for a user token policy that does not encrypt (as it is currently).

**Comment by jpfr** [comment]
Merged. Will there be a "complete" solution once we have encryption?

**Comment by Infinity95** [comment]
Once we have the first security policy for encryption (not only the plugin api), the accesscontrol can and should be expanded to allow encryption. Then we also have to extend those checks to conform with the standard.

**Comment by Pro** [comment]
Related to #934 (or duplicate?)

**Comment by jpfr** [comment]
The client supports this on master.
Server-side support is coming in #2390.
