### ISSUE TITLE
Implement VariableTypes from the DataAccess Spec (Part 8)

### ISSUE THREAD

**Issue by jpfr** [open62541/open62541#1121]
> The DataAccess model extends the variable model by defining VariableTypes. The
> DataItemType is the base type. ArrayItemType, AnalogItemType and DiscreteItemType (and its
> TwoState and MultiState subtypes) are specializations.

The DataAccess Spec is built on top of the core OPC UA functionality.
We can provide the DataAccess VariableTypes in open62541.
With a build-flag to make them optional.

**Comment by fmeerkoetter** [comment]
Can you please give a (short) outline what would need to be done?

**Comment by fmeerkoetter** [comment]
@Pro Can you provide an outline for this?

**Comment by Pro** [comment]
I'm not 100% sure what @jpfr means, maybe he can shed more light on it?

Probably adding the addtional datatypes which are mentioned in the spec. The datatypes in the NodeSet2.xml will be added anyways when using the new nodeset compiler in #739. So IMHO these "new" VariableTypes should already be there?

The corresponding spec can be found here:
https://opcfoundation.org/developer-tools/specifications-unified-architecture/part-8-data-access/

**Comment by Stasik0** [comment]
I think codesys rte provide a plcopen view. They run for 2 hours in a trial mode.

**Comment by Stasik0** [comment]
Wrong thread, sorry

**Comment by Pro** [comment]
@jpfr is this still an open issue or fixed by creating the corresponding nodes from the full NS0?

**Comment by jpfr** [comment]
This is done on master.
