### ISSUE TITLE
Client connect timeout

### ISSUE THREAD

**Issue by Pro** [open62541/open62541#1132]
Currently we do not define any timeout value for when a client connects to a server.
I.e. for the connect call here:
https://github.com/open62541/open62541/blob/master/plugins/ua_network_tcp.c#L657

This means that the connect to an invalid IP will time out after the default OS setting which is on linux around 130 seconds.

Shouldn't we use the timeout from `UA_ConnectionConfig` instead?

This could be implemented using a combination of select and non-blocking socket:
https://stackoverflow.com/a/2597774/869402

**Comment by StalderT** [comment]
+1

**Comment by jpfr** [comment]
👍
