### ISSUE TITLE
UA_THREAD_LOCAL defined even when UA_ENABLE_MULTITHREADING is disabled

### ISSUE THREAD

**Issue by cabralfortiss** [open62541/open62541#1136]
https://github.com/open62541/open62541/blob/master/src/ua_util.h#L26

Since `UA_THREAD_LOCAL` is used for making access to certain variables thread-safe, shouldn't this part be behind `UA_ENABLE_MULTITHREADING?`

**Comment by jpfr** [comment]
Fixed in #1136.
Thanks @cabralfortiss for reporting and to @Pro for the fix!
