### ISSUE TITLE
CTT on master fails 2

### ISSUE THREAD

**Issue by Infinity95** [open62541/open62541#1152]
Description
===========
The Compliance test tool fails on master in the afterTest.js test. See ![here](https://user-images.githubusercontent.com/1338425/29176177-64e4daac-7deb-11e7-8f2f-e0baf546fad6.png).

Background Information / Reproduction Steps
===========================================
Check out 5d5efc03d4484e7955757372a47274d0cbedbfd8 and run the CTT

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): 5d5efc03d4484e7955757372a47274d0cbedbfd8
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Windows 10
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
Is it this one?
https://github.com/open62541/open62541/blob/master/src/server/ua_services_discovery.c#L432

So server calls unregister even if it is not registered. 

This should then probably be `BadNothingToDo`. I'll check the spec and change it
