### ISSUE TITLE
Single file releases do not contain git-hashes

### ISSUE THREAD

**Issue by Stasik0** [open62541/open62541#1198]
Description
===========
hi

files open62541.h/.c i got from https://ci.appveyor.com/api/buildjobs/vwyktig442fa8pmh/artifacts/open62541-mingw-static.zip 
and
https://open62541.org/releases/303fd8d86a.zip

contain a line  `* Git-Revision: undefined`, but not the actual commit hash

**Comment by jpfr** [comment]
Good find!
Looks like a cmake thing.
That would be important to fix for landing a package in Fedora.
Eg. #1193, #1195 

The issue also impacts some macro definitions for version detection.
```c
/**
 * Library Version
 * --------------- */
#define UA_OPEN62541_VER_MAJOR 0
#define UA_OPEN62541_VER_MINOR 3
#define UA_OPEN62541_VER_PATCH 0
#define UA_OPEN62541_VER_LABEL "" /* Release candidate label, etc. */
#define UA_OPEN62541_VER_COMMIT "undefined"
```
