### ISSUE TITLE
open62541 is there an interface reserved for integrated SSL?

### ISSUE THREAD

**Issue by loujunang** [open62541/open62541#1200]
!ATTENTION!
Please read the following page carefully and provide us with all the
information requested:
https://github.com/open62541/open62541/wiki/Writing-Good-Issue-Reports

Use Github Markdown to format your text:
https://help.github.com/articles/basic-writing-and-formatting-syntax/

Fill out the sections and checklist below (add text at the end of each line).

Remove this text between the ATTENTION marks after reading it.
!ATTENTION!
--------------------------------------------------------------------------------

Description
===========

Background Information / Reproduction Steps
===========================================

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
You can follow #1187 for the SecurityPolicy interface.
We will then support encryption.
Note that the encryption of binary OPC UA protocol is not SSL (called TLS today).
It does however make use the same techniques and algrithms.

There are rumours concerning an upcoming TLS-encrypted transport layer for OPC UA.
But it has not been standardized so far.
