### ISSUE TITLE
Whether the project can be transplanted to the Ucos system, found a variety of header files could not be found

### ISSUE THREAD

**Issue by loujunang** [open62541/open62541#1204]

**Comment by jpfr** [comment]
Short answer.

Yes, open62541 can be ported. The core library has no external dependencies.
You will have to port some of the "plugins" in the /plugins folder.

A longer answer would depend on inside knowledge of the uCOS operating system.
Which we don't have.

Feel free to reopen the issue with upcoming technical questions.
