### ISSUE TITLE
0.3 release - open issues

### ISSUE THREAD

**Issue by Pro** [open62541/open62541#1205]
The 0.3 release is near.

There are currently the following open issues/pull requests which need to be merged.

The most important ones are:
- [x] Encryption plugin structure (#1003, #1187)
- [x] Basic encryption support
- [x] Nodeset plugin (#1168)
- [x] Nodeset compiler (#739)

Issues to close:
- [x] #1302

And here the full list:
https://github.com/open62541/open62541/milestones/0.3

After these are integrated a 0.3 release candidate will be published.

@open62541/open62541-core any more points you would like to add? Feel free to change the milestone tag of the issues.

**Comment by ccvca** [comment]
Should the async-Client (open62541:async_client_loop) be part of 0.3? If not, my issue (#1164) is not part of 0.3

**Comment by Pro** [comment]
@ccvca thanks, I just removed it from the milestone

**Comment by Pro** [comment]
See also #710

**Comment by ctron** [comment]
As already mentioned on the 4diac mailing list ... I would be interested in bringing version 0.3 of open62541 into Fedora 28 (instead of currently 0.2).

The easiest deadline for this would be 2018-02-20, also see [1]. It should be possible to use a release candidate build of open62541 for this and do an update later on.

[1] https://fedoraproject.org/wiki/Releases/28/Schedule

**Comment by jpfr** [comment]
Great to hear @ctron !
Given that the remaining features are nearly done in a PR, we could even aim for a v0.3.1 in Fedora 28.

**Comment by Infinity95** [comment]
You could maybe add encryption support for the client to the list. Although the none policy currently works with the client, there will be some changes necessary in order for full encryption to work.
This currently has low priority on my list of todo's (first unit tests, a working Basic128Rsa15 policy and then a plugin structure for certificate validation). If you want me to prioritize anything other first, tell me 😃

**Comment by sirop** [comment]
@Infinity95 
Is there a case of encrypted password sent to the server through non encrypted channel? As in https://github.com/open62541/open62541/issues/788#issuecomment-293891197 ?

**Comment by Infinity95** [comment]
That isn not implemented yet.

**Comment by Pro** [comment]
Closing as all the referenced features are in master.
0.3 release is near. As soon as all the open issues/PRs marked with 0.3 milestone are fixed we will release a Release Candidate.
We expect it to be within mid of February (and would appreciate any help on closing the remaining issues)
