### ISSUE TITLE
UA_Server_addDataSourceVariableNode() always returns UA_STATUSCODE_GOOD

### ISSUE THREAD

**Issue by jonasgreen88** [open62541/open62541#1226]
Hi,

I wonder why UA_Server_addDataSourceVariableNode() is implemented to always return UA_STATUSCODE_GOOD. Wouldn't it be good to get feedback if something fails when creating a data source variable node?

https://github.com/open62541/open62541/blob/2113ec1c9b4a96a17e1a8ee98952a71475911712/src/server/ua_services_nodemanagement.c#L966

I found that the function was changed to this behavior when fixing a memory leak in commit 72b0afbe7db885c381946e7782477aa05f81362d. But I'm not sure if the intention was to also change to always return success?

**Comment by Pro** [comment]
Oh, yes, that is my fault. It should return `retval`

**Comment by Pro** [comment]
Will be fixed with #1227

**Comment by jonasgreen88** [comment]
Thanks!
