### ISSUE TITLE
Add self signed certificates for opc client to communicate

### ISSUE THREAD

**Issue by bgshankars** [open62541/open62541#1232]
Description
===========
I am developing a opc client application to access the kepware opc server. Since the server enabled the encryption and certificates, I can't hit my server. How can i include the opc client to use the certificates which I have exported from the server.

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version (release number or git tag): v0.2
 - [ ] Operating system: Ubuntu 16

**Comment by Pro** [comment]
Client side encryption is not yet supported. For further discussion see #1539
