### ISSUE TITLE
No module named six

### ISSUE THREAD

**Issue by syvaren** [open62541/open62541#1250]
Description
===========
I am getting the following build errors out of the latest master commits.  Any ideas on what I'm missing?
![builderrors](https://user-images.githubusercontent.com/27020375/31565172-6e25f9e4-b02b-11e7-9015-269a8d8e5dd0.jpg)

Background Information / Reproduction Steps
===========================================

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version (release number or git tag): 0.3
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system: Debian 7
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
We had to add an additional dependency for python.

`pip install six`

See https://stackoverflow.com/questions/21990581/how-to-install-the-six-module-in-python2-7 or other sources, e.g. google for `ImportError: No module named six`

**Comment by syvaren** [comment]
@Pro 

Thanks for the fix, there is still the warning newEntry shadowing a global variable that is treated as an error due to -Werror in the flags files.  I removed it to get past it, but is this a known issue?

**Comment by Pro** [comment]
Ah interestingly this wasn't detected by the CI/Travis.
Anyways, it's fixed now in master with https://github.com/open62541/open62541/commit/c86c8e833f2e0911f64727a059a87a6f3102bb6b

**Comment by syvaren** [comment]
@Pro 
Thanks!

**Comment by jpfr** [comment]
Hey @Pro ,

can we add the dependency on python-six to /doc/building.rst?
Otherwise, these kinds of issues will continue to crop up.

**Comment by syvaren** [comment]
@Pro I think this is fixed now, I no longer see the shadowing variable error, and I saw a commit that said it added installing six in the guide.
