### ISSUE TITLE
Additional nodes with the nodeset compiler

### ISSUE THREAD

**Issue by santoshpanda1989** [open62541/open62541#1257]
Description
===========
I built and ran the server_nodeset example with the server_nodeset.xml. In the example XML file there is only one variable under "testinstance" object but in the client application, I can see an additional variable.  PFA the screenshot
![screen_shot_prosys](https://user-images.githubusercontent.com/19244975/31641059-8158296a-b2e2-11e7-98ec-8ff6b8e563fa.png)
 of the same.

Background Information / Reproduction Steps
===========================================

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): Master
 - [x] Other OPC UA SDKs used (client or server): Prosys OPC UA Client
 - [x] Operating system: OSX
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by santoshpanda1989** [comment]
Is it a mistake from my end or is it a genuine issue? I searched for the extra NodeId in the generated code but could not find it.

**Comment by Pro** [comment]
I think this is desired behaviour @jpfr ?

In the .xml there is the following (simplified) structure:
```
testType (ObjectType, i=1001) -> HasComponent -> Var1 (Variable, i=6001)

testInstance (Object, i=5001) -> HasTypeDefinition -> testType
testInstance (Object, i=5001) -> HasComponent -> Var1 (Variable, i=6002)
```

So this means when the testInstance is created, the Var1 (i=6001) is instanciated from the type as a mandatory child.
Then an additional variable is added as Var1 (i=6002).

Maybe we should change the name of i=6002 to Var2?

**Comment by Pro** [comment]
I think this issue can be closed since it is intended behaviour.

Anyways I changed the name of the second Var1 to Var2.
See
https://github.com/open62541/open62541/commit/add1b806ac173ca4bd0a26746be460617803a2df
