### ISSUE TITLE
Read Node Class fails because return type is Int32 not Node Class

### ISSUE THREAD

**Issue by bazza2jw** [open62541/open62541#1262]
Description
===========
When __UA_Client_readAttribute is used to read a node's class id it fails with   UA_STATUSCODE_BADUNEXPECTEDERROR.

The reason is that the variant value returned is of type UA_TYPES_INT32 not UA_TYPES_NODECLASS, though the value is correct. It appears the problem is in the encoding of the response by the server. The UA_NodeClass encode and decode methods are not called.

A workaround is to get __UA_Client_readAttribute treat UA_TYPES_NODECLASS as equivalent to UA_TYPES_INT32. 

Background Information / Reproduction Steps
===========================================

Code example

bool nodeClass(const UA_NodeId &nodeId, UA_NodeClass &c) {
                if (!_client) throw std::runtime_error("Null client");
                UA_NodeClass_init(&c);
                _lastError = UA_Client_readNodeClassAttribute(_client, nodeId, &c);
                return _lastError == UA_STATUSCODE_GOOD;
            }

Checklist
=========
Please provide the following information:

 - [0.2 ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ Linux] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
This is fixed in https://github.com/open62541/open62541/pull/1176/commits/6ae9c485e126c62254f14f641900706ede072d45
