### ISSUE TITLE
Setting DataType by UA_Variant_setScalar

### ISSUE THREAD

**Issue by adliner** [open62541/open62541#1270]
Description
===========
Hi,
we can indicate data type by using UA_Variant_setScalar() like in the example code below:

```
    /* Add a variable node */
    /* 1) Define the node attributes */
    UA_VariableAttributes attr;
    UA_VariableAttributes_init(&attr);
    attr.displayName = UA_LOCALIZEDTEXT("en_US", "the answer");
    UA_Int32 myInteger = 42;
    UA_Variant_setScalar(&attr.value, &myInteger, &UA_TYPES[UA_TYPES_INT32]);

    /* 2) Define where the node shall be added with which browsename */
    UA_NodeId newNodeId = UA_NODEID_STRING(1, "the.answer");
    UA_NodeId parentNodeId = UA_NODEID_NUMERIC(0, UA_NS0ID_OBJECTSFOLDER);
    UA_NodeId parentReferenceNodeId = UA_NODEID_NUMERIC(0, UA_NS0ID_ORGANIZES);
    UA_NodeId variableType = UA_NODEID_NULL; /* take the default variable type */
    UA_QualifiedName browseName = UA_QUALIFIEDNAME(1, "the answer");

    /* 3) Add the node */
    UA_Server_addVariableNode(server, newNodeId, parentNodeId, parentReferenceNodeId,
                              browseName, variableType, attr, NULL, NULL);
```

but having a look at the variable in UaExpert we can see data type set to BaseType, not to Int32:

![image](https://user-images.githubusercontent.com/8227441/31862998-b101ba82-b747-11e7-94d4-aced427cda6f.png)

Is this an intended behaviour? If it is - then how are supposed to set DataType field that we see in UaExpert. I've had a walk through the code but I'm not quite sure its intentions.

We could achieve this by simply:
attr.dataType = attr.value.type->typeId;

but shouldn't this be performed by UA_VariableAttributes_init() or UA_Variant_setScalar()?

**Comment by jpfr** [comment]
Hey @adliner ,

the datatype attribute is a constraint for the value attribute.
For example, if you set the datatype to `numeric`, the value needs to be int32, int64, float, ...
This comes out of the hierachy of the datatypes in the information model.
The BaseDataType is the most permissive constraint. It allows you to set any value.
