### ISSUE TITLE
UA_ReadValueId with UA_Array_new problem

### ISSUE THREAD

**Issue by WoutvdBerg** [open62541/open62541#1271]
Description
===========
In c++ when trying to add a new array to nodesToRead this error returns:
error: assigning to 'UA_ReadValueId *' from incompatible type 'void *'
It expects a UA_ReadValueId but it isn't, in C on Xcode no problem but with c++ on Netbeans it doesn't work.

Background Information / Reproduction Steps
===========================================

Os X, netbeans C++ 

UA_ReadRequest rReq;
UA_ReadRequest_init(&rReq);
rReq.nodesToRead = UA_Array_new(10, &UA_TYPES[UA_TYPES_READVALUEID]);
rReq.nodesToReadSize = 10;

Checklist
=========
Please provide the following information:

 - [ X] open62541 Version (release number or git tag): 0.2
 - [ ] Other OPC UA SDKs used (client or server): 
 - [X ] Operating system: Mac OS x
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Hey there,

In C++ you need to cast the pointer.
```c
 rReq.nodesToRead = (UA_ReadValueId*)UA_Array_new(10, &UA_TYPES[UA_TYPES_READVALUEID]);
```
