### ISSUE TITLE
SecureChannel Unit Tests

### ISSUE THREAD

**Issue by jpfr** [open62541/open62541#1296]
We currently have no dedicated unit tests for the securechannel.
Without unit tests, we risk regressions and non-conformant behaviour in edge cases.
Especially since the securechannel failure modes interact with the connection, the server, the client, etc.

PR #1295 adds the possibility to manually trigger failure modes via special hooks that are only defined with a compile flag for non-production builds. Together with the custom network layer for testing and the custom clock for testing, we can now reproduce nearly all failure modes in unit tests.

@Infinity95 You talked about unit tests for the encryption layer. This issue is highly related to that.

**Comment by Infinity95** [comment]
I could focus on first writing some unit tests for the SecureChannel before getting to work on the certificate plugin. I guess that would be better to avoid regressions like you said.

**Comment by jpfr** [comment]
#1284 contains a candidate for a connection-related unit test....

**Comment by Infinity95** [comment]
Unit tests for the SecureChannel are now WIP on this branch:https://github.com/Infinity95/open62541/tree/feature/unit-tests/securechannel

**Comment by jpfr** [comment]
Nice!
If you want, you can open a PR marked as WIP in the title.

**Comment by Infinity95** [comment]
Done: #1336

**Comment by jpfr** [comment]
Closing this as the PR is ready.

**Comment by Infinity95** [comment]
I would prefer if we leave this issue open, since that PR at the moment doesn't test all of the SecureChannel. I just want to merge the tests in bit by bit, so we can avoid regression quicker. Currently only the sendAsymmetricOPNMessage function and a few helpers are really tested.
The receiving function and the send Symmetric function haven't been tested yet.

**Comment by jpfr** [comment]
ok.
