### ISSUE TITLE
can't write value with opcfoundation UA Sample Client

### ISSUE THREAD

**Issue by StalderT** [open62541/open62541#1317]
Description
===========

can't write value with opcfoundation UA Sample Client

https://opcfoundation.org/developer-tools/developer-kits-unified-architecture/sample-applications

Background Information / Reproduction Steps
===========================================

compile open62541 with UA_BUILD_SELFSIGNED_CERTIFICATE

start sample server and connect with opcfoundation UA Sample Client

![1](https://user-images.githubusercontent.com/13799456/32487015-ae78eb60-c3a8-11e7-8281-64b34fc2aec8.PNG)

When I try to write a new value for the.answere I have the error "EXCEPTION (ArgumentOutOfRangeException)"

![2](https://user-images.githubusercontent.com/13799456/32487027-b71c5ed2-c3a8-11e7-9318-3e072953b929.PNG)

If I display attributes, I have : 

![3](https://user-images.githubusercontent.com/13799456/32487065-ddec91a8-c3a8-11e7-847b-f213fb2e2c6d.PNG)

Do we have a problem with "ArrayDimensions" field ?

Checklist
=========
Please provide the following information:

 - [x] open62541 Version master
 - [x] Other OPC UA SDKs used : opcfoundation UA Sample Client
 - [x] Critical issue

**Comment by Pro** [comment]
This definitely looks fishy...
Does it work on UA Expert? What does it show there for ArrayDimensions?

**Comment by StalderT** [comment]
With UaExpert I can write and I have :

![1](https://user-images.githubusercontent.com/13799456/32489518-99247498-c3b0-11e7-8849-74e0f2cfa8f5.PNG)

----------

With Siemens OPC UA .NET Client I can write and I have (ArrayDimensions???) : 

![2](https://user-images.githubusercontent.com/13799456/32489552-b02af536-c3b0-11e7-826c-a9bee73a1c39.PNG)

----------

opcfoundation UA Sample Client try to edit value as a string. It's probably a bug in the client.

![3](https://user-images.githubusercontent.com/13799456/32489874-8dbd7e32-c3b1-11e7-9b63-0e4aa30f748c.PNG)

**Comment by StalderT** [comment]
Can I close the issue, or someone would like to add something about the ArrayDiemensions ?

**Comment by Pro** [comment]
Before closing this, we should find out why the OPC UA Sample Client is erroring with `ArgumentOutOfRangeException` and if it is a fault in our stack or the client.

**Comment by StalderT** [comment]
works if we specify a dataType
e.g. : ```myVar.dataType = UA_TYPES[UA_TYPES_INT32].typeId;``` for ```the answer``` node.
