### ISSUE TITLE
Writing part of structure

### ISSUE THREAD

**Issue by WoutvdBerg** [open62541/open62541#1365]
Description
===========
Is there a "indexRange" equivalent for structures?

for example:
structure: myDemoStructure
-UA_Boolean myFirstVarinDemoStructure
-UA_Int32 mySecondVarInDemoStructure
-UA_String myThirdVarinDemoStructure

I want to write myThirdVarInDemoStructure without changing the other vars.

Now I read the valueAttribute and change the data and write the changed data. Problem is when data is changed between the readRequest and writeRequest the value changes back to the `old` value.

read mySecondVarInDemoStructure: 5
mySecondVarInDemoStructure = 6;
write structure (intended: myThirdVarinDemoStructure: "DemoTextAfterWrite", not-intended: mySecondVarInDemoStructure: 5)

read mySecondVarInDemoStructure: 5 (should be 6)

**Comment by jpfr** [comment]
No. The standard does not define an "indexRange" for structures.
We could add something for local server-side users.
But there are no current plans to do it.
