### ISSUE TITLE
best way to write different size string

### ISSUE THREAD

**Issue by WoutvdBerg** [open62541/open62541#1425]
I have a question about writing string's in array/structures:

Currently I am retrieving the value attribute from a node. This is stored in a variant.
If it's a custom datatype I get the data from the extensionObject. 
If it's a array of string I get the data at the right index with a UA_Array.

This data is changed with the data I want to write. Problem is string size = 4 bytes + length of string.
If new data is smaller, the data after the string needs to be shifted to the left. If new data is bigger, data has to be shifted to the right.

Shifting data to left is not a problem but shifting to the right causes problems because of overflow.

After datachange, I write the variant back to the server. For all used datatypes (integers, bytes, float, doubles) it works because size of data is same.
My solution will be allocate memory, if its data is changed reallocate. 
Are there better solutions?

Does UA_Array store the different indexes information right after each other or is there space/extra information between? So an UA_Array of int32 [0] 4 bytes, [1] 4 bytes or  [0] 4 bytes, [extra information x bytes], [1] 4 bytes?

**Comment by Pro** [comment]
To answer your last question first, UA_Array simply stores the data in one memory block without any additional info. So if you create a UA_Array of 3 int32 it will simply describe a memory block of 3*4=12 bytes. `mem = malloc(3*sizeof(int32))`. No additional information is required here.

A UA_Array of type UA_String will not be one block of strings, but rather the following layout:

The UA_String struct is:
```c
{
    size_t length;
    UA_Byte* data;
}
```
The memory size of `size_t` is 8 byte, and the pointer to `UA_Byte*` is also 8 byte (at least on a 64bit machine).

So an array of 4 strings is in total 4*16 byte and looks like this on the memory:
`[SIZE, PTR_TO_DATA], [SIZE, PTR_TO_DATA], [SIZE, PTR_TO_DATA]`

The proper string content is in a different memory block which is pointed by `PTR_TO_DATA`.

So to change the string within a string array you can simply swap the pointer and adjust the length parameter. Don't forget to free the old string content.
