### ISSUE TITLE
Query Size and Type of Input/Output Arguments of a Mehtod

### ISSUE THREAD

**Issue by gerdBert** [open62541/open62541#1434]
Description
===========
I am not sure how handle a method call when the size and type of input and output arguments is not known by the client that is connected to a server.
Is it possibel to query the size and type of the input and output arguments somehow?
Is possible to modify UA_Client_call so that it fullfills this job?
Or must this information be provided in the description of the method on server side?

Background Information / Reproduction Steps
===========================================
```c
UA_Client_call(UA_Client *client, const UA_NodeId objectId,
  const UA_NodeId methodId, size_t inputSize,
  const UA_Variant *input, size_t *outputSize,
  UA_Variant **output)

```

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version (release number or git tag): v0.2
 - [ ] Operating system: Win10x64

**Comment by jpfr** [comment]
Yes. You can query the arguments of the method.
There are two variables called "InputArguments" and "OutputArguments" below the method node.
They contain an array of the arguments: Type, ValueRank and ArrayDimensions (see the VariableNode docs for what these mean).
