### ISSUE TITLE
client delete/disconnect, secure channel related?

### ISSUE THREAD

**Issue by WoutvdBerg** [open62541/open62541#1443]
Description
===========
Total edit:

Using the connect example and breaking the connection results in malloc error.
Also not breaking cable with current master results in malloc error.

Program breaks on UA_Client_delete and _disconnect. I think because of the secure channel changes made since 0.3

Reverted back to 0.2 stable and it worked there.

Wireshark:
[readrequest in closesessions requests.pcapng.zip](https://github.com/open62541/open62541/files/1547229/readrequest.in.closesessions.requests.pcapng.zip)
lldb: 
![schermafbeelding 2017-12-11 om 09 57 19](https://user-images.githubusercontent.com/31468040/33824055-651da3b4-de5d-11e7-9bc6-a655e2bfeed6.png)
Background Information / Reproduction Steps
===========================================
reconnecting example
Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): current master
 - [x] Other OPC UA SDKs used (client or server):  Siemens PLC/uaCppServer
 - [x] Operating system: OS X
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [x] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by StalderT** [comment]
Can you provide the line 17752 of your actual open62541.c file ?

Can you try with https://github.com/open62541/open62541/pull/1444 ?

**Comment by WoutvdBerg** [comment]
It has to do with the remoteNonce.

UA_ByteString_deleteMembers(&channel->remoteNonce);

If I comment this out and try to reconnect it also fails on the remoteNonce but in 
processDecodedOPNResponse - >
UA_ByteString_deleteMembers(&client->channel.remoteNonce);

With #1444 it just goes by disconnectWhenFaulted but still crashes.

**Comment by StalderT** [comment]
And if you comment ```UA_ByteString_deleteMembers(&response->serverNonce);
``` in ```processDecodedOPNResponse``` ?

**Comment by WoutvdBerg** [comment]
With 
`UA_ByteString_deleteMembers(&client->channel.remoteNonce);` Commented out it works (with comment in UA_SecureChannel_deleteMembersCleanup)

` UA_ByteString_deleteMembers(&response->serverNonce);` commented only results in malloc error

**Comment by StalderT** [comment]
Can you try to only replace 

```client->channel.remoteNonce = response->serverNonce;```

 by

```UA_ByteString_copy(&response->serverNonce, &client->channel.remoteNonce);``` 

in ```processDecodedOPNResponse```

```
    /* Replace the nonce */
    UA_ByteString_deleteMembers(&client->channel.remoteNonce);
    UA_ByteString_copy(&response->serverNonce, &client->channel.remoteNonce);
//    client->channel.remoteNonce = response->serverNonce;
    UA_ByteString_deleteMembers(&response->serverNonce);
```

**Comment by WoutvdBerg** [comment]
uncommented the 2 lines and tested with the copy.
It works! Perfect. 
This was btw the error that you couldn't reproduce. So that's solved.
Thanks

**Comment by StalderT** [comment]
@WoutvdBerg can you check with the new commit on the PR : https://github.com/open62541/open62541/pull/1446/commits/200e951c5ff03bbf465b209ccc9c4aee216f635e ?

**Comment by WoutvdBerg** [comment]
@StalderT, works. 

Is intended to return goodnoncriticaltimeout at readValueAttribute and a broken connection instead of badconnectionclosed?

**Comment by StalderT** [comment]
@WoutvdBerg Thanks for testing the commit.

Sorry, but I did not understand your question. Could you please give some additional information.

**Comment by WoutvdBerg** [comment]
@StalderT, the statuscode returned from readvalueattribute is now GOODNONCRITICALTIMEOUT instead of BADCONNECTIONCLOSED when cable is not plugged in between server and client.

**Comment by StalderT** [comment]
I understand. I will check
