### ISSUE TITLE
closeSession between packets reassemble

### ISSUE THREAD

**Issue by WoutvdBerg** [open62541/open62541#1458]
Description
===========
When browsing a node with a lot of references to nodes there is a session close request between the network packets.

The problem occurs in __UA_Client_Service and fails because UA_Client_disconnect is called because UA_STATUSCODE_GOODNONCRITICALTIMEOUT is returned from receiveServiceResponse.
Disabling the: `if(now >= maxDate) ` return results in a good read/browse.

Background Information / Reproduction Steps
===========================================
browse request with 4 times a node with 1500 nodes.
Packet reassembling is good but there is a random close session request.

Program: 
https://pastebin.com/raw/Lbt9g2vh
loglevel 100: 
https://pastebin.com/raw/wAHNc7Aj
wireshark:
[closesessionrequest.pcapng.zip](https://github.com/open62541/open62541/files/1558774/closesessionrequest.pcapng.zip)

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): current master
 - [x] Other OPC UA SDKs used (client or server): Siemens
 - [x] Operating system: OS X
 - [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [x] Wireshark network dump attached
 - [x] Self-contained code example attached
 - [ ] Critical issue

**Comment by StalderT** [comment]
Have you set a timeout of one second?

If yes, can you try to increase the value of the timeout? According to the wireshark logs, your PLC takes about 1.16 seconds to answer completely.

**Comment by WoutvdBerg** [comment]
I found out this morning, it's right. PLC is pretty slow. I am testing at the moment where the break comes from.

**Comment by StalderT** [comment]
can you try : 

```
--- a/src/client/ua_client_connect.c
+++ b/src/client/ua_client_connect.c
@@ -502,15 +502,17 @@ UA_StatusCode
 UA_Client_disconnect(UA_Client *client) {
     /* Is a session established? */
     if(client->state == UA_CLIENTSTATE_SESSION){
-        client->state = UA_CLIENTSTATE_SESSION_DISCONNECTED;
+        client->state = UA_CLIENTSTATE_UA_CLIENTSTATE_SECURECHANNEL;
         sendCloseSession(client);
     }
     UA_NodeId_deleteMembers(&client->authenticationToken);
     client->requestHandle = 0;
 
     /* Is a secure channel established? */
-    if(client->state >= UA_CLIENTSTATE_SECURECHANNEL)
+    if(client->state >= UA_CLIENTSTATE_SECURECHANNEL){
+        client->state = UA_CLIENTSTATE_CONNECTED;
         sendCloseSecureChannel(client);
+    }
 
     /* Close the TCP connection */
     if(client->state >= UA_CLIENTSTATE_CONNECTED)
```

**Comment by StalderT** [comment]
https://github.com/open62541/open62541/pull/1444 should also correct the problem

but can you before testing only the diff without the PR?

**Comment by WoutvdBerg** [comment]
First one doesn't work. #1444 does, but connection closes, is this intended behavior?

**Comment by StalderT** [comment]
Still crash with the first one? Can you send the debugger log with the first one?

**Comment by StalderT** [comment]
What do you have on line 17752 of the file open62541.c?

**Comment by WoutvdBerg** [comment]
`UA_ByteString_deleteMembers(&channel->remoteNonce);`

debugger: https://pastebin.com/raw/TGkMG7aJ

**Comment by StalderT** [comment]
same error as https://github.com/open62541/open62541/issues/1443

**Comment by WoutvdBerg** [comment]
Yes, but I think this time caused by calling 2 times client_disconnect.

**Comment by WoutvdBerg** [comment]
Also occurs when the secure channel needs to be renewed when 75% of time has passed.
