### ISSUE TITLE
intention of low maxNotificationPerPublish

### ISSUE THREAD

**Issue by WoutvdBerg** [open62541/open62541#1462]
What is the intention of the standard 10 maxNotificationPerPublish in UA_SubscriptionSettings_Default?

I'm running a server on a PLC, which aren't fast but with the low maxNotificationPerPublish it makes the communication even worse.

**Comment by jpfr** [comment]
This default seems low indeed.
Feel free to propose a PR where the default is increased.
Or, if possible, set it to zero to allow any number of notifications.

**Comment by WoutvdBerg** [comment]
@jpfr, like this?

**Comment by jpfr** [comment]
Cool, issue resolved.
