### ISSUE TITLE
Missing implementation of UA_Server_call method

### ISSUE THREAD

**Issue by Spidey86** [open62541/open62541#1463]
Hi,

I'm using the 0.2 version amalgamated file and found that the UA_Sever_call method is included in the .h file but it is missing in the .c file. Is this method implemented or something weird may happened when compiling the file?

Thanks

**Comment by jpfr** [comment]
Implemented in #1465.
Drops when the PR is green.

**Comment by Spidey86** [comment]
Great! Thanks @jpfr
