### ISSUE TITLE
Malloc/free with O(1) runtime

### ISSUE THREAD

**Issue by jpfr** [open62541/open62541#147]
Hey guys,

look at this:
- http://www.gii.upv.es/tlsf/
- https://github.com/emeryberger/Malloc-Implementations/tree/master/allocators/TLSF/TLSF-2.4.6

Malloc und free in O(1). No loops, no recursion, no goto. With ~180 instructions per malloc. The max memorypool size is 2GB. More than enough for small and embedded applications.

Possibilities:
- Enable the TLSF malloc with a build switch (the code is LGPL)
- Since the memory pool might run full, we could test with a malloc that fails (returns NULL) with a small probability. The code should not crash but return errors.

**Comment by andysargent** [comment]
Just a note that we are using this on a uCLinux environment, so malloc is an interesting subject given the lack of MMU support under uCLinux.

**Comment by Stasik0** [comment]
@andysargent so you got it included in the build?

**Comment by NetoLe** [comment]
well, even if it's older, I would just say that I am using tlsf with the stack. just include the tlsf-header and use the UA_malloc-defines for defining them and it works. of course you need to do memory-pool allocation at another point somewhere but that should be easy. 
The using purposes for me are using the open62541-Stack out of an C++-environment and there the memory-pool is initialized by the class(which encapsulates the Stack)-constructor and that's it. 
In that point it would be usefull to implement "UA_malloc" etc. into the network_tcp etc. even if I know that you would recommend to leave it like it is, so everyone can change the network_layer to its behaviours but that would be a small improvement. Maybe I will find time to make a usefull pull for that.

**Comment by jpfr** [comment]
Move to wiki.
https://github.com/open62541/open62541/wiki/Different-memory-allocator
