### ISSUE TITLE
Please say in the 'Dependencies' section which versions of python fit the project

### ISSUE THREAD

**Issue by yurivict** [open62541/open62541#1477]
Some projects are python3 only, some are python2 only, some are 3.6+.
There is no easy way to know. It is required to specify this in the FreeBSD port.

**Comment by jpfr** [comment]
We support both python 2 and python 3.
Both versions are verified for every commit in our continuous integration infrastructure.

Where is the best place to add this information for distribution ports?

**Comment by yurivict** [comment]
> Where is the best place to add this information for distribution ports?

README.md that shows with the project on GitHub.

**Comment by jpfr** [comment]
done.
