### ISSUE TITLE
multithreaded client

### ISSUE THREAD

**Issue by WoutvdBerg** [open62541/open62541#1483]
Is a multithreaded client safe to use without enabled multithreading?

I've skimmed trough the source code and found that most ifdef multithreading are for server methods.

The only possible problem I found is a mixed printf that multiple lines show on one line because there is no lock.

Are there other problems?

**Comment by ccvca** [comment]
I've just had problems when (accidently) access client functions from multiple threads simultaneously, but you might get away with it. If you have a small amount of threads, you could also initialize one client per thread.

**Comment by WoutvdBerg** [comment]
Thanks.
