### ISSUE TITLE
Add multiple monitoredItems

### ISSUE THREAD

**Issue by Croton-D** [open62541/open62541#1489]
like #1460 
I did a test to get the cost time adding single monitoreditem.it is about 150ms and I have thousands of monitoreditem to be added,that can be a long time.So I want to change the UA_Client_Subscriptions_addMonitoredItem() function so that adding multiple  monitoreditems can be done.
`/* add multiple items */
UA_StatusCode
UA_Client_Subscriptions_addMonitoredItems(UA_Client *client, UA_UInt32 subscriptionId,
                                         UA_NodeIdMonid *nodeId, UA_UInt16 itemCount, UA_UInt32 attributeID,
                                         UA_MonitoredItemHandlingFunction hf,
                                         void *hfContext, UA_UInt32 *newMonitoredItemId) {
    UA_Client_Subscription *sub;
    LIST_FOREACH(sub, &client->subscriptions, listEntry) {
        if(sub->subscriptionID == subscriptionId)
            break;
    }
    if(!sub)
        return UA_STATUSCODE_BADSUBSCRIPTIONIDINVALID;
    /* Create the handler */
    UA_Client_MonitoredItem *newMon = UA_malloc(sizeof(UA_Client_MonitoredItem) * itemCount);
    if(!newMon)
        return UA_STATUSCODE_BADOUTOFMEMORY;

    /* Send the request */
    UA_CreateMonitoredItemsRequest request;
    UA_CreateMonitoredItemsRequest_init(&request);
    request.subscriptionId = subscriptionId;
    UA_MonitoredItemCreateRequest *item = UA_malloc(sizeof(UA_MonitoredItemCreateRequest) * itemCount);
    if(!item)
            return UA_STATUSCODE_BADOUTOFMEMORY;
    //UA_MonitoredItemsCreateRequest_init(item,itemCount);
    typedef struct {
        UA_UInt32 handle;
    }UA_ItemHands;
    UA_ItemHands *itemHandles = UA_malloc(sizeof(UA_ItemHands) * itemCount);
    if(!itemHandles)
            return UA_STATUSCODE_BADOUTOFMEMORY;
    for (int i=0;i<itemCount;i++) {
        UA_MonitoredItemCreateRequest* item1 = item +  i;
        UA_ItemHands* handle1 = &itemHandles + i;
        UA_NodeIdMonid *nodeId1 = nodeId + i;
        item1->itemToMonitor.nodeId = (*nodeId1).nodeId;
        printf("test nodeid string %s\n",nodeId1->nodeId.identifier.string.data);
        item1->itemToMonitor.attributeId = attributeID;
        item1->monitoringMode = UA_MONITORINGMODE_REPORTING;
        item1->requestedParameters.clientHandle = ++(client->monitoredItemHandles);
        handle1->handle = item1->requestedParameters.clientHandle;
        item1->requestedParameters.samplingInterval = sub->publishingInterval;
        item1->requestedParameters.discardOldest = true;
        item1->requestedParameters.queueSize = 1;
    }
    request.itemsToCreate = item;
    request.itemsToCreateSize = itemCount;
    UA_CreateMonitoredItemsResponse response = UA_Client_Service_createMonitoredItems(client, request);
    // slight misuse of retval here to check if the addition was successfull.
    UA_StatusCode retval = response.responseHeader.serviceResult;
   
    if(retval != UA_STATUSCODE_GOOD) {
        UA_free(newMon);
        UA_CreateMonitoredItemsResponse_deleteMembers(&response);
        return retval;
    }
    /* Set the handler */
    for (int i=0; i<itemCount; i++) {
        UA_ItemHands* handle1 = &itemHandles + i;
        UA_Client_MonitoredItem *newMon1 = newMon + i;
        UA_NodeIdMonid *nodeId1 = nodeId + i;
        newMon1->monitoringMode = UA_MONITORINGMODE_REPORTING;
        UA_NodeId_copy(&(nodeId1->nodeId), &newMon1->monitoredNodeId);
        newMon1->attributeID = attributeID;
        //newMon1->clientHandle = client->monitoredItemHandles;
        newMon1->clientHandle = handle1->handle;
        newMon1->samplingInterval = sub->publishingInterval;
        newMon1->queueSize = 1;
        newMon1->discardOldest = true;
        newMon1->handler = hf;
        newMon1->handlerContext = hfContext;
        newMon1->monitoredItemId = response.results[i].monitoredItemId;
        nodeId1->monId = newMon1->monitoredItemId;

        *newMonitoredItemId = newMon1->monitoredItemId;
        LIST_INSERT_HEAD(&sub->monitoredItems, newMon1, listEntry);

    }

    UA_LOG_DEBUG(client->config.logger, UA_LOGCATEGORY_CLIENT,
                 "Created a monitored item with client handle %u",
                 client->monitoredItemHandles);

    UA_CreateMonitoredItemsResponse_deleteMembers(&response);
    return UA_STATUSCODE_GOOD;
}
/* add multiple items */`
Then I make a group to restore the NodeIds made by UA_NODEID_STRING() with the same item named "|var|XXXXXXXXXX-ARM-Linux.Application.IO_GVL.AI301.AV",that means all elements int the group are the same.I call the changed function to add multiple monitoreditems and find an interesting result.When the itemCount is 6，everything goes right，when it >= 7，it crushed.I traced the code and found this
`/* crush in this function */
static UA_StatusCode
Array_encodeBinaryOverlayable(UA_Client *client, uintptr_t ptr, size_t length, size_t elementMemSize) {
    /* Store the number of already encoded elements */
    size_t finished = 0;

    /* Loop as long as more elements remain than fit into the chunk */
    while(client->g_end < client->g_pos + (elementMemSize * (length-finished))) {
        size_t possible = ((uintptr_t)client->g_end - (uintptr_t)client->g_pos) / (sizeof(UA_Byte) * elementMemSize);
        size_t possibleMem = possible * elementMemSize;
        memcpy(client->g_pos, (void*)ptr, possibleMem);
		client->g_pos += possibleMem;
        ptr += possibleMem;
        finished += possible;
        UA_StatusCode retval = exchangeBuffer(client);
        if(retval != UA_STATUSCODE_GOOD)
            return retval;
    }
    /* Encode the remaining elements */

/**************************NULL pointor ptr*******************************************/
    memcpy(client->g_pos, (void*)ptr, elementMemSize * (length-finished));
	client->g_pos += elementMemSize * (length-finished);
    return UA_STATUSCODE_GOOD;
}
/* crush in this function*/`
something more:
single item length：152 bytes
6 items：152 * 6 = 912 bytes (goes ok)
7 item : 152 * 7 = 1064 bytes (crushed)
is here any limitations for item lenth (1K)?
And how can I fix it ?

**Comment by jpfr** [comment]
Fixed in the upcoming #1490.
