### ISSUE TITLE
adding indexRange to monitoredItems

### ISSUE THREAD

**Issue by WoutvdBerg** [open62541/open62541#1513]
I would like to implement indexRanges to monitoredItems.
Since there are many changes to the monitored items ongoing, is it possible at this stage?

Are there any obstructions?

**Comment by jpfr** [comment]
This is already implemented.
If indexranges don't work, file a bug.

**Comment by WoutvdBerg** [comment]
Can't find them in client side use with UA_Client_subscriptions_addMonitoredItem.

**Comment by jpfr** [comment]
UA_Client_Subscriptions_addMonitoredItems lets you define a `UA_MonitoredItemCreateRequest`.
This contains an `itemToMonitor` that carries the indexRange.

If you have an idea for a nicer API, proposals are welcome.

**Comment by WoutvdBerg** [comment]
Thanks, I was still looking in the 'old' addMonitoredItem function. Issue resolved
