### ISSUE TITLE
Basic128Rsa15 support in the client

### ISSUE THREAD

**Issue by mmesa2016** [open62541/open62541#1539]
How write UA client Basic128Rsa15 example. To connect server (ej: Kepware Server)

**Comment by jpfr** [comment]
Encryption support landed only a few days ago for the server.
Client support is incomplete.

This requires two enhancements:
- Add a list of supported SecurityPolicies to the client configuration
- Select the endpoint with the desired securitypolicy when opening the SecureChannel

The server code should be a good reference for using the SecureChannel layer with encryption.

**Comment by srdgame** [comment]
@jpfr Is there a planned date for supporting Basic128Rsa15 in client?

**Comment by forkmaster7** [comment]
@jpfr Can you please give me a short description on it. 
After selecting the endpoint with desired security policy, is the client going to use the same implementation of `UA_SecurityPolicy_Basic128Rsa15` function or the functionality needs to be changed.
Or any specific suggestion are welcome!

**Comment by Pro** [comment]
@Infinity95 can you quickly summarize/sketch what would need to be done, maybe we find a volunteer (@forkmaster7?) to implement this?

**Comment by jpfr** [comment]
@forkmaster7 

The client configuration would have to contain a list of securitypolicies.
These are the same policies already implemented for the server.

The actual policy for a SecureChannel is chosen when the endpoint is selected.

**Comment by Infinity95** [comment]
The client would need some changes to how it handles securechannels.
It is also missing functionality for selecting securitypolicies. The discovery service for example always needs securitypolicy none and it should be possible for the user to just connect to a specified endpoint without much work. This means the required policy should be selected automatically.
It's just a matter of making a clean interface for that and integrating the already implemented functionality like certificate verification.
A lot of work is already done by the securechannel but theres some verification stuff that needs to be implemented by the client (see the standard).

**Comment by Pro** [comment]
Partially implemented in #1686

**Comment by jpfr** [comment]
Implemented on master.
