### ISSUE TITLE
Does Open62541 supports view node browsing ?

### ISSUE THREAD

**Issue by mukunth1987** [open62541/open62541#1540]
Does Open62541 supports view node browsing ?

Documentation says "View nodes can be created and interacted with. But their  use in browse service is currently unsupported"

!ATTENTION!
Please read the following page carefully and provide us with all the
information requested:
https://github.com/open62541/open62541/wiki/Writing-Good-Issue-Reports

Use Github Markdown to format your text:
https://help.github.com/articles/basic-writing-and-formatting-syntax/

Fill out the sections and checklist below (add text at the end of each line).

Remove this text between the ATTENTION marks after reading it.
!ATTENTION!
--------------------------------------------------------------------------------

Description
===========

Background Information / Reproduction Steps
===========================================

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
> Documentation says "View nodes can be created and interacted with. But their use in browse service is currently unsupported"

That's the status. Browsing with views is unsupported.
And it won't be supported in the upcoming 0.3.
If you need a solution fast, feel free to propose an approach.

https://github.com/open62541/open62541/blob/0578af91fdc210521562f04a8a917b9946cbeca9/src/server/ua_services_view.c#L301
