### ISSUE TITLE
How to covert UA_STRING to char OR copy UA_String to char?

### ISSUE THREAD

**Issue by embbo** [open62541/open62541#1588]
Description
===========
I am getting string from UaExpert and trying to convert upcomming UA_string in char or normal  C string.

Background Information / Reproduction Steps
===========================================

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
UA_String simply contains the bytes which represent a char*
To convert it to a char* you can use something like this:

```
char* convert = (char*)UA_malloc(sizeof(char)*uaString.length+1);
memcpy(convert, uaString.data, uaString.length );
convert[uaString.length] = '\0';
```

It allocates a new char array, copies the data from the ua string and adds the required null byte at the end to defined the string ending.
