### ISSUE TITLE
open62541 Nodeset Compiler/PLCOpen

### ISSUE THREAD

**Issue by MrPoudel** [open62541/open62541#1597]
--------------------------------------------------------------------------------

Description
===========
I am trying to generate a server code based on the PLCOpen companion specification. For this I created a simple information model  in UaModeler. The project uses following XML Schema.
1. Opc.Ua.Nodeset2.xml
2. Opc.Ua.Di.Nodeset2.xml
3. Opc.Ua.PLCopen.NodeSet.xml

Please see the `screenshot`.  
![uamodel](https://user-images.githubusercontent.com/25766210/36310802-74bde47c-1329-11e8-8322-b750a48a4b87.JPG)

After that, I exported the XML file from server_nodeset.ua, i.e. server_nodeset.xml. I replaced the original server_nodeset.xml file present in ../open62541/examples/nodeset/ with the new one.

Contents of the server_nodeset.xml
`<?xml version="1.0" encoding="utf-8"?>
<UANodeSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:uax="http://opcfoundation.org/UA/2008/02/Types.xsd" xmlns="http://opcfoundation.org/UA/2011/03/UANodeSet.xsd" xmlns:s1="http://yourorganisation.org/server_nodeset/Types.xsd" xmlns:s2="http://opcfoundation.org/UA/DI/Types.xsd" xmlns:ua="http://unifiedautomation.com/Configuration/NodeSet.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <NamespaceUris>
        <Uri>http://yourorganisation.org/server_nodeset/</Uri>
        <Uri>http://opcfoundation.org/UA/DI/</Uri>
    </NamespaceUris>
    <Aliases>
        <Alias Alias="UInt16">i=5</Alias>
        <Alias Alias="Organizes">i=35</Alias>
        <Alias Alias="HasTypeDefinition">i=40</Alias>
    </Aliases>
    <Extensions>
        <Extension>
            <ua:ModelInfo Tool="UaModeler" Hash="zbwfpy50fGWHbbDO/aV5Qw==" Version="1.5.2"/>
        </Extension>
    </Extensions>
    <UAObject NodeId="ns=1;i=5002" BrowseName="1:myObj">
        <DisplayName>myObj</DisplayName>
        <References>
            <Reference ReferenceType="HasTypeDefinition">i=58</Reference>
            <Reference ReferenceType="Organizes" IsForward="false">ns=2;i=5001</Reference>
            <Reference ReferenceType="Organizes">ns=1;i=6002</Reference>
        </References>
    </UAObject>
    <UAVariable DataType="UInt16" NodeId="ns=1;i=6002" BrowseName="1:myVar" UserAccessLevel="3" AccessLevel="3">
        <DisplayName>myVar</DisplayName>
        <References>
            <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
            <Reference ReferenceType="Organizes" IsForward="false">ns=1;i=5002</Reference>
        </References>
        <Value>
            <uax:UInt16>55</uax:UInt16>
        </Value>
    </UAVariable>
</UANodeSet>
`
After that I build the project with following changes on the CMakeLists.txt present on the project's root directory. 
`option(UA_ENABLE_FULL_NS0 "Use the full NS0 instead of a minimal Namespace 0 nodeset" ON)`
`option(UA_BUILD_EXAMPLES "Build example servers and clients" ON)`

However, after calling the Makefile, I got the following errors:
`
[ 88%] Generating ../../src_generated/example_nodeset.c, ../../src_generated/example_nodeset.h
INFO:__main__:Preprocessing (existing) /home/pi/open62541/deps/ua-nodeset/Schema/Opc.Ua.NodeSet2.xml
INFO:__main__:Preprocessing /home/pi/open62541/examples/nodeset/server_nodeset.xml
Traceback (most recent call last):
  File "/home/pi/open62541/tools/nodeset_compiler/nodeset_compiler.py", line 130, in <module>
    ns.addNodeSet(xmlfile, typesArray=getTypesArray(nsCount))
  File "/home/pi/open62541/tools/nodeset_compiler/nodeset.py", line 257, in addNodeSet
    newsource = self.nodes[ref.target]
KeyError: ns=2;i=5001
examples/nodeset/CMakeFiles/server_nodeset.dir/build.make:69: recipe for target 'src_generated/example_nodeset.c' failed
make[2]: *** [src_generated/example_nodeset.c] Error 1
CMakeFiles/Makefile2:1683: recipe for target 'examples/nodeset/CMakeFiles/server_nodeset.dir/all' failed
make[1]: *** [examples/nodeset/CMakeFiles/server_nodeset.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
`

@Pro Am I missing something? Where might be the problem? Thanks.

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): https://github.com/open62541/open62541.git
 - [x] Other OPC UA SDKs used (client or server): Server
 - [x] Operating system: Raspbian
 - [x] Self-contained code example attached
 - [x] Critical issue

**Comment by Pro** [comment]
Did you already see this example from the unit tests on how to compile with PLCopen:
https://github.com/open62541/open62541/blob/master/tests/CMakeLists.txt#L290

And
https://github.com/open62541/open62541/blob/master/tests/server/check_nodeset_compiler_plc.c

That should help you getting started.
Unfortunately the documentation is not yet fully written for the nodeset compiler...
