### ISSUE TITLE
Typo in CMakeLists.txt

### ISSUE THREAD

**Issue by bobbthebuilder** [open62541/open62541#1623]
Hello,

from the CMakeLists.txt in master:

line 62: option(BUILD_SHARED_LIBS "Enable building of shared libraries (dll/so)" OFF)
line 303: if(NOT BUILD_SHARED_LIB) # must be BUILD_SHARED_LIB**S** i believe

Background (current state):
- When building open62541 against mbedtls, the compiler options for the C Runtime-Libraries mbedtls is built with do not match the ones for open62541 anymore resulting in linker errors. This is because the branch in line 303 will always be executed no matter what BUILD_SHARED_LIBS is set to.
- This problem will affect you on MSVC only.

**Comment by Pro** [comment]
Jep, correct. Can you create a PR? Thanks!

**Comment by bobbthebuilder** [comment]
See #1627.
