### ISSUE TITLE
make does not generate open62541.c

### ISSUE THREAD

**Issue by mushruptor** [open62541/open62541#1625]
Description
===========
I was not able to generate the open62541.c file in the current master branch. The open62541.h generation works fine and I haven't seen other issues executing the cmake generated Makefile. Maybe I missed something? Worked fine in the release versions.

Reproduction Steps
===========================================
I just used cmake and make as well as with different flags.

**Comment by Stasik0** [comment]
Also no updates here https://open62541.org/releases/

**Comment by Pro** [comment]
There are the corresponding files on https://open62541.org/releases/
So this means that cmake should work fine.

The important thing is to enable the flag `UA_ENABLE_AMALGAMATION`.

```
mkdir -p build && cd build
    cmake -DCMAKE_BUILD_TYPE=Release -DUA_ENABLE_AMALGAMATION=ON -DUA_BUILD_EXAMPLES=ON ..
make -j
```

Please reopen and post more details on how you used cmake if you still have the issue
