### ISSUE TITLE
Can not build with encryption and amalgamation

### ISSUE THREAD

**Issue by the-om** [open62541/open62541#1643]
Description
===========
#1634 breaks my build.
The reason are 3 violations of the one definition rule when using amalgamation.
The functions sha1, asym_getRemotePlainTextBlockSize and asym_getRemoteEncryptionKeyLength are declared static which works for non-amalgamated builds, but when amalgamated they are defined twice in the same translation unit (open62541.c) which is not legal.

Background Information / Reproduction Steps
===========================================
Build with UA_ENABLE_AMALGAMATION and UA_ENABLE_ENCRYPTION

Compiler: Microsoft Visual Studio 2017

**Comment by ccvca** [comment]
Possible solutions might be:
- Use an "include Guard" around the static function definitions,
- Use normal header/source and use only one implementation

**Comment by jpfr** [comment]
- pull out the common code in common .c file that is used for both SecurityPolicy implementations
- rename the duplicate methods to something more specific
