### ISSUE TITLE
UA_Client secure and encrypted connection available?

### ISSUE THREAD

**Issue by Aleadinglight** [open62541/open62541#1653]
Please confirm. Is UA client support secure channel and encryption in open62541 3.0?  

For example: Client connects to a  Basic128Rsa15 UA Server?
If so, can someone please give an example code? I believe many people want to see it too.

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version 3.0
 - [ ] Operating system: Windows

**Comment by jpfr** [comment]
No. Client support will not make it into 0.3.
The SecureChannel implementation is reusable for the client in principle.

But nobody has stepped up for it so far.
