### ISSUE TITLE
Convert library to Golang

### ISSUE THREAD

**Issue by rtmaster** [open62541/open62541#1681]
I'm interested in converting this library from C to Golang.
Do you see any license restriction?
Any technical limitation that I should be aware of?

**Comment by Pro** [comment]
Cool! Thanks for your interest!

License wise there aren't any restrictions, as long as your modified source code is still under MPL 2.

I'm not aware of any technical restrictions.

Also note that there was already someone who did the same in #967

**Comment by rtmaster** [comment]
Hi @Pro 
thanks for your reply!
I believe the post you mentions is related to generating the bindings to generate the bindings in order to use from Golang the library using cgo.
I'm after a pure Golang implementation with no C at all involved (maybe using https://github.com/elliotchance/c2go to help in the conversion)... I understand that it would be difficult to keep the 2 implementations in sync, but I expect that after release 0.3 all the main functions would be available.
What do you think?

**Comment by jpfr** [comment]
Hey @rtmaster ,

I like the simplicity and async nature of go. Going for go is a cool project!
But don't underestimate the effort. This project has a couple thousand commits under the belt.

open62541 relies quite a bit on pointer magic and the struct layout specifics of C.
Especially in the type handling (ua_types.c and ua_types_binary_encoding.c come to mind).
If the type-handling proves to be difficult, maybe we can convince of a mixed approach with C+Go after all. 😄 

In any case, it would be great to hear how c2go worked out.

**Comment by rtmaster** [comment]
Yes I will let you know. Please let me know if there is anything else that you think I should pay attention to? Basically I need to convert only open62541.h and open62541.c right? No other dependencies?

**Comment by jpfr** [comment]
Right.

However, I would advise that you keep a file structure similar to our sources.
The open62541.c is generated from many files, including some auto-generated code.

**Comment by rtmaster** [comment]
thanks for the heads up, we will try... Any guidance is appreciated, is there a page that explains the whole thing?
Also, would you host the project on this repo in order to keep it consistent?

**Comment by Pro** [comment]
Ah sorry, I misunderstood your question, now I got it! I also find the idea nice, but as @jpfr already mentioned, there is a lot of pointer magic and other 'not so common' C stuff going on under the hood, so it may be quite an effort to get the C code transpiled. IMHO this work only makes sense if there's a significant advantage compared to e.g. the go bindings.

We are using a python script which more or less concatenates all the source files into a single file distribution `open62541.c`. That process is called amalgamation. See https://github.com/open62541/open62541/blob/master/tools/amalgamate.py
The script is executed by cmake. 

When doing your transpile project, you should make sure that you do not depend on a specific version, but are able to use our original repo as a basis.
When your project is in a first working state we can definitely host it under the open62541, as we already did for the python bindings:
https://github.com/open62541/open62541-python

**Comment by aepetelin** [comment]
Hi, I'm working on Go wrapper over open62541. I was thinking about moving all the C code to Go, but it would be much more job to do. And the idea to maintain to libraries sounds not so easy.
The solution might be CGO package and wrapper in Go.
Connecting, reading and writing work pretty well. But now I'm stuck with passing callbacks from Go to C subscription functions (UA_Client_MonitoredItems_createDataChange).
