### ISSUE TITLE
remove duplicated loadFile method in examples

### ISSUE THREAD

**Issue by StalderT** [open62541/open62541#1694]
```loadFile``` method is used in many examples : 

```client_basic128rsa15.c```
```server_basic128rsa15.c```
```server_ctt.c```

The goal would be to add this method in a simple common header in the examples folder.

see https://github.com/open62541/open62541/pull/1692

**Comment by Stasik0** [comment]
examples/shared.c or something?

**Comment by Pro** [comment]
Jep, something like this, or even just a header (with the method definition and declaration) which can simply be included, so that we don't need to include the additional source file.

**Comment by StalderT** [comment]
fixed in https://github.com/open62541/open62541/pull/1691
