### ISSUE TITLE
secure client/server - trust list verification

### ISSUE THREAD

**Issue by shamaster** [open62541/open62541#1708]
To verify the implementation of secure client with trust list provided, anyone can suggest the procedure on how to create trust list and to provide the file as an input to application?

**Comment by jpfr** [comment]
@Infinity95 Can we add a few sentences to the docs?
A link to an openssl tutorial would help as well.

**Comment by SebsSa** [comment]
*bump* 
Any news here?

Still searching for this : 
> the procedure on how to create trust list and to provide the file as an input to application?

**Comment by jpfr** [comment]
More docs would be helpful.

**Comment by ZekeLandon** [comment]
Hi @jpfr, could you point me to location of docs for reference if any available?

Regards,
Zeke

**Comment by jpfr** [comment]
the server_ctt example implements this.

**Comment by EvgKlin** [comment]
There are some docs?
