### ISSUE TITLE
UA client connect to Kepware server error;

### ISSUE THREAD

**Issue by mmesa2016** [open62541/open62541#1710]
Test OPC UA client test to connect to OPC UA KEPServerEX 5 Server version 5.20. Try to connect using username and password. In the log show "No suitable endpoint found". I' am configure OPC UA endpoint security policies None.
![imagen](https://user-images.githubusercontent.com/19754078/38257335-91fd6842-374f-11e8-8523-387b629582a6.png)

**Comment by jpfr** [comment]
Our Github issue template asks for some background information.
Can you give us more details to reproduce?

Which version of open62541? One of our example servers?
Can you connect with UAExpert?

**Comment by StalderT** [comment]
No encryption of username/password is supported at the moment #934

KEPServer accepts only username/password encryption.

![image](https://user-images.githubusercontent.com/13799456/38302345-947fa298-3802-11e8-87a0-8ee07eaa93be.png)

For now, you can enable KEPServer anonymous access : https://forum.inductiveautomation.com/t/faulted-connection-with-kepware/15710/5

**Comment by mmesa2016** [comment]
Description
Test OPC UA client test (open62541 client) to connect to OPC UA KEPServerEX 5 Server version 5.20. Try to connect using username and password. In the log show "No suitable endpoint found". I' am configure OPC UA endpoint security policies None. I' am use UAExpert and connection is successfull. OPC UA KEPServerEX 5 Server enable anonymous access.

 open62541 Version:
 https://github.com/open62541/open62541/tree/master

 Operating system:
 Wwindows 8.1 and build MinGW

 Logs:
1 endpoints found
URL of endpoint 0 is opc.tcp://127.0.0.1:49320
[2018-04-04 10:54:35.505 (UTC-0400)] error/client	No suitable UserTokenPolicy found for the possible endpoints

Code:
 client = UA_Client_new(UA_ClientConfig_default);
 retval = UA_Client_connect_username(client, CONNECTION_STRING, "admin", "admin");

**Comment by StalderT** [comment]
> OPC UA KEPServerEX 5 Server enable anonymous access.

So use ```UA_Client_connect``` instead of  ```UA_Client_connect_username```.

**Comment by mmesa2016** [comment]
I' am enbled OPC UA KEPServerEX 5 Server anonymous access. For use method UA_Client_getEndpoints in open62541 client, discovery endpoints.
