### ISSUE TITLE
Random NodeId generation may overflow or result in endless loop

### ISSUE THREAD

**Issue by Pro** [open62541/open62541#1711]
Currently we are creating a "random" node ID for new nodes, if none is specified:
https://github.com/open62541/open62541/blob/8066c68aa254366dbed2b9cc5e49e89e7fc3ea9c/plugins/ua_nodestore_default.c#L340

I just saw that there may be two issues:

- Overflow of `identifier` is not handled. Even though identifier is 32bit, a long running server which creates many events may result in an overflow (every event gets its own node ID temporarily).

- The `findFreeSlot` loop may result in an endless loop if there are no more free slots available (i.e., no more available node IDs).

**Comment by jpfr** [comment]
Solved in #1727.
