### ISSUE TITLE
install open62541.h 

### ISSUE THREAD

**Issue by etm** [open62541/open62541#1721]
I typically build with BUILD_SHARED_LIBS ON. It would be convenient when at least in this case "make install" would copy the generated open62541.h to CMAKE_INSTALL_PREFIX/include. Or is there a reason for not doing it?

**Comment by ccvca** [comment]
Do you set UA_ENABLE_AMALGAMATION? #1415

**Comment by etm** [comment]
I see. thanks for the pointer.
