### ISSUE TITLE
Building under VS 2015, Windows 10

### ISSUE THREAD

**Issue by sherylll** [open62541/open62541#1749]
Description
===========
Error building following the instruction:

Background Information / Reproduction Steps
===========================================
I changed 2 lines in CMakeLists.txt:

```
# Build Targets
option(UA_BUILD_EXAMPLES "Build example servers and clients" ON)
option(UA_BUILD_UNIT_TESTS "Build the unit tests" ON)
```

Following the instructions:

```
cd <path-to>\open62541
mkdir build
cd build
<path-to>\cmake.exe .. -G "Visual Studio 14 2015"

```
gives

```
fatal: Not a git repository (or any of the parent directories): .git
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE)
-- Could NOT find LATEX (missing: LATEX_COMPILER)
-- Could NOT find CHECK (missing: CHECK_INCLUDE_DIRS CHECK_LIBRARIES)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CHECK_INCLUDE_DIRS (ADVANCED)
   used as include directory in directory C:/Users/SunYuxi/Documents/open62541-checkconnectivity2/tests
   used as include directory in directory C:/Users/SunYuxi/Documents/open62541-checkconnectivity2/tests
   used as include directory in directory C:/Users/SunYuxi/Documents/open62541-checkconnectivity2/tests
 <...repeated...>
COMPAT_LIBRARY
    linked by target "check_services_nodemanagement" in directory C:/Users/SunYuxi/Documents/open62541-checkconnectivity2/tests
    linked by target "check_types_builtin" in directory C:/Users/SunYuxi/Documents/open62541-checkconnectivity2/tests
 <...repeated...>
CHECK_LIBRARY
    linked by target "check_utils" in directory C:/Users/SunYuxi/Documents/open62541-checkconnectivity2/tests
    linked by target "check_types_memory" in directory C:/Users/SunYuxi/Documents/open62541-checkconnectivity2/tests
 <...repeated...>

-- Configuring incomplete, errors occurred!
See also "C:/Users/SunYuxi/Documents/open62541-checkconnectivity2/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/SunYuxi/Documents/open62541-checkconnectivity2/build/CMakeFiles/CMakeError.log".
```

And no build/bin/executables are generated

More detailed guidance regarding building with Visual Studio would be appreciated. I'm trying to locate a bug which only occurs with Visual Studio + DrMem

Checklist
=========
 - [ ] Operating system: Windows 10 (64 bit)

**Comment by Pro** [comment]
You are missing the libcheck dependency to build the unit tests.
Since we are using CI for Linux and windows, you can always check the scripts how we are installing/building the stack with specific settings.
E.g. for your case:

Install libcheck:
https://github.com/open62541/open62541/blob/master/tools/appveyor/install.ps1#L47

And then build with the libcheck directory (`-DCHECK_PREFIX=c:\check`):
https://github.com/open62541/open62541/blob/master/tools/appveyor/build.ps1#L145

If you could create a PR which updates the docs that would be really nice for future users.
