### ISSUE TITLE
Macros MIN and MAX shoudl be UA_MIN and UA_MAX to avoid clashing

### ISSUE THREAD

**Issue by bazza2jw** [open62541/open62541#1760]
Description
===========
open62541 includes macro definitions for MAX and MIN. This causes a clash with various other packages.
For consistency the macros should be called UA_MIN and UA_MAX.

Background Information / Reproduction Steps
===========================================
None needed

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
Full ACK.

Can you create a PR?

**Comment by HolgerJeromin** [comment]
This issue should be closed
