### ISSUE TITLE
porting open62541 in c++ 

### ISSUE THREAD

**Issue by bnadem** [open62541/open62541#1768]
i want only porting open62541 in c++ for our company in commerical use  int IOT domain. it es possible! in description software: open625411 will mentioned

**Comment by jpfr** [comment]
open62541 is written in the common subset of C99 and C++98.
You can compile it with a range of C++ compilers already.

For example GCC and Visual Studio.

If you prefer an object-oriented wrapper around open62541, please refer to the ongoing effort by Bazza Hill. There is some activity here. I don't know the exact current state of the wrapper.

https://github.com/bazza2jw/open62541Cpp
https://groups.google.com/forum/#!topic/open62541/DX_Vk0fRXAY
