### ISSUE TITLE
open62541-mast/encryption/server_basic256sha256 Compile Failed

### ISSUE THREAD

**Issue by jhj0955** [open62541/open62541#1779]
------------------------------------------------------------

===========

1. We use an unmodified examples/encryption/server_basic256sha256.c
2. However, due to a compilation error, I added the header file path.
 . server_basic256sha256.c

#include <signal.h>
#include <stdio.h>
#include <errno.h>
#include "open62541.h"
#include "common.h"
#include "ua_config.h"
#include "ua_config_default.h"

3. I moved the file to the path below and ran it. (path: open62541-master/examples)
 : gcc -std=c99 server_basic256sha256.c open62541.c -o server -I encryption/ -I ../include

4. I failed to compile. how should i do?

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: linux (linaro - debian)
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by schroeder-** [comment]
You should add the compiler Log, otherwise nobody can tell you what went wrong.
Rebuild the project with cmake to enable Encryption. In CMAKE you must set UA_ENABLE_ENCRYPTION and make sure if have installed mbedtls on your system.
