### ISSUE TITLE
FULL_NS0 does not build

### ISSUE THREAD

**Issue by fabian727** [open62541/open62541#1802]
Description
===========
Hi guys,
nice repo, but I got out of nowhere some problems.

Background Information / Reproduction Steps
===========================================

I am running under Linux/ Ubuntu 16.04

```bash
git pull https://github.com/open62541/open62541.git
cd open62541
mkdir build
cd build
cmake ..
ccmake .
checking -> full NS0; saving and rechecking
changing CmakeCache.txt -> using cross-compiler gcc-arm-linux-gnueabihf
make
```

What I get as output:

```
-- Could NOT find LATEX (missing:  LATEX_COMPILER) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/open62541/build_armhf
[  0%] Generating src_generated/ua_transport_generated.c, src_generated/ua_transport_generated.h, src_generated/ua_transport_generated_handling.h, src_generated/ua_transport_generated_encoding_binary.h
^CTraceback (most recent call last):
  File "/home/user/open62541/tools/generate_datatypes.py", line 432, in <module>
    parseTypeDefinitions(outname, f, args.namespace)
  File "/home/user/open62541/tools/generate_datatypes.py", line 295, in parseTypeDefinitions
    if not typeReady(typeXml):
  File "/home/user/open62541/tools/generate_datatypes.py", line 268, in typeReady
    if child.tag == "{http://opcfoundation.org/BinarySchema/}Field":
```
there it hangs for as long as I wait. Afet pressing Ctrl+C
```
KeyboardInterrupt
CMakeFiles/open62541-generator-transport.dir/build.make:66: recipe for target 'src_generated/ua_transport_generated.c' failed
make[2]: *** [src_generated/ua_transport_generated.c] Error 1
CMakeFiles/Makefile2:236: recipe for target 'CMakeFiles/open62541-generator-transport.dir/all' failed
make[1]: *** [CMakeFiles/open62541-generator-transport.dir/all] Interrupt
Makefile:149: recipe for target 'all' failed
make: *** [all] Interrupt
```

With deactivated FULL_NS0 everything works fine, including cross-compiler and encryption

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (active):
 - [x] Other OPC UA SDKs used (client or server):  none
 - [x] Operating system: Linux -> Ubuntu 16.04

**Comment by Pro** [comment]
> there it hangs for as long as I wait. Afet pressing Ctrl+C

What exact time did you wait? The nodeset compiler for NS0 requires some computing power, thus it may take longer on some PCs. Anyways on normal up-to-date PC/Notebook it should not take more than 10 secs.

Could it be an issue with your python installation?

**Comment by fabian727** [comment]
Hi,
thanks for your fast reply.
I waited for about 5 minutes. (it is not an up to date computer, but this slow...; i don't think so)
The confusing fact: it already built on this machine and setup.

1 thing to add: in my description I shortened the file-path. Could this be a problem? It is very long. This is the only thing I changed. And I will check as next step.

**Comment by fabian727** [comment]
I should always sleep 1 night about my problems. It is up and running again.
If I clone the repo to a shorter path, everything works as expected. In the long path it does still not work.
The absolute long path exists of 8 directories + 68 chars (chars meaning a-z & A-Z and _)

Can someone verify this behaviour? I think this is a little bug.

**Comment by Pro** [comment]
Can you try to build with verbose make, so that we see the full output?
https://stackoverflow.com/questions/2670121/using-cmake-with-gnu-make-how-can-i-see-the-exact-commands

**Comment by fabian727** [comment]
thanks for your help. Seems like I had a problem with my computer (I installed some programs, which are independent from open62541, without reboot). Today the Debug Version builds fine.
But I get stuck at the moment with the Release Version. Maybe it needs more time to compile.

**Comment by fabian727** [comment]
okay, this needs extremely more time, than expected... but it also worked. But took about 2 coffees...

sorry for making more noise than needed
