### ISSUE TITLE
UserDefined Data in UA_ValueCallback

### ISSUE THREAD

**Issue by gerdBert** [open62541/open62541#1834]
Description
===========

server.h (v0.2) provides a _UA_ValueCallback_ structure with a handle for user-defined data that is also part of the signature of _onWrite_/_onRead_. The structure differs in the most recent version (rc 0.3): the handle has been removed and the signature of _onRead_/_onWrite_ has been adjusted according to the signature of _UA_Server_DataChangeNotificationCallback_. 

However, I found it helpful to have a handle for user-defined data within the _UA_ValueCallback_ which is available when onWrite/onRead is called. I need to update the content of my API if a OPC UA Client overwrites the value of a variable. I use the handle that is available in v0.2 to store a pointer of my API variable which must be updated when a OPC UA client overwrites the value of the related variable in the server.
Could the nodeContext be used instead to retrieve for user-defined data in _onRead_/_onWrite_?
Where could the nodeContext be set? 
If have seen that there is a _UA_Server_setNodeContext_ function.
What is the intended purpose of _nodeContext_?

Background Information / Reproduction Steps
===========================================

Checklist
=========
Please provide the following information:

 - [rc.03/v0.2 ] open62541 Version (release number or git tag):
 - [UAExpert] Other OPC UA SDKs used (client or server): 
 - [Win10 64bit] Operating system:
 - [Default] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [No ] Wireshark network dump attached
 - [No] Self-contained code example attached
 - [No ] Critical issue

**Comment by jpfr** [comment]
Hello @gerdBert ,

the nodeContext is the same as the previous callback context.
The difference is that all nodes have a context. Not only those with a ValueCallback.

Please reopen if you have ideas on how we can communicate this better.
