### ISSUE TITLE
Unable to set Length attribute of Field for StructuredType in .bsd file

### ISSUE THREAD

**Issue by CaseyDev12** [open62541/open62541#1837]
Riding the documentation, when I write this code in the .bsd file

<opc:StructuredType Name="Type1" BaseType="ua:ExtensionObject">
        <opc:Field Name="field_1" TypeName="opc:Float" Length="2" />
        <opc:Field Name="field_2" TypeName="opc:Float" />
</opc:StructuredType>

I expect that a structure TestVariable is generated with two fields and the field test1 is an array of size equal to 2. Instead in the generated .h file the field test1 is a scalar as shown below.

typedef struct {
    UA_Float field_1;
    UA_Float field_2;
} UA_Type1;

I would like to get the following structure:

typedef struct {
    UA_Float field_1[2];
    UA_Float field_2;
} UA_Type1;

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Fixed-lengths arrays do not exist in the OPC UA type system.
The structure can only contain a flexible-length array for field_1.
Or you add two scalars `field_1_a` and `field_1_b`.

Cf. part 6 of the OPC UA standard.
