### ISSUE TITLE
invalid source for UA_ENABLE_GENERATE_NAMESPACE0 with no AMALAGATION

### ISSUE THREAD

**Issue by lehned** [open62541/open62541#1857]
Description
===========
I'm compiling on Windows with CMake generated "MYSYS Makefile" for the branch 0.3 the examples. I enabled generation of Namespace 0 and disabled amalagation. 
On initiating the build following error occurs:
`src/server/ua_server.c:22:40: fatal error: ua_namespaceinit_generated.h: No such file or directory`

After modifing ua_server.c :
```
Index: ua_server.c
===================================================================
--- ua_server.c	(revision 103)
+++ ua_server.c	(working copy)
@@ -19,7 +19,7 @@
 #include "ua_server_internal.h"
 
 #ifdef UA_ENABLE_GENERATE_NAMESPACE0
-#include "ua_namespaceinit_generated.h"
+#include "ua_namespace0.h"
 #endif
 
 /**********************/
```

It works again. 

Background Information / Reproduction Steps
===========================================

1. cmake ../open62541-0.3/ -G 'MSYS Makefiles' -DUA_ENABLE_METHODCALLS='ON' -DUA_ENABLE_GENERATE_NAMESPACE0='ON' -DCMAKE_BUILD_TYPE='Debug' -DUA_ENABLE_FULL_NS0='ON' -DUA_BUILD_EXAMPLES='ON'

2. make 

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): branch 0.3 8845e493d7751fd4eee3917b540e5346646b9cf7
 - [x] Operating system: CMake, MYSYS
 - [x] Critical issue

**Comment by Pro** [comment]
Thanks for the issue report.

`UA_ENABLE_GENERATE_NAMESPACE0` is a deprecated option which is now called `UA_ENABLE_FULL_NS0`.

The doc is fixed in PR #1873
