### ISSUE TITLE
Could not connect to server: BadTimeout

### ISSUE THREAD

**Issue by embbo** [open62541/open62541#1859]
Hi, 
I am trying to Implement OPCUA server on stm32f4 using Freertos and LWIP. when i ping the server, it works fine but when i try to connect with UaExpert(OPCUA Client) it gives error "Could not connect to server: BadTimeout". I am using hard coded ip adress 192.168.xx.xx:16664.

**Comment by HolgerJeromin** [comment]
can you connect with telnet to this port?

**Comment by embbo** [comment]
@HolgerJeromin No it doesn't , when i try to connect it stops or break the connection. what i found is it works till LWIP (because it pings)

**Comment by Pro** [comment]
It could be a memory issue, that your server runs out of memory.

You can have a look at my sample project for an ESP32 using LWIP:

https://github.com/Pro/open62541-arduino

**Comment by cabralfortiss** [comment]
Did you manage solve this by implementing the time functions? How's is this issue now related to what's been going on in #2227 ?

**Comment by Pro** [comment]
Closing this to streamline the discussion in #2511
