### ISSUE TITLE
Compilation error with muticast discovery

### ISSUE THREAD

**Issue by Smeat** [open62541/open62541#1869]
Description
===========
Compiling with the option `UA_ENABLE_DISCOVERY_MULTICAST=ON` on Alpine Linux  results in the following compilation error:
```
/open62541/src/server/ua_services_discovery_multicast.c: In function 'iterateMulticastDiscoveryServer':
/open62541/src/server/ua_services_discovery_multicast.c:629:12: error: variable 'next_sleep' has initializer but incomplete type
     struct timeval next_sleep = { 0, 0 };
            ^~~~~~~
```

This doesn't occur on Gentoo or Ubuntu.

Background Information / Reproduction Steps
===========================================
Steps to reproduce:
```sh
sudo docker run --rm -it alpine /bin/sh
apk update && apk add git cmake make g++ py2-six
git clone https://github.com/open62541/open62541 -b 0.3-rc2 && mkdir open62541/build && cd open62541/build
git submodule init && git submodule update
cmake -DUA_ENABLE_DISCOVERY_MULTICAST=ON .. && make
```

Fix
===========================================
Add `#include <sys/time.h>` to `ua_services_discovery_multicast.c`

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): 0.3-rc2 and current master
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Alpine Linux Docker image
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
Thanks for your very detailed bug report! This will be fixed in #1872 in 0.3 and then also ported to master.
