### ISSUE TITLE
Object Type Tutorial

### ISSUE THREAD

**Issue by williamdai84** [open62541/open62541#1870]
Description
===========
I tried with Working with Objects and Object Types Tutorial and in the Object types, type hierarchies and instantiation part, just wondering how to create a nested object (object in object) and can be browsed using UA Client? Thanks a lot!

Background Information / Reproduction Steps
===========================================
Eclipse with Cygwin under Windows 10
Code from Working with Objects and Object Types Tutorial

Checklist
=========
Please provide the following information:

 - [X] open62541 Version (release number or git tag): 0.3rc2
 - [X] Other OPC UA SDKs used (client or server): UaExpert
 - [X] Operating system: Windows/Linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
It is possible to define nested objects.
Just add a child object to the ObjectType.
But you need to make them mandatory to be auto-generated when an instance is made.

See the tutorial here: https://open62541.org/doc/current/tutorial_server_object.html

Please reopen if you encounter any issues.
