### ISSUE TITLE
Compliance Test Tool (Nano Embedded Device Server Profile) err

### ISSUE THREAD

**Issue by jhj0955** [open62541/open62541#1895]
I run server_ctt provided by open 62541.
project setting's open62541-ctt-master by https://github.com/open62541/open62541-ctt
(check the Nano Embedded Device Server Profile )

![image](https://user-images.githubusercontent.com/28384271/42304027-17b7236c-805f-11e8-9f05-460aab9b5ba0.png)

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version (release number or git tag): 
 Git-Revision: 0.3-rc2-217-g0afd439a
 * Copyright (C) 2014-2018 the contributors as stated in the AUTHORS file
 
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system: linux  
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Thanks for reporting.
It looks as if we return the wrong error code.

We will fix this. Until then, this will not be problematic in practice.

**Comment by jhj0955** [comment]
Thank you for your response.

**Comment by jpfr** [comment]
The fix is coming in #1903.
