### ISSUE TITLE
Server: adding optional object [0.3; server; help wanted; question]

### ISSUE THREAD

**Issue by fabian727** [open62541/open62541#1898]
Hi guys,

I am trying to write a Server, which configures itself at startup.
For this I advanced the namespace with some more objecttypes which "hascomponent' mandatory and optional objecttypes.
E.g.:
```
list under objecttypes:

door-|
         |->window  (mandatory)
         |->mirror    (optional)
car -|
       |-> door (optional)
       |-> seat (mandatory)

and so on.
```
Now at startup I created a new object of this type "car" named myOwn. Now I would like to add the optional door, because the objectType "car" has it. How can I achieve it?
Suspicious to me: In the objectType "car" the "door" is already an object and referenced by "hasComponent" of the objectType "car". Shouldn't door be an objectType in the ObjectType "car"?

I hope I made clear where my problem is, else please ask. Thanks,

Fabian

**Comment by jpfr** [comment]
Dear Fabian,

ObjectTypes contain child objects not child ObjectTypes.
You can only have "hasSubType" relations between ObjectTypes.

The optional door is not created automatically during instanation.
You can however
- Manually add the door afterwards
- Split the object creation into addnodes_begin and addnodes_finish. Then you can add the door after _begin and it can be considered by constructors during _finish. (If you have defined constructors).

**Comment by fabian727** [comment]
Thanks for your quick answer.
does the "optional" have any effect during "construction"? As you stated, it is not instantiated and there are no functions like "addOptionalObjects"
So I could also just add mandatory objects and during setup I add other objects as I want to

**Comment by jpfr** [comment]
Yes.
