### ISSUE TITLE
Compliance Test Tool error

### ISSUE THREAD

**Issue by jhj0955** [open62541/open62541#1902]
open62541 Version (release number or git tag):
Git-Revision: 0.3-rc2-217-g0afd439a

It is similar to issues1875-error
I think our server needs a return code such as badcertificateUriInvalid
What needs to be corrected to fix this part?
I would really appreciate if you answer about this shortly.
Thank you.

project setting's open62541-ctt-master by https://github.com/open62541/open62541-ctt
(check the Nano Embedded Device Server Profile )

![image](https://user-images.githubusercontent.com/28384271/42357414-bf3e13bc-8112-11e8-8917-cdf6246982ad.png)

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
This might take a while.

The parse x509 certificate currently does not give us access to the URI field of the Subject Alternative Names.

There's an open bug for the mbedtls library we use.
https://github.com/ARMmbed/mbedtls/pull/731

If this doesn't move, we will have to add a second ASN.1 parser or switch security to a more complete lib. But openssl on embedded is a pain...

**Comment by jpfr** [comment]
Fixed with a workaround in #1907.
