### ISSUE TITLE
Client Browsing nodes open62541

### ISSUE THREAD

**Issue by Fabianx92** [open62541/open62541#1906]
Description
===========

When browsing the nodes of the example server with the client I see the following

Browsing nodes in objects folder:
NAMESPACE---- NODEID----           BROWSE NAME -------     DISPLAY NAME
0-----------------        61----------           FolderType-------------       FolderType
0-----------------         2253------  --           Server ------------- ---         Server
1-----------------       **the.answer**----       the answer----------       the answer

up to here all excellent

But my question is whether it is possible to obtain the numeric data from the address space **"the.answer"** without having to rewrite it again as it is done in the following sample method of the client:

    /* Read attribute */
    UA_Int32 value = 0;
    printf("\nReading the value of node (1, \"the.answer\"):\n");
    UA_Variant *val = UA_Variant_new();
    retval = UA_Client_readValueAttribute(client, UA_NODEID_STRING(1, "the.answer"), val);
    if(retval == UA_STATUSCODE_GOOD && UA_Variant_isScalar(val) &&
       val->type == &UA_TYPES[UA_TYPES_INT32]) {
            value = *(UA_Int32*)val->data;
            printf("the value is: %i\n", value);
    }
    UA_Variant_delete(val); 

There is a method that allows me to pass the attributes of address space "the.answer" automatically or saving it in a variable to the function `UA_Client_readValueAttribute`, without having to rewrite it again ??

Saludos Cordiales desde Ecuador

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
Close as dual crosspost:
https://stackoverflow.com/questions/51218863/open62541-client-browsing-nodes-and-get-value-attributes

https://groups.google.com/d/msg/open62541/o3EIOc1T9UU/F6NQS31wBwAJ

Do not post the same question multiple times on different portals. The discussion will continue on StackOverflow.
