### ISSUE TITLE
CI for freeRTOS

### ISSUE THREAD

**Issue by Pro** [open62541/open62541#1910]
After the Architecture PR #1595 we need Continuous Integration for FreeRTOS+LWIP

**Comment by cabralfortiss** [comment]
Here a comment about this issue. Just to organize

https://github.com/open62541/open62541/pull/2511#issuecomment-500227225

**Comment by Pro** [comment]
@cmbahadir in https://github.com/open62541/open62541/pull/2511#issuecomment-500227225 you note some infos for integrating freeRTOS in Travis CI.

To comment on the necessary changes:

> * Location of the "task.h" should be "freertos/task.h" on open62541.c.

Is it necessary to change this in the file. Can't you just set the additional include directory for the compiler?

> * #define UA_ARCHITECTURE_FREERTOSLWIP has to be defined under open62541.c

This should be done through compiler flags, i.e., `gcc -DUA_ARCHITECTURE_FREERTOSLWIP ...`

> * And also #define UA_IPV6 LWIP_IPV6 should be commented out since IPV6 is not supported.

For this there should be an additional ifdef for the FreeRTOS architecture.
(@cabralfortiss ping)

Based on my comments it shoudl not be necessary to use sed or other hacks to modify the code. Just by parametrizing the compiler correctly, everything should work.

@cmbahadir would you like to propose a PR which adds freeRTOS builds to travis?
We will of course support you!

**Comment by cmbahadir** [comment]
Hey @Pro ,

Ok i will check it, but it may take some time since currently ı am working on something else.

By the way it will be a CI with a xtensa-toolchain which is specific to espressif(ESP32) but it still uses freeRTOS-LWIP so ı guess it is not a major problem to test the integration.
