### ISSUE TITLE
CTT Regression: Subscription Acknowledgement of Available SequenceNumbers

### ISSUE THREAD

**Issue by jpfr** [open62541/open62541#1913]
This is a new regression. The test was green a couple of weeks ago.
So we should be able to pinpoint the PR responsible for the regression.

![ctt_sn](https://user-images.githubusercontent.com/1726411/42560921-2766943a-84f8-11e8-87e0-80dc7abf9e86.png)

A unit test is required to prevent this from happening again.

**Comment by StalderT** [comment]
@jpfr How can I help you to fix this issue? I don't have CTT.

**Comment by mlang-de** [comment]
Should be fixed by PR #1998 .
