### ISSUE TITLE
Support for Alarms & Conditions (Part 9)

### ISSUE THREAD

**Issue by basyskom-jvoe** [open62541/open62541#1947]
Description
===========
OPC UA Part 9, 5.5.7 specifies the ConditionRefresh method of the ConditionType object.
This method takes a subscription ID belonging to the client's session as parameter and issues event notifications for retained conditions using the subscription passed as parameter.

Implementing the ConditionRefresh method handler requires the following capabilities:
- Find out if a subscription ID belongs to a session
- Get the monitored items for a subscription and check for matching retained conditions using the event filter
- Insert event notifications into the queue of a subscription

Is there a way to do this using the public server API or is this a feature like the GetMonitoredItems method that should be implemented inside the library?

**Comment by Pro** [comment]
To check if a subscription belongs to a session you can use `UA_Session_getSubscriptionById` which will return NULL if it doesn't belong to the session.
https://github.com/open62541/open62541/blob/02734c310dc4f29a45879eeae1e1b7f63d9c9c12/src/server/ua_session.h#L86

You then use the returned subscription to get the monitored item with `UA_Subscription_getMonitoredItem`
https://github.com/open62541/open62541/blob/02734c310dc4f29a45879eeae1e1b7f63d9c9c12/src/server/ua_subscription.h#L206

Then you probably need the method here `UA_Event_addEventToMonitoredItem`
https://github.com/open62541/open62541/blob/02734c310dc4f29a45879eeae1e1b7f63d9c9c12/src/server/ua_subscription_events.c

Apart from the last one, the first two are only available in the internal API and if it is not really necessary to move them to the public API, we should keep them internal.
If you could reuse the last one to add an event to a monitored item, then we can also change it from static to internal API.

Does that somehow answer your question?
