### ISSUE TITLE
missing UA_Client_Subscriptions_addMonitoredItem [help wanted] [client]

### ISSUE THREAD

**Issue by fabian727** [open62541/open62541#1964]
I am missing the function UA_Client_Subscriptions_addMonitoredItem in the active master-branch/ release. It was here included, now it is missing: [https://github.com/open62541/open62541/blob/d5317cb2e590fab56adbbef75fd5a6255a954fde/include/ua_client_highlevel.h#L603](https://github.com/open62541/open62541/blob/d5317cb2e590fab56adbbef75fd5a6255a954fde/include/ua_client_highlevel.h#L603)

Is there a reason or alternative path to add Items to a subscription?

**Comment by StalderT** [comment]
You can check the example here : 

https://github.com/open62541/open62541/blob/59a3cfb8567abefe3f8f2f2f8bddfcf45f32e391/examples/client_subscription_loop.c#L74-L83

**Comment by fabian727** [comment]
but there is for each monitored node a single subscription
[https://github.com/open62541/open62541/blob/59a3cfb8567abefe3f8f2f2f8bddfcf45f32e391/examples/client_subscription_loop.c#L64-L83](https://github.com/open62541/open62541/blob/59a3cfb8567abefe3f8f2f2f8bddfcf45f32e391/examples/client_subscription_loop.c#L64-L83)

**Comment by StalderT** [comment]
You can call ```UA_Client_MonitoredItems_createDataChange``` multiple times for the same subscription. You can store ```response.subscriptionId``` value (while the subscription is valid).

**Comment by jpfr** [comment]
The old API was deprecated for 0.3 and removed for 0.4.

You can use UA_Client_MonitoredItems_createDataChanges to add many monitored items at once.
The relevant header file is comparably short and documented...
