### ISSUE TITLE
redduced portability 

### ISSUE THREAD

**Issue by Hootan-Man** [open62541/open62541#1968]
https://github.com/open62541/open62541/blob/59a3cfb8567abefe3f8f2f2f8bddfcf45f32e391/arch/ua_network_tcp.c#L565

I'm not sure. though, I wanted to discuss it with you guys.
isn't it better to use UA_free() instead of free() here ?!!!

**Comment by Pro** [comment]
Yes, there should also be use UA_free. Fixed in the referenced PR #1976
