### ISSUE TITLE
[Windows Build error] CMake build failed

### ISSUE THREAD

**Issue by mukunth1987** [open62541/open62541#1969]
Description
===========
Cloned the latest code and tried to build as per the instructions.
cmake .. -G "Visual Studio 2015" failed with below error

CMake Error at CMakeLists.txt:36 (string):
  **_string sub-command REPLACE requires at least four arguments._**

-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE)
-- Could NOT find LATEX (missing: LATEX_COMPILER)
-- Configuring incomplete, errors occurred!

Background Information / Reproduction Steps
===========================================
1) cmake v3.11.4
2) python 3.7
3) Visual Studio 2015
4) Git v2.18.0

Steps:
     1) git clone <open62541>
     2) mkdir build
     3) cd build
     4) cmake .. -G "Visual Studio 2015"

Followed the build instructions. But cmake build failed with :
**_string sub-command REPLACE requires at least four arguments._**

in CMakeLists.txt, error occurs in the below line
string(REPLACE "\n" "" OPEN62541_VER_COMMIT ${GIT_COM_ID} )

but if I add double quotes to the last argument, it works fine.
string(REPLACE "\n" "" OPEN62541_VER_COMMIT "${GIT_COM_ID}" )

Please let me know your opinion on this.

**Comment by mukunth1987** [comment]
[UPDATE]
It looks like GIT_COM_ID output variable is empty after 

execute_process(COMMAND ${GIT_EXECUTABLE} describe --always --tags
                    RESULT_VARIABLE res_var OUTPUT_VARIABLE GIT_COM_ID WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})

But if run "git describe --always --tags" in command prompt, it displays the output. But its not stored in GIT_COM_ID.

Any opinion on this ?

**Comment by Pro** [comment]
It looks like you are using cmake and git in two different shell environments.
Could it be that cmake is not able to find the git executable in the PATH environment?

We should add an additional check here:
https://github.com/open62541/open62541/blob/808239dc8ac79a7ee9b712a23ddcedd61ee38794/CMakeLists.txt#L34 to handle empty GIT_COM_ID

**Comment by Pro** [comment]
Can you try to add the patch from #1975 and see if that solves your issue?
(It will also be merged to master)

**Comment by mukunth1987** [comment]
hi @Pro 
I uninstalled git v2.18.0 64-bit installer and installed 32-bit version of the same installer. After that, build worked fine.
