### ISSUE TITLE
open62541 Rasp Geany

### ISSUE THREAD

**Issue by DB780** [open62541/open62541#1987]
Hi there

I want to use open 62541 with raspberry.
I have download the raspberry pi program from https://open62541.org/
I use geany to program, build and compile.
Got error with building the software.

![20180817_095549](https://user-images.githubusercontent.com/42464296/44256011-293b7280-a208-11e8-81f6-bcbb93b7e320.jpg)

What is going wrong???

**Comment by Infinity95** [comment]
Seems to me like you are not linking the open62541.c file
