### ISSUE TITLE
Windows Compact Embedded

### ISSUE THREAD

**Issue by TechAspirant** [open62541/open62541#2007]
Hello,

Anyone have compiled open62541.c & open62541.h latest release 0.3rc2 for windows compact embedded 6.0 , 7.0 or 2013 ?

**Comment by crafti5** [comment]
Yes I have done this, but I haven't time to publish this as a pull request. But I can try to upload the amalgated version. If someone can apply this to current master brnach?

**Comment by TechAspirant** [comment]
Hello,
can apply this to current master branch? How can I as I am new to github ?

**Comment by TechAspirant** [comment]
@crafti5 Please tell me how can I make request for your windows embedded solution ?

**Comment by crafti5** [comment]
@TechAspirant I dont know what you mean, I have changed amalgated files and there is a need to get this as a new arch.

**Comment by crafti5** [comment]
I have created a pull request: https://github.com/open62541/open62541/pull/2026

**Comment by jpfr** [comment]
This was added with #2059.
