### ISSUE TITLE
Certification, Encryption and user authentication [help wanted]

### ISSUE THREAD

**Issue by fabian727** [open62541/open62541#2008]
Hi again,

at the moment I am trying to make my server/ client secure

Certification and Encryption is documented well and was no problem.
But:
1. How can I force Certifcation-Usage and Encryption on the server? I think with describing the endpoints? I used 'UA_ServerConfig_new_basic256sha256' to create my server-configuration. Why do exist 3 endpoints after creation? Two seem to be identical (Security #None , two userTokens ANONYMOUS and USERNAME)
1.5 I tried to remove all Endpoints and recreate only the one with encryption, but there is no "UA_Endpoint_delete" function. Just a "UA_EndpointType_delete". Was it your intention or did you miss to create it?
2. the client can connect with username and password. What does the server do with this information? I couldn't gather any information about it. How can I allow an user to call methods/ variables etc or how can I deny it?
3. Are there any examples? I only found those under "access control"

**Comment by schroeder-** [comment]
1. Your best starting point is to copy UA_ServerConfig_new_basic256sha256 and modify the function to only create the endpoints you want.
2. Also here is to have a look at plugins/ua_accesscontrol_default.c and implement your custom UA_AccessControl, you supply to UA_ServerConfig.
