### ISSUE TITLE
[server] [discovery] ServerCapabilities

### ISSUE THREAD

**Issue by fabian727** [open62541/open62541#2009]
@jpfr  Part 4 of the specification (chapter 6.3.2) states that every server could have a capability. Why did you pack it into the Discovery-Part? I think it should be part of the config at every point of time

[from here](https://github.com/open62541/open62541/blob/master/include/ua_server_config.h#L74)
```c
#ifdef UA_ENABLE_DISCOVERY
    UA_String mdnsServerName;
    size_t serverCapabilitiesSize;
    UA_String *serverCapabilities;
#endif
```

so more like this:
```c
#ifdef UA_ENABLE_DISCOVERY
    UA_String mdnsServerName;
#endif
    size_t serverCapabilitiesSize;
    UA_String *serverCapabilities;
```

**Comment by fabian727** [comment]
What is about the ServerCapabilites?

**Comment by Pro** [comment]
The value of server capabilities is only read and used for the multicast discovery functionality.
As long as discovery is disabled, the server capability is not needed and that is why it is correctly within the ifdef.
