### ISSUE TITLE
Event validity is not checked properly when applying event filter

### ISSUE THREAD

**Issue by sqadasi** [open62541/open62541#2027]
Hello everyone!

I have noticed that UaExpert is specifing the BaseEventType in the SimpleAttributeOperand of all Clauses (properties/ Fields of the EventType) except for the Clause "CondtionId", which has the NodeId of the ConditionTypeNode and is always present in the selectClauses array set by UaExpert (from part 9, which is not implemented yet in open62541. Note: "CondtionId" is not explicitly modelled as component of the ConditionType, but should be provided by the Server. Please refer to Part 9, 5.5.2, Page 20, Table 10). UaExpert also specifies the BaseEventType for Clauses of the ConditionType and its Subtypes as well as for the Clauses of the AuditEventType and its Subtypes. That behaviour of UaExpert is complaint to the part 4 specs. (Please refer to Part 4, 7.17.3, Page 133)

So, when using UaExpert, it is true for all Clauses except "CondtionId", that the condition in the following code snippet will alway be evaluated as False and thus the SimpleAttributeOperand will be resolved. (no problem until now)
https://github.com/open62541/open62541/blob/3b4f84f248f5e14999da6afd0179979b51898fb0/src/server/ua_subscription_events.c#L250

However, for the "CondtionId" Clause, or when using other UA Clients (OPC Foundation Demo Client and Softing), where the real EventTypes are specified in the SimpleAttributeOperand, the previous code snippet will be evaluated as True and thus the other check will be evaluated:
https://github.com/open62541/open62541/blob/3b4f84f248f5e14999da6afd0179979b51898fb0/src/server/ua_subscription_events.c#L251

Problems:
1) Here, I think that the actual selectClauses[ i ] should be passed instead the first selectClauses[ 0 ]. The typeId of selectClauses[ 0 ] depends on the first Clause set by the client filter (However, when using UaExpert, the typeId of the first Clause is always BaseEventType).

2) The function
https://github.com/open62541/open62541/blob/3b4f84f248f5e14999da6afd0179979b51898fb0/src/server/ua_subscription_events.c#L138
checks whether the EventType Property is present, but then checks whether the **EventType Property NodeId** is a SubType of the passed "validEventParent" (which is a BaseEventType or a subtype of it), and this will be always evaluated as False and thus, the SimpleAttributeOperand won't be resolved. With this manner, the values of the fields of the subTypes of BaseEventType won't show up in the Event View of UA Clients other than UaExpert! 
I think here we have to get the **value of the EventType Property** (which is the NodeId of the EventType) and check whether it is a subType of the BaseEventType. However, we should check first that the EventType is not a subType of ConditionType (not supported yet) so "CondtionId" Clause won't be resolved, and thus a "CondtionId" Field won't show up in the normal events.

@aDogCalledSpot, what do you think? should I make a PR to change/correct that behaviour? 

Best regards

**Comment by aDogCalledSpot** [comment]
Well spotted, both of these things are certainly mistakes. I would appreciate a PR.
