### ISSUE TITLE
UA_Client_addObjectNode() throws BadRequestHeaderInvalid

### ISSUE THREAD

**Issue by NIPE-SYSTEMS** [open62541/open62541#2046]
I've found something odd: When I run the code below in a client, this will throw the following error on the client-side:

```
2018-09-05 16:40:09.116 DEBUG [client]  Sending a request of type 486
2018-09-05 16:40:09.182  INFO [client]  Error receiving the response with status code BadRequestHeaderInvalid
```

When I'm adding a debugging breakpoint at the position `// breakpoint here`, everything runs fine without any errors. Because of that I'm guessing that I've created a race-condition. I'm running `UA_Client_run_iterate()` in a separate thread and calling the below code from the main thread. open62541 (93c4d6caf2ff660042f7a46e1fc46cd3712a95bf) is built with `-DUA_ENABLE_ENCRYPTION=ON -DUA_ENABLE_SUBSCRIPTIONS_EVENTS=ON -DUA_NAMESPACE_ZERO="FULL" -DUA_LOGLEVEL="100"`. I'm running this via Visual Studio 2015 on Windows 10.

Do you have any tips on how to write a client with its own thread and the possibility to interact with it from another thread?

Thanks in advance!

```cpp
UA_NodeId nodeIdElement;
UA_ObjectAttributes attr = UA_ObjectAttributes_default;
attr.displayName = { UA_STRING_STATIC(""), UA_STRING_STATIC("__dummy__") };
attr.description = UA_LOCALIZEDTEXT_STATIC("", "???");
UA_StatusCode r = UA_Client_addObjectNode(
    getApiUaClient(),
    UA_NODEID_NUMERIC(ns, 0),
    UA_NODEID_NUMERIC(ns, m_ua_client_id),
    UA_NODEID_NUMERIC(0, 47), // hasComponent
    { ns, UA_STRING_STATIC("__dummy__") },
    UA_NODEID_NUMERIC(ns, 1001), // ElementType
    attr,
    &nodeIdElement
);
// breakpoint here
if(r != UA_STATUSCODE_GOOD) {
    return false;
}
```

**Comment by jpfr** [comment]
There is some preliminary work for multithreading in the server.
But this is nowhere complete.

You are advised to protect the client from parallel access with a muted.
You can for example wrap the muted locking around the call to client_run_iterate and addObjectNode.

Please reopen if required.
