### ISSUE TITLE
Getting node id from monitor id when using subscriptions

### ISSUE THREAD

**Issue by falknerdominik** [open62541/open62541#2049]
Description
===========
Hi, 

for my purpose it would be very useful to have the node id (string id) when a value is updated. I could not find any way to do this using the `UA_Client_MonitoredItems_createDataChange` method without keeping track of every monitored item myself. This callback provides me with the data but I did not find a way to get the node id at this point.

```
typedef void (*UA_Client_DataChangeNotificationCallback)
    (UA_Client *client, UA_UInt32 subId, void *subContext,
     UA_UInt32 monId, void *monContext,
     UA_DataValue *value);
```

Background Information / Reproduction Steps
===========================================

I am trying to make a more generic approach to read many data values (This is necessary because sensors in my system can change multiple times a year and i do not want to configure every sensor manually).

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): 0.3-rc2
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: linux/busybox
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by fabian727** [comment]
same here. I made myself a table and store the subscription Id, monitoring Id and NodeId in it. EveryTime I get an update, I research this database. It's the fastest I found.

just a guess: you could try to save the NodeId in the monContext, then you have it available in the function itself. Maybe its faster? (didn't try it yet)

**Comment by falknerdominik** [comment]
Mhh that is atleast a solution. 

@fabian727 do you have an example on how to set the monContext (could not find any in the documentation)?

**Comment by fabian727** [comment]
I am sorry, I do not have at the moment. I re-search my array every time at the moment.

As your cited code already shows, you have the variable void* monContext. You have to redirect this pointer to a global available variable / array, which holds the nodeId. If I update my code to this I will post it.

**Comment by Pro** [comment]
You can use the following steps to get the monitored node id:

Use the provided `subId` with `UA_Session_getSubscriptionById` which will return the associated subscription:
https://github.com/open62541/open62541/blob/02734c310dc4f29a45879eeae1e1b7f63d9c9c12/src/server/ua_session.h#L86

Then get the monitored item using `monId` with `UA_Subscription_getMonitoredItem`
https://github.com/open62541/open62541/blob/02734c310dc4f29a45879eeae1e1b7f63d9c9c12/src/server/ua_subscription.h#L206

In the returned `UA_MonitoredItem` you will find the data you need, i.e. `monItem->monitoredNodeId`.

Have a look at
https://github.com/open62541/open62541/blob/c5d730af2983ed1dbfad930819776c1ef72fee65/src/server/ua_subscription.h#L85

If this does not solve your issue please reopen.

**Comment by fabian727** [comment]
@Pro If I search my amalgated header file: open62541.h I do not find the function "UA_Session_getSubscriptionById". Though I can find it in the library open62541.a.

Shouldn't it be in the header too? Am I missing something? I just updated my repo again, though this code was merged 6 months ago.

**Comment by Pro** [comment]
Oh sorry, yes, you are right, these are only internal API functions.

@jpfr should these two methods made public? Then we have to make sure that the user can not change the returned objects (i.e. make them const).

**Comment by jpfr** [comment]
I would be against making UA_Session_getSubscriptionById public.
Neither `UA_Session` nor `UA_Subscription` are public at the moment.

We have the possibility to add a "context" pointer to both subscriptions and monitoreditems.
This is precisely why we added them. The "context" pointers are automatically forwarded to the respective callbacks.

**Comment by Pro** [comment]
We could also implement a method which would take the monitored item id and session id and just return the monitored node id (by using the methods I mentioned earlier).
That would still keep all the structures private and only return a node id. Would that make sense?

Something like:
```
UA_StatusCode UA_Server_getMonitoredNodeId(UA_UInt32 subscriptionId, UA_UInt32 monitoredItemId, UA_NodeId *outNodeId);
```

**Comment by fabian727** [comment]
@Pro I like your idea. Sounds to me safe and good for the user

**Comment by Pro** [comment]
Oh sorry, I mixed server and client functionality. It's not that easy to 'just' implement such a method for the client since it does not know all the monitoredItemId and NodeId mappings.

For now, the only solution to get the monitored node id from a data change notification is, that you store the node Id as the context pointer for the monitored item in `UA_Client_MonitoredItems_createDataChange`

Please reopen if you have additional questions!
