### ISSUE TITLE
Compilation error: undefinded reference to 'clock_gettime'

### ISSUE THREAD

**Issue by Nodrein** [open62541/open62541#2056]
Description
===========
Hello,

I can't build a opc-ua server after the description of the documentary from open62541, 3.2 Building a simple server [open62541.zip](https://github.com/open62541/open62541/files/2382059/open62541.zip). The pdf-file is in the folder too.
I execute the order
`$ gcc -std=c99 open62541.c myServer.c -o myServer`.
But the result is
`/tmp/cck8ArJt.o: In function UA_DateTime_nowMonotonic':`
`open62541.c:(.text+0x48f7e): undefined' reference to 'clock_gettime'`
`collect2: ld returned 1 exit status`.

Have anyone a solution for this issue?

Thanks,

Nodrein

Background Information / Reproduction Steps
===========================================
I have a begale board - a computer like the raspberry pi - with Linux begalebone on it.
To build this server I used the documentary open62541, release 0.4.0-dev, SEP 11, 2018.
I execute the order in the directory /home/debian/open62541/. In this folder are two files from open62541 and one file called myServer.c writen by me after the discription of open62541 
[open62541.zip](https://github.com/open62541/open62541/files/2382058/open62541.zip). I downloaded the files from [open62541/releases](https://open62541.org/releases/). It is the version c5d730af29 from 2018-09-11 15:36:47 +0200.

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): c5d730af29
 - [ ] Other OPC UA SDKs used (client or server):  /
 - [x] Operating system: Linux beaglebone 3.8.13-bone50 - I think a debian linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached: /
 - [ ] Wireshark network dump attached: /
 - [ ] Self-contained code example attached: /
 - [x] Critical issue: compilation error

**Comment by Pro** [comment]
Did you google for the issue first?

There are many solutions in the web, e.g. this one:
https://stackoverflow.com/a/2418175/869402

> Add -lrt to the end of g++ command line. This links in the librt.so "Real Time" shared library.

I.e.:

`gcc -std=c99 open62541.c myServer.c -o myServer -lrt`
