### ISSUE TITLE
CERN uses open62541

### ISSUE THREAD

**Issue by fabian727** [open62541/open62541#2074]
@Stasik0 
I do not know what they are using of this stack (or if they still use it), but 
CERN has internal servers to bridge canopen over OPC UA and state they use open62541
[github](https://github.com/quasar-team/quasar)
[docu](https://readthedocs.web.cern.ch/display/ICKB/OPC-UA)
[artikel i found about it](https://opcconnect.opcfoundation.org/2015/06/opc-news/)

just wanted you to know about it. Maybe you can reference their repo in your wiki

**Comment by jpfr** [comment]
Thanks for pointing this out.

Actually, OPC UA is making inroads to large-scale physics projects in general.
There is also the particle accelerator at HZDR that uses open62541.

http://accelconf.web.cern.ch/AccelConf/icalepcs2017/papers/thpha166.pdf

**Comment by jpfr** [comment]
I added the reference to the wiki.
