### ISSUE TITLE
How to update value of an instantiated object node

### ISSUE THREAD

**Issue by theresa95** [open62541/open62541#2097]
I have defined one object type, which is called TemperatureSensorObjectType and instantiated it three times as I have three temperature sensors with different locations. Each temperature sensor has a location and a temperature value. So far, so good. The implementation is mainly copied from the open62541 tutorial "Objects and Object Types":
https://open62541.org/doc/0.2/tutorial_server_object.html#

What I am trying to do is to update the temperature value attribute from one specific temperature sensor object. Let's say TempSens2. But I do not know how to differentiate between those three temperature sensor objects. I know every object has its own node id and its own specific qualifiedname/displayname as I pass the name when adding a new instance. But if I want to write on a attribute of a specific object with help of the UA_Server_writeValue() method, I need the nodeID. So is there a way to get the nodeID by the qualifiedname/displayname? And what does the number on UA_NODEID_STRING(1, "TempSens2"); mean?

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system: Ubuntu 18.04.1 LTS
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
- The first number in the node id is the namespace. The second number is part of the string and has no special meaning
- You  can use the Browse Service and the TranslateBrowsePathsToNodeIds Service to find the NodeId of the temperature below some specific object

https://open62541.org/doc/current/services.html#browse-service
