### ISSUE TITLE
Read and subscribe to nodes that contain a list of nodes.

### ISSUE THREAD

**Issue by falknerdominik** [open62541/open62541#2098]
Description
===========
I want to read from a list of floats from a single node with the client implementation. For that I create a simple subscription and monitor the node. When the node is updated the callback is invoked correctly but the documentation did not yield any information on how to access the array and the values contained in it (e.g. checking the type of the value attribute (it's not a float), reading the values, ...). Do you have any information on this.

Background Information / Reproduction Steps
===========================================

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): 0.3-rc2
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
The callback gives you an UA_DataValue.
https://github.com/open62541/open62541/blob/master/include/ua_client_subscriptions.h#L125

The DataValue contains timestamps, statuscode and a variant.
The variant can hold any datatype and any size of scalar / vector / matrix / ...
You can get all the type information from the variant.
https://open62541.org/doc/current/types.html#variant
