### ISSUE TITLE
make fails on master branch

### ISSUE THREAD

**Issue by crosland** [open62541/open62541#2107]
Description
===========
Trying to build from source.
Ubuntu 16.04.5 in Windows 10 Hyper-V VM
Cloned the master branch today (10th Oct '18) into a new directory
Followed the instructions here https://open62541.org/doc/current/building.html to install required packages and build

Running 'make' fails with unused variable 'sub' at line 160 of src/server/ua_subscription_monitoreditem.c

Commenting this line seems to allow make to run successfully.

Background Information / Reproduction Steps
===========================================

Checklist
=========
Please provide the following information:

 - [ master] open62541 Version (release number or git tag):
 - [n/a ] Other OPC UA SDKs used (client or server): 
 - [Ubuntu 16.04.5 in Windows 10 Hyper-V VM ] Operating system:
 - [n/a ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [n/a ] Wireshark network dump attached
 - [ n/a] Self-contained code example attached
 - [ No] Critical issue

**Comment by jpfr** [comment]
fixed via #2108.
