### ISSUE TITLE
Retransmission queue size issue in CTT 1.3

### ISSUE THREAD

**Issue by jonasgreen88** [open62541/open62541#2110]
Description
===========
Hi,

We ran into a new issue in the CTT 1.3 yesterday. It's concerns the retransmission queue of DataChange subscriptions. The specification (Part 4, chapter 5.13.1.1) says "Sessions maintain a retransmission queue of sent NotificationMessages.". I treat that as the session should have one retranmission queue for all its DataChange Subscriptions. In Open62541, a retransmission queue is managed by each DataChange Subscription instance. This design choice that deviates from the specification does now show up as an issue in CTT for us.

Assume the server is configured to accept 2 publish requests per session and that the retransmission queue is configured to its required minimum size according to the specification (Part 4, chapter 5.13.1.1): "The Session shall maintain a retransmission queue size of at least two times the number of Publish requests per Session the Server supports". The queue is then configured to store 4 notification messages.

The CTT has a setting named "Retransmission QueueSize" that we set to 4. In that case the test cases "Monitored Items – Monitor Basic -018" and "Subscription Basic - 52" fail. The test sets up 2 instances of DataChange Subscriptions on a single session with one monitored item each. Without giving the server publish requests it changes the value of the monitored parameters 3 times each. After that it sends publish requests to receive the data notifications stored in the retranmission queue of the session. Finally it sends another publish request to acknowledge the received notification messages. However, as we have configured the retransmission queue size to 4, it only acknowledges 4 notification messages and then the test fails as there are another two notification messages unacknowledged. As Open62541 manages one retransmission queue per subscription, it can store all 6 data changes, 3 per subscription. If we change the "Retransmission QueueSize" to 6 the test acknowledge all 6 notification messages and the test case passes.
But if we set the "Retransmission QueueSize" setting to 6 in CTT, the test case "Subscription Minimum 1 – 001" fails instead. In this case CTT verifies the queue length with only one subscription, which is 4.

So, with the current design choice made in Open62541 we cannot pass the CTT with one configuration. The design of Open62541 makes the retransmission queue length dynamic on the session depending on the number of subscriptions. According to the specification the queue shall be managed by the session and have the same length independent of how many subscriptions that are created. As described above, this behavior is also verified by CTT.

Background Information / Reproduction Steps
===========================================
Setup a server that accepts 2 publish requests per session. Configure the retransmission queue size to 4 (minimum length according to the specification when accepting 2 publish requests). Run the CTT test cases "Monitored Items – Monitor Basic -018", "Subscription Basic - 52" and "Subscription Minimum 1 – 001".

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): cce2d62  
 - [x] Other OPC UA SDKs used (client or server): CTT as client
 - [x] Operating system: Windows 7 and embedded os
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [x] Critical issue

**Comment by jpfr** [comment]
Confirmed.
We should move the retransmission queue to the session.
Maybe we can do this for 0.3 and the cherry-pick on master.

**Comment by jpfr** [comment]
Does this PR fix the issue for you #2125 ?

**Comment by jonasgreen88** [comment]
Thanks for the PR! 

I will participate in the OPC IOP Workshop in Nürnberg this week. I will try to find some time to integrate this fix and test it. Else I will check it out next week!

**Comment by jpfr** [comment]
Cool! A colleague from Fraunhofer IOSB is participating as well.
I will tell him to say hi. 😄

**Comment by StalderT** [comment]
Any news about this issue?

**Comment by jonasgreen88** [comment]
A colleague  to me tested this fix last week with the CTT test cases that failed but it didn't pass. I haven't seen the logs yet, hopefully I will have time to look into it next week.

**Comment by jonasgreen88** [comment]
> Does this PR fix the issue for you #2125 ?

@jpfr We can confirm that this PR solves the issue!

**Comment by jpfr** [comment]
Great!
