### ISSUE TITLE
XML Nodeset compiler: generated code emits various errors, array nodes are not created

### ISSUE THREAD

**Issue by mtenberge** [open62541/open62541#2119]
**Edit**: the example case in the original issue body is no longer up-to-date. See the newer discussion messages for an updated case.

---

What am I trying to do?:
- I created a minimalistic project in Siemens TIA Portal for an S7-1500 PLC (which includes an OPC-UA server).
- I exported the OPC-UA server configuration as an UANodeSet xml file.
- Goal: I want to run an open62541 OPC-UA server and load this UANodeSet, so it has the same nodes as the Siemens PLC.

**Self-contained example**: [simatic-opcua-demo.zip](https://github.com/open62541/open62541/files/2491840/simatic-opcua-demo.zip)

- Extract the zip, and place the open62541 tree under the folder with that name
- Run `original.sh` to encounter the first problems.
- I made some workarounds for these errors, to try to get a bit further. They are described below. Run `workarounds.sh` to see the situation with those workarounds applied. At this point I'm really stuck...

Problems and workarounds:
=====
1 The generated namespace setup code for my UaNodeSet XML file does not compile.
---
--> Run `original.sh` to see what happens.
(you should see various compilation errors while compiling `ua_namespace_simatic.c`, such as `error: ‘UA_TYPES_SIMATIC_BYTE’ undeclared (first use in this function); did you mean ‘UA_TYPES_SIMATIC’?`)

What happened?
Most UAVariable nodes in the Siemens file make use of Alias datatypes (such as _BYTE_, see line 28 of the XML file). These aliases point to nodes in the XML file, such as `ns=3;i=3001`. These nodes are defined as Subtype of the standard OPC data types, such as Byte (i=3). This is done via a reverse `HasSubtype` reference.
The first problem here is, that array index constants are generated for these types (for example UA_BYTE) by the nodeset compiler, but these types (including their constants or their array positions) are not produced by the type compiler.

Workaround: I modified the Aliases, so they point directly to the standard OPC-UA types, instead of to the Siemens subtypes. See `tools/replace_aliases.sh`.

What more?
The enum values node ns=3;i=6083 is not generated (correctly), so the UAVariable node ns=3;i=6071 encounters an undefined type `UA_TYPES_SIMATIC_SIMATICOPERATINGSTATE`.

Workaround: I replaced this data type by a simple Int. See the last line of  `tools/replace_aliases.sh`.

What more?
The data type STRING (see line 29) generates an array index constant with the name UA_STRING. This name collides with the helper function/macro UA_STRING, so compilation is screwed up.

Workaround: replace specific occurrences of UA_STRING (the ones which are not followed by a `(` character) with something else. See `tools/replace_uastring.h`.

2 Everything compiles, but nodes with arrays are not created
---
With the abovementioned workarounds, the code compiles.
--> Run workarounds.sh to see what happens next.

While creating namespace 3, using the generated function `ua_namespace_simatic()`, _all nodes that contain arrays_ are rejected with an error message:
`Type of variable node ... must be VariableType and not cannot be abstract`

After that, the child nodes (those that describe the individual array elements) are rejected with
`Parent node ... not found`

After all nodes are processed (and most are rejected), some other errors appear, which seem to concern the rejected nodes:
`WriteRequest returned status code BadTypeMismatch`
`AddNodes: Type-checking the variable node failed with error code BadTypeMismatch`

Finally, the server can be started, but the nodes that threw errors are not available.

Background Information / Reproduction Steps
===========================================
**input file**
The input file `testPLC.OPCUA.xml` is an unmodified export from Siemens TIA Portal (the development/configuration/commissioning software for Siemens PLCs).
Four namespaces are defined in this file:
0. default
1. urn:SIMATIC.S7-1500.OPC-UAServer:testPLC: this is the name of the Siemens OPC-UA server in this project. In the actual PLC, this namespace contains some data about the OPC-UA server itself, but these nodes are not included in the XML file.
2. http://opcfoundation.org/UA/DI/
3. http://www.siemens.com/simatic-s7-opcua: this namespace contains the user-defined data in the PLC project, including the custom-made types (structs etc) in the project.

**TypeDictionary**
Node "ns=3;i=6001" (see line 1252) holds the TypeDictionary for this namespace, encoded as base64.
I wrote a small utility to extract this data, the resulting file is simatic.types.bsd ( which is included in the zip file).

**Namespace 2**
The types and node setup code for namespace 2 can be generated and executed without errors.

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): git master 271c944049d0b33435f43ced139f5d76fcafadc3
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Debian Linux 9 and 10, amd64
 - [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached: see inline in the text above
 - [ ] Wireshark network dump attached
 - [x] Self-contained code example attached: the attached zip-file demonstrates the problems
 - [x] Critical issue: well, it doesn't work as expected, is that critical? :-S

**Comment by Pro** [comment]
Thanks for your bug report.
I had a thorough look at the nodeset you provided and got it up and running:
https://github.com/Pro/open62541/tree/testing/simatic

First things first:
The generated NodeSet has some issues:
 * I had to change the TypeDefinition of some nodes from `BaseVariableType` to `BaseDataVariableType`:
https://github.com/Pro/open62541/commit/314e1d3ee57d8b94c9f21229050eccc0faa8a7c3#diff-84d06cfcf0c11809ffdb285531f8e4beR738
Since these are Data Variables within a variable, these type definitions should IMHO be of type BaseDataVariableType
* The type `STRING` and `BYTE` are in general UA types reserved to the official specification, using the same names but just different capitalization is just **bad practice**. Anyways we should try to find some workaround for that case.
* Currently we do not support generating types and node ids directly out of the NodeSet.xml file. To use the nodeset compiler, you first need to generate the data types. For this the `generate_datatypes.py` script requires two files, a .bsd and a .csv file. I manually crafted them with the information from the NodeSet.xml here https://github.com/Pro/open62541/commit/314e1d3ee57d8b94c9f21229050eccc0faa8a7c3
* The `generate_datatypes.py` script currently does not support extending the opaque types (as it is used in the Simatic NodeSet for `STRING` and `BYTE`). This issue is probably solved by automatically extracting the info from the NodeSet. See https://github.com/Pro/open62541/commit/314e1d3ee57d8b94c9f21229050eccc0faa8a7c3#diff-93ecdee5f7a3bc4baaba978caee35160
* The ByteString in the NodeSet.xml (in this Case `NodeId="ns=3;i=6001" BrowseName="3:SimaticStructures"`) should normally contain all the data types used in the node set, but it only contains this: https://github.com/Pro/open62541/commit/314e1d3ee57d8b94c9f21229050eccc0faa8a7c3#diff-06d6c10965639f83e00048723398fad5 I had to manually extend it to include some missing definitions: https://github.com/Pro/open62541/commit/62c06f787c17d44e18142f04ada7bc017302e131#diff-88f1c987ce8b37aa7a5f0e25a994cd01

Open issues to be fixed from our side:

- [ ] Handle type names in the nodeset correctly, if they collide with a name which may already be defined in another nodeset. We should probably add a prefix to the generated types, if they do not belong to NS0. E.g. `generate_datatypes.py` creates:
```c
/**
 * "udtDemo2"
 * ^^^^^^^^^^
 */
typedef struct {
    UA_Byte byteFirst;
    UA_Byte byteSecond;
    UA_Int16 intFirst;
    UA_Int16 intSecond;
} UA_udtDemo2;

#define UA_TYPES_SIMATIC_UDTDEMO2 0

/**
 * STRING_SIMATIC
 * ^^^^^^^^^^^^^^
 * Simatic String */
typedef UA_String UA_STRING_SIMATIC;

#define UA_TYPES_SIMATIC_STRING_SIMATIC 2
```
We should add a prefix to the typedefs, e.g. to something like `UA_SIMATIC_udtDemo2` or make this prefix optional and configurable through command line args

- [ ] Automatically extract the .bsd file and the .csv file from the NodeSet.xml file and then use something similar to the `generate_datatypes.py` script to also generate the types definition. This should all be done in one run.

**Comment by mtenberge** [comment]
Thanks a lot for investigating this so far.

I assume that some of the diffs in your simatic-tree are just temporary, to get a working build, until a better fix is available?
For example, I have the feeling that hard-coding the data types in opaque_type_mapping.py is not the right final solution. All required information is available to the nodeset compiler, so it should be able to figure it out during runtime.
For example, this alias definition:
```xml
<Alias Alias="BYTE">ns=3;i=3001</Alias>
```
and the contents of this node (especially the 'HasSubtype' reference):
```xml
<UADataType NodeId="ns=3;i=3001" BrowseName="3:BYTE">
    <DisplayName>BYTE</DisplayName>
    <Description>BYTE is a bit string of 8 bits B#16#0 to B#16#FF.</Description>
    <References>
        <Reference ReferenceType="HasSubtype" IsForward="false">i=3</Reference>
    </References>
</UADataType>
```
together contain the same information as the entry in opaque_type_mapping.py:

```python
    'BYTE': {
        'ns': 0,
        'id': 3,
        'name': 'Byte'
    }
```

I have no control over the software that generates the NodeSet xml, so I'm stuck with the way the xml-file is generated. On the other hand, simply replacing all occurrences of i=62 with i=63 is not so difficult ;-).

However, it seems to me (but I'm no UA expert...) that there is a valid reasoning behind the existence of both `BaseVariableType` and `BaseDataVariableType`:
In the currently generated namespace setup code, the array node (the 'parent') is created first, and filled with initial data. After that, the individual elements are created and filled with initial data.
So each item is filled twice.
If the parent is a `BaseVariableType` and the childs are `BaseDataVariableType`, shouldn't that mean that the parent doesn't need to be initialized, because initialization will happen when the childs are created?


The example I provided is just a minimal example. The OPCUA.xml-file as exported from a 'real' PLC project is a lot larger, typically over 100MB (!), and also uses more types than just BYTE and STRING. These system-defined types (those for which an Alias is created) are mostly known in advance, but in each release of the development software, new types may be added, or their underlying base type changed (for example, some of these types went from Int16 to UInt16).
This large size means that manually modifying the file, or hand-crafting extra files, is not really doable anymore. It also requires a bit of patience: type generation, nodeset compiling and the final C compilation takes about 15 minutes and peaks at 11 GB RAM usage...  :grimacing:

If you are interested, I can send you such an xml-file, as long as it is not made public.

**Comment by jpfr** [comment]
@Pro fixed the string nodeid faults in #2123.

**Comment by Pro** [comment]
Thanks for the updated examples!
I'll try to have a look at it in the coming days.

**Comment by Pro** [comment]
Sorry for my late reply.
I just had another look at your issue. The nodeset is unfortunately still incomplete.

In the meantime we introduced some additional checks and the datatype generation now fails with:

> RuntimeError: NodeId for CONN_ANY not found in .csv file

The .csv file needs to have a node id mapping for the CONN_ANY name (and probably many more).

This node id is used to select the correct binary encoding id.

**Comment by Pro** [comment]
@mtenberge can you check my feedback and update your branch onto the current master?

**Comment by mtenberge** [comment]
Thanks for the update, I'll try to do that this week. Otherwise it will be after the summer holidays :-)

**Comment by mtenberge** [comment]
I just rebased https://github.com/mtenberge/open62541/tree/testing/simatic-uanodeset-without-manual-changes on the current master.
The script to modify the extracted BSD file added some extra opaque types, which were not used in the XML itself. This caused the compilation error. With the current master, this step is no longer necessary, the extracted BSD can now be used as-is.
The 'fixes' in `examples/nodeset/fix_opc_xml.sh` are still necessary.

The executable `server_nodeset_simatic` now no longer crashes when a client accesses a struct, which is good news :-)

However (using UaExpert as a client), all variables that I read have a Value of `NULL`, is that to be expected? I would have expected that e.g. a simple integer node would return value 0, and that they are writable (they aren't now).

**Comment by Pro** [comment]
Nodes should only be NULL if they do not yet have a value.
It is possible to initialize nodes from the NodeSet, e.g., have a look at https://github.com/open62541/open62541/blob/master/examples/nodeset/testnodeset.xml#L277

If a node is writable or not depends (among other settings) on the `AccessLevel` attribute inside the XML.

If there is no specific setting for that in the XML, then the default value is set to read:
https://github.com/open62541/open62541/blob/347a486f538ffe7c076e6e6e1dd0d2cd578efeff/tools/nodeset_compiler/nodes.py#L238

The value is a bitmask. 
Last bit = Read
Second-Last = Write

Therefore '3' means Read and Write access.

Which node did you try to write at?

**Comment by mtenberge** [comment]
For example the node `ns=3;s="globalDB"."singleInt"` (Root/Objects/testPLC/DataBlocksGlobal/globalDB/singleInt). The AccessLevel in the XML is indeed set to "3", and according to UaExpert, both AccessLevel and UserAccessLevel are `CurrentRead+CurrentWrite`.

Maybe UaExpert does not allow writing to a variable if the current value is NULL. I'll try to make a simple test to write to this node with the open62541 client, to rule out that the client is the cause.

**Comment by Pro** [comment]
> Maybe UaExpert does not allow writing to a variable if the current value is NULL

Yep, I also came across this issue before. I created a new issue for that #2924 

Please close this if the other questions are resolved.

**Comment by mtenberge** [comment]
Yes, after an initial write using the open62541 client library, the nodes can be written by UaExpert as well.
This means that the simatic example is now working correctly :+1: 
Thanks for pointing me in the right direction.

I still encounter an issue when I try to apply the same changes to my real project (having the full XML from Simatic with a lot more nodes). Possibly not all type info is extracted from the XML, or my CSV output is not formatted entirely correct. I'll look into that after my holiday. If anything results from that, I will make a new issue.

Thanks a lot for your support!
