### ISSUE TITLE
Is there a reason why the ValueRank are not described in an enumartion?

### ISSUE THREAD

**Issue by mlang-de** [open62541/open62541#2122]
At the moment the ValueRank are described with "magic numbers" like -1 for scalar, 1 for one dimension. Is there a reason not to change it to a human easier readable enumeration?

br

**Comment by jpfr** [comment]
The list is “open ended” for positive integers. So that is difficult to capture with an enum.

We can of course use macro defines for the most common valueranks.

Do you have a proposal for a naming scheme?

**Comment by jpfr** [comment]
Is this more readable?
```c
#define UA_VALUERANK_SCALAR_OR_ONE_DIMENSION    -3
#define UA_VALUERANK_ANY                     -2
#define UA_VALUERANK_SCALAR                  -1
#define UA_VALUERANK_ONE_OR_MORE_DIMENSIONS      0
#define UA_VALUERANK_ONE_DIMENSION             1
#define UA_VALUERANK_TWO_DIMENSIONS            2
#define UA_VALUERANK_THREE_DIMENSIONS          3
```

Yeah. We need a PR for everything now.
Because we check CLAs with PRs as well.

This could be merged right away without discussion.

**Comment by mlang-de** [comment]
I am fine with both variants.
Anyway, I will take yours.
