### ISSUE TITLE
Need a logger parameter added to all the UA_ServerConfig create functions

### ISSUE THREAD

**Issue by fatlab101** [open62541/open62541#2132]
Description
===========
If you use a custom logger function you potentially miss log calls generated inside any of the `UA_ServerConfig` create functions.

Background Information
===========================================
The problem is that when calling a `UA_ServerConfig` create function e.g. `UA_ServerConfig_new_minimal()`  the `conf->logger` field is set to the default logger function internally which then may be called multiple times before the create function returns.

This field can only be updated **after** the create function returns
`conf->logger=my_logger;`

To fix this a logger parameter must be  added to all the `UA_ServerConfig` create functions.

Checklist
=========
Please provide the following information:

 - [x] open62541 Version: 0.3-rc2
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: All
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
Thanks for your suggestion. Can you propose a PR?
This change will only land on master, since it's an API change and the API freeze was already a few months ago.

**Comment by fatlab101** [comment]
> Is it a problem to change the logger after the config is returned?
> After all, this is just a function pointer.
> 
> In the long run, we might need proper logging "plugins" with startup and shutdown methods.
> To support writing to log files where the plugin has to hold some state.

Tried that but ended up missing a range of network setup warnings etc... which are performed inside the create function.

**Comment by Pro** [comment]
With #2263 you can now set your own logger config, which also works for the network logs and dependencies. I tested it by setting spdlog as a custom logger:

```c
#include <ua_plugin_log.h>

namespace fortiss {
    namespace log {
        namespace opcua {
            // Hacky hack hack
            const char *LogsCategoryNames[6] = {"network", "channel", "session", "server", "client", "userland"};


            void UA_Log_Spdlog_log(void *context, UA_LogLevel level, UA_LogCategory category, const char *msg, va_list args) {
                auto logger = (spdlog::logger*)context;
                char tmpStr[400];
                snprintf(tmpStr, 400, "[OPC UA/%s] ", LogsCategoryNames[category]);
                char *start = &tmpStr[strlen(tmpStr)];

                vsprintf(start, msg, args);

                size_t len = strlen(tmpStr);
                tmpStr[len] = '\0';

                switch (level) {
                    case UA_LOGLEVEL_TRACE:
                        logger->trace(tmpStr);
                        break;
                    case UA_LOGLEVEL_DEBUG:
                        logger->debug(tmpStr);
                        break;
                    case UA_LOGLEVEL_INFO:
                        logger->info(tmpStr);
                        break;
                    case UA_LOGLEVEL_WARNING:
                        logger->warn(tmpStr);
                        break;
                    case UA_LOGLEVEL_ERROR:
                    case UA_LOGLEVEL_FATAL:
                        logger->error(tmpStr);
                        break;
                }
            }

            void
            UA_Log_Spdlog_clear(void *logContext) {
            }
        }
    }
}
```

And in your main function:
```c
        // initialize your spdlog logger
        std::shared_ptr<spdlog::logger> logger = ...;

        UA_ServerConfig* uaServerConfig = UA_ServerConfig_new_minimal(4840, nullptr);
        uaServerConfig->logger.log = fortiss::log::opcua::UA_Log_Spdlog_log;
        uaServerConfig->logger.context = logger.get();
        uaServerConfig->logger.clear = fortiss::log::opcua::UA_Log_Spdlog_clear;
```
