### ISSUE TITLE
XML Nodeset Exception with Opc.Ua.NodeSet2.xml

### ISSUE THREAD

**Issue by BigeYoung** [open62541/open62541#2135]
SOLVED
==========
Thanks for answer my question.
As a new newbie, I didn't understand node's target well. 
In `Opc.Ua.NodeSet2.xml` it defines a node `ns=0;i=15100`, while its target `ns=0,i=426` is defined in `Opc.Ua.NodeSet2.Part4.xml` that has not been include.
So I recommend to use `open62541/tools/schema/Opc.Ua.NodeSet2.Minimal.xml` instead.
Hope that it helps.

Please close this issues.

Description
===========

**Exception: Reference ns=0;i=15100<--[ns=0;i=38]--ns=0;i=426 has an unknown target.**

Run:

```bash
python ./nodeset_compiler.py --types-array=UA_TYPES --existing ../../deps/ua-nodeset/Schema/Opc.Ua.NodeSet2.xml --xml ModBus.xml MB_Node
```

Got:  
```bash
INFO:__main__:Preprocessing (existing) ../../deps/ua-nodeset/Schema/Opc.Ua.NodeSet2.xml
INFO:__main__:Preprocessing /home/bige/Desktop/ModBus.xml
Traceback (most recent call last):
  File "./nodeset_compiler.py", line 167, in <module>
    ns.sanitize()
  File "/home/bige/Desktop/open62541/tools/nodeset_compiler/nodeset.py", line 125, in sanitize
    raise Exception("Reference " + str(ref) + " has an unknown target")
Exception: Reference ns=0;i=15100<--[ns=0;i=38]--ns=0;i=426 has an unknown target
```

Note that node "ns=0;i=15100" is **not** in my xml code, but can be found in `Opc.Ua.NodeSet2.xml`:
```XML
  <UAObject NodeId="i=15100" BrowseName="Default JSON" SymbolicName="DefaultJson">
    <DisplayName>Default JSON</DisplayName>
    <References>
      <Reference ReferenceType="HasEncoding" IsForward="false">i=426</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=76</Reference>
    </References>
  </UAObject>
```

Background Information / Reproduction Steps
===========================================

* **OPCFoundation/UA-Nodeset** git master [5bbf784](https://github.com/OPCFoundation/UA-Nodeset/commit/f0ed9516561e08014bafd5500758d1d06515f09f)  on Mar 17
* **Python** 3.7.1

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag):  git master [e2d4b0b](https://github.com/open62541/open62541/commit/e2d4b0bf0355dfe8a064889f69307169959059b9)
 - [x] Other OPC UA SDKs used (client or server): `opcua-modeler-0.5.5` _(for create information models)_
 - [x] Operating system: `Ubuntu 16.04 LTS`
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Hello @BigeYoung ,

the node with i=15100 comes from the nodeset2.xml.

```xml
  <UAObject NodeId="i=15100" BrowseName="Default JSON" SymbolicName="DefaultJson">
    <DisplayName>Default JSON</DisplayName>
    <References>
      <Reference ReferenceType="HasEncoding" IsForward="false">i=426</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=76</Reference>
    </References>
  </UAObject>
```

**Comment by BigeYoung** [comment]
Sorry, I am still a newbie. I don't understand why it leads to errors, since this node is there. My xml can be open in FreeOpcUa Modeler, with "Node Sets" contains "Opc.Ua.NodeSet2.xml" only.

**Comment by BigeYoung** [comment]
I've run
```Bash
python ./nodeset_compiler.py --types-array=UA_TYPES --existing ../../deps/ua-nodeset/Schema/Opc.Ua.NodeSet2.xml --xml ../../examples/nodeset/server_nodeset.xml myNS
```
and got the same exception. So I think that this might not my fault.

**Comment by Pro** [comment]
Your solution is not 100% correct. Opc.Ua.NodeSet2.xml should contain all the nodes, including Part4. But if it is working for you, I just close it here.

**Comment by GeorgeSellner** [comment]
I have the same result if I use the OPC Foundation/UA-Nodeset [v1.04](https://github.com/OPCFoundation/UA-Nodeset/tree/v1.04)
