### ISSUE TITLE
Security Sequence Number and Security RequestId are not set to zero when reconnecting

### ISSUE THREAD

**Issue by engycz** [open62541/open62541#2139]
Description
===========
`Security Sequence Number` and `Security RequestId` are not set to zero when reconnecting.
Softing OPC UA server reject new connection with these numbers greater than 1000 and responds with
Error: 0x80880000 [BadSequenceNumberInvalid]
Wireshark capture [OPC.zip](https://github.com/open62541/open62541/files/2510917/OPC.zip) from example client `client_connect_loop.c`.

Background Information / Reproduction Steps
===========================================
- Connect to Softing OPC UA server
- Wait for `Security Sequence Number` become 1000
- Restart OPC UA server
- Open62541 failed to reconnect

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): master
 - [x] Other OPC UA SDKs used (client or server): server Softing OPC UA toolkit
 - [ ] Operating system: 
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [x] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by StalderT** [comment]
@engycz can you try with https://github.com/open62541/open62541/pull/2159 ?
