### ISSUE TITLE
PC-Lint complains about ignoring return value of functions

### ISSUE THREAD

**Issue by mlang-de** [open62541/open62541#2149]
Many times PC-lint complains about ignoring the return value of functions.
For example:
![image](https://user-images.githubusercontent.com/20433237/47618576-319c0d80-dad5-11e8-942e-e062a9f0132c.png)
![image](https://user-images.githubusercontent.com/20433237/47618586-3f519300-dad5-11e8-9f67-f525dc6a5391.png)
![image](https://user-images.githubusercontent.com/20433237/47618595-4f697280-dad5-11e8-8d4e-4f3f7101b2f7.png)

One solution could be to place 
```C
(void)
```
in front of these functions.
Imho this is ok for functions which remove something or for the snprintf function. But is the case a function do an allocation like 
![image](https://user-images.githubusercontent.com/20433237/47618633-9b1c1c00-dad5-11e8-9874-39183d42b06b.png)
the statuscode should be given back to the caller.

Some opions how could it be handled in a nice way?

**Comment by jpfr** [comment]
We can add function attributes that the return values must not be ignored.
Such as here: https://github.com/open62541/open62541/blob/master/src/ua_types_encoding_binary.h#L42

But I am a bit hesitant doing that for methods in the public API.
Anyway, if we want to be PC-Lint clean, then we'd have to integrate it in our CI infrastructure.

Is there an open source solution that approximates PC-Lint?

**Comment by mlang-de** [comment]
"But I am a bit hesitant doing that for methods in the public API."
You are right, this would be not a good solution for public API.
The page
http://open-tube.com/10-free-tools-for-static-code-analysis/ 
lists 5 free C-Code checker
1. Sparse
2. Splint
3. Uno
4. BLAST
5. Cppcheck

I only have experience in PC-lint for now and do not know which quality are the free tools.

**Comment by Pro** [comment]
I randomly picked some of the warnings you posted and checked there.
Most of them are valid warnings where the return value should be checked. The solution for these is to correctly handle the return value and pass the error to the caller.

For the rare cases, where the return value should be ignored, we can maybe wrap them with a macro like `UA_IGNORE_RETURN()` which mutes the warning but satisfies the linter. This was we also add semantic meaning to that line.

**Comment by jpfr** [comment]
This PR added an UA_INTERNAL macro that, if enabled before the first include, does additional checking.
https://github.com/open62541/open62541/pull/2173

We can extend the same mechanism to force that more methods have their return value checked in internal code. The use via the public interface would not trigger the same warnings.

**Comment by mlang-de** [comment]
This sounds great! I vote for to extend the mechanism.
