### ISSUE TITLE
Typo in documentation, gcc commandline

### ISSUE THREAD

**Issue by sme-gmbh** [open62541/open62541#2152]
Description
===========
Here: https://open62541.org/doc/current/tutorial_client_firststeps.html

Is:
$ gcc -std=c99 open6251.c myClient.c -o myClient
Result: gcc: Error: open6251.c: No such file or directory
Should be:
gcc -std=c99 open62541.c myClient.c -o myClient

**Comment by StalderT** [comment]
Thanks !

Fixed in #2157 (master) #2158 (0.3)
