### ISSUE TITLE
Client: foreign server responds to PublishRequest with BadTimeout and ServiceFault 

### ISSUE THREAD

**Issue by jrcoding** [open62541/open62541#2189]
Description
===========
I tried to monitor items with a open62541 client served by an opcua gateway from Softing (uaGate) and got _PublishResponses_ with error code _BadTimeout_ and _ServerFault_. Monitoring the same item with uaexpert works fine.

Background Information / Reproduction Steps
===========================================
After some debugging I found a differenz between the PublishRequest package send by uaexpert and open62541 that seems to provoke the error. 
Uaexpert sets the `timeoutHint` in the _RequestHeader_ of a _PublishRequest_ to 60000 and open62541 sets it to zero.
As a test I've changed it to 60000 in `UA_Client_Subscriptions_backgroundPublish` (see attached patch) and it works so far but I'm not sure if this is o.k. and about other implications this may have.

```
diff --git a/src/client/ua_client_subscriptions.c b/src/client/ua_client_subscriptions.c
index 5d0c42e7..40b93a92 100644
--- a/src/client/ua_client_subscriptions.c
+++ b/src/client/ua_client_subscriptions.c
@@ -759,6 +759,7 @@ UA_Client_Subscriptions_backgroundPublish(UA_Client *client) {
         if (!request)
             return UA_STATUSCODE_BADOUTOFMEMORY;
 
+        request->requestHeader.timeoutHint=60000;
         UA_StatusCode retval = UA_Client_preparePublishRequest(client, request);
         if(retval != UA_STATUSCODE_GOOD) {
             UA_PublishRequest_delete(request);

```
The OPC-UA Spec Part 4 says for _RequestHeader timeoutHint_
> This timeout in milliseconds is used in the Client side Communication Stack to set the timeout on a per-call base. 
For a Server this timeout is only a hint and can be used to cancel long running operations to free resources. If the Server detects a timeout, he can cancel the operation by sending the Service result Bad_Timeout. The Server should wait at minimum the timeout after he received the request before cancelling the operation. The Server shall check the timeoutHint parameter of a Publish request before processing a Publish response. If the request timed out, a Bad_Timeout Service result is sent and another Publish request is used. The value of 0 indicates no timeout.

setting the timeoutHint  to '0' in the client seems to be o.k. for my understanding and furthermore it seems to be a bug in the uaGate server not waiting for ever if timeoutHint is '0', but nevertheless isn't  it desirable if the user could define resp. overwrite the `timeoutHint` in an open62541 client application?

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag):  _0.4_
 - [x] Other OPC UA SDKs used (client or server): _ua-sdk_ _from unified automation_
 - [x] Operating system: _Linux (Debian 10)_
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Yes. We can add the timeouthint as you suggested.
Do you want to prepare a pull request? Otherwise we can take your patch and go from there.

**Comment by jrcoding** [comment]
First of all, great work the open62541 project!!!

Please feel free using the attached patch....
(but if wanted I can also provide a pull request, your choice)

BTW: 
Does it make sense to have such timeouts configurable, for example as items in the client config???

**Comment by jrcoding** [comment]
thanks for merging!
