### ISSUE TITLE
Method call within a FunctionalGroup not work

### ISSUE THREAD

**Issue by mlang-de** [open62541/open62541#2193]
The DI specification (Device Intergration - Part 100, 1.01) allows to reference a method from a FunctionalGroup.
![image](https://user-images.githubusercontent.com/20433237/48215177-f83f8980-e381-11e8-9f2e-c029cea90ed7.png)
![image](https://user-images.githubusercontent.com/20433237/48215824-5faa0900-e383-11e8-8fac-b5d3ba63523e.png)
The current implementation in function callWithMethodAndObject() verify:
![image](https://user-images.githubusercontent.com/20433237/48215245-2329dd80-e382-11e8-9df4-a66d92093d61.png)

Is it meaningful to implement a logic like:
1. parent object must have a HasTypeDefinition reference to FunctionalGroupType
2. parent object must have a Organize reference to the method

This kind of information modelling will be used at least in some Companion Specification for now.

**Comment by jpfr** [comment]
#2194 was merged.
