### ISSUE TITLE
undefined reference to `UA_DateTime_now' FreertosLWIP 

### ISSUE THREAD

**Issue by embbo** [open62541/open62541#2209]
Hi all,
I am trying to port open62541 (latest version---last version works fine) for stm32f and using eclipse.
but while compiling , I am facing these issues with UA_DateTime_now and UA_DateTime_nowMonotonic . if anyone can help.

 ../Src/open62541.c:20684: undefined reference to `UA_DateTime_nowMonotonic'
Src/open62541.o: In function `ServerNetworkLayerTCP_add':
 ../Src/open62541.c:50252: undefined reference to `UA_socket_set_nonblocking'
 ../Src/open62541.c:50306: undefined reference to `UA_DateTime_nowMonotonic'
Src/open62541.o: In function `addServerSocket':
 ../Src/open62541.c:50348: undefined reference to `UA_socket_set_nonblocking'
Src/open62541.o: In function `readAuditing':
 ../Src/open62541.c:22591: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `readServiceLevel':
 ../Src/open62541.c:22566: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `readNamespaces':
 ../Src/open62541.c:22615: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `readCurrentTime':
 ../Src/open62541.c:22665: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `ServerNetworkLayerTCP_start':
 ../Src/open62541.c:50379: undefined reference to `UA_initialize_architecture_network'
 ../Src/open62541.c:50394: undefined reference to `gethostname_lwip'
Src/open62541.o: In function `readStatus':
 ../Src/open62541.c:22527: undefined reference to `UA_DateTime_now'
 ../Src/open62541.c:22540: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `UA_ClientConnectionTCP_init':
 ../Src/open62541.c:50814: undefined reference to `UA_DateTime_nowMonotonic'
Src/open62541.o: In function `UA_ClientConnectionTCP':
 ../Src/open62541.c:50854: undefined reference to `UA_initialize_architecture_network'
 ../Src/open62541.c:50912: undefined reference to `UA_DateTime_nowMonotonic'
 ../Src/open62541.c:51035: undefined reference to `UA_DateTime_nowMonotonic'
 ../Src/open62541.c:50936: undefined reference to `UA_socket_set_nonblocking'
 ../Src/open62541.c:50960: undefined reference to `UA_DateTime_nowMonotonic'
 ../Src/open62541.c:51051: undefined reference to `UA_socket_set_blocking'
Src/open62541.o: In function `UA_Timer_addRepeatedCallback':
 ../Src/open62541.c:18931: undefined reference to `UA_DateTime_nowMonotonic'
Src/open62541.o: In function `checkSymHeader':
 ../Src/open62541.c:20699: undefined reference to `UA_DateTime_nowMonotonic'
Src/open62541.o: In function `sendServiceFault':
 ../Src/open62541.c:29463: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `subscriptionSendError':
 ../Src/open62541.c:38763: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `UA_Session_updateLifetime':
 ../Src/open62541.c:20982: undefined reference to `UA_DateTime_nowMonotonic'
Src/open62541.o: In function `UA_Server_run_iterate':
 ../Src/open62541.c:22179: undefined reference to `UA_DateTime_nowMonotonic'
 ../Src/open62541.c:22218: undefined reference to `UA_DateTime_nowMonotonic'
Src/open62541.o: In function `ServerNetworkLayerTCP_listen':
 ../Src/open62541.c:50495: undefined reference to `UA_DateTime_nowMonotonic'
Src/open62541.o: In function `ServerNetworkLayerTCP_stop':
 ../Src/open62541.c:50558: undefined reference to `UA_deinitialize_architecture_network'
Src/open62541.o: In function `UA_SecureChannelManager_create':
 ../Src/open62541.c:30966: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `UA_SecureChannelManager_open':
 ../Src/open62541.c:30991: undefined reference to `UA_DateTime_nowMonotonic'
 ../Src/open62541.c:30993: undefined reference to `UA_DateTime_now'
 ../Src/open62541.c:31024: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `UA_SecureChannelManager_renew':
 ../Src/open62541.c:31076: undefined reference to `UA_DateTime_nowMonotonic'
 ../Src/open62541.c:31047: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `ReadWithNode':
 ../Src/open62541.c:36282: undefined reference to `UA_DateTime_now'
 ../Src/open62541.c:36271: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `UA_Server_run_startup':
 ../Src/open62541.c:22136: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `UA_Log_Stdout':
 ../Src/open62541.c:46908: undefined reference to `UA_DateTime_localTimeUtcOffset'
 ../Src/open62541.c:46909: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `UA_random_seed':
 ../Src/open62541.c:7319: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `UA_SessionManager_getSessionByToken':
 ../Src/open62541.c:31201: undefined reference to `UA_DateTime_nowMonotonic'
Src/open62541.o: In function `UA_SessionManager_getSessionById':
 ../Src/open62541.c:31230: undefined reference to `UA_DateTime_nowMonotonic'
Src/open62541.o: In function `Service_ActivateSession':
 ../Src/open62541.c:35791: undefined reference to `UA_DateTime_nowMonotonic'
Src/open62541.o: In function `writeValueAttribute':
 ../Src/open62541.c:37010: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `process_RegisterServer':
 ../Src/open62541.c:37880: undefined reference to `UA_DateTime_nowMonotonic'
Src/open62541.o: In function `UA_Subscription_reachedPublishReqLimit':
 ../Src/open62541.c:46058: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `UA_Subscription_answerPublishRequestsNoSubscription':
 ../Src/open62541.c:46127: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `UA_Server_cleanup':
 ../Src/open62541.c:21926: undefined reference to `UA_DateTime_nowMonotonic'
Src/open62541.o: In function `UA_Subscription_publish':
 ../Src/open62541.c:45982: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `processMSG':
 ../Src/open62541.c:29959: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `UA_Server_new':
 ../Src/open62541.c:21958: undefined reference to `UA_DateTime_now'
Src/open62541.o: In function `UA_ClientConnectionTCP_poll':
 ../Src/open62541.c:50643: undefined reference to `UA_DateTime_nowMonotonic'
 ../Src/open62541.c:50651: undefined reference to `UA_DateTime_nowMonotonic'
 ../Src/open62541.c:50677: undefined reference to `UA_socket_set_nonblocking'
 ../Src/open62541.c:50700: undefined reference to `UA_DateTime_nowMonotonic'
collect2.exe: error: ld returned 1 exit status
makefile:47: recipe for target 'opc.elf' failed
make: *** [opc.elf] Error 1

**Comment by jpfr** [comment]
Maybe your architecture is not baked into the amalgamated files.
Can you use the "normal" source files?

Which architecture do you use?
It should come with a clock implementation.

https://github.com/open62541/open62541/blob/master/arch/freertosLWIP/ua_clock.c
https://github.com/open62541/open62541/blob/master/arch/win32/ua_clock.c
https://github.com/open62541/open62541/blob/master/arch/posix/ua_clock.c
https://github.com/open62541/open62541/blob/master/arch/vxworks/ua_clock.c
https://github.com/open62541/open62541/blob/master/arch/wec7/ua_clock.c

**Comment by embbo** [comment]
it backs ok , it includes ua_clock part in open62541.c and also declare in ua_types bt stills gives error .
what can be the issue:
my cmake command is :
/cmake.exe .. -G "Eclipse CDT4 - Unix Makefiles" -DUA_ARCHITECTURE="freertosLWIP"

**Comment by jpfr** [comment]
Is this file compiled?
https://github.com/open62541/open62541/blob/master/arch/freertosLWIP/ua_clock.c

Maybe you can regenerate the build system from scratch.

**Comment by embbo** [comment]
it works fine , but now its doesn't connct to uaExpert client, i can ping and can see on Wireshark

**Comment by Pro** [comment]
Can you post additional information how you fixed this? It may be helpful for others if they find this issue.

For your second question, please open a new issue and provide more info.

**Comment by embbo** [comment]
okay, I just used this cmake comand and include freertosLWIP arch in it.
cmake.exe .. -G "Eclipse CDT4 - Unix Makefiles" -DUA_ARCHITECTURE="freertosLWIP"

undefined these two function below  while cmake. (there can be other ways) and define manually when while using with attolic or eclipse. then i complied and  it works really fine and i can see on wireshark.

//UA_Int64 UA_DateTime_localTimeUtcOffset(void) 
//UA_DateTime UA_DateTime_nowMonotonic(void)

**Comment by embbo** [comment]
Here is second issue, i have no idea why i can connect . Stm_freertos_LWIP #2227

**Comment by cabralfortiss** [comment]
I think this issue could be closed now
