### ISSUE TITLE
Shadowed newEntry in UA_NodeMap_insertNode

### ISSUE THREAD

**Issue by cabralfortiss** [open62541/open62541#2216]
Description
===========
The newEntry variable in UA_NodeMap_insertNode is named the same as a function which produces shadow errors in some compilers. 

Background Information / Reproduction Steps
===========================================
A very similar issue is https://github.com/open62541/open62541/issues/1250#issuecomment-336565666 which was fixed with https://github.com/open62541/open62541/commit/c86c8e833f2e0911f64727a059a87a6f3102bb6b

**Comment by jpfr** [comment]
Fixed via #2217
