### ISSUE TITLE
New Feature: Add AppVeyor build with VS2017

### ISSUE THREAD

**Issue by escherstair** [open62541/open62541#2218]
AppVeyor is configured to build with VS2008, VS2013 and VS2015.
Since AppVeyor provide a pre-configured image with VS2017 too, it's quite easy to add a new build with VS2017.

If this seems a good idea I can propose a PR.

**Comment by Pro** [comment]
Is there a specific advantage to add VS2017?

Currently AppVeyor is already slow and we often have to wait hours until CI runs through. Adding an additional build will slow that down even more.

**Comment by Pro** [comment]
@escherstair it would be nice if you can propose a PR which includes the versions mentioned by @jpfr 
(and of course including the other special versions like mingw and clang)

**Comment by escherstair** [comment]
The reason to test with VS2017 is to use the latest code analysis tools.

@Pro sure I'm going to propose a PR..
To be 100% sure: in other words, the proposal from @jpfr means to replace VS2015 with VS2017.
Can you confirm?

**Comment by jpfr** [comment]
> To be 100% sure: in other words, the proposal from @jpfr means to replace VS2015 with VS2017.
Can you confirm?

Yes. Maybe wen can have both for 1,2 weeks and then disable VS2015.

**Comment by escherstair** [comment]
PR #2248  adds build for vs2017 side by side to vs2015.
If everything is ok we can leave it for 1 or 2 weeks, then disable vs2015.

**Comment by Pro** [comment]
I just merged the PR.

Let's leave this issue open until around December 15th 2018, then remove VS2015 and close this.

**Comment by Pro** [comment]
Closing. Removed in #2274
