### ISSUE TITLE
UA_SecurityPolicy_Basic128Rsa15 missing in 0.3-rc2

### ISSUE THREAD

**Issue by kjeldflarup** [open62541/open62541#2219]
Description
===========
I was trying to see if the 0.3 release candidate was useable. I do not like to release something just with a random git head.

Background Information / Reproduction Steps
===========================================
Linking these two files into a .so file. Use -DUA_ENABLE_ENCRYPTION=true when compiling.
- https://github.com/open62541/open62541/releases/download/0.3-rc2/open62541.c
- https://github.com/open62541/open62541/releases/download/0.3-rc2/open62541.h
This gives me this error:
`libCmpOpen62541.so: undefined symbol: UA_SecurityPolicy_Basic128Rsa15`

Looking into open62541.c the problem is quite obvious. `UA_SecurityPolicy_Basic128Rsa15` is used but not declared.

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): 0.3-rc2
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
solved.
