### ISSUE TITLE
Cleanup AppVeyor configuration

### ISSUE THREAD

**Issue by escherstair** [open62541/open62541#2221]
While trying to add clang build to AppVeyor #2116 I saw that AppVeyor configuration is a little bit complicated (I mean, more complicated than necessary with up-to-date AppVeyor infrastructure).
Probably the configuration files have been created some years ago, when AppVeyor was not so full-featured as it is now.

If someone is interested I can cleanup a little bit the configuration files.
This wuold take advantage of [software pre-installed on Windows build VMs](https://www.appveyor.com/docs/windows-images-software/) and this would save build time.

Moreover the AppVeyor configuration files would be a little bit easier to mantain.

If you think it would be a good idea I can propose a PR.

**Comment by jpfr** [comment]
Yes, please. 👍 
Simplification is always welcome.

**Comment by escherstair** [comment]
I've just created PR #2242

**Comment by Pro** [comment]
Done with PR
