### ISSUE TITLE
v0.3-rc3: wrong version info in CMakeLists.txt

### ISSUE THREAD

**Issue by mlang-de** [open62541/open62541#2222]
For information, not sure how important is it.
In the today new tagged Version v0.3-rc3 the CMakeList Version info is not updated.
![image](https://user-images.githubusercontent.com/20433237/48613779-f3379700-e98c-11e8-8330-f91465cc42bf.png)

**Comment by jpfr** [comment]
Hrmpf. You are right.
Fixed and bumped to 0.3-rc4.
