### ISSUE TITLE
[Question] How to get data from NodeContext?

### ISSUE THREAD

**Issue by fedelodo** [open62541/open62541#2228]
Description
===========
I can't understand how to get nodeContext values back.
Here Is my snippet of code:
```
static void
afterIntWrite(UA_Server *server,
               const UA_NodeId *sessionId, void *sessionContext,
               const UA_NodeId *nodeId, void *nodeContext,
               const UA_NumericRange *range, const UA_DataValue *data) {
	UA_Int32 value;
	UA_NodeId node = *nodeId;
	UA_Variant *val = UA_Variant_new();
	UA_Server_readValue(server,node, val);
    	value = *(UA_Int32*)val->data;
    	int pos = *(int *) nodeContext;
        //do other stuff
       ...........................
    	UA_LOG_INFO(UA_Log_Stdout, UA_LOGCATEGORY_USERLAND, // @suppress("Invalid arguments")
                	"The variable was updated with value %i at pos %i ", value, pos);
}

static void
addCallbacktoInt(UA_Server *server, char* name, int pos) {
    	UA_NodeId currentNodeId = UA_NODEID_STRING(1, name);
    	UA_ValueCallback callback ;
   	UA_Server_setNodeContext(server, currentNodeId, &pos);
   	callback.onWrite = afterIntWrite;
   	UA_Server_setVariableNode_valueCallback(server, currentNodeId, callback);
}
```

But it doesn't print the correct value. It prints something that resemble a memory address.
For example, when I try to add the callback with 530  as pos argument and I write the value in the node 67 I get:
`The variable was updated with value 67 at pos 134538511 `
 I also find the documentation very unhelpful on this topic with no explainations on how to use NodeContext.

Background Information / Reproduction Steps
===========================================

Checklist
=========
Please provide the following information:

 - [:heavy_check_mark: ] open62541 Version (0.3-r2):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [:heavy_check_mark: ] Operating system: Yocto Linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [:heavy_check_mark: ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
addCallbacktoInt cannot work that way.

The pos value is on the stack when addCallbacktoInt is called.
But this memory location is reused when addCallbacktoInt returns.

You should put the pos value into a global memory address that remains when addCallbacktoInt returns.
Or you can specifically allocate memory with malloc.

Please reopen if the issue remains.
