### ISSUE TITLE
/include/open62541/ua_architecture.h:145:10: fatal error: ua_architecture_functions.h: No such file or directory

### ISSUE THREAD

**Issue by ccvca** [open62541/open62541#2311]
Description
===========
When including <ua_types.h> I got the error:
[...]/include/open62541/ua_architecture.h:145:10: fatal error: ua_architecture_functions.h: No such file or directory
The file ua_architecture_function.h is not installed in [...]include/open62541/

@Pro When I get it right, the file should be added to these lines:
https://github.com/open62541/open62541/blob/20eccdcaf15162f48a372186e15f654d81331f59/CMakeLists.txt#L460-L464

Background Information / Reproduction Steps
===========================================
Install fresh on windows 10, include ua_types.h in any file.

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): 20eccdcaf15162f48a372186e15f654d81331f59
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Windows 10, Mingw-w64
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [x] Critical issue

**Comment by Pro** [comment]
This should be fixed in the current master branch ( i just merged #2302 which contains many improvements for the install).

The corresponding line is already there:
https://github.com/open62541/open62541/blob/82b6499f37dcb64646536218e0eadb3ef497ea08/CMakeLists.txt#L112

**Comment by Pro** [comment]
Oh right. Will be fixed with #2316

**Comment by Pro** [comment]
@tobijk1 @ccvca with #2318 we are now also testing every commit if `make install` is complete.

Thanks for all your issue reports and support!

**Comment by tobijk1** [comment]
Nice, thanks!

**Comment by ccvca** [comment]
Thank you for fixing.
