### ISSUE TITLE
[UA Client] Certificate authentication with server failed - UA_STATUSCODE_BADCERTIFICATEURIINVALID error

### ISSUE THREAD

**Issue by Giocast85** [open62541/open62541#2314]
Description
===========
I encountered an issue with a OPC UA Client implementation with security.
I'm trying to connect to a B&R PLC as OPC UA Server and when I call the UA_Client_connect method, it returns a UA_STATUSCODE_BADCERTIFICATEURIINVALID status code.
 

Background Information / Reproduction Steps
===========================================

I created a self-signed certificate for the client, called UA_Client_secure_new in order to initialize the secured configuration and then the UA_Client_connect method.

As I received the error, I tried to deeply investigate on source files. 
It seems that the issue is related to createSession method, and in particular that request.clientDescription.applicationUri is not assigned.
For this reason - probably - the server fails the certificate validation and it returns the error above.

I tried to manually force the applicationURI and - at this point - I've been able to connect to the server successfully.

Am I doing anything wrong? Is the applicationURI configurable elsewhere during the client initialization?

Checklist
=========
Please provide the following information:

 - [X ] open62541 Version (release number or git tag): current master - commit 27e9555
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by sanny32** [comment]
Probably, you must add your client certificate into server PKI trusted certificates.

**Comment by jpfr** [comment]
Reopen if required.
Please send log information, etc. so we can assist better.
