### ISSUE TITLE
Definition "ArrayDimension" differ from OPCUA Spec

### ISSUE THREAD

**Issue by mark1357945** [open62541/open62541#2325]
Description
===========
found there's a function called "compatibleValue".
when it is called in "typeCheckVariableNode" function:
```
/* Typecheck the value */
    if(value.hasValue) {
        /* If the type-check failed write the same value again. The
         * write-service tries to convert to the correct type... */
        if(!compatibleValue(server, session, &node->dataType, node->valueRank,
                            node->arrayDimensionsSize, node->arrayDimensions,
							&value.value, NULL)){
   //...
}
```
it would check if VariableNode's arrayDimension attributes member matchs it's real value arrayDimension property.
It makes me confuse because the definition of VariableNode's arrayDimension attributes in OPCUA spec 
more like to be "MaxArrayDimension": "This Attribute specifies the maximum supported length of each
dimension. If the maximum is unknown the value shall be 0."

so I think VariableNode.value.arrayDimension being less or equals to VariableNode.arrayDimension make sense to me.

Do I have misunderstand of the definition? hope to clear up my confusion, thanks!

Background Information / Reproduction Steps
===========================================
opcua rc2

Checklist
=========
Please provide the following information:

 - [v] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Yes, we are not conformant to the spec.
The array dimension is an upper bound. Values can have less entries.

I did not find information in the spec how the array dimensions between variable and variabletype (or hierarchies of variabletypes) must relate.

My interpretation is that for tow variabletypes `B subtypeOf A` all instances of `B` must also be instances of `A`. So the array dimensions of `B` must be less or equal the array dimensions of A.
