### ISSUE TITLE
Get OPCUA Server timestamp from client

### ISSUE THREAD

**Issue by sureshaei** [open62541/open62541#2327]
We are trying to make use of the server timestamp after reading an attribute using UA_Client_readNodeIdAttribute() at the client code. The structure UA_ReadResponse has the source timestamp but not exposed out of __UA_Client_readAttribute() from ../src/client/ua_client_highlevel.c. 

Is there any better way to get the read timestamp of an attribute?

Checklist
=========
Please provide the following information:

 - [x] open62541 Version (release number or git tag): d371aaf 
 - [ ] Other OPC UA SDKs used (client or server): Nil
 - [x] Operating system: Ubuntu 14.04
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached: No
 - [ ] Wireshark network dump attached: No
 - [ ] Self-contained code example attached: No
 - [ ] Critical issue: Yes

**Comment by jpfr** [comment]
The non-specialized read service returns the full results.
You use the “high level” version with an intentionally simplified api.
