### ISSUE TITLE
Unit test historical_data test randomly crash (SEGFAULT)

### ISSUE THREAD

**Issue by StalderT** [open62541/open62541#2330]
Description
===========

Unit test historical_data test randomly crash (SEGFAULT) see : https://travis-ci.org/open62541/open62541/jobs/473063184#L9687

Checklist
=========
Please provide the following information:

 - [X] open62541 Version (release number or git tag): master

**Comment by Pro** [comment]
See also https://travis-ci.org/open62541/open62541/jobs/474423872#L8280

**Comment by Pro** [comment]
![image](https://user-images.githubusercontent.com/251973/50638819-673ef600-0f5f-11e9-9d84-78f00d19a41b.png)

Found the issue. There's a race condition:
`startPoll` is creating a monitored item, and `stopPoll` is deleting it. Meanwile `serverloop` is executing `UA_Server_run_iterate` which is accessing the deleted timer object for the monitored item.

I'll create a fix for that.

**Comment by StalderT** [comment]
Thanks
