### ISSUE TITLE
Can Codacy be helpful?

### ISSUE THREAD

**Issue by escherstair** [open62541/open62541#2334]
open62541 already uses tools to check code quality.

I see that some projects on github use [Codacy](https://www.codacy.com/), which can be used free of charge [for open source projects](https://opensource.codacy.com/).

I see that C/C++ is one of the [Community Supported Language](https://support.codacy.com/hc/en-us/articles/207994735-Supported-Languages).

I have no experience and I don't know if this project can benefit of this tool.

What do you think?

**Comment by Pro** [comment]
Thanks for the hint!

I created a new project on Codacy:
https://app.codacy.com/project/open62541/open62541/dashboard

It looks there are some issues mainly with .md files, but not that many with C/Python.
https://app.codacy.com/app/open62541/open62541/files
https://app.codacy.com/app/open62541/open62541/issues/index

Very cool! It shows that our efforts in keeping a high code quality paid off :+1: 

We should try to fix those issues and then we can mark Codacy Status as required for new PRs.
