### ISSUE TITLE
UA_ByteString_clear() is not suitable to clear key material

### ISSUE THREAD

**Issue by basyskom-meerkoetter** [open62541/open62541#2381]
The examples in examples/encryption/client_basic*.c are using UA_ByteString_clear() to zero out key material after it has been used.

`UA_ByteString_clear(&certificate);
UA_ByteString_clear(&privateKey);
 for(size_t deleteCount = 0; deleteCount < trustListSize; deleteCount++) {
        UA_ByteString_clear(&trustList[deleteCount]);
 }`

This will often not work when the code is compiled with optimizations enabled.
UA_ByteString_clear() calls UA_Clear() calls memset(p, 0, type->memSize);
If the optimizer can prove that the memory of the bytestring isn't touched anymore after the call to UA_ByteString_clear() it is free to remove the memset(). Removing the call has no observable effect.

C11 offers memset_s(). Unfortuately the open62541 code base is C99.

See https://www.cryptologie.net/article/419/zeroing-memory-compiler-optimizations-and-memset_s/ for a discussion. The article links to https://github.com/jedisct1/libsodium/blob/be58b2e6664389d9c7993b55291402934b43b3ca/src/libsodium/sodium/utils.c#L78:L101 for a good implementation.

Still UA_ByteString_clear() will typically not be used on strings containing key material. Should there be a UA_ByteString_clear_s()?

**Comment by jpfr** [comment]
We now have a plug-in that uses a tpm for key material.
We don‘t have keys in the core library. Besides temporary nondescript, etc.
