### ISSUE TITLE
RFC: examples using UA_StatusCode values as exit codes

### ISSUE THREAD

**Issue by basyskom-meerkoetter** [open62541/open62541#2421]
Quite a few places are returning values from UA_StatusCode as process exit codes
open62541/examples/$ find -name "*.c" | xargs grep "return (int)" | wc -l
51

Something like
return UA_STATUSCODE_BADUNEXPECTEDERROR

There is a problem with that approach. We can return an int from a process as an exit code, but on a lot of systems only the lower 8bits are evaluated. Its even worse, to be portable only values between 0 and 125 can be used. See https://unix.stackexchange.com/questions/418784/what-is-the-min-and-max-values-of-exit-codes-in-linux for a discussion.

I have validated that for example the server_nodeset_plcopen returning  UA_STATUSCODE_BADUNEXPECTEDERROR has a successful exit code on the shell.
$ ./server_nodeset_plcopen // its running, it make it fail
$ echo $?
0

I propose to return EXIT_FAILURE or EXIT_SUCCESS from the stdlib.h.

I volunteer to provide a patch.

**Comment by jpfr** [comment]
👍

**Comment by basyskom-meerkoetter** [comment]
see https://github.com/open62541/open62541/pull/2437
