### ISSUE TITLE
Do we need to add whole variables nodes before running server?

### ISSUE THREAD

**Issue by HamidMapna** [open62541/open62541#2427]
Hi. What i inferred from source code it seems that we must define our whole variables in a loop `(UA_Server_AddVariableNode(...))`  and then start up the server `(UA_Server_run_startup(server)).`
If this is true it can bring me a problematic issue cause client might  define various variables at any moment, so how server can include new added variables after it started up?
appreciate if anyone could enlighten me.

**Comment by basyskom-meerkoetter** [comment]
Can you please expand a bit on your question? I am not sure what your specific problem is.
I assume you know: https://open62541.org/doc/current/server.html#node-addition-and-deletion

**Comment by HamidMapna** [comment]
Thank you Frank. It worked. You helped me a lot. sorry for my late appreciate

**Comment by basyskom-meerkoetter** [comment]
@jpfr can you please close this one?
