### ISSUE TITLE
Wrong _MSC_VER check for stdbool.h

### ISSUE THREAD

**Issue by the-om** [open62541/open62541#2431]
I can't compile open62541 with MS Visual Studio 2010 because arch/ua_architecture_definitions.h contains the following code:
```
#if !defined(_MSC_VER) || _MSC_VER >= 1600
# include <stdint.h>
# include <stdbool.h> /* C99 Boolean */
#else
# if !defined(__bool_true_false_are_defined)
#  define bool unsigned char
#  define true 1
#  define false 0
#  define __bool_true_false_are_defined
# endif
#endif
```
Visual Studio 2010 defines _MSC_VER as 1600.
However stdbool.h is not available until Visual Studio 2013(_MSC_VER >= 1800)

**Comment by jpfr** [comment]
Good find. Can you provide a commit?
