### ISSUE TITLE
How to change the nodeId from numeric to String

### ISSUE THREAD

**Issue by Jmiciak67** [open62541/open62541#2434]
- [ ] open62541 Version (release number or git tag): last one
 - [ ] Other OPC UA SDKs used (client or server):  server
 - [ ] Operating system: w7 64 bit

Hello everyone, I am stuck in a project of OPC UA server. I am very new to this so I should miss something.
I follow several example to create my first server test. On this server I have:
- One main object called Object_1234
- in subobject I have Config and Result
- And in each of these object (config result) I have several variables.
Here is the three architecture:
![image](https://user-images.githubusercontent.com/23309396/52468399-ef30a500-2b88-11e9-8eda-43e9624aa7e2.png)

The problem is that my variable have a numeric identifier and this is not usable to read or write a specific value
![image](https://user-images.githubusercontent.com/23309396/52468418-f952a380-2b88-11e9-8315-9202f3f14c73.png)

And when I am using the method "NewObject" it will create the same Object with another name, but also another identifier for the variable.
Concerning the subObject I have this:
![image](https://user-images.githubusercontent.com/23309396/52468483-2010da00-2b89-11e9-82c4-763b8a65e301.png)
![image](https://user-images.githubusercontent.com/23309396/52468728-d8d71900-2b89-11e9-8cd0-67c64f5e4516.png)
![image](https://user-images.githubusercontent.com/23309396/52468742-e2f91780-2b89-11e9-9ed4-f36f365a8888.png)

The identifier is fixed thanks to the main Object name and the concatenate of ".config"

Is there some Example that show how to have a correct architecture tree like:
Object1
Object1.config
Object1.obj2
Object1.config.var1

Is there another way to access to my variable without using this numeric NodeId ? I have seen something like with the browse name maybe ?
I cannot send the code because it is confidential project, if you can just link some example on NodeId or browseName utilities.
Thanks all and best regards !

**Comment by jpfr** [comment]
You can use

UA_Server_addNode_begin
UA_Server_addNode_finish

The child nodes are automatically added only during _finish.
If you add them manually in between (with the correct browsename), then the existing child nodes will be used.

https://github.com/open62541/open62541/blob/master/include/ua_server.h#L1178

**Comment by Jmiciak67** [comment]
Thanks a lot jpfr ! your solution is working properly !
Best regards
