### ISSUE TITLE
Nightly single file distributions

### ISSUE THREAD

**Issue by nicolasr75** [open62541/open62541#2515]
This site
https://open62541.org/
says I could download nightly single file distributions here
https://ci.appveyor.com/project/open62541/open62541/history
But all the build jobs seem to produce static/dynamic builds.

Any idea where to find the nightly single file distributions?

**Comment by Pro** [comment]
Nightly builds of every branch, including master, can be found here:
https://open62541.org/releases/

These .zip files include the single file distribution.

Other nightly build formats are:

- Appveyor (for windows), generating static and dynamic windows libs: https://ci.appveyor.com/project/open62541/open62541/history
- Travis (for linux), generating single file distribution and nightly .deb packages:
https://open62541.org/releases/

Keep in mind that these are experimental builds!
