### ISSUE TITLE
Documentations for building and installation are swapped for 0.3 and 0.4

### ISSUE THREAD

**Issue by tobiaslocker** [open62541/open62541#2536]
The current instructions for building and installing seem to be swapped for 0.3 and 0.4

The documentation for development branch states:
```
git submodule update --init --recursive
mkdir build && cd build
cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUA_ENABLE_FULL_NS0=ON ..
make
sudo make install
```

which results in an unused CMake option in 0.4 but works fine in 0.3.
Furthermore 0.4 documentation suggests
```
find_package(open62541 0.3.0 REQUIRED COMPONENTS FullNamespace DiscoveryMulticast)
add_executable(main main.cpp)
target_link_libraries(main open62541::open62541)
```
Is the version in `find_package` correct? this does not work for 0.3 either.

The documentation for 0.3 states:

```
find_package(open62541 0.4.0 REQUIRED COMPONENTS Events DiscoveryMulticast)
add_executable(main main.cpp )
target_link_libraries(main open62541)
```
Is the version in `find_package` correlating to `open62541` version? If so this seems to be faulty

**Comment by jpfr** [comment]
Can you elaborate?

**Comment by tobiaslocker** [comment]
Edited to clarify.

**Comment by Pro** [comment]
Thanks for reporting.
I created two PRs which fix this.
