### ISSUE TITLE
Add possibility to disable the DataChange Subscription retransmission queue

### ISSUE THREAD

**Issue by jonasgreen88** [open62541/open62541#2565]
## Description
The DataChange Subscription server requirement "Subscription Publish Min 02" of Part 7 (1.04) has the following requirement: "Support of a NotificationMessage retransmission queue is not required; if not available the Republish Service returns Bad_MessageNotAvailable.".

Currently, there  is no support to disable the retransmission queue. If configuring the queue length to 0 it means unlimited queue size. For resource constrained devices this could be a good option to save some memory and reduce the footprint of the OPC UA stack.

To keep the queue size configuration option consistent with other size options I think it would be good to let 0 be unlimited queue size. Instead I think a boolean config option can be added to server config to let the user configure if the server should support the retransmission queue.

https://github.com/open62541/open62541/blob/7722d7d2345c23b5eecb1d446c4b980617338c72/include/ua_server_config.h#L158

## Background Information / Reproduction Steps
Make it possible for resource constrained devices to support a limited feature set required by profiles.

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 7722d7d 
 - [x] Other OPC UA SDKs used (client or server): N/A
 - [x] Operating system: N/A
 - [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached: N/A
 - [x] Wireshark network dump attached: N/A
 - [x] Self-contained code example attached:
 - [ ] Critical issue

**Comment by jpfr** [comment]
The feature was done by @jonasgreen88 and is available on master.
