### ISSUE TITLE
Client can hang on blocking send calls

### ISSUE THREAD

**Issue by cookiejarlid** [open62541/open62541#2577]
## Description

UA_send in ua_network_tcp.c:connection_write is being called in blocking mode without a timeout, causing the client to hang arbitrarily and indefinitely.

## Background Information / Reproduction Steps

I think the issue can be consistently reproduced by having the remote peer (the server) abruptly drop the client without sending a TCP FIN/RST. This will cause the client to not realize that it has lost connection thus causing the send call to not return.

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): master branch
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [x] Critical issue

For the non-async API, I would suggest setting the SO_SNDTIMEO socket option (as well as the SO_RCVTIMEO since any UA_recv blocking call will be affected by the same issue) and checking for EAGAIN/EWOULDBLOCK.

For the async API, which is currently and incorrectly making use of blocking socket function calls, I would suggest that the socket be set to non-blocking mode and a timeout check be added.

I would like to emphasize the gravity of calling blocking socket functions on async API calls. These calls should be required to return control to the user code immediately, and not be dependent on any possible network delay or abrupt and undetected connection loss.

I've edited my issue post to add a possible reproduction method. I've also rechecked the source code for UA_recv and since it's using UA_select, the issue shouldn't affect it. It is however still a serious issue to have UA_select block for "timeout" seconds on async calls.

**Comment by jpfr** [comment]
We are moving to full-on event-based networking in the WIP PR #2408.
Until then, feel free to propose code changes.

It seems these changes would all fit into /arch/ua_network_tcp.c with minimal API changes.

**Comment by andranik-s** [comment]
@jpfr can you please elaborate on "full-on event-based networking"? Does that mean non blocking IO or something else? I'm asking because after taking a glance at https://github.com/open62541/open62541/pull/2408 it seems to me it still uses blocking IO: [UA_TCP_DataSocket_send, for example](https://github.com/mlgiraud/open62541/blob/9f9ef8fe43fbf446d37f0adb245bfe0e3c17902e/plugins/networking/ua_tcp_data_socket.c#L214-L227).

**Comment by andranik-s** [comment]
Also in the context this issue what do you (@jpfr, @Pro) think about libev/libevent? I was thinking of proposing a PR that will add optional non blocking IO support using libev, but wanted to check with you first.

Just to clarify that PR will not change the current code (or at least I'll try to minimize the changes). All the changes will be in conditional inclusion blocks like UA_USE_LIBEV_EXPERIMENTAL.

Will you consider such PR?

**Comment by jpfr** [comment]
@andranik-s , yes, the idea is to move to an event-based control flow.
The work is happening in the background. See #3409 for the upcoming network layer.
Libev would be easy to add once this has landed.

Closing this issue. Since v1.1 the client respects timeouts everywhere.

**Comment by mlgiraud** [comment]
I would like to add that the receive logic should be fully asynchronous in the new networking code, but the send logic is not, as @andranik-s pointed out.
But with the coming changes it should be a lot easier to implement fully asynchronous send as well.
