### ISSUE TITLE
How to handle embedded binary schemas?

### ISSUE THREAD

**Issue by basyskom-meerkoetter** [open62541/open62541#2582]
I am trying to generate the nodes for the AutoId information model. https://opcfoundation.org/UA/schemas/AutoID/1.0/ provides an XML nodeset and a CSV file, but no binary schema description (while still defining types).
After a hint of a colleague i noticed the bsd embedded as a base64 encoded string in the node set xml. I've extracted/decoded it by hand.

Said colleague also mentioned that recent versions of the ua modeler stopped exporting .bsd files but are rather embedded the .bsd as based64.

I wonder what the reason for this change is and if the open62541 python tooling should transparently handle it?

**Comment by Pro** [comment]
A general info (for other readers):

The .bsd file is used for creating the custom structs and datatypes for this specific nodeset.
If the nodeset does not define any custom data types, you can also skip the whole datatype generation.
This is done e.g. for the PLCopen nodeset here:
https://github.com/open62541/open62541/blob/master/examples/nodeset/CMakeLists.txt#L94

If your nodeset defines custom datatypes, currently a .bsd file is required. If it is not given with the .xml file, there are two ways to get it:
- you can extract it's content from the huge base64 encoded byte string in the NodeSet2.xml (use some online converter)
- you can use UaModeler: Open the NodeSet2.xml, confirm that it should be converted, and then just export it again. With this, UaModeler will also export a .bsd file

On the long term we need to get rid of the .bsd dependency and just use the `<Definition>` tags from within the NodeSet2.xml file.

I'm closing this in favor of the new issue #2587
