### ISSUE TITLE
Unit tests failing on master

### ISSUE THREAD

**Issue by mlgiraud** [open62541/open62541#2585]
## Description
Multiple unit tests fail when using the following cmake configuration:
```
-DCMAKE_BUILD_TYPE=Debug
-DUA_BUILD_EXAMPLES=ON
-DUA_BUILD_UNIT_TESTS=ON
-DUA_ENABLE_DISCOVERY=ON
-DUA_ENABLE_DISCOVERY_MULTICAST=ON
-DUA_ENABLE_COVERAGE=ON
-DUA_ENABLE_UNIT_TESTS_MEMCHECK=OFF
-DUA_ENABLE_SUBSCRIPTIONS=ON
-DUA_ENABLE_ENCRYPTION=ON
-DUA_LOGLEVEL=300
-DUA_ENABLE_VALGRIND_INTERACTIVE=OFF
-DUA_ENABLE_AMALGAMATION=OFF
-DUA_ENABLE_PUBSUB=ON
-DUA_NAMESPACE_ZERO=MINIMAL
-DUA_ENABLE_SUBSCRIPTIONS=ON
-DUA_ENABLE_SUBSCRIPTIONS_EVENTS=OFF
-DUA_BUILD_FUZZING=OFF
-DUA_BUILD_FUZZING_CORPUS=OFF
-DUA_BUILD_OSS_FUZZ=OFF
-DUA_ENABLE_PUBSUB=ON
-DUA_ENABLE_PUBSUB_ETH_UADP=ON
-DUA_ENABLE_PUBSUB_DELTAFRAMES=ON
-DUA_ENABLE_PUBSUB_INFORMATIONMODEL=ON
-DUA_ENABLE_PUBSUB_INFORMATIONMODEL_METHODS=ON
```

## Background Information / Reproduction Steps
Build the project with the above cmake options and execute the unit tests with `make test`
CMake version: 3.13.4
Compiler: clang-8
System: Ubuntu 18.04.2 LTS

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): master
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Ubuntu 18.04.2 LTS
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
The problem is the `MINIMAL` NS0 setting.

Which produces the following failures:

```

The following tests FAILED:
	 11 - services_attributes (Failed)
	 12 - services_nodemanagement (Failed)
	 13 - services_call (SEGFAULT)
	 22 - node_inheritance (Failed)
	 37 - client_subscriptions (Failed)
	 38 - client_highlevel (Failed)
```

Setting it to `REDUCED` your specific config runs through.

We are currently not testing the unit tests with `MINIMAL` setting. Guess we should also add this test. Let me see...
