### ISSUE TITLE
Running PubSub samples on different computers does not work?

### ISSUE THREAD

**Issue by theresa95** [open62541/open62541#2609]
I am currently experimenting with the publish and subscribe example applications. 
If I execute both samples on my windows desktop, it works like a charm: the publish-application publishes timestamps and the subscribe-application prints out the current timestamps. Also, I can see the transmitting udp packages in wireshark.

Now, I want to run the publish application on the raspberry pi and the subscribe application on my windows desktop (as before). But know, I do not see any udp packages in wireshark (windows) and there are no timestamps printed by the subscribe example also! 

I tried the same by running the publish example in a virtual box (with linux as operating system) and the subscribe example on windows desktop and I have the same problem as well: I can NOT see UDP packages transmitted in wireshark on the windows desktop, BUT I can see them if I start Wireshark in my Linux virtual box. So they are published, but it seems like the packages do not make it to the windows desktop. So what do I have to do to publish the UDP packages to my windows desktop, and not only on my raspberry pi/linux virtual box??

I also noticed that the publish example publishes the timestamp with the multicast address 224.0.0.22 and the subscribe example is listening to the same multicast address. So this should be fine, shouldn't it?

![image](https://user-images.githubusercontent.com/20508343/55145193-9c17af00-5142-11e9-889d-3d600bffd3cc.png)

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag):  clones from master branch in march 2019
 - [x] Operating system: Windows 10 Home, Virtual Box with Ubuntu 18.04.2 LTS and Raspberry Pi
 - [ ] Wireshark network dump attached: The wireshark output looks exactly like in the tutorial of the documentation when both the publish and subscribe sample applications are running on the same machine. No UDP packages are transferred if the publish/subscribe applications are running on different machines (for example: publish sample runs on linux virtual box machine, subscribe on windows machine)
 - [x] Critical issue

**Comment by jpfr** [comment]
Do not open duplicate issues.
You can add more comments below to an issue.

**Comment by jpfr** [comment]
Please try to set the network interface name together with the IP address.
Closing in favor of #2612.
