### ISSUE TITLE
Creating models to be used with the XML Nodeset Compiler

### ISSUE THREAD

**Issue by Demolishun** [open62541/open62541#2623]
## Description
Trying to understand how to use the XML Nodeset Compiler.  I have downloaded and installed
this https://github.com/FreeOpcUa/opcua-modeler program.  I have also successfully built the open62541 library and built a simple server which I can compile and run.
Does anyone know if opcua-modeler produces good xml for use by the open62541 XML Nodeset Compiler?  I want to create models, compile them into open62541 code, and then inspect these models to determine how to build my own.  One issue I am running into is I cannot figure out how to specify arrays.  So I was hoping the Nodeset Compiler could help me understand this.  

## Checklist

Please provide the following information:

 - [x ] open62541 Version (release number or git tag): 0.4.0 (0.3-rc2-868-g6d2381dd)
 - [x ] Other OPC UA SDKs used (client or server): Free OPC UA Modeler
 - [x ] Operating system: Ubuntu 18.04 Linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
I did some very basic tests with the opcua-modeler a few months ago, but unfortunately in that time it did not support all the necessary features I needed. Maybe it improved in the meantime.

There are some alternatives:
- Manually write the NodeSet2.xml (not recommended)
- Use the commercial UaModeler (free up to 100 nodes)
- Use the free UA-ModelCompiler (https://github.com/OPCFoundation/UA-ModelCompiler)

I personally always use the UA-ModelCompiler.
There you need to manually write Model.xml files which are much simpler and more intuitive than the NodeSet2.xml file. The ModelCompiler then takes this Model.xml file and generates all the necessary files out of it (NodeSet2.xml, Types.bsd, NodeId.csv, ...).

I created a PR to also use it on Linux:
https://github.com/OPCFoundation/UA-ModelCompiler/pull/20

Some example Model.xml files can be found here:
https://github.com/OPCFoundation/UA-ModelCompiler/tree/master/ModelCompiler/Design

For Arrays:
https://github.com/OPCFoundation/UA-ModelCompiler/blob/master/ModelCompiler/Design/OpcUaDiModel.xml#L49
