### ISSUE TITLE
Typo in documentation of NodeClass

### ISSUE THREAD

**Issue by tobiaslocker** [open62541/open62541#2632]
## Description

There's a typo in the NodeClass [documentation](https://open62541.org/doc/0.3/types_generated.html?highlight=ua_nodeclass_object#nodeclass). It says `UA_NODECLASS_OBJECT_TYPE` when it should be `UA_NODECLASS_OBJECTTYPE` 

 - [x] open62541 Version v0.3.0
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
This is generated code.
Fixed on master.

I would keep as-is on 0.3.
It would break API compatibility.
