### ISSUE TITLE
Building examples using CMake fails on a Linux system

### ISSUE THREAD

**Issue by alex-lotz** [open62541/open62541#2646]
## Description

On a Linux system and the open62541 library installed globally, CMake fails building the default client.c example (or any example) due to failing to find the include header named **ua_architecture_base.h** which is included from the installed header file **posix/ua_architecture.h**.

Possible fix, the header **posix/ua_architecture.h** should prefix the include of **ua_architecture_base.h** with **open62541** as follows. 

Change the installed file **posix/ua_architecture.h** in line 13 from this:
```
#include "ua_architecture_base.h"
```
to this:
```
#include "open62541/ua_architecture_base.h"
```
Moreover, probably the header files themselves should be renamed removing the "ua_" prefix to align with all the other header file names as this seems to be the new naming convention (but this would be optional).

## Background Information / Reproduction Steps

It seems that the global install of the open62541 library on a linux system now generates header files that do not have the "ua_" prefix anymore. However, a few files related to posix includes still seem to rely on the old naming convention and include strategy.

Steps to reproduce the error:

1. Git clone the open62541 library and build it using cmake and make (standard build) on a Linux/Posix system
2. Install the library globally using **sudo make install**
3. Create a simple custom [CMakeLists.txt](https://github.com/open62541/open62541/files/3072276/CMakeLists.txt) file to build the default [client.c](https://github.com/open62541/open62541/blob/master/examples/client.c) example.
4. Try building the client.c example using CMake, which fails with this error:

```
[ 50%] Building C object CMakeFiles/OpcUaClient.dir/client.c.o
In file included from /usr/local/include/open62541/config.h:103:0,
                 from /usr/local/include/open62541/client_config.h:12,
                 from /usr/local/include/open62541/client_config_default.h:12,
                 from /home/alexej/temp/open62541/client.c:4:
/usr/local/include/open62541/posix/ua_architecture.h:13:34: fatal error: ua_architecture_base.h: No such file or directory
compilation terminated.
CMakeFiles/OpcUaClient.dir/build.make:62: recipe for target 'CMakeFiles/OpcUaClient.dir/client.c.o' failed
make[2]: *** [CMakeFiles/OpcUaClient.dir/client.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/OpcUaClient.dir/all' failed
make[1]: *** [CMakeFiles/OpcUaClient.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
The fix to this problem seems to be obvious by renaming the remaining header files related to Posix in the same way as all the other headers.

## Checklist

Please provide the following information:

 - [X] open62541 Version: **latest master branch from 10th of April 2019**
 - [X] Operating system: **Ubuntu Linux 16.04 64bit**
 - [X] Self-contained code example attached: **[CMakeLists.txt](https://github.com/open62541/open62541/files/3072276/CMakeLists.txt)**
 - [X] Critical issue

**Comment by Pro** [comment]
Thanks for your issue report!

This should be fixed with #2655
