### ISSUE TITLE
Add multi dimension array to variable value callback

### ISSUE THREAD

**Issue by santoshpanda1989** [open62541/open62541#2665]
## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): Master
 - [x] Other OPC UA SDKs used (client or server): UAExpert
 - [x] Operating system: Windows
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [x] Self-contained code example attached
 - [ ] Critical issue
@jpfr Sorry for creating another issue as I was unavailable for 2 weeks. I did as you mentioned in the earlier issue. PFB the details.
I have created a sample array and tried to assign the dimensions for the Variant. But, I am getting BadTypeMismatch error. PFB the server screenshot. 
![server_error](https://user-images.githubusercontent.com/19244975/56659134-a7f08580-669c-11e9-96f4-4584e21f0628.JPG)
Also, find below the the nodeset.xml snippet.

![nodeset](https://user-images.githubusercontent.com/19244975/56659510-a1aed900-669d-11e9-99fc-14652c37ed12.JPG)

Find the code snippet below.

    UA_Variant v;
    UA_Double d[9] = {1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0};
    v.arrayDimensions = (UA_UInt32 *)UA_Array_new(9, &UA_TYPES[UA_TYPES_UINT32]);
    v.arrayDimensionsSize = 2;
    v.arrayDimensions[0] = 3;
    v.arrayDimensions[1] = 3;
    UA_Variant_setArrayCopy(&v, d, 9, &UA_TYPES[UA_TYPES_DOUBLE]);
    UA_NodeId currentNodeId = UA_NODEID_NUMERIC(3, 6010);
    UA_Server_writeValue(server, currentNodeId, v);

I would really appreciate any help regarding this. I also tried with array dimension as {3,3} in the information model.

Thanks,
Santosh

**Comment by jpfr** [comment]
UA_Variant_setArrayCopy is overriding the arraydimensions you have set before.

**Comment by santoshpanda1989** [comment]
Thanks @jpfr. It works now.
