### ISSUE TITLE
Parse+Load XML NodeSet at runtime

### ISSUE THREAD

**Issue by paddor** [open62541/open62541#2668]
Just getting started with this project, hopefully to replace another UA stack. So far we've been generating our own XML nodesets. We then provide the generated XML file to the server during startup.

Is there a way to do this with Open62541? Am I missing something or is it absolutely necessary to include a compilation step to be able to load a new nodeset?

**Comment by jpfr** [comment]
We currently do not parse XML at runtime.
Renaming as a feature-request for future reference.

**Comment by jpfr** [comment]
@matkonnerth has proposed a PR for this in #2937.

**Comment by paddor** [comment]
How would one have to proceed to avoid having to compile a nodeset in advance?

Is dynamically inserting folders, objects, and variables during runtime the only way? Is this possible before starting the server?

**Comment by matkonnerth** [comment]
maybe this helps: https://github.com/matkonnerth/nodesetLoader
