### ISSUE TITLE
tutorial_datatypes.c: file ua_types.h does not exist

### ISSUE THREAD

**Issue by franzhollerer** [open62541/open62541#2669]
The comment within the file tutorial_datatypes.c on the master branch referes the file *ua_types.h*.

```
 * Basic Data Handling
 * ^^^^^^^^^^^^^^^^^^^
 * This section shows the basic interaction patterns for data types. Make
 * sure to compare with the type definitions in ``ua_types.h``. */
```

It seems that the file was renamed to *types.h* and the documentation should be updated accordingly.

**Comment by jpfr** [comment]
Fixed on master by @franzhollerer .
