### ISSUE TITLE
tutorial_server_firststeps.c: running should be qualified volatile

### ISSUE THREAD

**Issue by franzhollerer** [open62541/open62541#2683]
On the master branch within file tutorial_server_firststeps.c: As the global variable *running* is modified from the signal handler it should be qualified *volatile*.

Furthermore, as it is passed as reference to *UA_Server_run()* its visibility could be restricted.

I suggest to change:

```
UA_Boolean running = true;
```

to

```
static volatile UA_Boolean running = true;
```

**Comment by Pro** [comment]
Fixed with #2684

Thanks
