### ISSUE TITLE
No suitable userToken Policy found for possible endpoints

### ISSUE THREAD

**Issue by valka465** [open62541/open62541#2701]
## Description
I'm sorry for my bad English. I have some problems. The main one is "No suitable UserToken Policy found for possible endpoints". 

- Open62541 Version is v0.4 (current). 

- Type is Client. 

- Operating System: Windows 10.

- Visual Studio: VS 2017 v15.

Screenshots:
![image](https://user-images.githubusercontent.com/46899675/57123178-92a8e480-6d89-11e9-894d-e173d965e71a.png)

I tried to test it in UAExpert. It works if ignoring the "BadSecurityModelnsufficient"

![image](https://user-images.githubusercontent.com/46899675/57123293-f29f8b00-6d89-11e9-9793-d09904a43bdb.png)

![image](https://user-images.githubusercontent.com/46899675/57123317-064af180-6d8a-11e9-9980-98ed3c971aff.png)

## Background Information / Reproduction Steps

Code:

```
#include "open62541.h"
#include <stdio.h>
#include <stdlib.h>

int main()
{
	UA_Client *client = UA_Client_new();
	UA_ClientConfig_setDefault(UA_Client_getConfig(client));

	UA_EndpointDescription* endpointArray = NULL; 
	size_t endpointArraySize = 0;
	UA_StatusCode retval = UA_Client_getEndpoints(client, "opc.tcp://10.0.16.33:4840", &endpointArraySize, &endpointArray);
	if (retval != UA_STATUSCODE_GOOD) {
		UA_Array_delete(endpointArray, endpointArraySize, &UA_TYPES[UA_TYPES_ENDPOINTDESCRIPTION]);
		UA_Client_delete(client);
		return EXIT_FAILURE;
	}
	printf("%i endpoints found\n", (int)endpointArraySize);
	for (size_t i = 0; i < endpointArraySize; i++) {
		printf("URL of endpoint %i is %.*s\n", (int)i,
			(int)endpointArray[i].endpointUrl.length,
			endpointArray[i].endpointUrl.data);
	}

  retval = UA_Client_connect_username(client, "opc.tcp://10.0.16.33:4840", "Maintenance", "0000");
  if (retval != UA_STATUSCODE_GOOD) {
    UA_Client_delete(client);
	getchar();
	return EXIT_FAILURE;
  }

  UA_Variant value;
  UA_Variant_init(&value);

  const UA_NodeId nodeId = UA_NODEID_NUMERIC(0, UA_NS0ID_SERVER_SERVERSTATUS_CURRENTTIME);
  retval = UA_Client_readValueAttribute(client, nodeId, &value);

  if (retval == UA_STATUSCODE_GOOD && UA_Variant_hasScalarType(&value, &UA_TYPES[UA_TYPES_DATETIME])) {
    UA_DateTime raw_date = *(UA_DateTime *)value.data;
    UA_DateTimeStruct dts = UA_DateTime_toStruct(raw_date);
    UA_LOG_INFO(UA_Log_Stdout, UA_LOGCATEGORY_USERLAND, "date is: %u-%u-%u %u:%u:%u.%03u\n", dts.day, dts.month, dts.year,
                dts.hour, dts.min, dts.sec, dts.milliSec);
  }

  UA_Variant_deleteMembers(&value);
  UA_Client_delete(client);
  return UA_STATUSCODE_GOOD;
}
```

Screenshots from shark 
![image](https://user-images.githubusercontent.com/46899675/57123374-3a261700-6d8a-11e9-9a1d-db9f8a767833.png)

Application - counter promag 300.

Please provide the following information:

 - [x] open62541 Version (release number or git tag): v0.4 (current)
 - [x] Other OPC UA SDKs used (client or server): client
 - [x] Operating system: windows 10
 - [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [x] Wireshark network dump attached
 - [x] Self-contained code example attached
 - [x] Critical issue

**Comment by jpfr** [comment]
You need to compile with encryption enabled and load the certificate and private key for the client.
This is not done in your code.

Even though the channel is not encrypted, the password is still encrypted.
So you need the entire infrastructure.
