### ISSUE TITLE
How to publish and subscribe random data using pubsub code?

### ISSUE THREAD

**Issue by jadhavshital** [open62541/open62541#2708]
The default pubsub code is publishing server's current datetime in "Datetime" datatype. When I am sending random data by using "rand()%40" it is not subscribed by subscriber.
I have attached the screenshots of same. (Highlighted lines are used for generating and publishing random values between 0 to 39.)
![addDataSetField](https://user-images.githubusercontent.com/17235485/57217890-82a33600-7011-11e9-862f-406df6be4240.PNG)
![dataSetWriter](https://user-images.githubusercontent.com/17235485/57217908-8a62da80-7011-11e9-87fb-65bd1fc09546.PNG)

In Subscriber, they are comparing for datatypes received from publisher. So I am not able to get how for what datatype I should compare this?
![subscriber](https://user-images.githubusercontent.com/17235485/57218151-3ad0de80-7012-11e9-9966-d56c712c636f.PNG)

Kindly help.

**Comment by jh-isw** [comment]
The second parameter of UA_NODEID_NUMERIC() is not the value to publish, but the identifier of the node in the server's address space.

Your server needs to have a node that is UA_Int32 and you assign it your random value. This node is your publishedVariable, identified by a NodeID.

**Comment by jadhavshital** [comment]
Can you please elaborate more in detail?

**Comment by jpfr** [comment]
You should not set the writerId to a random value.
You should set the value in the variable in the information model that is referenced in the DataSet.

Please read the spec and example code.
We are glad to help. But you need to put in the work as well.
