### ISSUE TITLE
ServerStatus->BuildInfo contains empty Values

### ISSUE THREAD

**Issue by derhexer13** [open62541/open62541#2729]
Since i have updated to the current open62541 sources all ServerStatus.BuildInfo subnodes (ProductUri, ManufacturerName etc.) of the example servers (e.g. server-mainloop) contains empty values.
My last setup (0.3-rc1) worked fine.

 - open62541 Version (release number or git tag): "0.3-rc2-973-gb66d533e"
 - Other OPC UA SDKs used (client or server): UaExpert 1.15.1
 - Operating system: Windows 10

**Comment by jpfr** [comment]
A fix is proposed in #2733.
