### ISSUE TITLE
Server crashes if UA_EventFilter is not set when calling UA_Client_MonitoredItems_createEvent

### ISSUE THREAD

**Issue by andranik-s** [open62541/open62541#2731]
## Description

`UA_Client_MonitoredItems_createEvent` crashes the server when an event is triggered if `UA_EventFilter` is not set in `UA_MonitoredItemCreateRequest` . I don't know if it is considered to be a malformed request, but the server shouldn't crash either way.

The crash occures in `resolveSimpleAttributeOperand` due to `const UA_SimpleAttributeOperand *sao` being `NULL`.

I think the problem is the `setMonitoredItemSettings` function. It jumps into the first if branch (`if(params->filter.encoding != UA_EXTENSIONOBJECT_DECODED)`) and inits the filter as `UA_DataChangeFilter`, which causes a segfault when the event is triggered (UA_EventFilter::selectClausesSize = 1, because UA_DataChangeFilter::trigger is set to 1).

## Background Information / Reproduction Steps

Comment out the following lines in `tutorial_client_events.c`
 ```c
item.requestedParameters.filter.encoding = UA_EXTENSIONOBJECT_DECODED;
item.requestedParameters.filter.content.decoded.data = &filter;
item.requestedParameters.filter.content.decoded.type = &UA_TYPES[UA_TYPES_EVENTFILTER];
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): master
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
Thanks! Will be fixed with #2734
