### ISSUE TITLE
Cross Compile open62541 for RPi on windows platform

### ISSUE THREAD

**Issue by Kathy135** [open62541/open62541#2750]
Hello community,

I am trying to cross compile the stack for RPI from Windows platform. In the tools folder, I could only see the steps for Linux. Is there a way to cross compile using Windows? Your response would be really helpful for my progress.

Thanks in advance.

**Comment by jpfr** [comment]
Why don't you directly compile the library on the raspberry?
That takes only a minute or so.

See here for cross compiler downloads.
https://gnutoolchains.com/raspberry/
It should be easy to use together with the CMake build tools.

Please reopen if questions remain that are specific to open62541.
For general stuff, there is stackoverflow.
