### ISSUE TITLE
question for user defined structure 

### ISSUE THREAD

**Issue by davesliu** [open62541/open62541#2754]
Hi,

I want to create user defined structure like below:
 struct {
int a;
float b;
long c;
}

I tried the custom_datatype example of open62541, it can't be parsed by the UaExpert tool.
The user defined structure can only be parsed if both client and server know the structure definition in open62541.

I have saw that  another OPC UA application python-opcua can support user defined structures, and the structure can be parsed by the UaExpert tool as shown in below example.
https://github.com/FreeOpcUa/python-opcua/blob/master/examples/server-create-custom-structures.py

So could open62541 support user defined structure like python-opcua?

Thanks1=!

## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Yes we do support custom types.
Have a look in the examples folder as well as the unit tests.

Please reopen if that is not enough documentation.
