### ISSUE TITLE
Diagnostics info of server object on OPC UA server

### ISSUE THREAD

**Issue by davesliu** [open62541/open62541#2770]
For the server example code of Open62541. I use UaExpert to connect to the server.
For the node Id i=2277 (Server_ServerDiagnostics_ServerDiagnosticsSummary_CurrentSessionCount)
The value is always 0.

Does it mean that current open62541 not support diagnostics feature of server?

BTW, If using the uaserver.cpp, the node Id i=2277 (Server_ServerDiagnostics_ServerDiagnosticsSummary_CurrentSessionCount) will reflect the correct current session count.

## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by NoelGraf** [comment]
EnabledFlag identifies whether or not diagnostic information is collected by the Server. It can also be used by a client to enable or disable the collection of diagnostic information of the Server. The following settings of the Boolean value apply: TRUE (1) indicates that the Server collects diagnostic information, and setting the value to TRUE leads to resetting and enabling the collection. FALSE (0) indicates that no diagnostic information is collected, and setting the value to FALSE disables the collection without resetting the diagnostic values.
The currentSessionCount shows the number of client sessions that are currently set up in the server.
I would then close the issue. Please reopen if required!
