### ISSUE TITLE
How to send ReadResponse from the Server?

### ISSUE THREAD

**Issue by EmbSys2019** [open62541/open62541#2780]
Hello .. i started to implement OPC UA Server on my hardware (STM32F7) and i am using freertos and lwIP and everything is ok.
i can run the Server and read the nodes, but what i can't understand is how to send ReadResponse from the Server to the Client.

i am following the examples in the tutorials like here:

[https://open62541.org/doc/current/tutorial_server_datasource.html]()

the UAExpert sends just publisher requests and if i stoped the publisher from UAExpert i cant see the changes of the node
do i do something wrong or i missed something?
the UAExpert send just ReadRequest for the node 2259 which is the state of the server. is there any example to make the server work as server/client?

here is wireshark capture:

![saa](https://user-images.githubusercontent.com/48807747/58855499-7bb72400-86a0-11e9-9f38-a549cc8f4d05.JPG)

thnx

## Checklist

Please provide the following information:

 - [x] open62541 Version (FixFreeRTOS_Branch):
 - [x] Other OPC UA SDKs used (UAExpert Client): 
 - [x] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
The read service is the same for everybody and cannot be modified.
You should make your changes to the object-oriented information model.
And keep the service as they are.

The server already is server/client. OPC UA always is (without the PubSub extension).
