### ISSUE TITLE
Subscriber: Wrong union-member is used when checking for publisherId

### ISSUE THREAD

**Issue by Fischer-Thomas** [open62541/open62541#2838]
When subscribing to a publisher with a UInt16 publisherId there is currently an error:
Instead of using the "publisherIdUInt16" Member of the union the "publisherIdByte" is used, as seen below in line 425.

https://github.com/open62541/open62541/blob/2cfff7aa4f513e661a718de5b561290b79c1b207/src/pubsub/ua_pubsub.c#L424-L425

**Comment by jpfr** [comment]
Thanks for reporting.
The fix is coming in #2840.
