### ISSUE TITLE
Running the example Server on my Mac

### ISSUE THREAD

**Issue by joesan** [open62541/open62541#2843]
## Description 
Unable to run the example server as mentioned in the documentation here: https://open62541.org/doc/0.3/tutorial_server_firststeps.html

## Background Information / Reproduction Steps
I was trying to get the server up and running on my Mac. I tried to do this as a Docker container. Here is the [Dockerfile](https://github.com/joesan/opc-client-stream/blob/master/Dockerfile) that I'm using!

When I build my Docker image, I get the following error:

```
Step 11/12 : RUN gcc -std=c99 open62541.c myServer.c -lws2_32 -o myServer.exe
 ---> Running in f95b293d0fd0
/usr/bin/ld: cannot find -lws2_32
collect2: error: ld returned 1 exit status
```
Any ideas on how I can load this ws2_32 library? Or any other ways to run this on Ubuntu? I guess the ws2_32 is a dll that can only run on Windows!

## Checklist
 - [x] open62541 Version (release number or git tag): 0.3.0
 - [x] Operating system: Mac OS Mojave

**Comment by jpfr** [comment]
ws2_32 is a Windows library. Your mac does not have it.

**Comment by joesan** [comment]
So to run the example server, I need to be on Windows is it? How can I run it on Ubuntu?

**Comment by jpfr** [comment]
The library works in Mac, Linux, Windows and a couple more.
But you don't need include ws2_32 on Linux. It should simply work without.

Please reopen if questions remain.
