### ISSUE TITLE
Assertion Fail in UA_Nodestore_releaseNode while calling UA_Server_readDataType

### ISSUE THREAD

**Issue by juangburgos** [open62541/open62541#2848]
## Description

I have been having this issue for a debug assertion violation in `UA_Nodestore_releaseNode`:

```c
UA_assert(entry->refCount > 0);
```

Of course it does not affect the release builds being an assertion, but I cannot run a server on debug mode for more than a couple of hours without it crashing the session.

What could be causing it? Maybe I am using the library API incorrectly?

Thanks.

## Background Information / Reproduction Steps

Call `UA_Server_readDataType` to read  every once in a while and it will eventually happen.

![error01](https://user-images.githubusercontent.com/4707341/60253655-cf4a1580-98cc-11e9-8570-1ba0ecd40813.jpg)

![Error02](https://user-images.githubusercontent.com/4707341/60253670-d3763300-98cc-11e9-8743-1dffbf9c73fd.jpg)

```c++
Q_ASSERT(!UA_NodeId_isNull(&m_nodeId));
if (UA_NodeId_isNull(&m_nodeId))
{
	return QMetaType::UnknownType;
}
// read type
UA_NodeId outDataType;
auto st = UA_Server_readDataType(m_qUaServer->m_server, m_nodeId, &outDataType);
Q_ASSERT(st == UA_STATUSCODE_GOOD);
Q_UNUSED(st)
```

**Full code** [**here**](https://github.com/juangburgos/QUaServer/blob/636543d1744a8427ae02a40d9e02cce66d5a31bf/src/wrapper/quabasevariable.cpp#L170).

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): master
 - [x] Other OPC UA SDKs used (client or server): UaExporer
 - [x] Operating system: Windows

**Comment by Pro** [comment]
Could it be that you are accessing `m_qUaServer->m_server` in different threads?

This assertion normally fails, if there are some race conditions, or (less likely) there is a missing `Node_release` in the internal code. Since you are using the public API which is tested via unit tests, that's less likely, but still possible.

**Comment by juangburgos** [comment]
Not that I am aware, but I will double check my threaded code for race conditions. Will report back if find something. Thanks for the reply.

**Comment by juangburgos** [comment]
Put some extra guards on threaded code and have not been able to reproduce again. Closing now, will reopen if comes back. Thank you!
