### ISSUE TITLE
Upload file from UAExpert client to the Server on STM32

### ISSUE THREAD

**Issue by Feras992** [open62541/open62541#2862]
Hello there,

i looked in the example folder for an example on how to upload file "binary file for example" from the client "UAExpert" to a server runs on STM32F429.

is there any example for it? support open62541 File uploading?

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): FixFreeRTOS Branch
 - [x] Other OPC UA SDKs used (client or server): UAExpert
 - [x] Operating system: FreeRTOS
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by embbo** [comment]
I have an idea... if you make call back function and make "string" as input arugument then you can upload whole string as input arguemnt .

**Comment by jpfr** [comment]
Umm. What binary do you mean?
The server binary you want to run?

**Comment by Feras992** [comment]
@embbo in Specification part 5 annex c there is somthing called Temporary File Transfer so i think it should be the way how to upload a file but i couldn't find any implementation for it.

@jpfr i mean with it a binary file like .bin .. it can be the binary code of STM32 so i can update the Software over the opc ua

**Comment by jpfr** [comment]
You should not use OPC UA to update the firmware.
It was made for runtime communication. Not for development purposes.

Ask your vendor about the compiler and toolchain he recommends.

**Comment by jpfr** [comment]
Or is this a feature where the end-customer can flash the firmware?

**Comment by Feras992** [comment]
> 
> 
> Or is this a feature where the end-customer can flash the firmware?

@jpfr  yes it will be a feature to flash a new firmware using opc ua. i'm not sure if open62541 support somthing like this

**Comment by schroeder-** [comment]
There is a FileType which you can use, but you have to implement your own instance. There is no out of the box support for it.

**Comment by Feras992** [comment]
@schroeder-  i couldn't find the FileType in open62541.
do u mean that i have to implement the whole FileType with all his Variables and Methods like "open, read, write, etc ... )?

**Comment by schroeder-** [comment]
> @schroeder- i couldn't find the FileType in open62541.
You have to build with CMake option namespace=full or you add **FileType** to tools/schema/datatypes_minimal.txt and rebuild with cmake. 

> do u mean that i have to implement the whole FileType with all his Variables and Methods like "open, read, write, etc ... )?
you have to instantiate a object from FileType and implement the OPC UA Methods Close, GetPostion, Open, Read, SetPosition, Write and some properties.

**Comment by Pro** [comment]
I guess the main issue is answered. If not, please reopen.

**Comment by EmbSys2019** [comment]
@schroeder- i have the same problem, i tried to add the FileType to the datatypes_minimal.txt and rebuild the stack using cmake.

i'm not pretty sure how to instantiate an object from the FileType.

`
  UA_NodeId fileID;
  UA_ObjectAttributes fileAttr = UA_ObjectAttributes_default;
  fileAttr.displayName = UA_LOCALIZEDTEXT("en-US", "File");
  UA_Server_addObjectNode(server, UA_NODEID_NULL,
                          UA_NODEID_NUMERIC(0, UA_NS0ID_FILETYPE),
                          UA_NODEID_NUMERIC(0, UA_NS0ID_ORGANIZES),
                          UA_QUALIFIEDNAME(1, "File"), UA_NODEID_NUMERIC(0, UA_NS0ID_BASEOBJECTTYPE),
                          fileAttr, NULL, &fileID);
`

**Comment by Feras992** [comment]
hello and sorry for opening the issue once again

i have a problem with the FileType .. first of all i tried to add the FileTypt to the minimal Server as @schroeder- wrote, but it didn't work. so i copied the functions from the full server to the minimal server and added the FileType manually.

i started to implement the functions of the FileType(very basic implementation) and i instantiated an objcet from the FileType.
i instantiate the object using this code:

```
  UA_ObjectAttributes fileAttr = UA_ObjectAttributes_default;
  fileAttr.displayName = UA_LOCALIZEDTEXT("en-US", "Firmware");
  UA_Server_addObjectNode(server,
                          UA_NODEID_NUMERIC(1, 11575),
                          UA_NODEID_NUMERIC(0, UA_NS0ID_OBJECTSFOLDER),
                          UA_NODEID_NUMERIC(0, UA_NS0ID_ORGANIZES),
                          UA_QUALIFIEDNAME(1, "Firmware"),
                          UA_NODEID_NUMERIC(0, UA_NS0ID_FILETYPE),
                          fileAttr,
                          NULL,
                          NULL);
```
and i can see the object Firmware in the Server:

![FileType_1](https://user-images.githubusercontent.com/34221781/83534898-b3de8600-a4f1-11ea-8562-d902fdaff5dd.png)

and i choosed write from local file and choosed the file to be sent and i get this error:
![FileType_2](https://user-images.githubusercontent.com/34221781/83535045-db355300-a4f1-11ea-9e6e-e3b2dd81a814.png)

after that i tried to use every method in the FileType(read and write ...) and they worked
![FileType_3](https://user-images.githubusercontent.com/34221781/83535265-1768b380-a4f2-11ea-9d1e-b2ff20edb6bd.JPG)

i wrote a text file from the laptop to the server and sent it back over UART and i saved a massage from the uC to the laptop over the OPCUA server.

i didn't used the attributes from the FileType(Size, Writable, MimeType ...) in my code and i couldn't know to use them in this case.

Any help please? do i instantiate the object correctly? how to use the attributes?

thnx

**Comment by samAvr** [comment]
@Feras992 Have you solved it?

@jpfr i used this PR: [[WIP] FileType implementation](https://github.com/open62541/open62541/pull/4436/commits/3a5743269bd169e5d4cdcf5c69e5b19187682660) and it works when i upload a small file, which fits in my free ram. the problem is, i want know to upload a file (about 40Kb) and the free available RAM is about 25Kb.
The write callback function receives the whole data from the file. is there any way to receive small pieces of the file and handle it?
