### ISSUE TITLE
Error binding a server socket

### ISSUE THREAD

**Issue by czqinyes** [open62541/open62541#2876]
Error binding a server socket.........

**Comment by schroeder-** [comment]
Have you tried to start with an other Port like 4880?

**Comment by johndzilva** [comment]
Your system may have some background application running in port 4840 (LDS).

Change this line in your server code to run your application in some other port 

`UA_ServerConfig_setMinimal(config, 4801, NULL);`

**Comment by czqinyes** [comment]
> Your system may have some background application running in port 4840 (LDS).
> 
> Change this line in your server code to run your application in some other port
> 
> `UA_ServerConfig_setMinimal(config, 4801, NULL);`

Thanks a lot , i have taskkill the progress, and go well

**Comment by ccvca** [comment]
@czqinyes If this issue is solved, please close.
