### ISSUE TITLE
UA_NodeId_order incorrectly compare UA_NodeId

### ISSUE THREAD

**Issue by melkorb** [open62541/open62541#2898]
## Description
UA_NodeId_order incorrectly compare UA_NodeIds when UA_NodeId.identifierType equal UA_NODEIDTYPE_GUID.
## Background Information / Reproduction Steps
**current code: ua_types.c line 311**
case UA_NODEIDTYPE_GUID:
&nbsp;&nbsp;&nbsp;&nbsp;if(n1->identifier.guid.data1 < n2->identifier.guid.data1 ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n1->identifier.guid.data2 < n2->identifier.guid.data2 ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n1->identifier.guid.data3 < n2->identifier.guid.data3 ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;strncmp((const char*)n1->identifier.guid.data4,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(const char*)n2->identifier.guid.data4, 8) < 0)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_LESS;
&nbsp;&nbsp;&nbsp;&nbsp;if(n1->identifier.guid.data1 > n2->identifier.guid.data1 ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n1->identifier.guid.data2 > n2->identifier.guid.data2 ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n1->identifier.guid.data3 > n2->identifier.guid.data3 ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;strncmp((const char*)n1->identifier.guid.data4,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(const char*)n2->identifier.guid.data4, 8) > 0)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_MORE;
&nbsp;&nbsp;&nbsp;&nbsp;break;

**fixed code:**
case UA_NODEIDTYPE_GUID: {
&nbsp;&nbsp;&nbsp;&nbsp;if(n1->identifier.guid.data1 < n2->identifier.guid.data1) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_LESS;
&nbsp;&nbsp;&nbsp;&nbsp;} else if(n1->identifier.guid.data1 > n2->identifier.guid.data1) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_MORE;
&nbsp;&nbsp;&nbsp;&nbsp;} else if(n1->identifier.guid.data2 < n2->identifier.guid.data2) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_LESS;
&nbsp;&nbsp;&nbsp;&nbsp;} else if(n1->identifier.guid.data2 > n2->identifier.guid.data2) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_MORE;
&nbsp;&nbsp;&nbsp;&nbsp;} else if(n1->identifier.guid.data3 < n2->identifier.guid.data3) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_LESS;
&nbsp;&nbsp;&nbsp;&nbsp;} else if(n1->identifier.guid.data3 > n2->identifier.guid.data3) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return UA_ORDER_MORE;
&nbsp;&nbsp;&nbsp;&nbsp;} else {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const int cmp = strncmp(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(const char*)n1->identifier.guid.data4,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(const char*)n2->identifier.guid.data4,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;8
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(cmp < 0) return UA_ORDER_LESS;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(cmp > 0) return UA_ORDER_MORE;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;break;
}

**Comment by Pro** [comment]
thanks for the issue report and the suggestion.

Could you please create a new Pull Request with your changes?

See https://hisham.hm/2016/01/01/how-to-make-a-pull-request-on-github-a-quick-tutorial/

**Comment by Pro** [comment]
Fixed in #2904
