### ISSUE TITLE
Decoding error when adding multiple custom data types

### ISSUE THREAD

**Issue by m-fila** [open62541/open62541#2899]
## Description
Edits: formatting and re-uploaded file

Hi, I'm trying to add two custom data types basing on the [example](https://github.com/open62541/open62541/tree/master/examples/custom_datatype). The extra type is just structure with 4 float members. The problem is that I can't add more than 1 custom type at the same time --- reading the other results in `BadDecodingError`:
```bash
Point = 3.000000, 4.000000, 5.000000 
info/client	Error receiving the response with status code BadDecodingError
```
I tried adding both in 1 DataTypeArray:
**client.c**
```C
UA_DataType types[2];
types[0] = PointType;
types[0] = Point2Type;
UA_DataTypeArray customDataTypes = {NULL, 2, types};
cc->customDataTypes = &customDataTypes;
```
as well as in 2 arrays.:
**client.c**
```C
UA_DataType types[1];
types[0] = PointType;
UA_DataType types2[1];
types2[0] = Point2Type;
UA_DataTypeArray customDataTypes2 = {NULL, 1, types2};
UA_DataTypeArray customDataTypes = {&customDataTypes2, 1, types};
cc->customDataTypes = &customDataTypes;
```
## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=REDUCED
```
Minimal example: 
[customtypes.zip](https://github.com/open62541/open62541/files/3412299/customtypes.zip)

* client.c  
* server.c         
* custom_datatype.h  
* custom_datatype2.h
* Makefile

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): efb52e6
 - [x] Self-contained code example attached

**Comment by m-fila** [comment]
Closing. By mistake I provided both DataTypes with the same BinaryEncodingId

**Comment by chuongvhn** [comment]
@m-fila : 

> UA_DataTypeArray customDataTypes = {NULL, 2, types};
> UA_DataTypeArray customDataTypes2 = {NULL, 1, types2};

Could you please help tell which is proper way to initialize value for second element of UA_DataTypeArray, typesSize ? Is is the size of custom datatype or something else ?

[https://github.com/open62541/open62541/blob/b074084510390601cda713ee9b2f3884411129ea/include/open62541/types.h#L1016](https://github.com/open62541/open62541/blob/b074084510390601cda713ee9b2f3884411129ea/include/open62541/types.h#L1016)

**Comment by m-fila** [comment]
@chuongvhn , it's number of elements in  UA_DataType array. If you plan to write more than a few custom data types then I recommend using xml nodeset generator:
https://open62541.org/doc/current/nodeset_compiler.html
https://opcua.rocks/custom-information-models/
