### ISSUE TITLE
Install error with package manager

### ISSUE THREAD

**Issue by andri12321** [open62541/open62541#2906]
[error_log.txt](https://github.com/open62541/open62541/files/3421218/error_log.txt)
##  Description
Installing the packages from the daily build fails on (l)Ubuntu

## Background Information / Reproduction Steps
sudo add-apt-repository ppa:open62541-team/daily
sudo apt-get update
sudo apt-get install open62541-dev

## Additional Notes
The package open62541 installed without problems. Based on the error log the fault is probably that the shared libraries are in both packages.

**Comment by Pro** [comment]
Thanks for the report! Will have a look at it.

**Comment by andri12321** [comment]
Thanks a lot! Works now
