### ISSUE TITLE
Wrong include file in example

### ISSUE THREAD

**Issue by udayg4** [open62541/open62541#2968]
## Description
This refers to open62541-1.0-rc2 source code examples->client.c
## Background Information / Reproduction Steps
The first line in client.c examples is:
#include <open62541/client_config_default.h>
However there is no client_config_default.h in the stated path. There is a "client_config.h".  However, renaming the client_config_default to client_config doesn't work.

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
You need to add /plugins/include to the search path for header files.
https://github.com/open62541/open62541/blob/master/plugins/include/open62541/client_config_default.h
