### ISSUE TITLE
Session Handle not cleaned when removing Session

### ISSUE THREAD

**Issue by sqadasi** [open62541/open62541#3013]
## Description
Hello everyone!
I've got a problem when using Access Control.
The callback function at line:
https://github.com/open62541/open62541/blob/51ed5301ef25c22ddaa14842baa327eca992feba/src/server/ua_services_session.c#L479

allocates memory for "session->sessionHandle".
I would've expected, that the allocated memory will be freed when the session is removed in the function:
https://github.com/open62541/open62541/blob/51ed5301ef25c22ddaa14842baa327eca992feba/src/server/ua_session_manager.c#L31

using the callback "server->config.accessControl.closeSession". But that doesn't happen here.

Is the current behavior correct, and I must free that memory in my application on my own by calling "server->config.accessControl.closeSession"? or should the session handle be freed inside the "removeSession" function?

**Comment by jpfr** [comment]
This is an oversight. The callback should be called in removeSession.
Giving it a high priority and adding to the 1.0 milestone.
