### ISSUE TITLE
UA_Client_sendAsyncRequest returns GOOD even if the client is not connected

### ISSUE THREAD

**Issue by cabralfortiss** [open62541/open62541#3040]
Specifically in https://github.com/open62541/open62541/blob/777eb9339d3f01802f3bcc0396a7c7391cacdb43/src/client/ua_client.c#L529 the function is returning UA_STATUSCODE_GOOD when the client is not connected. I don't know if I'm not seeing something, but shouldn't this return an error to let the caller know that its message wasn't dispatched?

Also, there's a typo in the LOG info in the line before ("Cient" instead of "Client").

If the return value is wrong, I can make a PR to change it to return UA_STATUSCODE_BADSERVERNOTCONNECTED instead

**Comment by jpfr** [comment]
Thanks for providing the fix.
