### ISSUE TITLE
Connect to MX-AOPC UA Server

### ISSUE THREAD

**Issue by TheGringerEye** [open62541/open62541#3041]
how to connect to MX-AOPC UA Server(Moxa`s opc server for io logic) ? I am use qt5 and msvc 2017 compiler, open62541 in single-file release, more: https://pastebin.com/96h3eV2H

**Comment by jpfr** [comment]
The log output tells the following story:
The SecureChannel is unencrypted. But you still have to encrypt the password as it is transmitted.

It seems your client is not configured for encryption.
See the docs and examples on how to do that.

Please reopen if required.

**Comment by TheGringerEye** [comment]
But AOPC Server tuned on "none"
![image](https://user-images.githubusercontent.com/26498253/63668685-73264380-c7e0-11e9-812b-0d67c9a5af75.png)

**Comment by TheGringerEye** [comment]
I am dont undestend how to connect.
