### ISSUE TITLE
Nodeset2 compiler

### ISSUE THREAD

**Issue by Lukas1811** [open62541/open62541#3045]
It's not really an issue but I want to mention it somewhere where a lot of maybe interested people could read this. 

I created an custom nodeset with the [free opcua-modeler ](https://github.com/FreeOpcUa/opcua-modeler) and wanted to compile it with the nodeset compiler, I set it up to create everything (nodeids, namespace, types, handling, ...). Long story short, it doesn't work with the output of the modeler.
After researching a little bit I find out that the problem is that the modeler outputs in the nodeset2 format which only consists of one XML file, instead of the xml, bsd and csv combination the nodeset compiler needs.

I wrote [a little script](https://github.com/Lukas1811/OPC-UA-Nodeset2-compiler) to convert the nodeset2 format to the old format, it works for my case, it's possible that there are tons of bugs, that's why I don't create a pull request.

**Comment by Pro** [comment]
Thanks for the script and your contribution.

This is very related to #2587

Would you be interested in creating a PR which improves the nodeset compiler to not depend on these extra files (see referenced issue)?
