### ISSUE TITLE
Add a build status badge for Azure Pipelines 

### ISSUE THREAD

**Issue by escherstair** [open62541/open62541#3049]
I've just seen that some of the AppVeyor builds have been moved to Azure Pipelines.
Cool!

Can someone add a build status badge too?
It should be possible as described [here](https://www.azuredevopslabs.com/labs/vstsextend/github-azurepipelines/).

**Comment by Pro** [comment]
Thanks @escherstair for the hint.

Yes, I moved some builds to Azure Pipelines because AppVeyor was very very slow lately. It slowed down our development process. Azure is much faster.

I created a new PR to fix this.
