### ISSUE TITLE
UA_Array_copy fails trying to copy 24-length string

### ISSUE THREAD

**Issue by arama7** [open62541/open62541#3101]
## Description

I had an error when I wanted to add a node with a name of exactly 24 characters. 
The error happened copying UA_NodeId and UA_QualifiedName structures inside the function AddNode_raw.

    `/* Fill the node attributes */
    node->context = nodeContext;
    UA_StatusCode retval = UA_STATUSCODE_GOOD;
    retval |= UA_NodeId_copy(&item->requestedNewNodeId.nodeId, &node->nodeId);
    retval |= UA_QualifiedName_copy(&item->browseName, &node->browseName);
    retval |= UA_Node_setAttributes(node, item->nodeAttributes.content.decoded.data,
                                    item->nodeAttributes.content.decoded.type);
    if(retval != UA_STATUSCODE_GOOD) {
        UA_LOG_INFO_SESSION(server->config.logger, session,
                            "AddNodes: Node could not create a node "
                            "with error code %s", UA_StatusCode_name(retval));
        UA_Nodestore_delete(server, node);
        return retval;
    }`

Both copy functions execute UA_copy function. For the datatypes UA_NodeId and UA_QualifiedName, memSize has the value 24. This means that the function allocates 24 bytes of memory before copying actually happens.

    `UA_StatusCode
     UA_copy(const void *src, void *dst, const UA_DataType *type) {
          memset(dst, 0, type->memSize); /* init */
          UA_StatusCode retval = copy_noInit(src, dst, type);
          if(retval != UA_STATUSCODE_GOOD)
              UA_deleteMembers(dst, type);
          return retval;
      }`

As UA_NodeId and UA_QualifiedName contain string type members, UA_Array_copy is executed.

    `UA_StatusCode
     UA_Array_copy(const void *src, size_t size, void **dst, const UA_DataType *type) {
         if(size == 0) {
             if(src == NULL)
                 *dst = NULL;
             else
                 *dst= UA_EMPTY_ARRAY_SENTINEL;
             return UA_STATUSCODE_GOOD;
         }

         if(!type)
             return UA_STATUSCODE_BADINTERNALERROR;

         /* calloc, so we don't have to check retval in every iteration of copying */
         *dst = UA_calloc(size, type->memSize);
         if(!*dst)
             return UA_STATUSCODE_BADOUTOFMEMORY;

         if(type->pointerFree) {
             memcpy(*dst, src, type->memSize * size);
             return UA_STATUSCODE_GOOD;
         }

         uintptr_t ptrs = (uintptr_t)src;
         uintptr_t ptrd = (uintptr_t)*dst;
         UA_StatusCode retval = UA_STATUSCODE_GOOD;
         for(size_t i = 0; i < size; ++i) {
             retval |= UA_copy((void*)ptrs, (void*)ptrd, type);
             ptrs += type->memSize;
             ptrd += type->memSize;
         }
         if(retval != UA_STATUSCODE_GOOD) {
             UA_Array_delete(*dst, size, type);
             *dst = NULL;
         }
         return retval;
     }`

The array copy function allocates a block of memory again and initializes to 0 using calloc()
`    *dst = UA_calloc(size, type->memSize);`

I noticed that this **copy is not correct when** the src parameter **string has length 24**. 
The reason is that UA_copy() allocates 24 bytes for UA_NodeId and UA_QualifiedName, so the NULL character that sets the end of string is not copied and other random characters appear after concatenated in the dst.
This problem does not exist when the string length<24, because the 24 byte memory block was already set to 0 with memset() in UA_copy().

For example:
src = 123456789012345678901234
the result of copy is:
dst = 123456789012345678901234A

**Should't the size in calloc() be size+1 to include also NULL character after string?**
`    *dst = UA_calloc(size+1, type->memSize);`

## Checklist

Please provide the following information:

 - [X] open62541 Version (release number or git tag): v0.3.0
 - [ ] Other OPC UA SDKs used (client or server): 
 - [X] Operating system: Debian 9
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [X] Self-contained code example attached
 - [ ] Critical issue

**Comment by arama7** [comment]
You're right @jpfr , after the copy function I´m using some string.h functions as strcpy(), strlen().
These functions consider that strings are null terminating elements.

When my string has 24 characters, is not terminating with null as I explained in the issue. The reason is, that only 24 bytes of memory are allocated and initialized to zero. 

Consequently, the use of string.h functions is not correct after UA_copy(), so I should use the size field to identify the end of string.

**Comment by jpfr** [comment]
You're welcome. 😄
