### ISSUE TITLE
Authenticate Clients with username/password

### ISSUE THREAD

**Issue by Hexsc** [open62541/open62541#313]
Hi!

I have a little question to you.
Is it possible to authenticate clients with username/password at a server with the actual master branch?
At open62541.c I found:

...........
.Login_enableAnonymous = UA_TRUE,				// in my case UA_FALSE
.Login_enableUsernamePassword = UA_TRUE,
.Login_usernames = (char *[]){"user1","user2"},
.Login_passwords = (char *[]){"password","password1"},
...........

so it schould be possible to manage that, right?

But I found no place at the client, neither at the darkest corners of the client definition, where a username/password can be added.

Thanks for your answers in advance.
With best regards,
Hexsc

**Comment by Stasik0** [comment]
Hi,

it is only possible with external clients e.g. with UaExpert, not with our client, yet. Should not be that hard to add, though.

**Comment by Hexsc** [comment]
Ok, thank you very much!

**Comment by HolgerJeromin** [comment]
I would like to let this issue open till it is possible with our client.

**Comment by jpfr** [comment]
So we would have `UA_Client_connectAnonymous`, `UA_Client_connectUsername`, ...?

**Comment by HolgerJeromin** [comment]
Makes sense.

**Comment by Stasik0** [comment]
hey guys, what about to add some "authentication=UA_CLIENT_NONE" field to the client structure? In this case we can keep one function and not break existing code...

also..

currently the connect function selects the *first* endpoint with anonymous access.... this is probably not good aswell, what can we do, i propose to support "opc.tcp://host:port/endpoint" syntax to enforce the endpoint and add ```UA_Client_getEndpoints(UA_String, UA_Client, UA_String**)``` method returning an array of enpoint strings

**Comment by jpfr** [comment]
+1

**Comment by jpfr** [comment]
Can we tag this either 0.2 or 0.3?
Getting the endpoints is ready. Now we need to distinguish between them in the connect function.

**Comment by Stasik0** [comment]
+1 for 0.2, i suggest putting authentication into client structure? Can we elaborate an api?

**Comment by Stasik0** [comment]
Ping, so, what about the api? Should we leave the method signature unchanged and add the connection parameters to the client config struct?

**Comment by jpfr** [comment]
Implemented by @Stasik0 in #558.
So this is done.
