### ISSUE TITLE
server  information model - XML or not (eg C language defined)  ? 

### ISSUE THREAD

**Issue by sancelot** [open62541/open62541#3203]
## Description
Hi,
I am brand new to opc ua , in case of deploying an OPC UA server, it looks like many people are using XML file server information model.
This seems flexible when you provide an opc ua stack to some people that define and customize their own server .

However, in case of a machine builder you will provide an OPC UA server information model that you will be standalone to manage and provide it to all of your customers. 

So, the questions is :
From my viewpoint, there is no interest doing it in this case with an XML file, but instead being able doing it within the c server code. 
 Is it mandatory to use an XML file to define the information model server in this stack , or can it be defined all in the C language ?

**Comment by jpfr** [comment]
You don't need any XML files to build up the information model.
In our case, the XML Nodeset definitions are used to generate C-code that uses the respective API.
Have a look at the examples and tutorials.

Best of luck!
