### ISSUE TITLE
Feature Request: Thread-Safe Client

### ISSUE THREAD

**Issue by fengshaoxie** [open62541/open62541#3208]
UA_Client_Subscriptions_create and UA_Client_Subscriptions_deleteSingle function can suppost  asynchronous mode？

If my connection is one thread and my subscription is another thread, I will not be able to subscribe

**Comment by jpfr** [comment]
Your subscription is another thread?

Be sure not to mix up async and multi-threading.
The client lib is **not thread safe** at the moment.

That will happen eventually. But we don't have it now.

**Comment by fengshaoxie** [comment]
yes,I just try to multi-threading

**Comment by fengshaoxie** [comment]
It's like I'm trying to multithread and cause bugs.

![image](https://user-images.githubusercontent.com/37693004/67842890-fb54fc00-fb35-11e9-90d2-4b531cc34b50.png)

**Comment by fengshaoxie** [comment]
Sorry, I am not familiar with this frame. Could you tell me where to add the lock

**Comment by jpfr** [comment]
This is now solved for the last release families.
