### ISSUE TITLE
UA_Client_connect_username and UA_Client_connect question

### ISSUE THREAD

**Issue by fengshaoxie** [open62541/open62541#3244]
I first time use UA_Client_connect function connect to server,
And then second time use UA_Client_connect_username connect to server(not new a UA_Client and use the first time UA_Client point),
The username and password is lose efficacy ,connect failed and return 0x80200000

**Comment by fengshaoxie** [comment]
use UA_Client_connect_username function connect to Prosys OPC UA Simulation Server is Error and return to 0x80020000

**Comment by fredilarsen** [comment]
I get the same error, not being able to log in to the server. The server endpoint is set up with security None and user token security Basic128Rsa15.

Created a similar test client program with Eclipse Milo (Java based), and it connects immediately.

What am I missing? Is the feature missing or do I have to do something special?

**Comment by jpfr** [comment]
Verify that you have the necessary encryption support.

Reopen if not solved.
