### ISSUE TITLE
subscriber receive no messages

### ISSUE THREAD

**Issue by mcHinrichs** [open62541/open62541#3247]
## Description
I try to receive messages from the _tutorial_pubsub_publisher.c_ multicast on a different pc, with the _tutorial_pubsub_subscriber.c_. On the same pc it works fine.

The wireshark dump shows that the UDP packets are received (subscriber pc):

![UDP Multicast dump](https://user-images.githubusercontent.com/56306878/68222377-3601dd00-ffeb-11e9-8b30-3fb900a9239e.PNG)

But the subscriber doesn't show _message received:_ message:

![UDP Multicast output](https://user-images.githubusercontent.com/56306878/68222768-d0622080-ffeb-11e9-9871-40b1be482052.PNG)

## Background
publisher pc:     192.168.0.1
subscriber pc: 192.168.0.4

Used CMake options:

```bash
cmake -UA_ENABLE_PUBSUB=ON
```

## Checklist

Please provide the following information:

 - [x] open62541 commit: 1748f82
 - [x] Other OPC UA SDKs used (client or server): UaExpert
 - [x] Operating system: ubuntu 19.04
 - [x] Logs (UA_LOGLEVEL = 100) attached
 - [x] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by mcHinrichs** [comment]
I found out that the subscriber on the ubuntu vm doesn't create a PublishSubscribe object:
![subscriber pc](https://user-images.githubusercontent.com/56306878/68398180-9ff9be00-0174-11ea-8b53-d4e5c413a3ac.PNG)
(subscriber on pc)

![subscriber vm](https://user-images.githubusercontent.com/56306878/68398181-9ff9be00-0174-11ea-9218-0ed05a929c10.PNG)
(subscriber on vm)

It's the same ubuntu on both machines. Do I have to configure something so PublishSubscribe is created or is it because of the vm?

**Comment by mcHinrichs** [comment]
The problem was JSON_ENCODING was enabled. If I disable JSON_ENCODING in ccmake the PublishSubscribe object reappears.

**Comment by prrw** [comment]
@mcHinrichs How are you able to build using CMake having UA_ENABLE_JSON_ENCODING=ON ? In my case, if i make it on, there are errors while building.
