### ISSUE TITLE
undefined reference to `mbedtls_sha256_ret'

### ISSUE THREAD

**Issue by ripkop** [open62541/open62541#3274]
## Description
I install libopen62541 with make and make install with no error, but when I want to compile my ua_server source code with gcc commad below
```bash
gcc -std=c99 -o server server.c  -lopen62541
```
it shows this error

`/usr/bin/ld: /usr/local/lib/libopen62541.so: undefined reference to mbedtls_sha256_ret
/usr/bin/ld: /usr/local/lib/libopen62541.so: undefined reference to mbedtls_sha1_ret
`
## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUA_NAMESPACE_ZERO=FULL -DUA_ENABLE_ENCRYPTION=ON ..
```

## Checklist

 - [x] open62541 Version (release number or git tag):master(latest)
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: debian jessie
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
You have security enabled.
You need to add mbedtls as a library for the linker.

Try adding `-lmbedtls` or similar. That depends on your Linux distribution.
