### ISSUE TITLE
how to reflect node value in server by client

### ISSUE THREAD

**Issue by Ronak667** [open62541/open62541#3278]
## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [* ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [*] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
See https://github.com/open62541/open62541/blob/master/examples/client.c
