### ISSUE TITLE
how browse object folder?

### ISSUE THREAD

**Issue by Ronak667** [open62541/open62541#3279]
I am Implement OPC-UA client  successfully communication to  the server.
but difficulties  found  when i Browse  the  server object is successfully. but  in how can i browse a object folder ??

![image](https://user-images.githubusercontent.com/55443296/68925105-53cc0080-07a8-11ea-99bf-727ec13a9f81.png)

## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [* ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
See https://github.com/open62541/open62541/blob/master/examples/client.c
