### ISSUE TITLE
What's ApplicationURI?

### ISSUE THREAD

**Issue by Zvicii** [open62541/open62541#3283]
I wrote a client and a server following the examples under "encryption", and generate certificate using create_self-signed.py, but when i connect my client to my server, the server log says "the client's ApplicationURI did not match the certificate". 
So I manually set "ClientDescription.applicationURI" to "urn:open62541.server.application", then it worked. But i still dont know what's "applicationURI", what does it mean?

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by jpfr** [comment]
The ApplicationUri is part of the self-description.
Basically just an identifier.

Since a few days ago, you can set the ApplicationUri as an argument to the certificate generation script.
