### ISSUE TITLE
Open62541 creating .c/.h files for STM32 with freeRTOS + lwIP

### ISSUE THREAD

**Issue by Student721** [open62541/open62541#3293]
Hey there,
I was trying to Install an OPC UA Server on my STM32 project with working freeRTOS + lwIP. So i downloaded/cloned the file from https://github.com/open62541/open62541 with Git. Then I followed the instruction on https://open62541.org/doc/current/building.html. Installed cmake and visual studio for windows.
Now I have started CMake GUI and enable AMALGAMATION and switched freertosLWIP on UA_ARCHITECTURE. After generated the data, I open the open62541.sln File with Visual Studio. Right click on ALL_BUILD and build. The upcoming open62541.c /.h files I copied to my STM folder. 

After that I have continued to follow the instructions and changed lwipopts.h. and FreeRTOSConfig.h. 
Also put the task code in my main. After build that project in STM32CubeIDE there are over 200 error in open62541.c and .h. 

What did I wrong? Any held?
Thanks to all

**Comment by jpfr** [comment]
Can you post of the error messages?

**Comment by Student721** [comment]
![Errors_Open62541_#3239](https://user-images.githubusercontent.com/58040137/69408268-c6882f00-0d06-11ea-9eb7-da1e95800bdd.jpg)

**Comment by Student721** [comment]
![Errors_Open62541_#3239](https://user-images.githubusercontent.com/58040137/69413454-22f04c00-0d11-11ea-8017-7b31e50b4859.jpg)

**Comment by Student721** [comment]
![Errors_Open62541_#3239](https://user-images.githubusercontent.com/58040137/69414757-a27f1a80-0d13-11ea-8721-617016f1d553.jpg)

**Comment by zxiang1996** [comment]
Can you tell me how many ROM and ram are needed for the port
