### ISSUE TITLE
Couldn't get all child nodes when browsing

### ISSUE THREAD

**Issue by Zvicii** [open62541/open62541#3322]
I try to browse a siemens server.
I managed to get noded under UA_NS0ID_ROOTFOLDER using UA_Client_Service_browse.
But there is a folder that I couldn't get its children.
the referenceSize is 0;

But UA_EXPERT can get children under it.
and UA_EXPERT can't get the folder's attributes, they are all red and the values are all'801f0000'

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Zvicii** [comment]
![9E916463-267A-483B-9445-8ECF9D1DAB72](https://user-images.githubusercontent.com/36950948/70903618-348bf180-203a-11ea-9e99-4292543c90b7.jpeg)

**Comment by RantiE** [comment]
UA_STATUSCODE_BADUSERACCESSDENIED 0x801F0000
/* User does not have permission to perform the requested operation. */

Have you got permission to browse the server?

**Comment by Zvicii** [comment]
> UA_STATUSCODE_BADUSERACCESSDENIED 0x801F0000
> /* User does not have permission to perform the requested operation. */
> 
> Have you got permission to browse the server?

im not sure，but if UA_EXPERT can browse the nodes.under it, why cant I?
the settings are the same.

**Comment by Zvicii** [comment]
also when i user ua_client_service_browse，the response header has status UA_STATUS_GOOD,if i dont have permission, the header should be different right? but stiil it returns with no nodes

**Comment by jpfr** [comment]
How do you browse?
Do you constrain the reference types used for browsing?

Also, reading attributes is done with a different service.
`Read`, not `Browse`.

**Comment by Zvicii** [comment]
I haven't set any constraint，other nodes like "Types"、"Views"、"Server" work just fine. But this node I want to browse doesn't return any child, the response_header means at least I have permission to browse right? even if I dont have permission to read;

**Comment by Zvicii** [comment]
![5D4C7E11-2F02-4FBC-A72B-0E6A5EF42F55](https://user-images.githubusercontent.com/36950948/71046213-a0717580-2172-11ea-942a-20de5534efb3.png)

**Comment by Zvicii** [comment]
![A6B267A3-A552-46B7-B354-C5FBB84A2101](https://user-images.githubusercontent.com/36950948/71046373-0d850b00-2173-11ea-864a-83a314ffa16b.png)

**Comment by jpfr** [comment]
The BrowseDescription is incomplete. You should set `referenceTypeId` and possibly `includeSubtypes`.

https://open62541.org/doc/current/types_generated.html#browsedescription

```c
typedef struct {
    UA_NodeId nodeId;
    UA_BrowseDirection browseDirection;
    UA_NodeId referenceTypeId;
    UA_Boolean includeSubtypes;
    UA_UInt32 nodeClassMask;
    UA_UInt32 resultMask;
} UA_BrowseDescription;
```

**Comment by Zvicii** [comment]
> The BrowseDescription is incomplete. You should set `referenceTypeId` and possibly `includeSubtypes`.
> 
> https://open62541.org/doc/current/types_generated.html#browsedescription
> 
> ```c
> typedef struct {
>     UA_NodeId nodeId;
>     UA_BrowseDirection browseDirection;
>     UA_NodeId referenceTypeId;
>     UA_Boolean includeSubtypes;
>     UA_UInt32 nodeClassMask;
>     UA_UInt32 resultMask;
> } UA_BrowseDescription;
> ```

thank you for reply so quickly；
I'll try and get back to you.

**Comment by Zvicii** [comment]
> The BrowseDescription is incomplete. You should set `referenceTypeId` and possibly `includeSubtypes`.
> 
> https://open62541.org/doc/current/types_generated.html#browsedescription
> 
> ```c
> typedef struct {
>     UA_NodeId nodeId;
>     UA_BrowseDirection browseDirection;
>     UA_NodeId referenceTypeId;
>     UA_Boolean includeSubtypes;
>     UA_UInt32 nodeClassMask;
>     UA_UInt32 resultMask;
> } UA_BrowseDescription;
> ```

what referenceTypeId should I set to get everything？
UA_NS0ID_REFERENCES?

**Comment by Zvicii** [comment]
I set [includeSubtypes] to true and [refrenceTypeId] to UA_NODEID_NUMERIC(0, UA_NS0ID_REFERENCES). Still not working;
I appears that I can't get nodes which are obejcttype added manually;

**Comment by Zvicii** [comment]
![9DAD4D52-8BCB-4F29-B9D8-DB86BDBAAF8A](https://user-images.githubusercontent.com/36950948/71078094-aa6f9480-21c3-11ea-882c-1994fdaf08f8.png)
![573E27DC-AEC7-425E-B946-9CD36BE5848A](https://user-images.githubusercontent.com/36950948/71078106-afccdf00-21c3-11ea-98a2-ca885937e1ee.png)
![65DB5D96-D718-4F14-844A-A058E4076BB6](https://user-images.githubusercontent.com/36950948/71078112-b2c7cf80-21c3-11ea-9401-70e8b66ce6ff.png)
![0326AA84-D916-4AED-9034-F7471B06EBC6](https://user-images.githubusercontent.com/36950948/71078272-fe7a7900-21c3-11ea-81c0-a14562f8aea1.png)


DeviceType1 DeviceType2 DeviceType3
I cant get these 3 nodes

**Comment by Zvicii** [comment]
![273BD0F9-9BA9-4DB1-ACB5-2AC807FB947A](https://user-images.githubusercontent.com/36950948/71084112-86b24b80-21cf-11ea-9535-919210105ac5.png)

still not working

**Comment by jpfr** [comment]
Difficult to say from here.

We have a unit test for the client browsing.
https://github.com/open62541/open62541/blob/master/tests/client/check_client_highlevel.c#L251

It is definitely working threre.
The status code UA_STATUSCODE_BADUSERACCESSDENIED hints at another problem.
Did you see my response from #3319?

> Try to initialize the variable attributes as

> UA_VariableAttributes attr = UA_VariableAttributes_default;

> This sets some sane defaults. For example read permissions.

**Comment by Zvicii** [comment]
I made a mistake;


> The BrowseDescription is incomplete. You should set `referenceTypeId` and possibly `includeSubtypes`.
> 
> https://open62541.org/doc/current/types_generated.html#browsedescription
> 
> ```c
> typedef struct {
>     UA_NodeId nodeId;
>     UA_BrowseDirection browseDirection;
>     UA_NodeId referenceTypeId;
>     UA_Boolean includeSubtypes;
>     UA_UInt32 nodeClassMask;
>     UA_UInt32 resultMask;
> } UA_BrowseDescription;
> ```

I made a mistake.
this works!
you guys are the best, love you!
