### ISSUE TITLE
Assert failed when triggering (too) many events or clients receive events too slow

### ISSUE THREAD

**Issue by ccvca** [open62541/open62541#3330]
## Description

When there are too many events in the queue to the client this assertation failed:
https://github.com/open62541/open62541/blob/63771722737a723f2f4352bdf03ae0c640a8395d/src/server/ua_subscription_monitoreditem.c#L275

Example numbers from my project:
mon->eventOverflows: 4
mon->queueSize: 6
=> 4 _(mon->eventOverflows)_ <= 6 _(mon->queueSize)_ - 4 _(mon->eventOverflows)_ + 1
=> 4 <= 3 (FAIL)

I triggered this consistently in my application, by producing 2 events every second after connecting by UaExpert and subscribe the Server object. This freezes UaExpert for several seconds (looks like creating the subscriptions in a blocking manner, so no publish-Messages are send) and then my application crashes.

## Background Information / Reproduction Steps
I modified the [tutorial_server_events](https://github.com/open62541/open62541/files/3987150/tutorial_server_events.zip) to create 6 (5 works fine) events every 2 seconds. Just connection by UaExpert crashes the application. with this assertation.

<details>
<summary>Embedded source code of modified event tutorial to trigger this assert, Click to reveal</summary>
    
    /* This work is licensed under a Creative Commons CCZero 1.0 Universal License.
     * See http://creativecommons.org/publicdomain/zero/1.0/ for more information. */

    #include <open62541/plugin/log_stdout.h>
    #include <open62541/server.h>
    #include <open62541/server_config_default.h>

    #include <signal.h>
    #include <stdlib.h>

    /**
     * Generating events
     * -----------------
     * To make sense of the many things going on in a server, monitoring items can be useful. Though in many cases, data
     * change does not convey enough information to be the optimal solution. Events can be generated at any time,
     * hold a lot of information and can be filtered so the client only receives the specific attributes he is interested in.
     *
     * Emitting events by calling methods
     * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     * The following example will be based on the server method tutorial. We will be
     * creating a method node which generates an event from the server node.
     *
     * The event we want to generate should be very simple. Since the `BaseEventType` is abstract,
     * we will have to create our own event type. `EventTypes` are saved internally as `ObjectTypes`,
     * so add the type as you would a new `ObjectType`. */

    static UA_NodeId eventType;

    static UA_StatusCode
    addNewEventType(UA_Server *server) {
    	UA_ObjectTypeAttributes attr = UA_ObjectTypeAttributes_default;
    	attr.displayName = UA_LOCALIZEDTEXT("en-US", "SimpleEventType");
    	attr.description = UA_LOCALIZEDTEXT("en-US", "The simple event type we created");
    	return UA_Server_addObjectTypeNode(server, UA_NODEID_NULL,
    									   UA_NODEID_NUMERIC(0, UA_NS0ID_BASEEVENTTYPE),
    									   UA_NODEID_NUMERIC(0, UA_NS0ID_HASSUBTYPE),
    									   UA_QUALIFIEDNAME(0, "SimpleEventType"),
    									   attr, NULL, &eventType);
    }

    /**
     * Setting up an event
     * ^^^^^^^^^^^^^^^^^^^
     * In order to set up the event, we can first use ``UA_Server_createEvent`` to give us a node representation of the event.
     * All we need for this is our `EventType`. Once we have our event node, which is saved internally as an `ObjectNode`,
     * we can define the attributes the event has the same way we would define the attributes of an object node. It is not
     * necessary to define the attributes `EventId`, `ReceiveTime`, `SourceNode` or `EventType` since these are set
     * automatically by the server. In this example, we will be setting the fields 'Message' and 'Severity' in addition
     * to `Time` which is needed to make the example UaExpert compliant.
     */
    static UA_StatusCode
    setUpEvent(UA_Server *server, UA_NodeId *outId) {
    	UA_StatusCode retval = UA_Server_createEvent(server, eventType, outId);
    	if (retval != UA_STATUSCODE_GOOD) {
    		UA_LOG_WARNING(UA_Log_Stdout, UA_LOGCATEGORY_SERVER,
    					   "createEvent failed. StatusCode %s", UA_StatusCode_name(retval));
    		return retval;
    	}

    	/* Set the Event Attributes */
    	/* Setting the Time is required or else the event will not show up in UAExpert! */
    	UA_DateTime eventTime = UA_DateTime_now();
    	UA_Server_writeObjectProperty_scalar(server, *outId, UA_QUALIFIEDNAME(0, "Time"),
    										 &eventTime, &UA_TYPES[UA_TYPES_DATETIME]);

    	UA_UInt16 eventSeverity = 100;
    	UA_Server_writeObjectProperty_scalar(server, *outId, UA_QUALIFIEDNAME(0, "Severity"),
    										 &eventSeverity, &UA_TYPES[UA_TYPES_UINT16]);

    	UA_LocalizedText eventMessage = UA_LOCALIZEDTEXT("en-US", "An event has been generated.");
    	UA_Server_writeObjectProperty_scalar(server, *outId, UA_QUALIFIEDNAME(0, "Message"),
    										 &eventMessage, &UA_TYPES[UA_TYPES_LOCALIZEDTEXT]);

    	UA_String eventSourceName = UA_STRING("Server");
    	UA_Server_writeObjectProperty_scalar(server, *outId, UA_QUALIFIEDNAME(0, "SourceName"),
    										 &eventSourceName, &UA_TYPES[UA_TYPES_STRING]);

    	return UA_STATUSCODE_GOOD;
    }

    /**
     * Triggering an event
     * ^^^^^^^^^^^^^^^^^^^
     * First a node representing an event is generated using ``setUpEvent``. Once our event is good to go, we specify
     * a node which emits the event - in this case the server node. We can use ``UA_Server_triggerEvent`` to trigger our
     * event onto said node. Passing ``NULL`` as the second-last argument means we will not receive the `EventId`.
     * The last boolean argument states whether the node should be deleted. */
    static UA_StatusCode
    generateEventMethodCallback(UA_Server *server,
    						 const UA_NodeId *sessionId, void *sessionHandle,
    						 const UA_NodeId *methodId, void *methodContext,
    						 const UA_NodeId *objectId, void *objectContext,
    						 size_t inputSize, const UA_Variant *input,
    						 size_t outputSize, UA_Variant *output) {

    	UA_LOG_INFO(UA_Log_Stdout, UA_LOGCATEGORY_USERLAND, "Creating event");

    	/* set up event */
    	UA_NodeId eventNodeId;
    	UA_StatusCode retval = setUpEvent(server, &eventNodeId);
    	if(retval != UA_STATUSCODE_GOOD) {
    		UA_LOG_WARNING(UA_Log_Stdout, UA_LOGCATEGORY_USERLAND,
    					   "Creating event failed. StatusCode %s", UA_StatusCode_name(retval));
    		return retval;
    	}

    	retval = UA_Server_triggerEvent(server, eventNodeId,
    									UA_NODEID_NUMERIC(0, UA_NS0ID_SERVER),
    									NULL, UA_TRUE);
    	if(retval != UA_STATUSCODE_GOOD)
    		UA_LOG_WARNING(UA_Log_Stdout, UA_LOGCATEGORY_USERLAND, 
    					   "Triggering event failed. StatusCode %s", UA_StatusCode_name(retval));

    	return retval;
    }

    /**
     * Now, all that is left to do is to create a method node which uses our callback. We do not
     * require any input and as output we will be using the `EventId` we receive from ``triggerEvent``. The `EventId` is
     * generated by the server internally and is a random unique ID which identifies that specific event.
     *
     * This method node will be added to a basic server setup.
     */

    static void
    addGenerateEventMethod(UA_Server *server) {
    	UA_MethodAttributes generateAttr = UA_MethodAttributes_default;
    	generateAttr.description = UA_LOCALIZEDTEXT("en-US","Generate an event.");
    	generateAttr.displayName = UA_LOCALIZEDTEXT("en-US","Generate Event");
    	generateAttr.executable = true;
    	generateAttr.userExecutable = true;
    	UA_Server_addMethodNode(server, UA_NODEID_NUMERIC(1, 62541),
    							UA_NODEID_NUMERIC(0, UA_NS0ID_OBJECTSFOLDER),
    							UA_NODEID_NUMERIC(0, UA_NS0ID_HASORDEREDCOMPONENT),
    							UA_QUALIFIEDNAME(1, "Generate Event"),
    							generateAttr, &generateEventMethodCallback,
    							0, NULL, 0, NULL, NULL, NULL);
    }

    /** It follows the main server code, making use of the above definitions. */

    static volatile UA_Boolean running = true;
    static void stopHandler(int sig) {
    	running = false;
    }

    static void
    testCallback(UA_Server *server, void *data)
    {
    	UA_LOG_INFO(UA_Log_Stdout, UA_LOGCATEGORY_USERLAND, "Creating event");

    	for(int i = 0; i < 6; ++i)
    	{
    		/* set up event */
    		UA_NodeId eventNodeId;
    		UA_StatusCode retval = setUpEvent(server, &eventNodeId);
    		if(retval != UA_STATUSCODE_GOOD) {
    			UA_LOG_WARNING(UA_Log_Stdout, UA_LOGCATEGORY_USERLAND,
    						   "Creating event failed. StatusCode %s", UA_StatusCode_name(retval));
    			return;
    		}

    		retval = UA_Server_triggerEvent(server, eventNodeId,
    										UA_NODEID_NUMERIC(0, UA_NS0ID_SERVER),
    										NULL, UA_TRUE);
    		if(retval != UA_STATUSCODE_GOOD)
    			UA_LOG_WARNING(UA_Log_Stdout, UA_LOGCATEGORY_USERLAND, 
    						   "Triggering event failed. StatusCode %s", UA_StatusCode_name(retval));
    	}
    }

    int main (void) {
    	/* default server values */
    	signal(SIGINT, stopHandler);
    	signal(SIGTERM, stopHandler);

    	UA_Server *server = UA_Server_new();
    	UA_ServerConfig_setDefault(UA_Server_getConfig(server));

    	addNewEventType(server);
    	addGenerateEventMethod(server);
    	UA_Server_addRepeatedCallback(server, testCallback, NULL, 2000, NULL); /* call every 2 sec */
    	UA_StatusCode retval = UA_Server_run(server, &running);

    	UA_Server_delete(server);
    	return retval == UA_STATUSCODE_GOOD ? EXIT_SUCCESS : EXIT_FAILURE;
    }

</details>

<details>
<summary>Log output</summary>
    
    [2019-12-20 08:16:29.759 (UTC+0100)] warn/server        Username/Password configured, but no encrypting SecurityPolicy. This can leak credentials on the network.
    [2019-12-20 08:16:29.759 (UTC+0100)] warn/userland      AcceptAll Certificate Verification. Any remote certificate will be accepted.
    [2019-12-20 08:16:29.774 (UTC+0100)] info/network       TCP network layer listening on opc.tcp://XXXXXXXXXX:4840/
    [2019-12-20 08:16:31.776 (UTC+0100)] info/userland      Creating event
    [2019-12-20 08:16:32.308 (UTC+0100)] info/network       Connection 300 | New connection over TCP from 127.0.0.1
    [2019-12-20 08:16:32.308 (UTC+0100)] info/channel       Creating a new SecureChannel
    [2019-12-20 08:16:32.308 (UTC+0100)] warn/securitypolicy        Security policy None is used to create SecureChannel. Accepting all certificates
    [2019-12-20 08:16:32.308 (UTC+0100)] info/channel       Connection 300 | SecureChannel 1 | Opened SecureChannel
    [2019-12-20 08:16:32.308 (UTC+0100)] info/session       Try to use Session with token ns=1;g=e9fc7ded-594d-506e-da0d-405495499499 but is not found
    [2019-12-20 08:16:32.323 (UTC+0100)] info/channel       Connection 300 | SecureChannel 1 | Session bc7e14ad-c7f0-aaa9-5295-39e3765715e1 created
    [2019-12-20 08:16:32.323 (UTC+0100)] info/session       Connection 300 | SecureChannel 1 | Session ns=1;g=bc7e14ad-c7f0-aaa9-5295-39e3765715e1 | ActivateSession: Session activated
    [2019-12-20 08:16:32.361 (UTC+0100)] info/session       Connection 300 | SecureChannel 1 | Session ns=1;g=bc7e14ad-c7f0-aaa9-5295-39e3765715e1 | Subscription 1 | Created the Subscription with a publishing interval of 100.00 ms
    [2019-12-20 08:16:32.361 (UTC+0100)] info/session       Connection 300 | SecureChannel 1 | Session ns=1;g=bc7e14ad-c7f0-aaa9-5295-39e3765715e1 | Subscription 1 | MonitoredItem 1 | Created the MonitoredItem
    [2019-12-20 08:16:33.778 (UTC+0100)] info/userland      Creating event
    Assertion failed!
    
    Program: D:\Programmieren\Cpp\Open62541_Tests\cmake-build-debug\open62541\bin\examples\tutorial_server_events.exe
    File: D:\Programmieren\Cpp\Open62541_Tests\open62541\src\server\ua_subscription_monitoreditem.c, Line 275
    
    Expression: mon->eventOverflows <= mon->queueSize - mon->eventOverflows + 1
</details>

By investigating this a little bit further, I noticed an inconsistancy in the code, which might cause this:

https://github.com/open62541/open62541/blob/63771722737a723f2f4352bdf03ae0c640a8395d/src/server/ua_subscription.h#L195-L197

https://github.com/open62541/open62541/blob/63771722737a723f2f4352bdf03ae0c640a8395d/src/server/ua_subscription_monitoreditem.c#L275

The comment assume that eventOverflows can be up to 2x queueSize while the assertation assumes that queueSize is two times larger than eventOverflows. 

Used CMake options:
BUILD_SHARED_LIBS:BOOL=OFF
CLANG_FORMAT_EXE:FILEPATH=CLANG_FORMAT_EXE-NOTFOUND
CMAKE_BUILD_TYPE:STRING=Debug
CMAKE_GNUtoMS:BOOL=OFF
CMAKE_INSTALL_PREFIX:PATH=D:/Programmieren/Cpp/Open62541_Tests/install-debug
UA_ARCHITECTURE:STRING=win32
UA_BUILD_EXAMPLES:BOOL=ON
UA_BUILD_TOOLS:BOOL=OFF
UA_BUILD_UNIT_TESTS:BOOL=OFF
UA_ENABLE_AMALGAMATION:BOOL=OFF
UA_ENABLE_DA:BOOL=ON
UA_ENABLE_DISCOVERY:BOOL=ON
UA_ENABLE_DISCOVERY_MULTICAST:BOOL=OFF
UA_ENABLE_ENCRYPTION:BOOL=OFF
UA_ENABLE_HISTORIZING:BOOL=OFF
UA_ENABLE_METHODCALLS:BOOL=ON
UA_ENABLE_MICRO_EMB_DEV_PROFILE:BOOL=OFF
UA_ENABLE_NODEMANAGEMENT:BOOL=ON
UA_ENABLE_SUBSCRIPTIONS:BOOL=ON
UA_ENABLE_SUBSCRIPTIONS_ALARMS_CONDITIONS:BOOL=ON
UA_ENABLE_SUBSCRIPTIONS_EVENTS:BOOL=ON
UA_ENABLE_WEBSOCKET_SERVER:BOOL=OFF
UA_LOGLEVEL:STRING=300
UA_MULTITHREADING:STRING=0
UA_NAMESPACE_ZERO:STRING=FULL

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): master / 63771722737a723f2f4352bdf03ae0c640a8395d
 - [x] Other OPC UA SDKs used (client or server): UaExpert 1.5.0
 - [x] Operating system: Win 10
 - [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached (added in issue)
 - [ ] Wireshark network dump attached
 - [x] Self-contained code example attached
 - [x] Critical issue: Might break Servers, when (bad) clients do not send enought publish-messages to read events fast enought

**Comment by Pro** [comment]
We (myself and @aDogCalledSpot) also ran into the same issue a few days ago.
@aDogCalledSpot is already working on a fix, it will land soon.

The issue only arises, if DiscardOldest is set to false and the client doesn't query the events fast enough. In that case, the events pile up in the queue and as soon as the queue is full, the server is supposed to add overflow events.

If DiscardOldest is true, then the OverflowEvent is just added at the beginning of the queue and new overflow events are discarded, as long as there is already an overflow event at that place.

If DiscardOldest is false, the overflow event is added at the end of the queue. And here is currently a bug which adds multiple OverflowEvents after each other without an event in between. That is causing the assert.

**Comment by jpfr** [comment]
Very cool @pro
