### ISSUE TITLE
Is there a way to set severity of log not via CMAKE build option ?

### ISSUE THREAD

**Issue by chuongvhn** [open62541/open62541#3334]
## Description
it is possible to set severity of log by adding CMAKE build option UA_LOGLEVEL=\<value\> ([see this](https://github.com/open62541/open62541/issues/3333#issue-542246538) ) .  
Is there any other ways to have the same but by programing ?  
eg:  
`UA_SetSeverity(server.config->logger, SEVERITY_VALUE);`

It is quite convenience in sense of my application can have a parameter to select which kind of information I want to see for each run.

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 0.1
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
The logging plugin is just an example.
You can create an extended fork of that with facilities for runtime configuration.
