### ISSUE TITLE
PubSub Problem: Error to build PubSub with make command

### ISSUE THREAD

**Issue by BreemTUKL** [open62541/open62541#3350]
Hello,

I am new here and am currently completing my thesis on time sensitive networking with open62541.
I am currently having problems with the build PubSub using the make command (see screenshot).

can someone please help me?
Thanks in advance

Greetings Breem

Background information:
Operating system: Ubuntu 19.10 - 64-bit
- BUILD_SHARED_LIBS OFF
- UA_BUILD_EXAMPLES ON
- UA_ENABLE_AMALGAMATION OFF
- UA_NAMESPACE_ZERO FULL
- UA_ENABLE_PUBSUB ON
- UA_ENABLE_PUBSUB_ETH_UADP ON
Steps:
# enable additional features
sudo apt-get install cmake-curses-gui # for the ccmake graphical interface
sudo apt-get install libmbedtls-dev # for encryption support
sudo apt-get install check libsubunit-dev # for unit tests
sudo apt-get install python-sphinx graphviz # for documentation generation
sudo apt-get install python-sphinx-rtd-theme # documentation style

cd open62541
mkdir build
cd build
cmake ..
ccmake ..
make

## Checklist

Please provide the following information:

 - [ x] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

[open62541_cmake ...pdf](https://github.com/open62541/open62541/files/4040378/open62541_cmake.pdf)
[open62541_make.pdf](https://github.com/open62541/open62541/files/4040393/open62541_make.pdf)

**Comment by ZekeLandon** [comment]
I followed your steps but I am **not able to reproduce** the error as shown in attachment.
Build is success for me. Can you confirm if you are using the [latest commit](https://github.com/open62541/open62541/commit/d02fc4f5a4b60bb30a3c9394643abdd93b1fd59c) from master branch?

**Comment by BreemTUKL** [comment]
Hello ZekeLandon,

Thank you very much for your answer. I changed the src / server / ua_services_nodemanagement.c file as in the commit, but unfortunately the error still exists.
The error is in the file ua_pubsub_udp.c line 84 and line 104.
best regards
Breem

![2020-01-10_13-17](https://user-images.githubusercontent.com/59475602/72152570-b0fcc080-33ab-11ea-958a-4d840bd9b8c1.png)
![screenshot from ua_services_nodemanagement c](https://user-images.githubusercontent.com/59475602/72152643-e73a4000-33ab-11ea-9d0e-c042afa88d0d.png)

**Comment by ZekeLandon** [comment]
@BreemTUKL, would you believe if I say this? I am stuck with different error in another machine.
Weirdo! By the way, what is the version of cmake and make used in your system?
Something related to compiler, I suspect. Post the results here and give a try in another machine.

**Version details in my PC:**
- CMake --> v3.5.1
- make   --> v4.1

![compilerIssues_WerrorCodesGenerated](https://user-images.githubusercontent.com/59595721/72170247-8a17ac00-33f6-11ea-8351-111be9058105.PNG)


Regards,
Zeke

**Comment by BreemTUKL** [comment]
Hello @ZekeLandon,

Thank you for your reply.
So the problem was solved as follows, as you recommended to me.
I deleted the open62541 folder and created a new one, then made all the settings again and it worked :-)
But do you always have to delete the folders and install new ones if there is a problem? Is there no debug or anything to discover the errors?

thanks in advance for your help.
best regards
Breem

![image](https://user-images.githubusercontent.com/59475602/72207599-ef24dd80-349a-11ea-9902-e1a7c6eb48c5.png)

ccmake ..

![image](https://user-images.githubusercontent.com/59475602/72207713-da951500-349b-11ea-9153-81762f3ab6fc.png)


![image](https://user-images.githubusercontent.com/59475602/72207608-05cb3480-349b-11ea-955b-4ed69ee43bc4.png)

![image](https://user-images.githubusercontent.com/59475602/72207616-209da900-349b-11ea-8ced-1fef0f4fe537.png)

![image](https://user-images.githubusercontent.com/59475602/72207625-3c08b400-349b-11ea-99e5-1af364a5b9b6.png)

![image](https://user-images.githubusercontent.com/59475602/72207662-6fe3d980-349b-11ea-9cde-e3b9c1e7635b.png)

![image](https://user-images.githubusercontent.com/59475602/72207677-8ee26b80-349b-11ea-9ed4-1299b0fd2add.png)



![image](https://user-images.githubusercontent.com/59475602/72207948-930f8880-349d-11ea-8029-014f6b65767a.png)

![image](https://user-images.githubusercontent.com/59475602/72207958-a589c200-349d-11ea-942d-c1b0ee5805ea.png)

![image](https://user-images.githubusercontent.com/59475602/72207965-b76b6500-349d-11ea-9b16-81dce85b5b30.png)

![image](https://user-images.githubusercontent.com/59475602/72207974-ce11bc00-349d-11ea-9d00-93aa0f7f24ec.png)

**Comment by ZekeLandon** [comment]
It's good that you're able to resolve the issue. I guess you need delete everything and clone again.
You could just delete your build folder and start again. That should be fine.

Cheers,
Zeke

**Comment by BreemTUKL** [comment]
ok @ZekeLandon  thanks again for your help.

best regards
Breem
