### ISSUE TITLE
can't make project 

### ISSUE THREAD

**Issue by mojaxx** [open62541/open62541#3360]
hi
i am starting to use open62541 
i make the steps in issue #2567 but when i use make command (step 7 on issue) the progress stick at 88%
i try it several times 
please help me 

Sorry for my english.

thanks

**Comment by Pro** [comment]
Try to use `-DCMAKE_BUILD_TYPE=Debug` which is building faster.

Release builds can take a few minutes with full namespace zero.

Please also read this:
https://open62541.org/doc/current/building.html

**Comment by mojaxx** [comment]
hi again 

thanks for that but i try and it did not progress more than 88% and i wait one hour 

i don't know what to do 

thanks
![1](https://user-images.githubusercontent.com/59830709/72338689-41a00d00-36da-11ea-9285-6b362a084826.jpg)

**Comment by mojaxx** [comment]
hi  again
thanks very much for your help
sorry but i have one more problem
at the end when i want to start the server it gives an error as shown in blew figure
i appreciate if you help me 
thanks a lot
![1](https://user-images.githubusercontent.com/59830709/72339694-03a3e880-36dc-11ea-824a-7df4a9784a9b.jpg)

**Comment by mojaxx** [comment]
Hi
Thanks very much
