### ISSUE TITLE
Cannot Compile tutorial_server_historicaldata.c in examples

### ISSUE THREAD

**Issue by mojaxx** [open62541/open62541#3368]
HI 
I am trying to compile this example but it gives me this error :server.c:9:70: fatal error: open62541/plugin/historydata/history_data_backend_memory.h: No such file or directory
 #include <open62541/plugin/historydata/history_data_backend_memory.h>
                                                                      ^
compilation terminated.

Do i need to install or do anything before compiling this example ??
thanks

**Comment by maleselo** [comment]
@mojaxx You may need to enable UA_ENABLE_EXPERIMENTAL_HISTORIZING option

**Comment by mojaxx** [comment]
HI 
Thanks for that 
Where should i enable this??
Thanks

**Comment by mojaxx** [comment]
Thank you a lot
In general do i need to install data base on beaglebone black or what?

**Comment by mojaxx** [comment]
Hi
There is no opinion??
