### ISSUE TITLE
SecureChannel broken after #3383

### ISSUE THREAD

**Issue by Pro** [open62541/open62541#3386]
@jpfr it seems that #3383 broke the secure channel somehow.

If I start the server_ctt example and then use UaExpert to connect to it, it fails here:

https://github.com/open62541/open62541/pull/3383/files#diff-f7732748b7e13e607783dbd36f54eb82R442

Same if I use the `tutorial_client_firststep` demo.

Can you check? Thanks

**Comment by jpfr** [comment]
The certificate needs to be validated. Rather the pki plugin needs to be fixed.

One exception to pute here is SecureChannel#None when no certificate is defined at all.

**Comment by jpfr** [comment]
This is better now?

**Comment by Pro** [comment]
Yes, perfetto! Thanks for the fix
