### ISSUE TITLE
Local connection config and UA_SecureChannel_processHELACK

### ISSUE THREAD

**Issue by andranik-s** [open62541/open62541#3392]
## Description

After https://github.com/open62541/open62541/commit/a25bb7539304a08d43b3f001f892bf8604140b45: 

1. local connection config is completely ignored, so now servers cannot control max send/recv buffer size (I believe it's critical): [diff](https://github.com/open62541/open62541/commit/a25bb7539304a08d43b3f001f892bf8604140b45#diff-f7732748b7e13e607783dbd36f54eb82L292-L296)
2. `UA_SecureChannel_processHELACK` does almost nothing (basically sets `channel->config` and then compares it to itself): https://github.com/open62541/open62541/blob/5dce2701a3156b1489fd6661deb150861fc082e1/src/ua_securechannel.c#L172-L182

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [x] Critical issue

**Comment by jpfr** [comment]
fixed on master
