### ISSUE TITLE
ENCRYPTION

### ISSUE THREAD

**Issue by mojaxx** [open62541/open62541#3416]
Hi

I am trying to use encryption server example but it gives me errors.
I wonder if it needs any thing else for run??
Can anyone help me PLEASE .

Errors:
server.c: In function ‘main’:
server.c:38:33: warning: implicit declaration of function ‘loadFile’ [-Wimplicit-function-declaration]
     UA_ByteString certificate = loadFile(argv[1]);
                                 ^~~~~~~~
server.c:38:33: error: invalid initializer
server.c:39:32: error: invalid initializer
     UA_ByteString privateKey = loadFile(argv[2]);
                                ^~~~~~~~
server.c:47:22: error: incompatible types when assigning to type ‘UA_ByteString {aka struct <anonymous>}’ from type ‘int’
         trustList[i] = loadFile(argv[i+3]);
                      ^
server.c:61:9: warning: implicit declaration of function ‘UA_ServerConfig_setDefaultWithSecurityPolicies’ [-Wimplicit-function-declaration]
         UA_ServerConfig_setDefaultWithSecurityPolicies(config, 4840,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Regards .

**Comment by jpfr** [comment]
The loadFile method is defined here.
https://github.com/open62541/open62541/blob/master/examples/common.h

**Comment by mojaxx** [comment]
Thanks
