### ISSUE TITLE
client_async on Windows don't call WSAStartup

### ISSUE THREAD

**Issue by nokem61** [open62541/open62541#3421]
## Description
Example - client_async does not work on Windows because WSAStartup is not called.

In function `UA_ClientConnectionTCP` is colled `UA_initialize_architecture_network();`
but `UA_Client_connect_async` use `UA_ClientConnectionTCP_init` where `UA_initialize_architecture_network();` is not called.

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): tag 1.0.1
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Windows 10
 - [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached [log.txt](https://github.com/open62541/open62541/files/4159300/log.txt)
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Soysauce007** [comment]
I suffered the same problem as you, have you solved it now?
It works very well when I use the _server.exe_, but it doesn't work when I use the _client.exe_

```
[2020-03-19 11:06:26.336 (UTC+0800)] warn/userland      AcceptAll Certificate Verification. Any remote certificate will be accepted.
[2020-03-19 11:06:26.337 (UTC+0800)] warn/network       DNS lookup of localhost failed with error 应用程序没有调用 WSAStartup，或者 WSAStartup 失败。
```

Thanks

**Comment by Matt-Edwards** [comment]
I'm having the same problem on Windows

**Comment by Matt-Edwards** [comment]
I switched from master to v1.0.1 and now my client connects and runs.

**Comment by timosmd** [comment]
I receive the same error message. Tried Branches "Master" and "0.1" - both didn't work...

**Comment by jpfr** [comment]
This was fixed a view days ago.

**Comment by jpfr** [comment]
Few days...
