### ISSUE TITLE
Extra `.` character in tag name: v.1.0.1 -> v1.0.1

### ISSUE THREAD

**Issue by yurybura** [open62541/open62541#3427]
## Description
Tag name for 1.0.1 release contains extra character.
## Background Information / Reproduction Steps
n/a
## Checklist
Please provide the following information:

 - [x] open62541 Version (release number or git tag): v.1.0.1
 - [ ] Other OPC UA SDKs used (client or server): all
 - [ ] Operating system: all
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
The release tag was updated / added.
