### ISSUE TITLE
Question: Namespace Zero Full Size?

### ISSUE THREAD

**Issue by Mosbeard** [open62541/open62541#3435]
Hello,

in our project we want to implement an open62541 OPC UA Server on an embedded ESP32 microcontroller with a little custom namespace which depends on namespace DI and full namespace zero. Does someone know how much RAM and ROM we will need at least, when working with full namespace zero and namespace DI?

**Comment by jpfr** [comment]
For full you will need 2-3MB.
But this will get massively better once PR #3411 has landed.

**Comment by Mosbeard** [comment]
Thanks for information.
Do you mean 2-3 MB RAM?
And after this PR it is possible to hold the nodestore in ROM.

**Comment by jpfr** [comment]
Yes.

**Comment by saperlot** [comment]
With namespace minimal, i've got about 200kb code size and 50kb Read Only and 4kb Read Write Data. To give you an idea..

**Comment by NoelGraf** [comment]
@Mosbeard can the issue be closed?

**Comment by adarshvergis** [comment]
Hello @saperlot you mentioned, you implemented a fulll namespace server on esp32. Im having trouble with it : https://github.com/open62541/open62541/issues/8061

Did you face any such issues ?

**Comment by saperlot** [comment]
Hi @adarshvergis, it was on ARM, at that time i had it on a STM32F7, i‘m sorry i can‘t help.
