### ISSUE TITLE
UA_Client_Service_Read returns BadRequestTooLarge

### ISSUE THREAD

**Issue by Zvicii** [open62541/open62541#3482]
## Description
When I use UA_Client_Service_Read to read 10000 Nodes, it fails and return BadRequestTooLarge.
Also if I try to read 50000 nodes by reading 5000 nodes per read，it takes nearly 10 seconds,  its too long for me, can I read 50000 nodes in a shorter time? 

## Background Information / Reproduction Steps

Used CMake options:ENCRYPTION;AMALGAMATION

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag):1.1
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system:windows
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by ricksy** [comment]
I have also noticed that the examples provided use the high_level client which is meant for few nodes. Can someone please point me to any code excerpt where a large number of nodes (typically thousands) are being read at one?
