### ISSUE TITLE
Use python3 instead of python2

### ISSUE THREAD

**Issue by guenhter** [open62541/open62541#3529]
## Description
Because python2 reached its EOL, can all the python commands be switched to python 3?

e.g. in the documentation https://open62541.org/doc/current/nodeset_compiler.html

the examples are based on the command `python` (what is basically python2). Can this be updated to `python3 ...`?

**Comment by jpfr** [comment]
We support both Python2 and Python3 at the moment.
We can remove Python3 when this is a burden to maintain.

On my Windows box, `python` starts Python3.

```
C:\>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Feel free to send a Pull Request if you have proposals for documentation changes.
