### ISSUE TITLE
Create MonitoredItems stuck in loop

### ISSUE THREAD

**Issue by Zvicii** [open62541/open62541#3534]
## Description
I build a client and a server using open62541 v1.1.
but when i try to create monitoreditems using UA_Client_MonitoredItems_createDataChanges, if the number is too large(5000 string nodeid), it gets stuck and doesnt return.the server would also stuck in its loop and cant be stopped by setting 'running' to false.
if the number of nodes is small like 500 per request, it works fine.
## Background Information / Reproduction Steps

Used CMake options:Encryption,single file,subscription

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag):v1.1
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system:win7
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by evminaev** [comment]
Stack is used inside, so you must split monitoreditems into 500 item parts. or use UA_Client_MonitoredItems_createDataChange to do it one by one. The problem is that both of them   too slow...
