### ISSUE TITLE
Failed to Connect with QOPCUa Plug In

### ISSUE THREAD

**Issue by sanicr0** [open62541/open62541#3556]
## Description

I'm using the open62541 Qt Plug-in for QOPCUa to create a Client and connect it to a Server.
With OPC Expert I can connect to this Server without any issue but when I debug my QT C++ Code I get following Error:
qt.opcua.plugins.open62541: Open62541: Failed to connect

Also I print out the ClientError and Connection Error Enums from QT which are both Unknown Error.

## Background Information / Reproduction Steps

Basically what I'm doing in my code is:

- create a client (which works!)

- connect all signals and slots (also works)

- request endpoints from the localhost + port (works, I'm also getting the right endpoint back)

- connect to endpoint (auth-type is anonymous)

and with connect to endpoint it goes into connecting state but then it throws the unknown errors and disconnect. so it never goes into connected state. and then it throws the 
qt.opcua.plugins.open62541: Open62541: Failed to connect
error.

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 1.0
 - [x] Other OPC UA SDKs used (client or server): OPC Expert
 - [x] Operating system: Windows 10
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Did you integrate encryption?
Sometimes encryption is necessary as the password is encrypted even on an unencrypted SecureChannel.

Can you bring this up on the qtOPCUA github?

**Comment by sanicr0** [comment]
i don't need a password, the connection type from the server is: http://opcfoundation.org/UA/SecurityPolicy#None

**Comment by jpfr** [comment]
No. Even with an unencrypted SecureChannel, the server might set a "UserTokenPolicy" where just the password is encrypted.
The selected UserTokenPolicy should appear in the logs.

**Comment by jpfr** [comment]
Reopen if required.
