### ISSUE TITLE
Crash due to use of NULL session object in server

### ISSUE THREAD

**Issue by juangburgos** [open62541/open62541#3596]
## Crash Description

In [`processMSGDecoded`](https://github.com/open62541/open62541/blob/9ed0e090ccff4392dc8a2aa9994ba559b9a9c78f/src/server/ua_server_binary.c#L546) should there be a test condition on `session` when calling `((UA_SessionService)(uintptr_t)service)(server, channel, session ...` ?

I see there is a comment saying `/* Session lifecycle service. The session pointer can still be NULL. */`, but further in the stack there is an attempt to close on that `NULL` session with `Service_CloseSession` which causes a crash.

![image](https://user-images.githubusercontent.com/4707341/81720966-66857080-947f-11ea-83d4-2ffa3bd34fc7.png)

![image](https://user-images.githubusercontent.com/4707341/81721040-84eb6c00-947f-11ea-824d-04b47010a386.png)

![image](https://user-images.githubusercontent.com/4707341/81721123-acdacf80-947f-11ea-828d-3bf75fa03b80.png)

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): master
 - [x] Critical issue

**Comment by jpfr** [comment]
Fixed via #3597.

**Comment by juangburgos** [comment]
Beautiful!
