### ISSUE TITLE
Are UA_Client_Service_read and UA_Client_Service_write synchronous or asynchronous?

### ISSUE THREAD

**Issue by I-Yoo** [open62541/open62541#3603]

**Comment by I-Yoo** [comment]
@Julius Pfrommer

**Comment by I-Yoo** [comment]
@jpfr

**Comment by I-Yoo** [comment]
I read their implementation code, are they asynchronous? @jpfr

**Comment by jpfr** [comment]
Yes, they are sync. We have special async versions for these services.

**Comment by I-Yoo** [comment]
So where are they?Would you please tell me? @jpfr
