### ISSUE TITLE
Issues building open62541 for FreeRTOS+LwIP on STM32

### ISSUE THREAD

**Issue by Rixem** [open62541/open62541#3645]
## Description
Hello everyone. I am trying to port this beautiful library onto my STM32 board. On this board, I have a working FreeRTOS and LwIP package. Works like a charm. Nom, i tried to build myself the library but get some difficulties to get it working.

## Background Information / Reproduction Steps

What I've done? I've followed precisely every steps even the #2511 thread but still have issues.
Step 1 : Fetching the repo.
Step 2 : Configure Cmake building --> 
![CMAKECAP](https://user-images.githubusercontent.com/34239344/83260680-7b217280-a1ba-11ea-98ad-2cba6b4074ca.PNG)

Step 3 : Open the solution in visual studio, generate the "ALL_BUILD" package, and wait for the build. Nice ! I have the open62541.c/.h files.

Step 4 : Integrate these files in my STM32CubeIDE project.
![stm32cap](https://user-images.githubusercontent.com/34239344/83260989-f420ca00-a1ba-11ea-8cec-c7df2572e0c5.PNG)

Step 5 : configure lwipopts.h and FreeRTOSCOnfig.h. I have double check these files, and the are ok.

Step 6 : (Here is where is messed up something i think) I configured STM32CubeIDE to compile this project. 
![stm32miscecap](https://user-images.githubusercontent.com/34239344/83261320-70b3a880-a1bb-11ea-9b3b-b26d2f6a50b3.PNG)

Build command is like that : `-mcpu=cortex-m4 -std=gnu99 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F429xx -c -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/LwIP/system/arch -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../LWIP/App -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Core/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/system -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Include -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/netif -O0 -ffunction-sections -fdata-sections -Wall -DUA_ARCHITECTURE_FREERTOSLWIP -fstack-usage --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb`

When i try to compile this project, unfortunately i get multiple errors.
![errorscap](https://user-images.githubusercontent.com/34239344/83261561-d869f380-a1bb-11ea-8397-7d724af52f9d.PNG)
![warningscap](https://user-images.githubusercontent.com/34239344/83261570-dbfd7a80-a1bb-11ea-83c7-4c9dd1c33e57.PNG)
![infoscap](https://user-images.githubusercontent.com/34239344/83261578-dd2ea780-a1bb-11ea-8d58-dc3ee677da47.PNG)

Used CMake options:

Here is CMake generation Debug Output: 
`Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.16299.
fatal: not a git repository (or any of the parent directories): .git

CMake Warning at tools/cmake/SetGitBasedVersion.cmake:83 (message):
  Failed to determine OPEN62541_VERSION from repository tags.  Using default
  version "".
Call Stack (most recent call first):
  CMakeLists.txt:40 (set_open62541_version)

open62541 Version: 0.0.0-unknown
Architectures included in amalgamation: freertosLWIP
The selected architecture is: freertosLWIP
   Entering             D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1/arch
   Entering             D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1/arch/posix
   Returning to         D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1/arch
   Entering             D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1/arch/win32
   Returning to         D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1/arch
   Entering             D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1/arch/freertosLWIP
   Returning to         D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1/arch
   Entering             D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1/arch/vxworks
   Returning to         D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1/arch
   Entering             D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1/arch/eCos
   Returning to         D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1/arch
   Entering             D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1/arch/wec7
   Returning to         D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1/arch
   Returning to         D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1
   Entering             D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1/doc
Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
   Returning to         D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1
   Entering             D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1/tools/packaging
   Returning to         D:/PROJETS_BUREAU_ETUDES/PROJETS_EMBARQUES/open62541-master/open62541-1.1-rc1
Configuring done`

## Checklist

Please provide the following information:

 - [ 1.1-rc1] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ FreeRTOS] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

Can you help me ? What am I doing wrong?

Thank you by advance for your help.

**Comment by Rixem** [comment]
For those who have the same problem. I finally get it working.

I'm using STM32CubeIDE. I was entering the symbol -DUA_ARCHITECTURE_FREERTOS_LWIP in the wrong place.

Make sure you have this symbol here : 

![pathsymbol](https://user-images.githubusercontent.com/34239344/83278158-6ac9c180-a1d3-11ea-81f9-85da57d2f0a2.PNG)


Thanks to #2511 

Bye.

**Comment by acer1204** [comment]
Hi, Rixem
When i add the DUA_ARCHITECTURE_FREERTOS_LWIP in true path and compile it,
it show one error "dereferencing pointer to incomplete type 'struct sockaddr_in6"
Have you ever see this problem?
