### ISSUE TITLE
Problem building on STM32CubeIDE for FreeRTOS+LwIP

### ISSUE THREAD

**Issue by Rixem** [open62541/open62541#3658]
## Description

Hi,

I try to build this stack on a STM32F429 with FreeRTOS + LwIP. Unfortunately, I have some problems and errors when build finish. I think it's a CMake problem. Some functions are not defined, like UA_Server_New.

Can you help me ?

Thanks.

![Capture](https://user-images.githubusercontent.com/34239344/83501697-c8eef100-a4c0-11ea-9fa3-6768838718be.png)

## Background Information / Reproduction Steps

Used CMake options:

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
The main question here is, which CMake options did you use? Please fill out the complete Issue template!

Did you set the correct architecture with `-DUA_ARCHITECTURE=freertosLWIP`?

Example:
https://github.com/Pro/open62541-esp32/blob/master/components/open62541/CMakeLists.txt#L27

Also, when using the amalgamated version, you need to add the following compiler definitions:
`-DUA_ENABLE_AMALGAMATION -DUA_ARCHITECTURE_FREERTOSLWIP -DUA_ARCHITECTURE_FREERTOSLWIP_POSIX_CLOCK`

**Comment by Rixem** [comment]
Hey,

Yup, sorry i forgot to mention that it is working like a charm now ;)

The problem was clearly simple : I had compilation problems after CMake, building with Visual Studio, because of missing includes.  I had to point CMake property "UA_ARCH_EXTRA_INCLUDES" to my FreeRTOS folder.

I'll update #2511 to tell it works on my STM32F429.

Thanks ! :)
