### ISSUE TITLE
How to query all nodes from namespace? [question] 

### ISSUE THREAD

**Issue by STUBA-rupr** [open62541/open62541#3684]
## Question
Hello,
is there an example of a call a query to return all nodes from specific namespace?
Thank you

**Comment by jpfr** [comment]
Remotely or locally?
Locally you can use the nodestore API to iterate over all nodes.
https://github.com/open62541/open62541/blob/master/include/open62541/plugin/nodestore.h#L499

Remotely you have no choice but to recursively browse the information model.
