### ISSUE TITLE
Multinodes read get BadRequestHeaderInvalid if read nodes with bad status code

### ISSUE THREAD

**Issue by reyanvaldes** [open62541/open62541#3688]
## Description
When try to read multi nodes with bad status using the UA_Client_Service_Read got an error "BadRequestHeaderInvalid" in KepwareEx 6.8. If reading nodes with good status code, can read fine. I am following this example https://stackoverflow.com/questions/47591339/multiple-node-read-in-single-request-from-client-in-open62541. 
Thanks for any recommendation. 

## Background Information / Reproduction Steps
In kepware, create a channel with siemens PLC, that actually doesn't exist or not connected and created a couple of int tags with following address: MW0, MW2.
In the  multi nodes example try to read these two tags. 
[testing_kepware.zip](https://github.com/open62541/open62541/files/4752140/testing_kepware.zip)

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 0.3
 - [x] Other OPC UA SDKs used (client or server):  Client
 - [x] Operating system:  Linux
- [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
![opcua_readOk_nodes_good_status](https://user-images.githubusercontent.com/11097772/84148474-0d344100-aa2d-11ea-801d-158be13e3f0c.PNG)
![opcua_badRequest](https://user-images.githubusercontent.com/11097772/84148476-0d344100-aa2d-11ea-9f66-dd879ba4434e.PNG)

 - [ ] Critical issue

**Comment by jpfr** [comment]
You write that you are on version 0.3.
Can you try with the current stable release 1.0?

**Comment by NoelGraf** [comment]
@reyanvaldes what's the status?

**Comment by NoelGraf** [comment]
I would close the issue for now. Pls reopen if required!
