### ISSUE TITLE
Build and install on windows10 - PubSub/Encryption 

### ISSUE THREAD

**Issue by massimo-gollo** [open62541/open62541#3694]
## Description
Hi. 
I'm trying to build and install open62541 on windows 10, using Cmake and Visual Studio 16 2019 to build solutions
I'm working on PubSub mechanism and i would test this feature with the encryption enabled. Until now, building library worked but when i tried to add pubsub mechanism something went wrong. 

I report following my steps, maybe could be useful for someone else.

## Background Information / Reproduction Steps
To enable encryption, it's necessary build and install mbedtls, so i downloaded the package (v1.1.0-rc1-62-ga524accc), opened with cmake and generate project. Opened solution in admin mode and build and install all. 
Then, following docs instructions
```git clone https://github.com/open62541/open62541.git
cd open62541
git submodule update --init --recursive
mkdir build
```
with Cmake GUI 
Used CMake options:
```
Commandline options:

DMBEDX509_LIBRARY:FILEPATH=C:/Program Files (x86)/mbed TLS/lib/mbedx509.lib
DMBEDTLS_INCLUDE_DIRS:PATH=C:/Program Files (x86)/mbed TLS/include
DUA_ENABLE_PUBSUB_INFORMATIONMODEL:BOOL=1
DMBEDCRYPTO_LIBRARY:FILEPATH=C:/Program Files (x86)/mbed TLS/lib/mbedcrypto.lib 
DMBEDTLS_LIBRARY:FILEPATH=C:/Program Files (x86)/mbed TLS/lib/mbedtls.lib
DUA_ENABLE_ENCRYPTION:BOOL="1" 
DUA_ENABLE_PUBSUB:BOOL=1
DUA_MULTITHREADING:STRING=0
DUA_NAMESPACE_ZERO:STRING=FULL
DUA_BUILD_EXAMPLES:BOOL="0" 


Cache file:
MBEDX509_LIBRARY:FILEPATH="C:/Program Files (x86)/mbed TLS/lib/mbedx509.lib"
MBEDTLS_INCLUDE_DIRS:PATH="C:/Program Files (x86)/mbed TLS/include"
UA_ENABLE_PUBSUB_INFORMATIONMODEL:BOOL="1"
MBEDCRYPTO_LIBRARY:FILEPATH="C:/Program Files (x86)/mbed TLS/lib/mbedcrypto.lib"
MBEDTLS_LIBRARY:FILEPATH="C:/Program Files (x86)/mbed TLS/lib/mbedtls.lib"
UA_ENABLE_ENCRYPTION:BOOL="1"
UA_ENABLE_PUBSUB:BOOL="1"
UA_MULTITHREADING:STRING="0"
UA_NAMESPACE_ZERO:STRING="FULL"
UA_BUILD_EXAMPLES:BOOL="0"
```
Then, i open solution Open62541.sln in admin mode and build all in admin mode. After that, build Install only. 

So, now i should have lib installed. To be sure, i copied .dll from bin folder to System32 and from cmd run
```
regsvr32 open62541.dll
```
but i don't know if this could be useful. 

At this point, i create a empy solution and include C:/Program Files (x86)/open62541/include 
and add to linker open62541.lib
I wrote a server that publish some custom value. I would display this value published on a subscriber( i'm thinking to use tutorial_pubsub_subscriber) but, if  I include the example project in my solution, I have this following errors: 

```
Error LNK2019	unresolved external symbol _UA_PubSubConnection_regist referenced in function _addPubSubConnection	tutorial_pubsub_subscribe ..\examples\tutorial_pubsub_subscribe.obj		

LNK2019	unresolved external symbol _UA_Server_DataSetReader_addTargetVariables referenced in function _addSubscribedVariables	tutorial_pubsub_subscribe	..\examples\tutorial_pubsub_subscribe.obj	
```
Am I wrong something in the process?
P.s.  = if I disable 
```
BUILD_SHARED_LIBS 
```
Seems doesn't find mbedtls libs, but if I enable, seems there are problems with PubSub.

Thank you in advice

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 1.1.0-rc1-62-ga524accc
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Windows10 
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by EvgKlin** [comment]
@massimo-gollo do you find solution? I get other Error LNK2019, but maybe your solution will be helpfull
