### ISSUE TITLE
Client can't connect to local server on win10

### ISSUE THREAD

**Issue by matejk87** [open62541/open62541#3702]
Hi!
I compiled basic server and client example of the latest open62541(V1.1) lib for win10 (64bit). 
Server seems to work as I have tested it with UAExspert. But I can't connect to server with basic client example.
I've tested this client with different servers(localhost, and external embedded server), without difference.
Here is client response:

![UA client error](https://user-images.githubusercontent.com/7039815/84568896-e22a5400-ad82-11ea-9aea-a5e81d0ae338.JPG)

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ x] Operating system: win10
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Which version do you use?
If you can, try the latest v1.1.1 release.
A networking problem on windows was resolved earlier this year.

**Comment by NoelGraf** [comment]
@matejk87 what's the status

**Comment by NoelGraf** [comment]
I would then close the issue. Please reopen if required!
