### ISSUE TITLE
Release v1.1 source code archive does not have initialized submodules. 

### ISSUE THREAD

**Issue by saukijan** [open62541/open62541#3706]
## Description

The latest release, as well as some of the previous ones (I only checked down to v1.0 release) provides source code archives [open62541-1.1.zip](https://github.com/open62541/open62541/archive/v1.1.zip) and [open62541-1.1.tar.gz](https://github.com/open62541/open62541/archive/v1.1.tar.gz) which do not contain code from the sub-modules: [Pro/mdnsd](https://github.com/Pro/mdnsd/tree/5af316c4b79460c0c1b6c2a674a37e28a85441a3) and [ OPCFoundation/UA-Nodeset](https://github.com/OPCFoundation/UA-Nodeset/tree/805cb46ad326d8375ea2449082f264b7d0175f24) which causes complications for [conan package](https://github.com/conan-io/conan-center-index/pull/1687) maintenance.

I have written a utility function to solve this problem during package creation, however it requires internet access and if not maintained and tested properly, can cause unexpected issues for the end user (desired features not being activated, missing node definitions or failure to compile entirely). 

I could avoid these problems, if the sub-modules were initialized before the source code is archived and published under releases. 

This does not need to be applied for the current release or previous ones, however it would simplify package maintenance if applied going forward.

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag):
 - [x] Other OPC UA SDKs used (client or server):  Not related to the binaries
 - [x] Operating system: Irrelevant
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
The zip files are auto-generated by Github.
Good to see you found a workaround.
