### ISSUE TITLE
Some of volatile is being deprecated in C++20

### ISSUE THREAD

**Issue by Troels51** [open62541/open62541#3712]
## Description
C++20 has deprecated some parts of the volatile keyword [P1152R3](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1152r3.html).
This causes warnings to be thrown when compiling open62541. For example
```
error: compound assignment with ‘volatile’-qualified left operand is deprecated [-Werror=volatile]
  367 |     *addr += increase;
      |     ~~~~~~^~~~~~~~~~~
```

## Background Information / Reproduction Steps
These warnings appear with on a C++20 compatible compiler like gcc10.

I am using open62541 version 1.1 on linux

Used CMake options:
UA_FORCE_CPP=ON CMAKE_CXX_STANDARD=20

```bash
cmake -DUA_FORCE_CPP=ON -DCMAKE_CXX_STANDARD=20 ..
```

## Checklist

Please provide the following information:

 - [X] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [X] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
You’re welcome to send a PR with a fix.
