### ISSUE TITLE
UA Client without encryption can not connect

### ISSUE THREAD

**Issue by frax2222** [open62541/open62541#3784]
Hello,

I have built open62541.c and open62541.h from master branch 1.0 for operating system WEC7 (useing VS2008) without encryption.
I have built an OPCUA server on that basis that works with UAExpert OPCUA Client.

Now I have built an OPCUA client for WEC7.  From this client I can connect to my server.
But I can not connect to Prosys OPC UA Simulation server and I can not connect to IntegrationObjects simulation server.

There seems to be a problem with missing encryption. 
Do I have to accept that connection does not work without encryption ? 

If I need encryption, how can I add encryption ? On page https://open62541.org/doc/1.0/installing.html it is said that Ecnryption can be added via Build Options.  But I can not find it here: https://open62541.org/doc/1.0/building.html#build-options

Attached log-files of OPCUA client and screen shot of Prosys Simulation server.

Thank you !

[opcualog_myServer.txt](https://github.com/open62541/open62541/files/4929651/opcualog_myServer.txt)
[opcualog_Prosys.txt](https://github.com/open62541/open62541/files/4929652/opcualog_Prosys.txt)
![Prosys_Endpoints](https://user-images.githubusercontent.com/23507172/87633978-b4974880-c73c-11ea-95ec-5c57874de668.png)
[opcualog_IntegrationObjects.txt](https://github.com/open62541/open62541/files/4929653/opcualog_IntegrationObjects.txt)

**Comment by jpfr** [comment]
It might be that anonymous login does not require encryption.

Password based login usually needs encryption. At least for the password itself if the channel is unencrypted.

**Comment by jpfr** [comment]
Oh right. The build option for encryption is missing from the docs.
That’s a bug.

You can use cmake-GUI or ccmake to see all options.

**Comment by frax2222** [comment]
Hello,

as shown in opcualog_Prosys,txt I try anonymous connection:

[2020-07-16 21:49:04] info/client 	Selected UserTokenPolicy anonymous with UserTokenType Anonymous and SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#None

In Prosys Users anonymous login is allowed:
![Prosys_Users](https://user-images.githubusercontent.com/23507172/87657248-dbfd0e00-c75a-11ea-80a9-58cc18739d88.png)

**Comment by frax2222** [comment]
Hello,

just an additional information: I can connect to UaCPPServer  (Demo Server V1.7.2) of Unified Automation.

So despite all standardisation this seems to be handled differently .....

**Comment by jpfr** [comment]
At least integrationobjects complains about missing encryption.
Can you try with v1.1 and enabled encryption?
Error logging is better in the newer versions at well.

**Comment by frax2222** [comment]
I will try but as far as I have seen I have to include mbedtls. I am not sure whether and how I can compile this stuff with VS2008. I have to use VS2008 for WEC7.

**Comment by NoelGraf** [comment]
I would close the topic for now. Please reopen if required!
