### ISSUE TITLE
UA_Client_getEndpoints() can't get endpoints with User Identity Token

### ISSUE THREAD

**Issue by jixian79** [open62541/open62541#3805]
## Description

When use `UA_ServerConfig_setDefaultWithSecurityPolicies`  create opcua server, the `client_find_servers.c` can find the endpoints。
But when i create a server with below code, the `client_find_servers.c` can't get the endpoints.
```
retval = UA_ServerConfig_setMinimal(config, 0, NULL);

retval = UA_ServerConfig_addSecurityPolicyBasic256Sha256(config, &certificate, &privateKey);
if(retval != UA_STATUSCODE_GOOD) {
        UA_ServerConfig_clean(config);
        return retval;
    }
retval = UA_ServerConfig_addEndpoint(config, config->securityPolicies[config->securityPoliciesSize - 1].policyUri,
        UA_MESSAGESECURITYMODE_SIGNANDENCRYPT);
config->accessControl.clear(&config->accessControl);
retval = UA_AccessControl_default(config, false,
        &config->securityPolicies[config->securityPoliciesSize - 1].policyUri, 2, logins);
```

UaExpert can find my opcua server with basic256sha256 endpoint, and connect to it
But UA_Client_getEndpoints() can't find the endpoint.

i have some questions:
1. what kind of opcua server the client can use the `UA_Client_getEndpoints()` to get the endpoints?
    it seems the opcua server with user identify token can't .  

2. how client connect to the server found by LDS? 
    I use `UA_Client_connectUsername()`  to connect the url returned by LDS , for example `opc.tcp://localhost:4532`, but  always get BadTimeout.  by the way , i configured the same security policy and  Message Security Mode with the server.  And the same client program can connect to a normal opcua server with the same  security policy 、 Message Security Mode、User identify token.  

client
```
  UA_Client *client = UA_Client_new();
    UA_ClientConfig *config = UA_Client_getConfig(client);

    config->securityMode = UA_MESSAGESECURITYMODE_SIGNANDENCRYPT;
    UA_StatusCode retval = UA_ClientConfig_setDefaultEncryption(config, certificate, privateKey,
                                                                    trust_list, trust_list_size,
                                                                    revocationList, revocationListSize);

    if(retval != UA_STATUSCODE_GOOD)
    {
        UA_LOG_ERROR(UA_Log_Stdout, UA_LOGCATEGORY_CLIENT, 
                "Initial Failed: %s \n", UA_StatusCode_name(retval));
    }
    
    UA_ServerOnNetwork *server = &serverOnNetwork[0];
    UA_String server_name = server->serverName;
    UA_String server_url  = server->discoveryUrl;

    char *endpoint = (char *) UA_malloc(sizeof(char) * server_url.length + 1);
    memcpy(endpoint,server_url.data,server_url.length);
    endpoint[server_url.length] = '\0';

    config->securityMode = UA_MESSAGESECURITYMODE_SIGNANDENCRYPT; /* require encryption */
    retval = UA_Client_connect_username(client, endpoint, "peter", "peter123");
```

## Checklist

Please provide the following information:

-  [x] open62541 Version (release number or git tag): v 1.1.1
 - [x] Other OPC UA SDKs used (client or server):  open62541's server and client, UaExpert
 - [x] Operating system:Windows
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by ZekeLandon** [comment]
@jixian79, could you post your logs here related to UA_Client_getEndpoints() and the server for better understanding?
When UaExpert can find the endpoints, internal client should also be able to do so.

**Comment by NoelGraf** [comment]
@jixian79 Is your issue still current?

**Comment by NoelGraf** [comment]
I would then close the issue. Please reopen if required!
