### ISSUE TITLE
volatile compound assignment deprecated in c++20

### ISSUE THREAD

**Issue by mlgiraud** [open62541/open62541#3808]
## Description
c++20 deprecates some uses of volatile, which breaks compilation when compiling the library with a c++20 compiler (e.g. clang11)
This is used in [include/open62541/architecture_definitions.h](https://github.com/open62541/open62541/blob/629d9ddd1dd2a9cf18eb1afd4134648da48cf0ee/include/open62541/architecture_definitions.h#L424) for example.
The error:
```
warning: compound assignment to object of volatile-qualified type 'volatile uint32_t' (aka 'volatile unsigned int') is deprecated [-Wdeprecated-volatile]
    *addr += increase;
```

Solution: Disable the warning via flag, or replace `a+=b` with `a=a+b`

## Background Information / Reproduction Steps
compile with clang11 as c++

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): master
 - [x] Other OPC UA SDKs used (client or server):  none
 - [x] Operating system: ubuntu 20.04.1 LTS
 - [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached: not applicable
 - [x] Wireshark network dump attached: not applicable
 - [x] Self-contained code example attached: not applicable
 - [ ] Critical issue

**Comment by ccvca** [comment]
Duplicate of #3712

**Comment by mlgiraud** [comment]
Closing in favor of continuing in the original issue
