### ISSUE TITLE
How to get OPC UA variable nodes of the PLC, to address them in an OPC UA client-open62541

### ISSUE THREAD

**Issue by mohamedalielghoula** [open62541/open62541#3821]
## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [x] Critical issue

**Comment by embbo** [comment]
@mohamedalielghoula what do yu mean ? what i understand you are asking about Plc adress ..in VariableNode?

**Comment by mohamedalielghoula** [comment]
Hello @embbo,
yes exactly

**Comment by jpfr** [comment]
Connect with a graphical client like UA Expert.
Or use the browse service to find nodes.

**Comment by mohamedalielghoula** [comment]
Hello @jpfr , I'm a beginner in open62541 
in my project, I use two stm32s 
the first includes an opc client to communicate with an opc server in PLC and the second includes an opc server to communicate with a desktop application opc ua, the communication between the two cards is serial, 
I don't need all the node IDs in the PLC, so I access the node IDs in the first board by names that are not with the navigation service, and I use this function for each node ID :
 UA_Client_readValueAttribute(client, UA_NODEID_STRING(3, "xxx"), &value) ;
My question is that there are some nodes under a repositories named like this xx.yy.zz 
how do I get it with this function?

**Comment by embbo** [comment]
@jpfr can I write somewhere Userdata ?? for example I need tou send adress of each Node with that Node (0x1234456), where can I write it ..

**Comment by embbo** [comment]
@mohamedalielghoula ..what i am doing , I use two node . and I put adress in value of the other..

**Comment by mohamedalielghoula** [comment]
@embbo Sorry but I'm not understood, can you please tell me more. 
In my example, my node ID is "FB_DB". "Tag1" and I want to read the value of Tag1, and there are other nodes under FB_DB, 
how can read it with this function UA_Client_readValueAttribute() 
or there is another function that allows me to get access under "FB_DB".

**Comment by mohamedalielghoula** [comment]
> Connect with a graphical client like UA Expert.
> Or use the browse service to find nodes.

i have nodeid string separated by point as u see in my example "FB_DB". "Tag1", it didnt work with this function 
UA_Client_readValueAttribute(client, UA_NODEID_STRING(3, "xxx"), &value)

**Comment by EugenM-sie** [comment]
@mohamedalielghoula hi, wich desktop application opc ua do you mean?

**Comment by mohamedalielghoula** [comment]
@EugenM-sie i developped my own opc ua client application 
The problem is solved
 To read this node i have to named in this function like this UA_NODEID_STRING(3, "\"FB_DB_1\".\"Tag1\"")
