### ISSUE TITLE
Support for the OPC UA 1.04 profiles 

### ISSUE THREAD

**Issue by daab007** [open62541/open62541#3840]
Hello,

you use deprecated names for the profiles when you talk about certification. Does it mean that OPC UA 1.04 profiles were not tested? Could we expect any problems with that?

It could be a potential showstopper for us...

Best Regards,
Daniel Cyran.

**Comment by jpfr** [comment]
The 1.04 profiles were not used by the testing lab one year ago.

We are now using the current version of the CTT internally.

**Comment by jpfr** [comment]
Note that the release family 1.0 is certified.
Certification of new features since 1.0 is not yet done.

**Comment by daab007** [comment]
It is clear, that not all newest features were certified in the past.

I am wondering about potential problems with the features/facets  already certified in the past in regards to new profiles.  
What is more we are planning to introduce Alarm and Condition Server as well. Same question here... Any advises here?

**Comment by daab007** [comment]
Thanks for the feedback, will contact you later on.
