### ISSUE TITLE
Question: When do I need UA_MULTITHREADING

### ISSUE THREAD

**Issue by heppth** [open62541/open62541#3871]
Lets assume the following: I use open62541 for multiple simultan client connections. Multiple threads are used to handle the clients.

Question A: If I ensure via mutex, that every client context is used only once at time, do I need to enable UA_MULTITHREADING?
Question B: If I enable UA_MULTITHREADING, may I use one client context with on two diffrent threads?

**Comment by jpfr** [comment]
UA_MULTITHREADING only impacts the server at this time.
You can activate it if you want to access the server via the C API from parallel threads.

> Question A: If I ensure via mutex, that every client context is used only once at time, do I need to enable UA_MULTITHREADING?

No

> Question B: If I enable UA_MULTITHREADING, may I use one client context with on two diffrent threads?

No. For the server yes.
