### ISSUE TITLE
UA_Client_run_iterate   UA_Client_readValueAttribute   threads 

### ISSUE THREAD

**Issue by I-Yoo** [open62541/open62541#3875]
I get an error using UA_Client_run_iterate and UA_Client_readValueAttribute in different threads and the connection disconnects. How do I fix this?

**Comment by I-Yoo** [comment]
LOG: 
info/client       Error receiving the response with status code BadSecurityChecksFailed

**Comment by I-Yoo** [comment]
Is it because the UA_Client_readValueAttribute method affects the UA_Client_run_iterate method? Are there resource conflicts between the two methods?

**Comment by jpfr** [comment]
Protect the client with a mutex.
The work to make the client thread-safe is still ongoing.
