### ISSUE TITLE
small memory leak on processServiceResponse when I use the UA_Client_Service_read method

### ISSUE THREAD

**Issue by I-Yoo** [open62541/open62541#3906]
open62541 Version release 1.1, windows, TCP

**Comment by jpfr** [comment]
Use Dr. Memory to produce some indication on the origin of the leak.

**Comment by I-Yoo** [comment]
I debugged in Visual Studio 2017 using a memory snapshot for heap analysis and found that a memory leak occurred during the following call
[
![批注 2020-09-25 093038](https://user-images.githubusercontent.com/26811265/94216405-d74e9600-ff11-11ea-8cb9-ab75c5f83810.png)
](url)

**Comment by I-Yoo** [comment]
I debugged in Visual Studio 2017 using a memory snapshot for heap analysis and found a memory leak in the following call structure. There is a linear relationship between the count difference and the number of nodes I request to read.
![批注 2020-09-25 093038](https://user-images.githubusercontent.com/26811265/94216642-783d5100-ff12-11ea-8545-5b04a1e8dc8d.png)

**Comment by I-Yoo** [comment]
I debugged in Visual Studio 2017 using a memory snapshot for heap analysis and found a memory leak in the following call structure. There is a linear relationship between the count difference and the number of nodes I request to read.
![批注 2020-09-25 093038](https://user-images.githubusercontent.com/26811265/94219030-652d7f80-ff18-11ea-8b07-d61e5a1682b2.png)

**Comment by I-Yoo** [comment]
I debugged in Visual Studio 2017 using a memory snapshot for heap analysis and found a memory leak in the following call structure. There is a linear relationship between the count difference and the number of nodes I request to read.
![memory](https://user-images.githubusercontent.com/26811265/94219504-8fcc0800-ff19-11ea-975f-8db2623a4b60.png)

**Comment by I-Yoo** [comment]
Is the problem in the diagram in Array_decodeBinary and UA_new?

**Comment by jpfr** [comment]
Do you clean up the value returned from UA_Client_Service_read?
