### ISSUE TITLE
Create Objects with xml-compiler on client side

### ISSUE THREAD

**Issue by MichaelKlin** [open62541/open62541#3908]
## Description
Sorry, for my new Question/Problem. I want to ask: With XML Nodeset compiler i can create object for server. My Question is: Can I create Object with xml for client side?
## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): master v1.1.2.
 - [x] Operating system: Windows, Linux

**Comment by Pro** [comment]
Short answer: Yes.

Please have a look at the documentation and the examples: 
https://github.com/open62541/open62541/tree/master/examples/nodeset
