### ISSUE TITLE
Loading PubSub configuration from File is broken

### ISSUE THREAD

**Issue by Fischer-Thomas** [open62541/open62541#3909]
## Description

https://github.com/open62541/open62541/pull/3772 changed the structure of the DataSetReader, DataSetReaderConfig and the method to createTargetVariables as well. However when trying to build the library with UA_PUBSUB_FILE_CONFIG enabled you get some error messages which are caused by the merge of #3772 and #3806.

## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_ENABLE_PUBSUB=On -DUA_ENABLE_PUBSUB_FILE_CONFIG=On
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): master

**Comment by jpfr** [comment]
@andreasebner This should be part of a CI run.
