### ISSUE TITLE
Timestamp configuration 

### ISSUE THREAD

**Issue by mohamedalielghoula** [open62541/open62541#3912]
Hello all 
I use stm32 as an OPC server, and the timestamp starts at 01:00 
I want to change this time manually or is there another way to get this time from the host automatically

**Comment by jpfr** [comment]
We use the system time.
That has to be set globally, not just for OPC.

**Comment by mlang-de** [comment]
Your system should support NTP. Check OPC UA Spec. Part 6, chapter 6.3 Time synchronization.
