### ISSUE TITLE
It may rise a TypeError when node.value.value is None

### ISSUE THREAD

**Issue by tyhser** [open62541/open62541#3923]
Hi, i'm also new to open62541,
when i use UA Model eXcelerator Pro to create opc UA model then use this tool to generate c code,
this position always rise a TypeError: object of type 'NoneType' has no len(), could you please help me solve this problem,
thank you very much!
 https://github.com/open62541/open62541/blob/aaba07f73165090281eb950cc19d2e5aa54a45e6/tools/nodeset_compiler/backend_open62541_nodes.py#L233

**Comment by jpfr** [comment]
Fix in #3930.

**Comment by NoelGraf** [comment]
Then I would close the issue now.
