### ISSUE TITLE
FeatureRequest: PubSub with UA_FIELDENCODING_RAWDATA

### ISSUE THREAD

**Issue by mlang-de** [open62541/open62541#3966]
Have somebody the intention to implement the third pubsub encoding (RawData)?
Is it on the roadmap in general? 
TIA

**Comment by jpfr** [comment]
We are actively working on it.
Results will become visible in a PR when ready.

**Comment by mlang-de** [comment]
Is it planned for 2020 or Q1/Q2/... 2021 to be visible as PR?

**Comment by jpfr** [comment]
My guess is Q1.
