### ISSUE TITLE
How to add User?

### ISSUE THREAD

**Issue by EugenM-sie** [open62541/open62541#3968]
## Description
Hallo, i would like to add user like Mike, Kennword:1234. I do not fint fuction. Or do it work only with session? In Dokumentation i do not find anything 
## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag):v1.1.12
 - [x] Other OPC UA SDKs used (client or server): server
 - [x] Operating system: Windows 10

**Comment by EugenM-sie** [comment]
I found your example, sorry

**Comment by jpfr** [comment]
Please reopen if required.
