### ISSUE TITLE
How to add/change url

### ISSUE THREAD

**Issue by EvgKlin** [open62541/open62541#3980]
## Description
Hallo, i want to ask, how can I add URL like http://opcapi.place/example. 
## Background Information / Reproduction Steps
I find some variables for host and port, but nothing for URL. Thank you

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): last release 
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: windows

**Comment by MichaelKlin** [comment]
@jpfr can you please give a reference or some help and can close issue

**Comment by jpfr** [comment]
OPC UA does not use http.

Are you on the server or client side?

**Comment by MichaelKlin** [comment]
@jpfr i am on server side

**Comment by MichaelKlin** [comment]
@jpfr because in OPC UA gui client widget i see, that can connect with   opc.tcp:// and with   https://

**Comment by MichaelKlin** [comment]
![image](https://user-images.githubusercontent.com/64699335/97800089-ae1cd600-1c32-11eb-9649-85a6bdd3d9b9.png)

**Comment by MichaelKlin** [comment]
Hallo @jpfr , last question, there is no opportunity to use http? Bcause I do not know, there is field for Url and http. Sorry for my English

**Comment by EugenM-sie** [comment]
Hallo @Pro can you maybe please help and i close this issue

**Comment by MichaelKlin** [comment]
Hallo @Pro can you maybe please help and i close this issue
