### ISSUE TITLE
Ua Expert gets 'BadSecurityModeInsufficent' during activatesession

### ISSUE THREAD

**Issue by RFil** [open62541/open62541#3993]
Ua Expert always gets 'BadSecurityModeInsufficent' during activatesession when I try to login providing username and password

**Comment by MichaelKlin** [comment]
@RFil Do you get solution?

**Comment by RFil** [comment]
> 
> 
> @RFil Do you get solution?

Not yet... any help is welcome

**Comment by mlang-de** [comment]
See https://forum.unified-automation.com/viewtopic.php?f=22&t=3422
If security and encryption is none + Username/Password is used the UaExpert throws this warning intentionally.

**Comment by RFil** [comment]
> 
> 
> See https://forum.unified-automation.com/viewtopic.php?f=22&t=3422
> If security and encryption is none + Username/Password is used the UaExpert throws this warning intentionally.

Thanks

**Comment by mlang-de** [comment]
@RFil Please close this issue.
