### ISSUE TITLE
access_control_server gives errors

### ISSUE THREAD

**Issue by EvgKlin** [open62541/open62541#3999]
## Description

Hallo, 
if i start "access_control_server" code from your examples and i connect the server with Unified Automation UAexpert (gui Client), i get the following error:
Error ‘BadSecureModelsufficient‘ was returned during ActivateSession, press ‘Ignore‘ to suppress the error and continue connecting (Picture)

By pressing „Ignore“, i get Connection to Server 

## Background Information / Reproduction Steps

![Meldung](https://user-images.githubusercontent.com/64699335/98472501-c755f180-21f3-11eb-88f6-8d4c3b403277.PNG)
![Meldungcmd](https://user-images.githubusercontent.com/64699335/98472525-db015800-21f3-11eb-8ebd-dd59848e00ff.PNG)

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag):v1.1.2
 - [x] Other OPC UA SDKs used (client or server): Ua Expert
 - [x] Operating system:Windows
 - [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached

**Comment by NoelGraf** [comment]
The message appears when you call a method that requires an encrypted channel but invokes it using an insecure channel. The problem with this example is that the credentials are sent as plain text. If you configure the server with encryption, the warning should not appear anymore

**Comment by EvgKlin** [comment]
Thank you
