### ISSUE TITLE
An error in doc page.

### ISSUE THREAD

**Issue by lukezmiles** [open62541/open62541#4001]
Hi.

I couldn't find an appropriate way to contact with you, so I mention it here.

In doc pages, about multithreading, you wrote:
>  0-199: Multithreading support disabled.
>  100-199: API functions marked with the ......
>  ≥200: Work is distributed to a number of ......

Is <0-199> right? I'm a little confused.

Thank you.

**Comment by NoelGraf** [comment]
No, that was a mistake. Is already fixed in the documentation.
