### ISSUE TITLE
AddVariable: Node could not create a varable. error code BadNodeAttributesInvalid

### ISSUE THREAD

**Issue by EugenM-sie** [open62541/open62541#4023]
## Description
I add some objets and variables in Server and I can not  see Objects with Unified Automation Uaexpert. I compiled server for ARM-Architecture and execute it on Linux, The  UA gui client i call on Windows. All Other Configuratiion of Server I can see

I see my Problem,that i get BadNodeAttributesInvalid
## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): least release
 - [x] Other OPC UA SDKs used (client or server): UA gui Client
 - [x] Operating system: Windows, Debian 9
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [x] Critical issue

**Comment by EugenM-sie** [comment]
Hallo @pro Do you have the same Issue. Or can can you maybe reproduce error?

**Comment by viktor-morin** [comment]
@EugenM-sie 
I downloaded the latest package, get same error.
How did you solve it?
