### ISSUE TITLE
submodule dependencies

### ISSUE THREAD

**Issue by maldag** [open62541/open62541#4072]
Integrating this repository in our build system does not lock the gitmodules dependencies to certain hashes.

This can cause serious problems in this repository. 

Have you considered locking git submodules to hashes instead of branches?

It will break builds for older releases once the tracked branch progresses

**Comment by ccvca** [comment]
Git submodules uses hashes by default, e.g. here in this implementation:
https://github.com/umati/Sample-Server/tree/main/deps

Make sure, that your .gitmodules does **not** define branches:
https://github.com/umati/Sample-Server/blob/e79c062cce435b343d8e6fdd143507dcf28034ed/.gitmodules

**Comment by maldag** [comment]
I'm trying to point out, that releases tagged in this repository are in a stale state. 

We are fixing the hashes for our private fork.

**Comment by NoelGraf** [comment]
I would close the issue. The "workaround" regarding the submodule is described in the documentation. Reopen this one if required.
