### ISSUE TITLE
Not able to set/increase MaxArrayLength

### ISSUE THREAD

**Issue by fijo1015** [open62541/open62541#4074]
## Description

Hi,
I want to increase the MaxArrayLength, which is a property of the array node. The UAExpert shows this:

![MaxArrayLength](https://user-images.githubusercontent.com/73999251/102472111-4261c180-4056-11eb-8345-2fed199f2abf.png)

Now I want to set the maxArrayLength value using the following code. 

> 	UA_VariableAttributes m_VariableAttr = UA_VariableAttributes_default;
> 	m_VariableAttr.displayName = UA_LOCALIZEDTEXT_CONST("en-US", "MaxArrayValue");
> 	m_VariableAttr.description = UA_LOCALIZEDTEXT_CONST("en-US", "");
> 	m_VariableAttr.accessLevel = UA_ACCESSLEVELMASK_READ | UA_ACCESSLEVELMASK_WRITE;
> 	m_VariableAttr.dataType = UA_NODEID_NUMERIC(0, UA_NS0ID_MAXARRAYLENGTH);
> 	UA_UInt32 maxvalue =  70000;
> 	UA_Variant_setScalarCopy(&m_VariableAttr.value, &maxvalue, &UA_TYPES[UA_TYPES_UINT32]),
> 
> 	UA_Server_addVariableNode(server,
> 		UA_NODEID_NUMERIC(1, NULL),
> 		UA_NODEID_NUMERIC(1, 54441),
> 		UA_NODEID_NUMERIC(0, UA_NS0ID_HASPROPERTY),
> 		UA_QUALIFIEDNAME_CONST(1, "MaxArrayValue"),
> 		UA_NODEID_NUMERIC(0, UA_NS0ID_PROPERTYTYPE),
> 		m_VariableAttr,
> 		NULL,
> 		NULL);

If I run this, I get the following error messages:

> WriteRequest returned status code BadTypeMismatch
> AddNodes: The value of ns=1;i=54442 is incompatible with the variable definition
> AddNodes: Type-checking the variable node ns=1;i=54442 failed with error code BadTypeMismatch

If I leave out the "setScalarCopy"-Line, then there is no Error Message anymore but the MaxArraySize Value has not been set. Can anybody tell me, what´s my fault?

Best regards
jo

**Comment by jpfr** [comment]
Which version of the sek do you use?

Later versions have much better error logs on the type checking.

The required type is MaxArray. But you try to set an Int32. Are the two compatible?

**Comment by jpfr** [comment]
Also, try with the latest 1.2-rc1.
At least you should get better logs.

**Comment by NoelGraf** [comment]
Have you tried the suggested solutions? Does the problem still exist?

**Comment by NoelGraf** [comment]
Close the issue for now, reopen it if necessary.
