### ISSUE TITLE
Open62541  1.0.5 - Unable to build

### ISSUE THREAD

**Issue by Twoshrubs** [open62541/open62541#4102]
Hello,

I'm currently moving from 1.0.3 to 1.0.5 of the Server and getting the error 'serviceMutex' is missing when trying to build.

## Background Information / Reproduction Steps

I have had no issues in the past building the previous versions and following the same setup..

CMake options -

Build_Shared_libs = True
Build_Type = Release
Discovery = True
Encryption = True
MethodCalls = True
Micro_EMB_Dev_profile = True
NodeManagement = True
Enable_Subscriptions = True
LogLevel = 300
UA_Namespace_Zero = Full

Everything else as default.

Here are the errors I'm getting while building..

`MESSAGE: Entering directory `/home/shrubs/Downloads/open62541-1.0.5/build'
/bin/sh -c '/usr/bin/make -j 36'
----------Building project:[ open62541 - Release ]----------
[  1%] Built target open62541-generator-transport
[  3%] Built target open62541-generator-types
[  5%] Built target open62541-generator-statuscode
[  7%] Built target open62541-generator-namespace
[ 28%] Built target open62541-plugins
[ 30%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_server_ns0.c.o
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c: In function 'readMonitoredItems':
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c:556:5: warning: implicit declaration of function 'UA_LOCK'; did you mean 'F_LOCK'? [-Wimplicit-function-declaration]
     UA_LOCK(server->serviceMutex);
     ^~~~~~~
     F_LOCK
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c:556:5: warning: nested extern declaration of 'UA_LOCK' [-Wnested-externs]
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c:556:19: error: 'UA_Server {aka struct UA_Server}' has no member named 'serviceMutex'
     UA_LOCK(server->serviceMutex);
                   ^~
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c:557:27: warning: implicit declaration of function 'UA_Server_getSessionById'; did you mean 'UA_Server_getNodeContext'? [-Wimplicit-function-declaration]
     UA_Session *session = UA_Server_getSessionById(server, sessionId);
                           ^~~~~~~~~~~~~~~~~~~~~~~~
                           UA_Server_getNodeContext
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c:557:27: warning: nested extern declaration of 'UA_Server_getSessionById' [-Wnested-externs]
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c:557:27: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c:559:9: warning: implicit declaration of function 'UA_UNLOCK'; did you mean 'F_ULOCK'? [-Wimplicit-function-declaration]
         UA_UNLOCK(server->serviceMutex);
         ^~~~~~~~~
         F_ULOCK
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c:559:9: warning: nested extern declaration of 'UA_UNLOCK' [-Wnested-externs]
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c:559:25: error: 'UA_Server {aka struct UA_Server}' has no member named 'serviceMutex'
         UA_UNLOCK(server->serviceMutex);
                         ^~
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c:563:25: error: 'UA_Server {aka struct UA_Server}' has no member named 'serviceMutex'
         UA_UNLOCK(server->serviceMutex);
                         ^~
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c:571:25: error: 'UA_Server {aka struct UA_Server}' has no member named 'serviceMutex'
         UA_UNLOCK(server->serviceMutex);
                         ^~
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c:582:25: error: 'UA_Server {aka struct UA_Server}' has no member named 'serviceMutex'
         UA_UNLOCK(server->serviceMutex);
                         ^~
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c:590:25: error: 'UA_Server {aka struct UA_Server}' has no member named 'serviceMutex'
         UA_UNLOCK(server->serviceMutex);
                         ^~
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c:596:25: error: 'UA_Server {aka struct UA_Server}' has no member named 'serviceMutex'
         UA_UNLOCK(server->serviceMutex);
                         ^~
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c:611:21: error: 'UA_Server {aka struct UA_Server}' has no member named 'serviceMutex'
     UA_UNLOCK(server->serviceMutex);
                     ^~
/home/shrubs/Downloads/open62541-1.0.5/src/server/ua_server_ns0.c: At top level:
cc1: warning: unrecognized command line option '-Wno-static-in-inline'
CMakeFiles/open62541-object.dir/build.make:433: recipe for target 'CMakeFiles/open62541-object.dir/src/server/ua_server_ns0.c.o' failed
make[2]: *** [CMakeFiles/open62541-object.dir/src/server/ua_server_ns0.c.o] Error 1
CMakeFiles/Makefile2:262: recipe for target 'CMakeFiles/open62541-object.dir/all' failed
make[1]: *** [CMakeFiles/open62541-object.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
====8 errors, 7 warnings====
`

This is running on Linux Mint

update..
As a sanity check, I tried building 1.0.3 with the same settings/method and that had no issues.. so i think there is an issue there on 1.0.5.

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Solved via https://github.com/open62541/open62541/releases/tag/v1.0.6
