### ISSUE TITLE
set Priority to the publisher messages

### ISSUE THREAD

**Issue by rass92** [open62541/open62541#4106]
Dear Community,

I am using the RT publisher and subscriber connection, and I need to edit the prioritization of the traffic that is been sent by the publisher. I am using the pubsub_TSN_loopback.c and pubsub_TSN_publisher.c.

Where can I edit the priority of the messages sent by the publisher? I understand that have to done at the socket level with the function "setsockopt", but I dont know where to do it. Does somebody have any hint

Thank you in advance

**Comment by johndzilva** [comment]
You can assign the priority the publisher packets here,
https://github.com/open62541/open62541/blob/beeafc02e9f98c52f0dee2364620f5c3527da5db/examples/pubsub_realtime/pubsub_TSN_publisher.c#L534

After doing that you need to map the priority using qdisc command,
https://github.com/open62541/open62541/blob/beeafc02e9f98c52f0dee2364620f5c3527da5db/examples/pubsub_realtime/README_pubsub_TSN.txt#L37

**Comment by rass92** [comment]
Thank you very much Johndzilva !! that is exactly what I need

**Comment by rass92** [comment]
Johndzilva I came with another question this Priority can be put use if the config->pubsubTransportLayers[1]=UA_PubSubTransportLayerUDPMP();

**Comment by johndzilva** [comment]
@rass92 no it is not possible to do with UA_PubSubTransportLayerUDPMP();.
Linux socket option SO_PRIORITY is used to set the socket priority.

**Comment by rass92** [comment]
But do you know in which file is the socket of the Pub/Sub communication created so I can set the SO_PRIORITY?

**Comment by johndzilva** [comment]
@rass92 
https://github.com/open62541/open62541/blob/e5eba7bd591642281717be9edbcd0b6d2ba0fe0b/plugins/ua_pubsub_ethernet.c#L324

**Comment by rass92** [comment]
Dear johndzilva

thank you for your answer, another way give a priority to the package is with iptables.

The command is like this

```
iptables -t mangle -A POSTROUTING -p udp --dport 4010 -j CLASSIFY --set-class 0:4
```
Where the outgoing UDP packages that have destination port 4010 will have a priority 4.
