### ISSUE TITLE
Cygwin build fails due to missing 'TCP_NODELAY'

### ISSUE THREAD

**Issue by cmbahadir** [open62541/open62541#4109]
## Description

First let me point out that, i am not sure if Windows build with Cygwin64 (msys2) is officially supported or has a high priority to maintain. But, when I try to build Open62541 with Cygwin64 (version 3.1.7-1) on Windows, i got an error stating that 'TCP_NODELAY' has not declared.

## Background Information / Reproduction Steps

![image](https://user-images.githubusercontent.com/8937774/103761309-8168ae80-5027-11eb-92ab-950227ce521b.png)

This is probably because of the removed TCP macros from cygwin in;
https://cygwin.com/git/?p=newlib-cygwin.git;a=commit;h=e037192b505b4f233fca9a6deafc9797210f6693

Adding;
```
# if defined(__CYGWIN__)
#  include <netinet/tcp.h>
# endif
```

to `arch/network_tcp.c` made it build successfully, but i am not sure if that is the best place to add `netinet/tcp.h` header.

Used CMake options:

BUILD_SHARED_LIBS:BOOL=OFF
CLANG_FORMAT_EXE:FILEPATH=CLANG_FORMAT_EXE-NOTFOUND
CMAKE_BUILD_TYPE:STRING=Debug
CMAKE_INSTALL_PREFIX:PATH=/usr/local
**UA_ARCHITECTURE:STRING=posix**
UA_BUILD_EXAMPLES:BOOL=OFF
UA_BUILD_TOOLS:BOOL=OFF
UA_BUILD_UNIT_TESTS:BOOL=OFF
UA_ENABLE_AMALGAMATION:BOOL=OFF
UA_ENABLE_DA:BOOL=ON
UA_ENABLE_DISCOVERY:BOOL=OFF
UA_ENABLE_DISCOVERY_MULTICAST:BOOL=OFF
UA_ENABLE_ENCRYPTION:BOOL=OFF
UA_ENABLE_ENCRYPTION_MBEDTLS:BOOL=OFF
UA_ENABLE_ENCRYPTION_OPENSSL:BOOL=OFF
UA_ENABLE_HISTORIZING:BOOL=OFF
UA_ENABLE_METHODCALLS:BOOL=ON
UA_ENABLE_MICRO_EMB_DEV_PROFILE:BOOL=OFF
UA_ENABLE_NODEMANAGEMENT:BOOL=ON
UA_ENABLE_PARSING:BOOL=ON
UA_ENABLE_SUBSCRIPTIONS:BOOL=ON
UA_ENABLE_SUBSCRIPTIONS_ALARMS_CONDITIONS:BOOL=OFF
UA_ENABLE_SUBSCRIPTIONS_EVENTS:BOOL=OFF
UA_ENABLE_WEBSOCKET_SERVER:BOOL=OFF
UA_LOGLEVEL:STRING=300
UA_MULTITHREADING:STRING=0
UA_NAMESPACE_ZERO:STRING=REDUCED

## Checklist

 - [X ] open62541 Version (release number or git tag): v1.2-rc2 - master - 78a6721bcbf932f74446d023370ab203cd48c093
 - [X ] Operating system: Windows 10 - OS Build 17134.1902

**Comment by jpfr** [comment]
Fixed in #4110.
It seems previous versions of Cygwin required a workaround that no longer applies.
