### ISSUE TITLE
Add Timestamps to Node/Variable failled/false Data

### ISSUE THREAD

**Issue by EvgKlin** [open62541/open62541#4129]
## Description
I use Function (UA_Client_addVariableNode) to add Datatimes, but i get false times on my Server. See my Code. Can you please help me
## Background Information / Reproduction Steps

void fn_addTimestampVariable(UA_Client* client, int iDay, int iHour, int iMin, int iMonth, int iYear, int iSec) {
	/* Define the attribute of the myInteger variable node */
	UA_VariableAttributes attr = UA_VariableAttributes_default;
	UA_DateTimeStruct Timestamp;
	Timestamp.day = iDay;
	Timestamp.hour = iHour;
	Timestamp.min = iMin;
	Timestamp.month = iMonth;
	Timestamp.year = iYear;
	Timestamp.sec = iSec;
	char* Groupname = "Example";
	
	UA_Variant_setScalar(&attr.value, &Timestamp, &UA_TYPES[UA_TYPES_DATETIME]);
	attr.description = UA_LOCALIZEDTEXT("en-US", Groupname);
	attr.displayName = UA_LOCALIZEDTEXT("en-US", Groupname);
	attr.dataType = UA_TYPES[UA_TYPES_DATETIME].typeId;
	attr.accessLevel = UA_ACCESSLEVELMASK_READ | UA_ACCESSLEVELMASK_WRITE;

	UA_NodeId myDoubleNodeId = UA_NODEID_STRING(3, Groupname);
	UA_QualifiedName myDoubleName = UA_QUALIFIEDNAME(3, Groupname);
	UA_NodeId parentNodeId = UA_NODEID_NUMERIC(0, UA_NS0ID_OBJECTSFOLDER);
	UA_NodeId parentReferenceNodeId = UA_NODEID_NUMERIC(0, UA_NS0ID_ORGANIZES);
	UA_StatusCode retval= UA_Client_addVariableNode(
		client, myDoubleNodeId, parentNodeId, parentReferenceNodeId, myDoubleName,
		UA_NODEID_NUMERIC(0, UA_NS0ID_BASEDATAVARIABLETYPE), attr, NULL);
	UA_LOG_INFO(UA_Log_Stdout, UA_LOGCATEGORY_USERLAND,
		"Setting the Value Rank failed with Status Code %s",
		UA_StatusCode_name(retval));

}

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): last version
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Linux, Debian
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [x] Self-contained code example attached
 - [ ] Critical issue

**Comment by MichaelKlin** [comment]
@jpfr Maybe can you help
