### ISSUE TITLE
Node with Namespace >= 2 is unable to add ?

### ISSUE THREAD

**Issue by chuongvhn** [open62541/open62541#4155]
## Description
Adding Node with NS >= 2, e.g NS =3, causes error "Namespace invalid"
## Background Information / Reproduction Steps
A server is always initialized with namespace size = 2 (for NS 0,1) 
https://github.com/open62541/open62541/blob/c95fe0f2e0f0433763a23c01958fbdb876e84250/src/server/ua_server.c#L293

Then when trying to add a node with NS >=2 , e.g NS3 cause error:
https://github.com/open62541/open62541/blob/c95fe0f2e0f0433763a23c01958fbdb876e84250/src/server/ua_services_nodemanagement.c#L975

So is there a way to configure max namespace size other than 2 ?

**Comment by mlang-de** [comment]
May you need to add/create the namespace with UA_Server_addNamespace before adding new nodes?

**Comment by chuongvhn** [comment]
Thank you !
