### ISSUE TITLE
how to limit the clients number connected to my opc server (stm32)

### ISSUE THREAD

**Issue by mohamedalielghoula** [open62541/open62541#4177]
hello all
@cochicde @jpfr 
I am using my stm32 as opc server, to avoid the crashes i need to limit the number of clients connexion to my opc server,
there is a function to define this number ?

**Comment by mlang-de** [comment]
See https://open62541.org/doc/1.1/server.html#server-configuration, search for maxSessions.
As well as search for maxSecureChannels.
For instance the shall support 5 Sessions, imho the configuration looks like
maxSessions = 5;
maxSecureChannels = 6;

The 6. SecureChannel is required that the server can response to the Client "BadTooMuchSesions".

**Comment by mohamedalielghoula** [comment]
thanks @mlang-de 
it's work now
