### ISSUE TITLE
Is Micro Embedded Device Server implemented

### ISSUE THREAD

**Issue by EvgKlin** [open62541/open62541#4224]
## Description
I read that, open62541 implements Micro Embedded Device Server, but i can not found example for the Server und which ist difference between Micro Embedded Device Server and normal Server 
## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 1.2.1
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Windows, Linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by mlang-de** [comment]
The open62541 v1.1 was certified against OPC UA Spec. 1.03 in 2019 (at this time the OPCF Complaince Test Tool(CTT) did not support UA 1.04) see for this https://opcfoundation.org/products/view/open62541-server-sdk.
The current master is on the way to meets the requirements from the Embedded Server 2017 Profile.
