### ISSUE TITLE
How can my OPC client connect to the server with X509 certificate authentication

### ISSUE THREAD

**Issue by zhiliangxiaoying** [open62541/open62541#4232]
such as uaexpert
I can see three ways to connect server(prosys)
1，anonymous
2，username
3，certificate
but i read open62541 ，no certificate authentication examples were found;
So how can my OPC client connect to the server with X509 certificate authentication
thank u

**Comment by zhiliangxiaoying** [comment]
![图片](https://user-images.githubusercontent.com/30211331/110344931-fe84c400-8068-11eb-9b71-542ce3c72660.png)

![图片](https://user-images.githubusercontent.com/30211331/110344840-e1e88c00-8068-11eb-915d-6dd9f3c70d65.png)

**Comment by juangburgos** [comment]
Take a look at [this PR](https://github.com/open62541/open62541/pull/3969)

**Comment by MartinMajewski** [comment]
> such as uaexpert
> I can see three ways to connect server(prosys)
> 1，anonymous
> 2，username
> 3，certificate
> but i read open62541 ，no certificate authentication examples were found;
> So how can my OPC client connect to the server with X509 certificate authentication
> thank u

Would you mind pointing me to the section in the docs where those connection options are described? I'm missing something for sure as I am new to it, but I think the "clients" section should have a paragraph mentioning 3rd party clients.

**Comment by NoelGraf** [comment]
You can find basic information in the documentation under Protocol/Establishing a Connection. More detailed information can also be found in the OPC UA documentation of the OPC foundation.

In the examples folder you can find some examples on this topic. For encryption (examples/encryption) but also for access control (examples/access_control) (user login).

**Comment by NoelGraf** [comment]
I would close the issue for now. Please reopen if required!

**Comment by zhiliangxiaoying** [comment]
> 
> 
> You can find basic information in the documentation under Protocol/Establishing a Connection. More detailed information can also be found in the OPC UA documentation of the OPC foundation.
> 
> In the examples folder you can find some examples on this topic. For encryption (examples/encryption) but also for access control (examples/access_control) (user login).

I've already read it；In the examples folder，just have username authentication and Certificate of encryption；
It's not about Certificate authentication；uaexpert have this function;
I dont know i should how to deal with it;

**Comment by zhiliangxiaoying** [comment]
> 
> 
> > You can find basic information in the documentation under Protocol/Establishing a Connection. More detailed information can also be found in the OPC UA documentation of the OPC foundation.
> > In the examples folder you can find some examples on this topic. For encryption (examples/encryption) but also for access control (examples/access_control) (user login).
> 
> I've already read it；In the examples folder，just have username authentication and Certificate of encryption；
> It's not about Certificate authentication；uaexpert have this function;
> I dont know i should how to deal with it;

I can set up an OPCUA Server with certificate authentication function through OPC UA Simulation Server
