### ISSUE TITLE
How to get element index when use DataSource reading array?

### ISSUE THREAD

**Issue by jixian79** [open62541/open62541#4245]
If I create a variable node with bool array datatype, and i use datasrouce to read the data from a modbus device to the array. When i change one of the elements of the array ,  how can i get the element index from the datasource callback function?   is there any way to only write the changed value to the physical device?

in the datasource function signature, the parameter related with the variable is  `UA_DataValue* data `， but it seems have no information about the index.

Please provide the following information:

 - [x] open62541 Version (release number or git tag): v1.2
 - [x] Other OPC UA SDKs used (client or server): UaExpert
 - [x] Operating system:Windows

**Comment by jpfr** [comment]
See here: https://open62541.org/doc/current/nodestore.html#variablenode

The DataSource callback contains the NumericRange attribute.

**Comment by jixian79** [comment]
> See here: https://open62541.org/doc/current/nodestore.html#variablenode
> 
> The DataSource callback contains the NumericRange attribute.


![image](https://user-images.githubusercontent.com/26180524/112452712-de0b7800-8d91-11eb-8273-831c302d2422.png)

But actually, the NumericRange is empty while running the write callback。

![image](https://user-images.githubusercontent.com/26180524/112453331-8cafb880-8d92-11eb-8b8c-2a7a2b1ca1d6.png)

I Use the UaExpert change the 9th bool。In debug mode, the NumericRange is a null pointer.

**Comment by jixian79** [comment]
> See here: https://open62541.org/doc/current/nodestore.html#variablenode
> 
> The DataSource callback contains the NumericRange attribute.


![image](https://user-images.githubusercontent.com/26180524/112452712-de0b7800-8d91-11eb-8273-831c302d2422.png)

But actually, the NumericRange is empty while running the write callback。

![image](https://user-images.githubusercontent.com/26180524/112453331-8cafb880-8d92-11eb-8b8c-2a7a2b1ca1d6.png)

I Use the UaExpert change the 9th bool。In debug mode, the NumericRange is a null pointer.

**Comment by jixian79** [comment]
> See here: https://open62541.org/doc/current/nodestore.html#variablenode
> 
> The DataSource callback contains the NumericRange attribute.


![image](https://user-images.githubusercontent.com/26180524/112452712-de0b7800-8d91-11eb-8273-831c302d2422.png)

But actually, the NumericRange is empty while running the write callback。

![image](https://user-images.githubusercontent.com/26180524/112453331-8cafb880-8d92-11eb-8b8c-2a7a2b1ca1d6.png)

I Use the UaExpert change the 9th bool。In debug mode, the NumericRange is a null pointer.

So how can i get the index information from the write callback ?

**Comment by jixian79** [comment]
> See here: https://open62541.org/doc/current/nodestore.html#variablenode
> 
> The DataSource callback contains the NumericRange attribute.


![image](https://user-images.githubusercontent.com/26180524/112452712-de0b7800-8d91-11eb-8273-831c302d2422.png)

But actually, the NumericRange is empty while running the write callback。

![image](https://user-images.githubusercontent.com/26180524/112453331-8cafb880-8d92-11eb-8b8c-2a7a2b1ca1d6.png)

I Use the UaExpert change the 9th bool。In debug mode, the NumericRange is a null pointer.

So how can i get the index information from the write callback ?

**Comment by jixian79** [comment]
> See here: https://open62541.org/doc/current/nodestore.html#variablenode
> 
> The DataSource callback contains the NumericRange attribute.


![image](https://user-images.githubusercontent.com/26180524/112452712-de0b7800-8d91-11eb-8273-831c302d2422.png)

But actually, the NumericRange is empty while running the write callback。

![image](https://user-images.githubusercontent.com/26180524/112453331-8cafb880-8d92-11eb-8b8c-2a7a2b1ca1d6.png)

I Use the UaExpert change the 9th bool。In debug mode, the NumericRange is a null pointer.

So how can i get the index information from the write callback ?

**Comment by jixian79** [comment]
> See here: https://open62541.org/doc/current/nodestore.html#variablenode
> 
> The DataSource callback contains the NumericRange attribute.


![image](https://user-images.githubusercontent.com/26180524/112452712-de0b7800-8d91-11eb-8273-831c302d2422.png)

But actually, the NumericRange is empty while running the write callback。

![image](https://user-images.githubusercontent.com/26180524/112453331-8cafb880-8d92-11eb-8b8c-2a7a2b1ca1d6.png)

I Use the UaExpert change the 9th bool。In debug mode, the NumericRange is a null pointer.

So how can i get the index information from the write callback ?

**Comment by jixian79** [comment]
> See here: https://open62541.org/doc/current/nodestore.html#variablenode
> 
> The DataSource callback contains the NumericRange attribute.


![image](https://user-images.githubusercontent.com/26180524/112452712-de0b7800-8d91-11eb-8273-831c302d2422.png)

But actually, the NumericRange is empty while running the write callback。

![image](https://user-images.githubusercontent.com/26180524/112453331-8cafb880-8d92-11eb-8b8c-2a7a2b1ca1d6.png)

I Use the UaExpert change the 9th bool。In debug mode, the NumericRange is a null pointer.

So how can i get the index information from the write callback ?

**Comment by jixian79** [comment]
> See here: https://open62541.org/doc/current/nodestore.html#variablenode
> 
> The DataSource callback contains the NumericRange attribute.


![image](https://user-images.githubusercontent.com/26180524/112452712-de0b7800-8d91-11eb-8273-831c302d2422.png)

But actually, the NumericRange is empty while running the write callback。

![image](https://user-images.githubusercontent.com/26180524/112453331-8cafb880-8d92-11eb-8b8c-2a7a2b1ca1d6.png)

I Use the UaExpert change the 9th bool。In debug mode, the NumericRange is a null pointer.

So how can i get the index information from the write callback ?

**Comment by jixian79** [comment]
> See here: https://open62541.org/doc/current/nodestore.html#variablenode
> 
> The DataSource callback contains the NumericRange attribute.


![image](https://user-images.githubusercontent.com/26180524/112452712-de0b7800-8d91-11eb-8273-831c302d2422.png)

But actually, the NumericRange is empty while running the write callback。

![image](https://user-images.githubusercontent.com/26180524/112453331-8cafb880-8d92-11eb-8b8c-2a7a2b1ca1d6.png)

I Use the UaExpert change the 9th bool。In debug mode, the NumericRange is a null pointer.

So how can i get the index information from the write callback ?

**Comment by mlang-de** [comment]
The client has to send the NumericRange. I guess the UaExpert does not support writing with ranges.
May check it with Wireshark.

**Comment by jixian79** [comment]
thank you very much

**Comment by NoelGraf** [comment]
Has your question been clarified? Can the issue be closed?
