### ISSUE TITLE
Bug: UA_MULTITHREADING=199 breaks the build

### ISSUE THREAD

**Issue by rexsum** [open62541/open62541#4270]
## Description

Using multi-threading (i.e. CMAKE flag UA_MULTITHREADING=199) breaks the build on the master branch. This bug was introduced in commit fa5ed7a4ef1af4e088fb44b96b33c7895d0f6a1a.

## Background Information / Reproduction Steps

Use CMAKE flag UA_MULTITHREADING=199 and attempt to build

Used CMake options:

```bash
cmake -DUA_MULTITHREADING=199 ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): fa5ed7a4ef1af4e088fb44b96b33c7895d0f6a1a
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [x] Critical issue

**Comment by jpfr** [comment]
Fixed via #4273.
