### ISSUE TITLE
PubSub Ethernet packet type wrong in v1.2

### ISSUE THREAD

**Issue by rexsum** [open62541/open62541#4271]
## Description

The change to fix the Ethernet header to contain a packet type of 0xb62c that was pushed in commit bc159a0 on Feb. 12th is missing in v1.2. The header contains type LLC which does not conform to the OPC UA Foundation standard spec, Part 14, section 7.3.3, https://reference.opcfoundation.org/v104/Core/docs/Part14/7.3.3/.

## Background Information / Reproduction Steps

Examine PubSub traffic in WireShark to see that the Ethernet packet type is LLC and not 0xb62c.

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): v1.2
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [x] Critical issue

**Comment by jpfr** [comment]
Fixed via #4331
