### ISSUE TITLE
need more documentation for functions

### ISSUE THREAD

**Issue by HolgerJeromin** [open62541/open62541#429]
For example all public ua_client functions needs a doxygen comment...
especially these from the examples.

I still have no idea which is the correct way to free a 
`UA_STRING 	foo = UA_String_fromChars("bar");`

This code crashes:
`UA_String_delete(&foo);`

relates to #332

**Comment by Stasik0** [comment]
This is simple

*_delete methods free content of the struct + struct
*_deleteMembers methods free content of the struct only

Since the string struct itself is in the stack - take deleteMembers.

**Comment by HolgerJeromin** [comment]
Thanks. Should go at least in an comment.

**Comment by jpfr** [comment]
The documentation needs a serious upgrade.
Our codebase is nice but completely unusable without.

Handling types is described here: http://open62541.org/doc/sphinx/datatypes.html

**Comment by HolgerJeromin** [comment]
I will try to add some comments in the client code I understand.

**Comment by tpiat** [comment]
```
UA_STRING foo = UA_String_fromChars("bar");
UA_String_delete(&foo);
```
In c++ gives memory leak if not crashed.

**Comment by Stasik0** [comment]
_delete tries to free the pointer itself which is on the stack, try _deleteMembers, it frees only content, no pointer itself

**Comment by HolgerJeromin** [comment]
Do we want a huge amount of repeated comment like
```
/* free content of the struct and the struct itself */
void UA_EXPORT UA_Float_delete(UA_Float *p);
/* free content of the struct only */
static UA_INLINE void UA_Float_deleteMembers(UA_Float *p) { }
```
for all datatypes? I added this in in all the C files and in the python script. 
Is this useful for help in the IDE or is this not wanted?
