### ISSUE TITLE
Incomplete type error for 'UA_PubSubConfiguration' in amalgamated open62541.h 

### ISSUE THREAD

**Issue by cmbahadir** [open62541/open62541#4302]
## Description

Incomplete type error has been raised when the amalgamated open62541.c and open62541.h are used in "FreeRTOSLWIP". Below CMake options were used while creating the amalgamated files.

## Background Information / Reproduction Steps

1. Build open62541 to create amalgamated files with the options below.
2. Use the open62541.c and open62541.h files to compile a publisher app on ESP32 using (xtensa toolchain).

It seems that the `UA_PubSubConfiguration`(Line: ~29602) has to be defined before it is used in 'UA_ServerConfig'(Line: ~27849). When it's definition is moved before `UA_ServerConfig` it compiles with success.

[open62541_h.txt](https://github.com/open62541/open62541/files/6254236/open62541_h.txt)

## Result

```
../components/open62541lib/include/open62541.h:27849:28: error: field 'pubSubConfig' has incomplete type
     UA_PubSubConfiguration pubSubConfig;
```

Used CMake options:

```
BUILD_SHARED_LIBS:BOOL=OFF
CLANG_FORMAT_EXE:FILEPATH=/usr/bin/clang-format
CMAKE_BUILD_TYPE:STRING=Debug
CMAKE_INSTALL_PREFIX:PATH=/usr/local
MBEDCRYPTO_LIBRARY:FILEPATH=MBEDCRYPTO_LIBRARY-NOTFOUND
MBEDTLS_INCLUDE_DIRS:PATH=MBEDTLS_INCLUDE_DIRS-NOTFOUND
MBEDTLS_LIBRARY:FILEPATH=MBEDTLS_LIBRARY-NOTFOUND
MBEDX509_LIBRARY:FILEPATH=MBEDX509_LIBRARY-NOTFOUND
MDNSD_LOGLEVEL:STRING=300
UA_ARCHITECTURE:STRING=freertosLWIP
UA_ARCH_FREERTOS_USE_OWN_MEMORY_FUNCTIONS:BOOL=OFF
UA_BUILD_EXAMPLES:BOOL=OFF
UA_BUILD_TOOLS:BOOL=OFF
UA_BUILD_UNIT_TESTS:BOOL=OFF
UA_ENABLE_AMALGAMATION:BOOL=ON
UA_ENABLE_DA:BOOL=ON
UA_ENABLE_DISCOVERY:BOOL=ON
UA_ENABLE_DISCOVERY_MULTICAST:BOOL=ON
UA_ENABLE_ENCRYPTION:BOOL=ON
UA_ENABLE_ENCRYPTION_MBEDTLS:BOOL=OFF
UA_ENABLE_ENCRYPTION_OPENSSL:BOOL=ON
UA_ENABLE_HISTORIZING:BOOL=OFF
UA_ENABLE_METHODCALLS:BOOL=ON
UA_ENABLE_MICRO_EMB_DEV_PROFILE:BOOL=OFF
UA_ENABLE_NODEMANAGEMENT:BOOL=ON
UA_ENABLE_PARSING:BOOL=ON
UA_ENABLE_SUBSCRIPTIONS:BOOL=ON
UA_ENABLE_SUBSCRIPTIONS_ALARMS_CONDITIONS:BOOL=OFF
UA_ENABLE_SUBSCRIPTIONS_EVENTS:BOOL=OFF
UA_ENABLE_WEBSOCKET_SERVER:BOOL=OFF
UA_LOGLEVEL:STRING=100
UA_MULTITHREADING:STRING=0
UA_NAMESPACE_ZERO:STRING=REDUCED
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): v1.2-168-g7bd79f10
 - [ ] Other OPC UA SDKs used (client or server):  No
 - [x] Operating system: Linux Mint 20.1
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Fixed and added a CI build in #4305.
