### ISSUE TITLE
In PubSub Ethernet, unicast frames would not be received due to bad filtering.

### ISSUE THREAD

**Issue by MurzynJ** [open62541/open62541#4325]
## Description
In PubSub Ethernet plugin preliminary filtering of incoming frames is done using the address of PubSubConnection.
Currently the unicast frames are dropped because the destination address doesn't match the configured PubSubConnection's address.

Logic has to be different in case of multicast or unicast PubSubConnections. In case of multicast, the connection's address has to match the frame's destination. In case of unicast, the connection's address has to match the frame's source. Behavior in case of multicast vs. unicast is not clearly specified in the current version of Part14, but that's the only logical way to interpret the address field of PubSubConnection. This point is known to specification authors and it will be clarified in the future releases of the spec.

Used CMake options:
UA_ENABLE_PUBSUB
UA_ENABLE_PUBSUB_ETH_UADP

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag): afb74a26f98ef63b17175085fda79763db939c0e
 - [ ] Operating system: any

**Comment by jpfr** [comment]
We had to revert the PR.
See #4409. Feel free to propose a solution.
