### ISSUE TITLE
server_nodeset_powerlink failled

### ISSUE THREAD

**Issue by EvgKlin** [open62541/open62541#4337]
## Description
Example server_nodeset_powerlink failled at  `UA_StatusCode retval = namespace_di_generated(server);` 
server_nodeset_plcopen is not working too. 
server_nodeset works well
## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 1.2.1
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Windows
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Right.
It seems the generated value-variant contains an array but does not have ArrayDimensions.
But the ArrayDimensions are expected to be present in the value if they are defined for the Variable. We will fix this.

**Comment by EvgKlin** [comment]
Thank you

**Comment by EvgKlin** [comment]
Is there other possibility to see nodes and information model? or can i export this xml to UaModeler

**Comment by jpfr** [comment]
You can directly import the XML in UAModeler.
Its a standard format.

**Comment by EvgKlin** [comment]
Small question, view nodes are not implemented or?
