### ISSUE TITLE
PubSub UADP encoding: key frame and delta frame

### ISSUE THREAD

**Issue by matkonnerth** [open62541/open62541#4347]
Hi, I've some questions regarding delta frame:

Are the supported in combination with the fastPath implementation?

Regarding recovery from lost key frames:

**Example without delta frames**

0: keyframe
1: keyframe
2: keyframe (is lost)
3: keyframe (subscriber has again a valid dataset)
4: keyframe

**Example with delta frame**

0: keyframe
1: delta
2: keyframe (is lost)
3: delta (Can the subscriber recover to a valid dataset because keyframe 0, delta 1 and delta 3 are considered?)
4: keyframe (Or is this the next valid dataset?)

**Comment by jpfr** [comment]
The fast path supports only key frames at this time.

Your second example depends on which fields have changed.
You can reconstruct something in theory. But the values could be outdated.
