### ISSUE TITLE
HasInterface reference on base type

### ISSUE THREAD

**Issue by basyskom-jvoe** [open62541/open62541#4363]
The mandatory child nodes of an Interface type only show up on the resulting object if the HasInterface reference is directly attached to the object type that is being instantiated.

If the HasInterface reference is on the base type of the object type that is being instantiated, the properties are missing from the resulting object.

Is there already a function in object node instantiation which traverses the subtype tree where the interface instantiation could be hooked into?

Please provide the following information:

[X ] open62541 Version (release number or git tag): v1.2.1

**Comment by basyskom-meerkoetter** [comment]
This issues is currently being worked on.
