### ISSUE TITLE
Write unit tests for Attributes and NodeManagement service sets

### ISSUE THREAD

**Issue by jpfr** [open62541/open62541#445]
We do not sufficiently cover those two service sets.
Regressions still crop up from time to time.

**Comment by martinhomuth** [comment]
These are already available, right? At least the Attributes service test seems to be quite large.

**Comment by Pro** [comment]
@martinhomuth if you are interested in adding some unit tests you can also check coveralls (https://coveralls.io/github/open62541/open62541) and see which lines are not yet covered.

**Comment by Pro** [comment]
The unit tests are already implemented, so closing this issue
