### ISSUE TITLE
Can I use only Libary/.so

### ISSUE THREAD

**Issue by Micha20** [open62541/open62541#4450]
## Description
I build with CMake on Windows the Library. In Project configuration/c++-> Dependencies i see
open62541\
\examples
\arch
\src
\deps
\build\sr_generated
can i use only Lib and headers without that 

## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Yes. An "amalgamated build" (set in the cmake flags) will result in a single open62541.c/.h pair you can drop into your project.

**Comment by Micha20** [comment]
ok, there are no other possibilities to build lib

**Comment by EvgKlin** [comment]
use visual studuio Project to build lib or use this https://github.com/open62541/open62541/releases

**Comment by jpfr** [comment]
Sure. The default is to build a static lib.
You can build a dll by activating the shared_lib flag in cmake.

**Comment by jpfr** [comment]
Seems to be solved.
Just reopen if required.
