### ISSUE TITLE
Encoding of empty array of ExtensionObject

### ISSUE THREAD

**Issue by Stasik0** [open62541/open62541#4462]
- [x ] open62541 Version (release number or git tag): 1.2

Dear community,

just one generic question. In the method callback I need to return an empty array of extension objects.

I use the following code
`UA_Variant_setArray(&(output[0]), NULL, 0, &UA_TYPES[UA_TYPES_EXTENSIONOBJECT]); `

however wireshark shows "-1" as transmitted array length.

![image](https://user-images.githubusercontent.com/469170/121259532-8a003200-c8b0-11eb-9c3c-695269067b5c.png)

In case 0 length is invalid, is it something I missed in the spec? In case it is valid - how do I set it from the API?

**Comment by jpfr** [comment]
We use size_t, an unsigned integer to track array sizes internally.

- length 0, NULL pointer -> -1 array
- length 0, UA_EMPTY_ARRAY_SENTINEL pointer -> 0 array

You can use UA_Array_new to generate an array of length 0.
That automatically gives a UA_EMPTY_ARRAY_SENTINEL pointer.

**Comment by Stasik0** [comment]
Thanks! But is -1 a valid value „on wire“?

**Comment by jpfr** [comment]
Yes. On the wire.
But we use an unsigned size_t for array sizes internally.

Reopen if necessary.
