### ISSUE TITLE
Can a server be notified about remote creation of objects/nodes?

### ISSUE THREAD

**Issue by tboeckel** [open62541/open62541#4469]
I have a server which allows objects and nodes on the server side to be created by a remote client via UA_Client_addVariableNode() and UA_Client_addObjectNode(). This works perfectly. Also removing the created stuff again works as expected.

But now my server application needs to know that a new object/node has been created by the remote client. So far I have found no way how to detect this modification or how to be notified about the modification.

Is this possible at all? If yes, how? If no, can this be implemented?

 - [X] open62541 Version (release number or git tag): 1.2.2
 - [ ] Other OPC UA SDKs used (client or server): 
 - [X] Operating system: Linux, various distributions
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by undroidwish** [comment]
Maybe my little topcua (Tcl binding to open62541 in https://www.androwish.org/home/dir?ci=tip&name=jni/topcua)
gives some inspiration. It boils down to observe object lifecycles using appropriate callbacks in the server config, here's the snippet:

        serverConfig = UA_Server_getConfig(theServer);
        serverConfig->nodeLifecycle.constructor = NodeConstructor; /* your callback function */
        serverConfig->nodeLifecycle.destructor = NodeDestructor; /* your callback function */

**Comment by tboeckel** [comment]
Many thanks! That was exactly what I was looking for!
