### ISSUE TITLE
missing member in structure 

### ISSUE THREAD

**Issue by jackybek** [open62541/open62541#4536]
## Description
Please fix the following errors relating to invalid fields in structures.

## Background Information / Reproduction Steps

[ 65%] Building C object CMakeFiles/open62541-object.dir/open62541.c.o
/home/pi/open62541/build/open62541.c: In function ‘UA_PubSubChannelMQTT_regist’:
/home/pi/open62541/build/open62541.c:215072:57: error: ‘UA_DataType’ {aka ‘const struct UA_DataType’} has no member named ‘typeIndex’; did you mean ‘typeId’?
             && transportSettings->content.decoded.type->typeIndex == UA_TYPES_BROKERDATASETREADERTRANSPORTDATATYPE){
                                                         ^~~~~~~~~
                                                         typeId
/home/pi/open62541/build/open62541.c: In function ‘UA_PubSubChannelMQTT_unregist’:
/home/pi/open62541/build/open62541.c:215100:57: error: ‘UA_DataType’ {aka ‘const struct UA_DataType’} has no member named ‘typeIndex’; did you mean ‘typeId’?
             && transportSettings->content.decoded.type->typeIndex == UA_TYPES_BROKERWRITERGROUPTRANSPORTDATATYPE){
                                                         ^~~~~~~~~
                                                         typeId
/home/pi/open62541/build/open62541.c: In function ‘UA_PubSubChannelMQTT_send’:
/home/pi/open62541/build/open62541.c:215128:57: error: ‘UA_DataType’ {aka ‘const struct UA_DataType’} has no member named ‘typeIndex’; did you mean ‘typeId’?
             && transportSettings->content.decoded.type->typeIndex == UA_TYPES_BROKERWRITERGROUPTRANSPORTDATATYPE){
                                                         ^~~~~~~~~
                                                         typeId
/home/pi/open62541/build/open62541.c: In function ‘ServerNetworkLayerWS_start’:
/home/pi/open62541/build/open62541.c:217118:9: error: ‘struct lws_context_creation_info’ has no member named ‘ws_ping_pong_interval’
     info.ws_ping_pong_interval = 10;

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [ X] open62541 Version (release number or git tag): v1.2.2-357-g2238f4fb
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system: raspbian
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [X ] Critical issue

**Comment by jpfr** [comment]
Fixed via #4537.
