### ISSUE TITLE
Update the value of a variable node in object node

### ISSUE THREAD

**Issue by Maku-chan** [open62541/open62541#4555]
## Description
I want to ask that is it possible to update the variables in an object node from the server and how can I do that.

**Comment by mlang-de** [comment]
May the examples
https://github.com/open62541/open62541/blob/master/examples/tutorial_server_variable.c
and
https://github.com/open62541/open62541/blob/master/examples/tutorial_server_datasource.c
help you.

**Comment by Maku-chan** [comment]
Thanks a lot
