### ISSUE TITLE
open62541 Does it support user login communication encryption？

### ISSUE THREAD

**Issue by liutt1312** [open62541/open62541#4567]
Does version 2.0 support encryption when users log in？
Can I use user login with the server software？

## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
There is only version 1.2.
And yes, encryptions is supported.

just reopen if questions remain.
