### ISSUE TITLE
Get node id from the outnewNodeId after successful node creation

### ISSUE THREAD

**Issue by Maku-chan** [open62541/open62541#4568]
## Description
How can I get the node id if I call the function of this class to add nodes from a different file.

The below mentioned class is just an example.

class newdevice {
        public:
             void test() {
  
                       UA_Server_addObjectTypeNode(Internal_server, UA_NODEID_NULL,
			         UA_NODEID_NUMERIC(0, UA_NS0ID_BASEOBJECTTYPE),
			         UA_NODEID_NUMERIC(0, UA_NS0ID_HASSUBTYPE),
			         UA_QUALIFIEDNAME(namespace_id, qualified_name), object_attr,
			         NULL, &deviceNodeType);
             }
}

**Comment by jpfr** [comment]
The outNodeId is set automatically if you provide a pointer to a NodeId to be overwritten.

Given that adding is successful...

**Comment by jpfr** [comment]
Reopen if required.
