### ISSUE TITLE
Check UA_Logger messages through STM32 uart

### ISSUE THREAD

**Issue by Maku-chan** [open62541/open62541#4585]
## Description
I want to ask that how can I send the messages generated by the UA_Logger to Uart so that I can view them in case of embedded boards.

Thanks.

**Comment by johndzilva** [comment]
https://github.com/open62541/open62541/blob/5d7b509d26939065b6e8768c647a53366904b5f9/plugins/ua_log_stdout.c#L51

You can use this function. Inside of this you can work on your UART logic.

**Comment by jpfr** [comment]
You can fork the logger plugin and adjust to your use case. It is licensed as CC0.

**Comment by Maku-chan** [comment]
I tried it but it doesnt work. The header file log_stdout.h contains the following

extern UA_EXPORT const UA_Logger UA_Log_Stdout_; /* Logger structure */
extern UA_EXPORT const UA_Logger *UA_Log_Stdout; /* Shorthand pointer */

/* Don't use these definitions. They are only exported as long as the client
 * config is static and required compile-time  */
UA_EXPORT void
UA_Log_Stdout_log(UA_LogLevel level, UA_LogCategory category,
                  const char *msg);
UA_EXPORT void
UA_Log_Stdout_clear(void *logContext);

The logger attribute of the UA_ServerConfig struct is provided the UA_Log_Stdout_ struct which is then used to display all the logging messages so changing the UA_Log_Stdout_log doesnt change it.

UA_Server *
UA_Server_new() {
    UA_ServerConfig config;
    memset(&config, 0, sizeof(UA_ServerConfig));
    /* Set a default logger and NodeStore for the initialization */
    config.logger = UA_Log_Stdout_;
    if(UA_STATUSCODE_GOOD != UA_Nodestore_HashMap(&config.nodestore)) {
        return NULL;
    }

    return UA_Server_newWithConfig(&config);
}
