### ISSUE TITLE
Linux comple open62541.h/.c error with UA_MULTITHREADING  in masterBranch

### ISSUE THREAD

**Issue by official-minister** [open62541/open62541#4633]
git log : commit f7e679a330fdb0b66b068692c0f5d8a9695a675f
Used CMake options:
addtional cmake option from default:
**UA_ENABLE_AMALGAMATION 
UA_MULTITHREADING 100**
UA_ENABLE_SUBSCRIPTIONS_EVENTS.

I get Error such as:
_Scanning dependencies of target open62541-object
[ 65%] Building C object CMakeFiles/open62541-object.dir/open62541.c.o
In file included from /tmp/wangyichen/open62541/build/open62541.c:28:
/tmp/wangyichen/open62541/build/open62541.h:512:17: error: expected ‘;’ before ‘void’
  512 | static UA_INLINE void
      |                 ^~~~~
      |                 ;
/tmp/wangyichen/open62541/build/open62541.h:513:1: error: no previous prototype for ‘UA_LOCK_INIT’ [-Werror=missing-prototypes]
  513 | UA_LOCK_INIT(UA_Lock *lock) {
      | ^~~~~~~~~~~~
/tmp/wangyichen/open62541/build/open62541.h:520:17: error: expected ‘;’ before ‘void’
  520 | static UA_INLINE void
      |                 ^~~~~
      |                 ;
/tmp/wangyichen/open62541/build/open62541.h:521:1: error: no previous prototype for ‘UA_LOCK_DESTROY’ [-Werror=missing-prototypes]
  521 | UA_LOCK_DESTROY(UA_Lock *lock) {
      | ^~~~~~~~~~~~~~~
/tmp/wangyichen/open62541/build/open62541.h:526:17: error: expected ‘;’ before ‘void’
  526 | static UA_INLINE void
      |                 ^~~~~
      |                 ;
/tmp/wangyichen/open62541/build/open62541.h:527:1: error: no previous prototype for ‘UA_LOCK’ [-Werror=missing-prototypes]
  527 | UA_LOCK(UA_Lock *lock) {_

**But I complie  UA_MULTITHREADING OK whitout UA_ENABLE_AMALGAMATION. And I try to complie on Realsea 1.2.2 and it works well. Will this bug be fixed soon?**

**Comment by kimim** [comment]
I tried to fix this with PR #4674
I'll try to create another PR soon.
