### ISSUE TITLE
Nodestore API not compatible with Nodestore switch

### ISSUE THREAD

**Issue by jonasgreen88** [open62541/open62541#4634]
## Description
The addition of the `getReferenceTypeId()` function pointer in the Nodestore API breaks the possibility to implement a Nodestore switch that switch nodestore requests based on NamespaceIndex to different underlying nodestore implementations (e.g. PR #2748).
https://github.com/open62541/open62541/blob/f7e679a330fdb0b66b068692c0f5d8a9695a675f/include/open62541/plugin/nodestore.h#L990

The Nodestore switch implementation is a convenient solution to allow several nodestores with one server. It can for example be used to allow some nodes being located in RAM, some located in a ROM and some nodes might be generated upon request based of some source of information.

Would it be possible to somehow extend the `getReferenceTypeId()` to allow switching on NamespaceIndex also for this function call?

A possible solution could be to replace the argument `UA_Byte refTypeIndex` with either a `UA_UInt32 refTypeIndex` or a structure with two elements, `UA_UInt16 namespaceIndex` and `UA_Byte refTypeIndex`. 
If relacing with a 32 bit argument the nodestore switch implementation can chose to add a NamespaceIndex in the most significant 16 bits and allow the nodestore implementations registered to a nodestore switch to use the less significant 16 bits for the reference type index. If replacing with a struct it gets more explicit that the namespace index shall be part of the reference type index.

## Background Information / Reproduction Steps

N/A

Used CMake options:

N/A

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag): 1.2
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [x] Critical issue

**Comment by jpfr** [comment]
The idea of the reftypeindex is to use it as the index in a bitfield. Do that an integer can be used to represent sets of reference types.

So no, we cannot split into two parts.

But I see no problem in assigning the index in the “switch” layer itself that has several namespace back ends.

Please reopen if required. We can also address this in the dev call.
