### ISSUE TITLE
Unable to compile ADI nodeset

### ISSUE THREAD

**Issue by apropp-molex** [open62541/open62541#4729]
## Description

The [ADI nodeset](https://github.com/OPCF-Members/UA-Nodeset-1/tree/v1.04/ADI) is unable to be compiled due to a reference having no target. Full details are in the attached [logs.txt](https://github.com/open62541/open62541/files/7442927/logs.txt).

## Background Information / Reproduction Steps

The [CMakeLists.txt](https://github.com/open62541/open62541/files/7442996/CMakeLists.txt) is attached.
The server code is here for reference: [main.c.txt](https://github.com/open62541/open62541/files/7443033/main.c.txt).

`ns=2;i=1002` is a reference to DeviceType in the DI nodeset.
I've tried adding `2:http://opcfoundation.org/UA/DI` to the `NAMESPACE_MAP`, but this doesn't seem to work.

Used CMake options (when compiling open62541):

```bash
cmake -DCMAKE_INSTALL_PREFIX=/home/user/install -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUA_NAMESPACE_ZERO=Full ..
```

## Checklist

Please provide the following information:

 - [X] open62541 Version (release number or git tag): 1.2.2 (commit hash 465e8c473540304dafa21f364472271d77768031)
 - [X] Other OPC UA SDKs used (client or server): None
 - [X] Operating system: Ubuntu 20.04
 - [X] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by NoelGraf** [comment]
The nodeset compiler needs the bsd file for nodesets with their own defined data types. For this, you must specify the bsd file within the CMake function "ua_generate_nodeset_and_datatypes" with IMPORT_BSD.
[CMakeLists.txt](https://github.com/open62541/open62541/files/7487205/CMakeLists.txt)

**Comment by apropp-molex** [comment]
I've tried adding the `IMPORT_BSD` as you recommended and modifying the `NAMESPACE_MAP`. Unfortunately, I still get the same error. I've attached the updated [CMakeLists.txt](https://github.com/open62541/open62541/files/7492962/CMakeLists.txt) file. Do you any other ideas for options that I could be missing? Thanks for your help so far!

**Comment by NoelGraf** [comment]
For the sake of simplicity, I have extended an example in example/nodeset. With this, the ADI Nodeset can be built and executed. The corresponding C-file is also in the examples/nodeset folder.


[CMakeLists.txt](https://github.com/open62541/open62541/files/7526407/CMakeLists.txt)
[server_nodeset_adi.c.txt](https://github.com/open62541/open62541/files/7526413/server_nodeset_adi.c.txt)

To build the example execute the following commands in the build folder:
`cmake -DCMAKE_BUILD_TYPE=Debug -DUA_BUILD_EXAMPLES=ON -DUA_NAMESPACE_ZERO=FULL ..`
`make server_nodeset_adi`
