### ISSUE TITLE
How to compile the new open65421 on qnx6.5

### ISSUE THREAD

**Issue by wangyuan02605** [open62541/open62541#4745]
I cannot cross compile open65421 in the current version or previous versions

I execute $ cmake -DCMAKE_TOOLCHAIN_FILE= ../tools/cmake/Toolchain-QNX-6.5.0.cmake .. -G "Unix Makefiles"

$mak
<img width="989" alt="截屏2021-11-03 下午11 25 48" src="https://user-images.githubusercontent.com/32026655/140090559-544bfc61-cc92-4d5d-bf03-cc99e089cb79.png">
e

**Comment by wangyuan02605** [comment]
add execuate in 1.2.2
<img width="898" alt="截屏2021-11-03 下午11 29 22" src="https://user-images.githubusercontent.com/32026655/140091370-5d254c70-25a8-4350-a893-e0768e648010.png">

**Comment by kimim** [comment]
seems you are still using win32 arch, maybe you need to specify `-DUA_ARCHITECTURE=posix` for `cmake`

**Comment by jpfr** [comment]
Try setting UA_ARCHITECTURE to `posix`.
You get errors for including win32 system APIs. That won't work on QNX.
