### ISSUE TITLE
Compilation error at 32 bit gnu/linux, +++

### ISSUE THREAD

**Issue by fantomsam** [open62541/open62541#4804]
Hi.
The latest release with commit id: "223d3d5d55e6bbc771f9e0d6bfe2af0facc6f395: can not compile in 32 bit gnu/linux system. 
The error:
/open62541/arch/eventloop_posix.c:277:9: error: conversion from ‘long long int’ to ‘long int’ may change value [-Werror=conversion]
         usedTimeout / UA_DATETIME_SEC,
         ^~~~~~~~~~~
is appearing. 
I possible fix is to add some preprocess directive other than "WIN32", that can detect the bit width of the operating system. at line 276 in the file "eventloop_posix.c"

also If I bypass this check in line 276, and compile the library with the examples. I get an warning "No valid FDs for processing" when I run the example server_mainloop.

## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Debian GNU/Linux 10 (buster) i386(32bit)
 - [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [x] Critical issue

**Comment by jpfr** [comment]
The fix for both issues is part of #4808.
Thanks for reporting.
