### ISSUE TITLE
Cannot download zip file

### ISSUE THREAD

**Issue by tpiat** [open62541/open62541#484]
After aeb01903c3 no releases exist.
"Error 40
File not found
The site configured at this address does not contain the requested file."

**Comment by ichrispa** [comment]
Hi @tpiat ,

Which branch are we talking about? In general, github is responsible for that service. If we can reproduce this, I think it merits an issue with the site.

Best regards,

ichrispa

**Comment by tpiat** [comment]
http://open62541.org/releases/

**Comment by Stasik0** [comment]
its an issue with the build script, i am on it

**Comment by Stasik0** [comment]
releases are back up, e.g., http://open62541.org/releases/f597dc1edc.zip
