### ISSUE TITLE
VariableNode valueCallback not used by MonitoredItem

### ISSUE THREAD

**Issue by jpfr** [open62541/open62541#487]
@Stasik0 wanted a callback for attribute reads and writes on variable values.
It is used similar to datasources, but the value is still stored in the node.
But it is not used for monitoreditems.

@ichrispa The change is trivial in `ua_subscription.c:371`.
Can we just go for it?

**Comment by HolgerJeromin** [comment]
direct link:
https://github.com/open62541/open62541/blob/master/src/server/ua_subscription.c#L371

**Comment by jpfr** [comment]
implemented in 19fb205713f9c092e3ec695c970c7bcb76406dec
