### ISSUE TITLE
Nodeset Compiler Issue: Value of a Union.

### ISSUE THREAD

**Issue by MurzynJ** [open62541/open62541#4901]
## Description
The generated code doesn't initialize the value according to the content of the XML.

Test code (including a sample nodeset):
https://github.com/MurzynJ/open62541/tree/NcIssue_UnionValue

Example:
![image](https://user-images.githubusercontent.com/70644594/149770021-891e7921-d7f5-4c1b-8092-a55bd6a067cf.png)
![image](https://user-images.githubusercontent.com/70644594/149770088-e23ac9c4-152a-48a1-8bec-09c4267633dc.png)

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): Latest master: b061554990ab38cd9062212aaa69c322f1415f33
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by MurzynJ** [comment]
This issue is still open, even after the latest commits by @NoelGraf. Value of a Union is not set in the generated code.

![image](https://user-images.githubusercontent.com/70644594/152380414-5e619a2e-65a6-468d-b93a-5e48eb0bf84d.png)

FYI @Fischer-Thomas

**Comment by andreasebner** [comment]
@MurzynJ The issue should be solved, can we close it?

**Comment by MurzynJ** [comment]
Sorry, I haven't had time to check the fix yet. But I trust that it's working. If I find anything in future, I will just create another issue.
