### ISSUE TITLE
Connection breaks in several seconds on ARM

### ISSUE THREAD

**Issue by Wtango** [open62541/open62541#491]
I use uaexpert as client connect to open62541 sample server(ARM cortex A9,little endian),why the connection break in several seconds?But it's fine in x86?

**Comment by Stasik0** [comment]
Can you please record a wireshark trace? https://github.com/open62541/open62541/wiki/Capturing-traffic-with-Wireshark

**Comment by Wtango** [comment]
It seems work well in newset commit.This issue occur in 242a2052071fbdf82ac06ab1fba87af449326b52.
[Uploading open62541_issue#491_Wireshark.pcapng.zip…]()

**Comment by Stasik0** [comment]
Id say, if its fixed already -- no action required.

**Comment by Wtango** [comment]
OK,thanks.
