### ISSUE TITLE
ua_pubsub_udp.c:137:5: error: ‘networkPort’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

### ISSUE THREAD

**Issue by terkaa** [open62541/open62541#4913]
## Description

[ 48%] Linking C executable ../bin/examples/server_pubsub_publisher_iop
/open62541/plugins/ua_pubsub_udp.c: In function ‘UA_PubSubChannelUDPMC_open’:
/open62541/plugins/ua_pubsub_udp.c:137:5: error: ‘networkPort’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  137 |     sprintf(port, "%u", networkPort);
      |     ^
/home/tero/open62541/plugins/ua_pubsub_udp.c:117:15: note: ‘networkPort’ was declared here
  117 |     UA_UInt16 networkPort;
      |               ^
lto1: all warnings being treated as errors
lto-wrapper: fatal error: /usr/bin/cc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [examples/CMakeFiles/pubsub_subscribe_standalone.dir/build.make:89: bin/examples/pubsub_subscribe_standalone] Error 1

## Background Information / Reproduction Steps

1. Get latest code from github
2. Complie examples with pubsub on Ubuntu 20.04

Used CMake options:

cmake -DUA_BUILD_EXAMPLES=ON -DUA_ENABLE_PUBSUB=ON -DUA_ENABLE_PUBSUB_ETH_UADP=ON -DUA_ENABLE_PUBSUB_ENCRYPTION=ON -DUA_ENABLE_ENCRYPTION=MBEDTLS -DUA_ENABLE_ENCRYPTION_TPM2=ON -DUA_ENABLE_AMALGAMATION=OFF

**Comment by jpfr** [comment]
Right.
Fixed via #4917.
