### ISSUE TITLE
/plugin/ua_config_default.c : default server settings cannot be overwritten in own OPCServer code

### ISSUE THREAD

**Issue by jackybek** [open62541/open62541#4914]
## Description
In my own source code, i have the following

        #include "open62541.h"
        #ifndef APPLICATION_URI
              #define APPLICATION_URI "urn:virtualskies.com.sg
        #else
              #undef APPLICATION_URI
              #define APPLICATION_URI "urn:virtualskies.com.sg
        #endif
        #ifndef APPLICATION_URI_SERVER
              #define APPLICATION_URI_SERVER "urn:virtualskies.com.sg
        #else
              #undef APPLICATION_URI_SERVER
              #define APPLICATION_URI_SERVER "urn:virtualskies.com.sg
        #endif
        ....

        UA_ServerConfig_setDefaultWithSecurityPolicies(&config1, 4840,
                                                       &certificate, &privateKey,
                                                       trustList, trustListSize,
                                                       issueList, issueListSize,
                                                       revocationList, revocationListSize);
         ...
         UA_ApplicationDescription_clear(&config1.applicationDescription);
         config1.applicationDescription.applicationUri = UA_STRING_ALLOC(APPLICATION_URI_SERVER)
         config1.serverCertificate = certificate;

When i run my code, the certificate is created successfully.
However when i try to use UAExpert to connect to my server, i get

             Bad Certificate untrusted
             <Under UA Extensions>
             URI : urn.virtualskies.com.sg (highlighted in yellow)
             The tool tip shows : The URI returned in the certificate does not match the ApplicationURI of the server (urn.open62541.server.application)

When i trace where ApplicationURI (urn.open62541.server.application) is defined, I found it in /plugin/ua_config_default.c.
In amalgamated open62541.c (section /plugin/ua_config_default.c), there is a statement

             #define APPLICATION_URI_SERVER "urn:open62541.server.application"

Questions:
1.  How come there is no effect when i try in my own code to #undef and #define APPLICATION_URI_SERVER to replace "urn.open62541.server.application" with "urn:virtualskies.com.sg"
2. I have to resort to changing the original file <open62541.c> from

             #define APPLICATION_URI_SERVER "urn:open62541.server.application" to
             #define APPLICATION_URI_SERVER "urn:virtualskies.com.sg"

3. When changes in step 2 is made and i recompile my code (with the amended open62541.c), the error message in UAExpert then disappears.
4. I don't think performing step 2 is the correct approach. 

Please advise.

## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [ X] open62541 Version (release number or git tag): v1.3 rc1-193-g5bac0225
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ X] Operating system: Ubuntu
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ X] Critical issue

**Comment by jpfr** [comment]
What you see is indeed the correct behavior.
We initialize with a default server config.
If you want to change it, just change it!

Before you run the server, get the config via `UA_Server_getConfig`.
Then edit to your needs.

Another way is to take make a copy of the "plugin" that generates the initial config.

We will have a way to load a textfile-config eventually.
But we are not there yet.
