### ISSUE TITLE
Indexed HTML API documentation

### ISSUE THREAD

**Issue by paddor** [open62541/open62541#4935]
The generated HTML API documentation is partially outdated and combersome when trying to find call signatures. What I'd like is a simple Doxygen generated documentation of all the public functions, enums, structs, and typedefs.

Any pointers? I'm not very familiar with Doxygen, so my local attempts of generating it weren't successful.

**Comment by jpfr** [comment]
Just call `make doc`.
The documentation is generated from the current header files.

we will update the homepage to reflect the master and 1.3 branch…

**Comment by paddor** [comment]
Can you include an index page that lists ALL public functions?
