### ISSUE TITLE
is open62541 compatible with Y2038 under a 32-bit architecture?

### ISSUE THREAD

**Issue by StalderT** [open62541/open62541#4967]
Hello,

open62541 use gettimeofday and clock_gettime :
https://github.com/open62541/open62541/blob/683c4b9e543fd4d12e92ad759c884ff3685a41d1/arch/posix/ua_clock.c#L23
https://github.com/open62541/open62541/blob/683c4b9e543fd4d12e92ad759c884ff3685a41d1/arch/posix/ua_clock.c#L54

These two functions seem not to be Y2038 compliant.

Does anyone have more info on this or an idea?

https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by jpfr** [comment]
I guess your operating system will update the underlying type definitions until then.
Internally in the SDK, timestamps are already 64 bit UA_DateTime.
