### ISSUE TITLE
How to stop UaExpert Send peridoic ReadRequest to open62541Server?

### ISSUE THREAD

**Issue by mentospcg** [open62541/open62541#499]
When I use UaExpert connect to the open62541Server, the UaExpert peridoic send ReadRequest to the server, about 5 seconds per one. How to stop it ? 

thanks a lot！

**Comment by Stasik0** [comment]
It is probably reading server status to check if the server is alive. 

Is this behavior seen with other servers or only with open62541?

**Comment by mentospcg** [comment]
@Stasik0 only open62541 got this phenomenon. when use UaExpert connect to the OPC foundation UA Sample server does not have this phenomenon.

The periodic ReadRequest wiresharp capture as below:
![qq 20160107092925](https://cloud.githubusercontent.com/assets/12525913/12160089/70c8b3bc-b523-11e5-9edc-6a15a8e0af15.gif)

**Comment by Stasik0** [comment]
It is reading node 2259. Maybe it is trying to simulate a subscription by polling? Do you have subscriptions activated in open62541 server?

You can also try to raise a question on uaexpert forum.

**Comment by jpfr** [comment]
ns=0,i=2259 ist the "State" variable. That is frequently read by UAExpert.

> when use UaExpert connect to the OPC foundation UA Sample server does not have this phenomenon.

I cannot confirm this. On my box, connecting to the official C Server example from UnifiedAutomation results in the same behavior. Here's a screenshot of the network dump:
![2259](https://cloud.githubusercontent.com/assets/1726411/12170996/451bfe2c-b546-11e5-814f-81bf9d1aacc1.png)

@mentospcg Can you tell us your exact configuration so we can reproduce?

**Comment by destogl** [comment]
Just today was talk about that in the [python-opcua repository](https://github.com/FreeOpcUa/python-opcua/issues/106). There was cited the specification:

> The preferred mechanism for a Client to monitor the connection status is through the keep-alive of the Subscription. A Client should subscribe for the State Variable in the ServerStatus to detect shutdown or other failure states. If no Subscription is created or the Server does not support Subscriptions, the connection can be monitored by periodically reading the State Variable.

**Comment by jpfr** [comment]
Hey Denis, nice find. :-)
I guess we can close the issue then.
