### ISSUE TITLE
Build size fluctuations for the same build settings

### ISSUE THREAD

**Issue by epetrevska** [open62541/open62541#5000]
## Description

When building the stack using the regular procedure as explained here: https://open62541.org/doc/current/building.html#building-with-cmake-on-ubuntu-or-debian we noticed that the size of the binary file (libopen62541.a) fluctuates even without any CMake options being changed.

This behavior can be pretty dangerous for production firmware, especially if the fluctuations are happening on smaller controllers which anyhows work with critically low amounts of memory. The differences which we observed here were in Bytes and KBytes sizes, some examples are:
- 7637500 bytes
- 7637468 bytes
- 7637620 bytes
![BuildSizeOPCUAStack](https://user-images.githubusercontent.com/77783092/157707361-a9e5dd0d-0069-478a-87e0-5fb2f7ff5f4d.png)

After debugging it a little, we think the problem is in the NodeSet Compiler. Every time we let it generate the .h and .c files, it randomly shifts the order of the nodes for whichever reason... Also, in case further information models are attached, and not just the base information model, the size fluctuations increases as well... 

We wanted to ask you if this behavior is already known to you and you have some solution against it?

Thank you and many greetings.

## Background Information / Reproduction Steps
Happens during any normal "cmake .. && make" build.

Used CMake options:

```bash
cmake .. && make
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): we tried it with various branches, but as an example tag 1.2.3
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Ubuntu 20.04
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [x] Critical issue

**Comment by jpfr** [comment]
Hmm.
That’s a good observation.
The problem might be the use of dictionaries in Python.
We can switch them to OrderedDict to be order-stable.
