### ISSUE TITLE
Big complexity in the "processDataChangeNotification" function.

### ISSUE THREAD

**Issue by xydan83** [open62541/open62541#5053]
## Description

Hello!

I have same trouble with Client. 
_Originally posted by @xydan83 in https://github.com/open62541/open62541/issues/4318#issuecomment-1087318664_

If I try to subscribe to 30,000 nodes that change at the same time once a second, then this filtering algorithm causes a very heavy load on the processor core. There is a quadratic complexity O(n ^ 2). It is quite possible to remove this problem by replacing the second loop with a lookup in a dictionary (hash table).
And it would also be cool if you could make a callback function that would return all the changes at once, in which I agree with the author of this issue.

Is it possible to replace list macro with hashmap?

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): v1.3-rc2-ef2
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: 20.04.1
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Hey @xydan83 ,

that is a good observation.
My recommendation then is to use the binary tree implementation from /deps/ziptree.h instead of the linked list.
The zip tree is used for example in /plugins/ua_nodestore_ziptree.c.

**Comment by xydan83** [comment]
> Hey @xydan83 ,
> 
> that is a good observation. My recommendation then is to use the binary tree implementation from /deps/ziptree.h instead of the linked list. The zip tree is used for example in /plugins/ua_nodestore_ziptree.c.

Thanks for the answer.
I recently tried using [hashmap] (https://github.com/tidwall/hashmap.c) and it gave good results. CPU core load is reduced to 2-3%.

**Comment by xydan83** [comment]
@jpfr Hi!
I'm trying to use your **ziptree** instead of a linked list in **ua_client_intrnal.h** and **ua_client_subscription.c** and I need help.
What I have done:
1.I made changes to two structures
![image](https://user-images.githubusercontent.com/86729310/163409556-dee469f1-eb88-4d76-9026-66665a6a4f17.png)

2.In **ua_client_subscription.c** I added a comparison function and defined a macro **ZIP_FUNCTION**.
![image](https://user-images.githubusercontent.com/86729310/163409982-ba99e678-a170-44e9-8384-b17a251305e4.png)

3. Added ZIP_INIT
![image](https://user-images.githubusercontent.com/86729310/163410131-47ea5481-d40e-41e4-86d5-4e407011cb4b.png)

4.Added ZIP_INSERT into **ua_MonitoredItems_create**.
![image](https://user-images.githubusercontent.com/86729310/163410497-fa11ce69-32b9-4732-97df-19700481b309.png)

5. Added ZIP_FIND to search for **UA_Client_MonitoredItem** in both **processData Change Notification** and **processEventNotification** functions.
 
![image](https://user-images.githubusercontent.com/86729310/163411011-d4d97834-1691-44aa-83ab-90f430cebd65.png)

![image](https://user-images.githubusercontent.com/86729310/163411107-9a96d203-f4f5-4f20-af07-a00a310c0545.png)

With this minimum set, I'm trying to subscribe to a **UaCPPServer** test server, where I added 100,000 dynamic nodes that change their values once per second, and I get a good result. CPU usage is 10-15% if I print results to screen or 5-10% if I print results to file. When testing with **30,000 nodes**, the load is approximately 3-5%, if the result is output to a file, similar to hashmap.

But the big problem is how can I remove **UA_Client_MonitoredItem** from the tree if I compare **clientHandle** but some functions use **monitoredItemId** field to lookup.
Well, if we are removing all items from the subscription, I can use ZIP_ITER.
![image](https://user-images.githubusercontent.com/86729310/163415095-71b814bf-2acd-42b2-9ced-b5203bbd8a3c.png)

And then ZIP_REMOVE
![image](https://user-images.githubusercontent.com/86729310/163415174-55014d3f-d497-404a-8933-cff2ddada213.png)

But how to find **UA_Client_MonitoredItem** in **ua_MonitoredItems_delete** and **UA_Client_MonitoredItems_modify** functions?
Both are used to look for **monitoredItemId** and not **clientHandle**

![image](https://user-images.githubusercontent.com/86729310/163416344-581d7302-08e1-4e95-8025-28734231b28f.png)
![image](https://user-images.githubusercontent.com/86729310/163416689-98285127-aec5-469d-ada5-0000d08f619f.png)

I think using ZIP_ITER would be a bad idea.

Can you give me some advice or a hint on how to solve this situation?

**Comment by xydan83** [comment]
**Upd:** Well, I tried **ZIP_ITER** in the delete and modify functions and it looks really good despite being O(n) complexity. **100,000** monitored items are removed in about 1-2 seconds.

**Comment by jpfr** [comment]
Thanks for the fix @xydan83 !
