### ISSUE TITLE
UA_BUILD_EXAMPLES builds all examples at once -> Build time increases

### ISSUE THREAD

**Issue by mister-potter** [open62541/open62541#5060]
## Description
Upon enabling the `UA_BUILD_EXAMPLES` option, stack builds all the example at once. It takes around 25-30 seconds in my system. 

Build time increases even though my intention would be to explore and build a specific example. If I just build the intended example along with library, time consumed is reduced to 5-7 seconds (4x time reduction).

Can this be decoupled by adding specific CMake options for the examples too?

```bash
cmake -DUA_BUILD_EXAMPLES=ON ..
```
### Goal:
To reduce the build time

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 1.3
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by mlgiraud** [comment]
Instead of building with `make all` or `ninja all` you can just supply the specific target to build with for example `ninja tutorial_server_first_steps`. This will only build the specified example and all targets it depends on.
