### ISSUE TITLE
Error: git clone https://github.com/open62541/open62541.git

### ISSUE THREAD

**Issue by jackybek** [open62541/open62541#5066]
## Description

fatal: unable to access 'https://github.com/open62541/open62541.git/': Failed to connect to github.com port 443: No route to host

## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [X ] open62541 Version (release number or git tag): v1.3
 - [ ] Other OPC UA SDKs used (client or server): 
 - [X ] Operating system: raspbian
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ X] Critical issue

**Comment by ccvca** [comment]
> No route to host

This is neither a open62541 issue nor github.com issue. The network of your PI not setup correctly.
