### ISSUE TITLE
Sending read/write requests to OPC Server in a loop

### ISSUE THREAD

**Issue by OsamaOAyoub** [open62541/open62541#5133]
## Description
Hello,

I have a running OPCServer with several variables (No final count yet), but can be expanded through time, for now there are 62 variables.

## Background Information / Reproduction Steps

I need to read the values of these variables and push these values to a third party platform and I am doing so as follows:

1) The server generate all nodes/variables/methods.
2) An OPC client connects to the server, browse all server nodes using browseNodes() to get the hierarchy of the server and all the nodes IDs that we are interested in.
3) The node IDs are using to form a request and this request is sent in an infinite while loop (At every loop the same request is sent and the response is read).
4) In every loop I use the values that the client read to push them into the third party platform.
5) Later on, I will add a feature to read values from the third party platform and push these values to their respective variables on the server.

## Questions

My questions are:
1) Is my implementation is done in a correct way or there are some features in the library that I am missing?
2) If the answer to 1 is yes, then will I face issues because I am sending requests every loop (Every request has all nodes, so one request is sent every loop) and the server will be overloaded?
3) If the answer to 1 is no, what features/architecture should I use instead to use the library in the intended way?
4) Is it possible to browse/read/write nodes on the server from the server code itself and do all the pushing/pulling to/from the third party platform within the server code?
5) Is there a way to detect from this client if another client called a method on the server? Because if a method is called by any client I also need to send some data to the third party platform.

Thanks in advanced!

**Comment by jpfr** [comment]
Have a look at the monitoring feature of open62541.
Than you get notified about changes and do not have to poll variables in a tight loop.

**Comment by OsamaOAyoub** [comment]
Thank you for your answer, should I publish all nodes that I am interested in from the server to use the monitoring features or a server/client would be ok? In other words should I use PubSub instead of server/client?

Thanks again! :)
