### ISSUE TITLE
How to report a security issue?

### ISSUE THREAD

**Issue by SharonBrizinov** [open62541/open62541#5137]
We would like to responsibly report on a vulnerability we found in open62541. Where should we send our detailed report?

Additionally I would like to suggest adding a security policy to the repository to help other security researchers reach out to you properly.

Thanks!
Team82 Claroty Research
https://claroty.com/team82/

**Comment by jpfr** [comment]
@SharonBrizinov ,

for private messages to the core developer group you can send an email to open62541-core@googlegroups.com .
Regardless of your finding, thank you for the responsible disclosure.
