### ISSUE TITLE
CI build of pull requests: How to re-run failed checks?

### ISSUE THREAD

**Issue by keba-estr** [open62541/open62541#5183]
## Description

Is there a possibility to restart a single check in the CI build of a pull request, if it failed because of a sporadic error (for example: download of some debian archive failed because of a connection timeout)?

The only way to restart the checks I found so far is to push again a changed commit.

**Comment by GoetzGoerisch** [comment]
As far I am aware only the maintainers could rerun failed test manually for this repo.


For your fork, you can enable the GitHub Actions to also run in the fork
<img width="672" alt="image" src="https://user-images.githubusercontent.com/47734341/172823873-aa642343-3e52-47a8-9f13-d19aba33f8d4.png">

There your have the controls as well to re run failed runs.

**Comment by keba-estr** [comment]
Thank you very much for the detailed answer.
