### ISSUE TITLE
how to verify security Policy Uri string?

### ISSUE THREAD

**Issue by Muddasir-Shakil** [open62541/open62541#5264]
Is there a helper function to verify that PolicyUri string is a valid Policy? for both client-server and pubsub related policyUris
Thank you

**Comment by jpfr** [comment]
That depends on your definition of "valid".
In the current code we loop over the locally configured SecurityPolicies and compare the string.

**Comment by Muddasir-Shakil** [comment]
Thanks @jpfr , for the reply.
