### ISSUE TITLE
cmake build with UA_NAMESPACE_ZERO=FULL fails

### ISSUE THREAD

**Issue by augustinust** [open62541/open62541#5281]
## Description
Downloaded Version 1.3 as ``tar.gz`` from ``http://www.open62541.org/download/``, tried to run cmake with option
``UA_NAMESPACE_ZERO                FULL``

and got this error message:

```
CMake Error at CMakeLists.txt:1170 (message):
  File
  /.../open62541-1.3/deps/ua-nodeset/Schema/Opc.Ua.NodeSet2.xml
  not found.  You probably need to initialize the git submodule for
  deps/ua-nodeset or set open62541_NODESET_DIR.

```

## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=FULL ../open62541-1.3/
```

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by GoetzGoerisch** [comment]
Due to licensing reasons the UA base _NodeSet_ is not included in the download.

As the error message suggests you need to initialise the git submodule or get the _NodeSet_ from here and specifiy the location as suggested: https://github.com/OPCFoundation/UA-Nodeset/tree/latest/Schema

@andreasebner did I overlooked something?

**Comment by jpfr** [comment]
This should be documented better.
And/or we can automatically do the checkout of the submodule via cmake:
https://www.scivision.dev/cmake-git-submodule/

**Comment by NoelGraf** [comment]
I have created a PR where the git submodules are automatically initialized via cmake #5290

**Comment by NoelGraf** [comment]
@augustinust can the issue be closed?

**Comment by augustinust** [comment]
It would be sufficient for me to have it documented as @jpfr suggested.
