### ISSUE TITLE
Zero timestamp in response header for renew secure channel

### ISSUE THREAD

**Issue by Rowesca1** [open62541/open62541#5306]
## Description
When receiving a renew secure channel message the response header timestamp field is not set.

## Background Information / Reproduction Steps
In the file ua_services_securechannel.c when a new secure channel is opened via UA_SecureChannelManager_open the timestamp is filled in. It is done at line 286.

`response->responseHeader.timestamp = response->securityToken.createdAt; ` 

This is not done when renew is called using UA_SecureChannelManager_renew.
The same line should be added around line 338.

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): All
 - [x] Other OPC UA SDKs used (client or server): Server
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Did you have problems with a particular SDK and this?

**Comment by Rowesca1** [comment]
> Did you have problems with a particular SDK and this?

No major problems.

A 3rd party client would generate warnings because of this.
