### ISSUE TITLE
Network statistics broken in the eventloop implementation

### ISSUE THREAD

**Issue by jonasgreen88** [open62541/open62541#5343]
## Description
The networkStatistics structure of the UA_Server type is no longer updated by the network layer on the master branch. It looks like the new eventloop implementation hasn't considered this feature.

## Background Information / Reproduction Steps
Search for any variable of the UA_NetworkStatistics type and there is no hits except of the definition of the type.

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): master
 - [x] Other OPC UA SDKs used (client or server): N/A
 - [x] Operating system: N/A
 - [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached N/A
 - [x] Wireshark network dump attached N/A
 - [x] Self-contained code example attached N/A
 - [ ] Critical issue

**Comment by jpfr** [comment]
The indirection between network connections and SecureChannels no longer exists in the server.  The network statistics are made directly on the  SecureChannel level.

Solved by removing the unused statistics in #5357 .
