### ISSUE TITLE
Linker errors on MSVS

### ISSUE THREAD

**Issue by andy295** [open62541/open62541#5347]
## Description
I'm trying to implement my own server starting from the [official tutorial](https://www.open62541.org/doc/1.3/toc.html), but unfortunately I'm running into some issues.

I tried with Visual Studio 2013 and I got the following results

![image](https://user-images.githubusercontent.com/30796351/191443757-1a15e698-b1e8-4d70-91bb-c8710e6d451d.png)

Then I tried with Visual Studio 2019 and I got the following results

![image](https://user-images.githubusercontent.com/30796351/191443596-3582b198-1098-498f-907e-693fabab6566.png)

For both I reported just some rows.

I'm not sure about the reasons of the issues.

## Project steps
Here below the steps I followed to build in and include the library: 

  1_     I opened the solution on Visual Studio, it was generate by using CMake (this last configuration into the appropriate section).
  2_     After building the solution, I created a new project and added in the open62541.h and open62541.c files.
  3_     I created the first [simple server](https://www.open62541.org/doc/1.3/tutorial_server_firststeps.html#server-configuration-and-plugins).
  4_     Finally, I compiled the project on Visual Studio and I ran into the above errors.

Used CMake options:

I used the CMake GUI, here below the chosen options

![image](https://user-images.githubusercontent.com/30796351/191449387-745d97f3-ac6c-4668-9769-f5814adc3393.png)

![image](https://user-images.githubusercontent.com/30796351/191449624-b3b8639f-7609-4928-9624-7e9fe13cbebe.png)

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 1.3.2-512
 - [x] Operating system: Windows 10 Enterprise x64

**Comment by jpfr** [comment]
Try to add ws2_32 to the libraries that are linked in.

**Comment by jpfr** [comment]
You're welcome :-)
