### ISSUE TITLE
open62541Targets.cmake uses absolute paths in the INTERFACE_LINK_LIBRARIES

### ISSUE THREAD

**Issue by carl-cimon** [open62541/open62541#5421]
## Description

In the generated open62541Targets.cmake file, the INTERFACE_LINK_LIBRARIES uses the absolute paths of any linked libraries, which causes the library to not be relocatable. This is affecting our cross compile toolchain, as the path of the OpenSSL library when we build the toolchain is different than location after the toolchain is installed.

I'm going to be honest, I'm not super knowledgeable about the toolchain build process (as that is handled by another member of my team), but looking into how the INTERFACE_LINK_LIBRARIES is generated in cmake, it seems like the absolute path is being provided to the target_link_libraries() call in the CMakeLists. According to the [cmake docs](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#creating-relocatable-packages), it seems that using the imported target for an external library is better practice.

I was able to fix this on our end by modifying the CMakeLists to do just that, replacing:
```
list(APPEND open62541_LIBRARIES ${OPENSSL_LIBRARIES})
````
with
```
list(APPEND open62541_LIBRARIES OpenSSL::SSL)
list(APPEND open62541_LIBRARIES OpenSSL::Crypto)
```

I do not know if this is the best method to fix the issue, but figured I'd share a fix in case anyone else runs into a similar problem. It did require us to find_package() OpenSSL separately in our project which uses open62541 though, likely to be able to resolve where the libraries are, but this should be acceptable in most cases. I assume a similar fix would work for the other external libraries as well.

## Background Information / Reproduction Steps

Here's the steps I used on a windows build.  This occurs for both and static shared builds. I believe this would happen with any build which links an external library, not just OpenSSL. 

```
git clone https://github.com/open62541/open62541.git
cd open62541
git checkout ff73268
git submodule update --init --recursive

mkdir build && cd build

cmake -GNinja -DCMAKE_C_COMPILER="cl.exe" -DCMAKE_CXX_COMPILER="cl.exe" -DMSVC_TOOLSET_VERSION=141 .. -DCMAKE_BUILD_TYPE=release -DCMAKE_INSTALL_PREFIX={install_path} -DUA_ENABLE_SUBSCRIPTIONS=ON -DBUILD_SHARED_LIBS=OFF -DUA_ENABLE_AMALGAMATION=OFF -DUA_NAMESPACE_ZERO=FULL  -DUA_ENABLE_ENCRYPTION=OPENSSL -DOPENSSL_USE_STATIC_LIBS=ON -DOPENSSL_ROOT_DIR={openssl_path}

cmake --build . --target install --config release --parallel 4
```

Now check the open62541Targets.cmake inside {install_path}/lib/cmake and you'll see that INTERFACE_LINK_LIBRARIES uses the absolute path to the OpenSSL libraries.

Used CMake options:

```bash
See above.
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): v1.3.3
 - [ ] Other OPC UA SDKs used (client or server): N/A
 - [x] Operating system: Windows and linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached: N/A
 - [ ] Wireshark network dump attached: N/A
 - [ ] Self-contained code example attached: N/A
 - [ ] Critical issue: No

**Comment by matthiasklein** [comment]
We are also affected by the bug in connection with Yocto SDKs. The problem causes paths to end up in the CMake file that are only present in the build of the SDK.

As a workaround we include open62541 not via find_package but via pkgconfig / pkg_search_module.
