### ISSUE TITLE
Reading Variable Data Sources

### ISSUE THREAD

**Issue by Boberic1999** [open62541/open62541#5436]
--------------------------------------------------------------------------------
-->

## Description
Hello!
I will just get to the point. I created OPC UA server using open62541 library (1.3.2), it has implemented encryption, username and pass logging in. It uses variable Data Sources to keep track of the used variables.
I am using UaExpert as OPC Client, to test my server.
My problem is that I have to manually refresh nodes to see changed value in selected node( I have select another node, and then, select the first node back again for result to be seen in Attributes windows of the UaExpert.)
Another thing, I see in Log window, that RevisedSamplingInterval = 0.
Also, I did some debugging, I concluded that read function is called only when I reselect the node.
Please, do you have any tips to fix this issue?

I am sending you UaExpert log:

09:41:15.206 | AddressSpaceModel  | open62541-based OPC UA Appl... | Browse on node 'ns=1;s=opc_ua_server2' succeeded.
09:41:15.221 | AddressSpaceModel  | open62541-based OPC UA Appl... | Browse on node 'ns=1;s=Measurements' succeeded.
09:41:15.221 | AddressSpaceModel  | open62541-based OPC UA Appl... | Browse on node 'ns=1;s=Outputs' succeeded.
09:41:15.253 | AddressSpaceModel  | open62541-based OPC UA Appl... | Browse on node 'ns=1;s=Cmd out' succeeded.
09:41:15.268 | AddressSpaceModel  | open62541-based OPC UA Appl... | Browse on node 'ns=1;s=Current and voltage' succeeded.
09:41:15.284 | AddressSpaceModel  | open62541-based OPC UA Appl... | Browse on node 'ns=1;s=Current in' succeeded.
09:41:15.284 | AddressSpaceModel  | open62541-based OPC UA Appl... | Browse on node 'ns=1;s=Voltage in' succeeded.
09:41:15.300 | DA Plugin          | open62541-based OPC UA Appl... | No subscription available for ServerId 2
09:41:15.300 | DA Plugin          | open62541-based OPC UA Appl... | Creating new subscription: ClientHandle=2, PublishingEnable=1, LifeTimeCount=2400, MaxKeepAliveCount=10, Priority=0, PublishingInterval=500, MaxNotificationsPerPublish=0
09:41:15.300 | DA Plugin          | open62541-based OPC UA Appl... | CreateSubscription succeeded [ret = Good]
09:41:15.300 | DA Plugin          | open62541-based OPC UA Appl... | Revised values: LifeTimeCount=2400, MaxKeepAliveCount=10, Priority=0, PublishingInterval=500, SubscriptionId=2
09:41:15.300 | DA Plugin          | open62541-based OPC UA Appl... | Created subscription for ServerId 2
09:41:15.300 | DA Plugin          | open62541-based OPC UA Appl... | Item [NS1|String|Cmd out]: SamplingInterval=-1, QueueSize=1, DiscardOldest=1, ClientHandle=16
09:41:15.300 | DA Plugin          | open62541-based OPC UA Appl... | Item [NS1|String|Current and voltage]: SamplingInterval=-1, QueueSize=1, DiscardOldest=1, ClientHandle=17
09:41:15.300 | DA Plugin          | open62541-based OPC UA Appl... | Item [NS1|String|Current in]: SamplingInterval=-1, QueueSize=1, DiscardOldest=1, ClientHandle=18
09:41:15.300 | DA Plugin          | open62541-based OPC UA Appl... | Item [NS1|String|Voltage in]: SamplingInterval=-1, QueueSize=1, DiscardOldest=1, ClientHandle=19
09:41:15.331 | DA Plugin          | open62541-based OPC UA Appl... | CreateMonitoredItems succeeded [ret = Good]
09:41:15.331 | DA Plugin          | open62541-based OPC UA Appl... | Item [NS1|String|Cmd out] succeeded : RevisedSamplingInterval=0, RevisedQueueSize=1, MonitoredItemId=1 [ret = Good]
09:41:15.331 | DA Plugin          | open62541-based OPC UA Appl... | Item [NS1|String|Current and voltage] succeeded : RevisedSamplingInterval=0, RevisedQueueSize=1, MonitoredItemId=2 [ret = Good]
09:41:15.331 | DA Plugin          | open62541-based OPC UA Appl... | Item [NS1|String|Current in] succeeded : RevisedSamplingInterval=0, RevisedQueueSize=1, MonitoredItemId=3 [ret = Good]
09:41:15.331 | DA Plugin          | open62541-based OPC UA Appl... | Item [NS1|String|Voltage in] succeeded : RevisedSamplingInterval=0, RevisedQueueSize=1, MonitoredItemId=4 [ret = Good]
09:41:41.232 | Attribute Plugin   | open62541-based OPC UA Appl... | Read attributes of node 'NS1|String|Current in' succeeded [ret = Good].
09:41:41.232 | Reference Plugin   | open62541-based OPC UA Appl... | Browse succeeded.
09:41:47.623 | Attribute Plugin   | open62541-based OPC UA Appl... | Read attributes of node 'NS1|String|Voltage in' succeeded [ret = Good].
09:41:47.638 | Reference Plugin   | open62541-based OPC UA Appl... | Browse succeeded.
09:41:48.154 | Attribute Plugin   | open62541-based OPC UA Appl... | Read attributes of node 'NS1|String|Current in' succeeded [ret = Good].
09:41:48.154 | Reference Plugin   | open62541-based OPC UA Appl... | Browse succeeded.
09:42:00.145 | Attribute Plugin   | open62541-based OPC UA Appl... | Read attributes of node 'NS1|String|Voltage in' succeeded [ret = Good].
09:42:00.145 | Reference Plugin   | open62541-based OPC UA Appl... | Browse succeeded.
09:42:01.933 | Attribute Plugin   | open62541-based OPC UA Appl... | Read attributes of node 'NS1|String|Current in' succeeded [ret = Good].
09:42:01.933 | Reference Plugin   | open62541-based OPC UA Appl... | Browse succeeded.
09:42:05.507 | Attribute Plugin   | open62541-based OPC UA Appl... | Read attributes of node 'NS1|String|Voltage in' succeeded [ret = Good].
09:42:05.507 | Reference Plugin   | open62541-based OPC UA Appl... | Browse succeeded.
09:42:06.163 | Attribute Plugin   | open62541-based OPC UA Appl... | Read attributes of node 'NS1|String|Current in' succeeded [ret = Good].
09:42:06.163 | Reference Plugin   | open62541-based OPC UA Appl... | Browse succeeded.

## Background Information / Reproduction Steps

Used CMake options:
-DUA_ENABLE_ENCRYPTION = OPENSSL
-DUA_NAMESPACE_ZERO=FULL
-DUA_NAMESPACE_ZERO=FULL
-DUA_ENABLE_AMALGAMATION=ON

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag): open62541 1.3.2
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system: both Windows and Linux (Ubuntu 20.4)
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by undroidwish** [comment]
Set a MinimumSamplingInterval greater than zero on your data variables, then use subscription/monitor from UAExpert.
