### ISSUE TITLE
getTypeByString cannot parse 'Variant' BuiltinType

### ISSUE THREAD

**Issue by ReidJunLi-Rockwell** [open62541/open62541#5469]
The builtin_types[] defined in Type_parser.py **DOES** include 'Variant' type, while getTypeByString() in datatypes.py **DOES NOT** parse 'Variant' type. It means that if a variable type include a field whose type is 'Variant', then in it cannot be parsed in __parseXMLSingleValue() of Datatypes.py. Then in line 286 of datatype.py, "t = self.getTypeByString(e.member_type.name, None)", t will be None for 'Variant' type, so t.parseXML will return fault **"AttributeError: ‘NoneType’ object has no attribute ‘alias’"**

Below are line 286~289 of datatypes.py of master branch.
```
  else:
      t = self.getTypeByString(e.member_type.name, None)
      t.alias = ebodypart.localName
      t.parseXML(ebodypart)
      extobj.value.append(t)
```

it works after changed as below
```
  else:
      t = self.getTypeByString(e.member_type.name, None)
      if t is not None:
             t.alias = ebodypart.localName
             t.parseXML(ebodypart)
             extobj.value.append(t)
```

Please provide the following information:

 - [ ] open62541 Version (release number or git tag): 1.3.4
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system: Linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Fixed via https://github.com/open62541/open62541/pull/5487.
