### ISSUE TITLE
UnboundLocalError: local variable ‘val’ reference before assignment when parse GUID

### ISSUE THREAD

**Issue by ReidJunLi-Rockwell** [open62541/open62541#5472]
when parse GUID field of variableNode, if not find the 'String' tag, then 'val' is not assigned, then will get below fault
![image](https://user-images.githubusercontent.com/73766811/203881314-4c03586a-09ad-444a-8529-74d5dbe9d9de.png)

It works when set the val to None before check
```
class Guid(Value):
    def __init__(self, xmlelement=None):
        Value.__init__(self)
        if xmlelement:
            self.parseXML(xmlelement)

    def parseXML(self, xmlvalue):
        self.checkXML(xmlvalue)

        # Support GUID in format:
        # <Guid>
        #   <String>01234567-89AB-CDEF-ABCD-0123456789AB</String>
        # </Guid>
        val = None  # Added: set to None before check
        if len(xmlvalue.getElementsByTagName("String")) != 0:
            val = getXmlTextTrimmed(xmlvalue.getElementsByTagName("String")[0].firstChild)

        if val is None:
            self.value = ['00000000', '0000', '0000', '0000', '000000000000']  # Catch XML <Guid /> by setting the value to a default
        else:

```

Please provide the following information:

 - [ ] open62541 Version (release number or git tag): 1.3.4
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system: Linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Fixed via https://github.com/open62541/open62541/pull/5487.
