### ISSUE TITLE
UA_Server_createCondition is undefined

### ISSUE THREAD

**Issue by growgreat77** [open62541/open62541#5488]
I am trying to follow  "4.10 Using Alarms and Conditions Server" to make use of the Alarms. But there is a problem "identifier UA_Server_createCondition is undefinedC/C++(20", how can i to solve this problem. Thank you very much.
![image](https://user-images.githubusercontent.com/56195883/204689629-646099e4-1f59-49df-bb87-66901879214c.png)

**Comment by kimim** [comment]
did you compile the stack with `UA_ENABLE_SUBSCRIPTIONS_ALARMS_CONDITIONS`

**Comment by growgreat77** [comment]
> did you compile the stack with `UA_ENABLE_SUBSCRIPTIONS_ALARMS_CONDITIONS`

Yeah，Thank you very much, I'll compile it again.
