### ISSUE TITLE
Asynchronous Client

### ISSUE THREAD

**Issue by Aleskey78** [open62541/open62541#552]
Hello,

I would really like to use SendPublishRequest asynchronously, non-blocking to Read/Write calls.
Is there any way to do it? Some kind of message loop / dispatcher?

Thanks!

**Comment by jpfr** [comment]
Hey @Aleskey78,

not yet. Eventually, I'd like to have the same event-based dispatch in client and server. But that is post 0.2 if nobody steps up.

Best, Julius

**Comment by Stasik0** [comment]
the first step would be this one: https://github.com/open62541/open62541/issues/279 making a client to have its own thread

**Comment by jpfr** [comment]
This feature was implemented server-side. Client-side async will follow after 0.2.

**Comment by jpfr** [comment]
Implemented in bffefa4cd0331d75a8ed46698ab1a959217c14f9.
