### ISSUE TITLE
Bug in getNamespaceByIndex

### ISSUE THREAD

**Issue by chhuebner** [open62541/open62541#5527]
There is a bug in getNamespaceByIndex:

https://github.com/open62541/open62541/blob/8eeb6c33da78a0d020aeafcf20eab6cbf84a3c0a/src/server/ua_server.c#L131 

It should be: 

if(namespaceIndex >= server->namespacesSize)

**Comment by keba-estr** [comment]
Yes, this is an error. Could you please create a pull request with the fix?

**Comment by chhuebner** [comment]
I created the pull request: #5528

**Comment by chhuebner** [comment]
Created new PR #5534 for 1.3 branch

**Comment by jpfr** [comment]
Merged.
Will go to master from there.
