### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by maldag** [open62541/open62541#5539]
Is there a testsuite available to test performance (latency / throughput) with different package sizes and protocols? This could be beneficial to monitor these stats during development

**Comment by jpfr** [comment]
We have a few speed tests in our unit tests. But not to the point you mention.

UA Expert has a few speed tests built in that you can use out of the box.

There are a few academic publications that do benchmarking. Google Scholar finds a lot of references for open62541.
If there are benchmark scripts available, we’d be happy to reference them from here.
