### ISSUE TITLE
Data transmission over unidirectional UDP

### ISSUE THREAD

**Issue by vvpnet** [open62541/open62541#5616]
Hi guys! See the OPC UA interaction diagram. Tell me is it possible to do this?
![схема через InfoDiode](https://user-images.githubusercontent.com/6735723/216530041-ece5526a-f6c4-4dfd-864b-2d9b20753b9a.png)

**Comment by jpfr** [comment]
Have a look at OPC UA PubSub.
Which is different from the client/server protocol.
