### ISSUE TITLE
Can't compile on Windows 11: undefined reference to 'if_nametoindex'

### ISSUE THREAD

**Issue by KnowingBat** [open62541/open62541#5622]
## Description
I recently installed open62541 on Windows 11 and build it successfully. I used ```amalgamation``` in order to use the open62541.c/.h files. I setup the example project called ```tutorial_server_firststeps.c``` and, as i'm using a MinGW-64 compiler, i tried to compile as mentioned in the documentation, using the command ```gcc -std=c99 open62541.c tutorial_server_firststeps.c -lsw2_32 -o test.exe ```

## Background Information / Reproduction Steps
Running the command above, i bump into this error:
![image](https://user-images.githubusercontent.com/75283094/217789959-a75eae5e-3c53-4d11-ba9c-fbf1e52e275e.png)

This is my current version of MinGW-64:
![image](https://user-images.githubusercontent.com/75283094/217790249-751d7b46-3f50-485a-81e3-f36fe82b765a.png)

I also tried to change MinGW-64 from ```posix``` to ```win32```, but the issue still remains.

In addiction, this is my "tutorial_server_firststeps.c" file:
![image](https://user-images.githubusercontent.com/75283094/217790987-cad05cb7-80a9-4ee7-8ae2-fec41f94dd53.png)

Is there something that i'm missing here? 

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): Lastest Version 1.3
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Windows 11
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Hmm. After creating the open62541.c.h files, I can only find benign uses:
```
jpfr@virtualbox:~/software/open62541/build$ grep -r -H nametoindex
open62541.h:# define UA_if_nametoindex if_nametoindex
open62541.h:# ifndef UA_if_nametoindex
open62541.h:unsigned int UA_if_nametoindex(const char *ifname);//equivalent to posix if_nametoindex implementation
```

Please do the same to see where this comes from.

**Comment by KnowingBat** [comment]
Hello @jpfr, i did what you suggested, this is the output:

```  
open62541.c: ipMulticastRequest.ipv6.ipv6mr_interface = UA_if_nametoindex(interfaceAsChar);
open62541.c: ipMulticastRequest.ipv6.ipv6mr_interface = UA_if_nametoindex(interfaceAsChar);
open62541.h:# define UA_if_nametoindex if_nametoindex
open62541.h:# define UA_if_nametoindex if_nametoindex
open62541.h:# ifndef UA_if_nametoindex
open62541.h:unsigned int UA_if_nametoindex(const char *ifname);//equivalent to posix if_nametoindex implementation 
```
Actually i did "solve" the problem by commenting out ```#define UA_IPV6 1```. That's fine because i don't really need IPV6 right now. However i don't really understand why if_nametoindex is causing this issue...  Do you have any further informations about this?

**Comment by 8188** [comment]
Add **-lIphlpapi** will solve this problem. The reason is [here.](https://learn.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-if_nametoindex)
At last, with MinGW-64 on Windows10 my command line: 
`gcc tutorial_server_firststeps.c -o tutorial_server_firststeps -I..\build\src_generated -I..\include -I..\arch -I..\deps -L..\build\bin -lopen62541 -lws2_32 -lIphlpapi`
