### ISSUE TITLE
After changing from version 1.2 to 1.35, certificate validation failed. What is the reason for this?

### ISSUE THREAD

**Issue by liutt1312** [open62541/open62541#5690]
## Background Information / Reproduction Steps

After changing from version 1.2 to 1.35, certificate validation failed. What is the reason for this?
![image](https://user-images.githubusercontent.com/86719542/225791081-2c8da031-6cc7-4554-ae75-9cf661aa90b3.png)

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag):1.35
 - [x] Other OPC UA SDKs used (client or server): client
 - [x] Operating system:posix
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by neojaw** [comment]
Try setting up the certificate trust list in the config. Since v1.3.4 an empty trust list will result in certificate rejection (as it should).

**Comment by liutt1312** [comment]
> Try setting up the certificate trust list in the config. Since v1.3.4 an empty trust list will result in certificate rejection (as it should).

The certificate used is in the server trust list

**Comment by liutt1312** [comment]
> > Try setting up the certificate trust list in the config. Since v1.3.4 an empty trust list will result in certificate rejection (as it should).
> 
> The certificate used is in the server trust list

The only difference between the same code and certificate is the library version

**Comment by neojaw** [comment]
> The certificate used is in the server trust list

And is the server certificate in the client trust list?

**Comment by liutt1312** [comment]
> > The certificate used is in the server trust list
> 
> And is the server certificate in the client trust list?

Do you need this step? It is also possible to add a server certificate when using version 1.2

**Comment by neojaw** [comment]
Yes, this is needed. Up to [v1.3.4](https://github.com/open62541/open62541/releases/tag/v1.3.4) an empty trust list caused the client to just accept all server certificates but then this was changed/fixed.

**Comment by liutt1312** [comment]
> Yes, this is needed. Up to [v1.3.4](https://github.com/open62541/open62541/releases/tag/v1.3.4) an empty trust list caused the client to just accept all server certificates but then this was changed/fixed.

okay, thank you

**Comment by liutt1312** [comment]
> Yes, this is needed. Up to [v1.3.4](https://github.com/open62541/open62541/releases/tag/v1.3.4) an empty trust list caused the client to just accept all server certificates but then this was changed/fixed.

Can this problem be solved？
After cross compilation, this error occurs when running on arm linux. What is the reason for this error #5691
