### ISSUE TITLE
Client: ActivateSession without disconnect/connect

### ISSUE THREAD

**Issue by matkonnerth** [open62541/open62541#5704]
Hi, is there a possibility to change the session locales without a disconnect/connnect from the session? OPC UA Standard specifies this in the ActivateSession service?

**Comment by jpfr** [comment]
I don't think that can be done.
You could try to "re-activate" the same session on the same SecureChannel.
Not sure how well that works across the different SDK though.

**Comment by matkonnerth** [comment]
ok, we will provide a pull request for that.

**Comment by matkonnerth** [comment]
here is the corresponding pull request: https://github.com/open62541/open62541/pull/5744

**Comment by jpfr** [comment]
This is now on master.

**Comment by NoelGraf** [comment]
Fixed with #5789
