### ISSUE TITLE
Allow setting up a listening socket while the network interface is waiting for IP

### ISSUE THREAD

**Issue by dbeinder** [open62541/open62541#5709]
## Description
This change https://github.com/open62541/open62541/pull/3940 set `AI_ADDRCONFIG` on [getaddrinfo()](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html) which is used in server mode to find local addresses to bind to.

However, this means `getaddrinfo()` will only return an addressinfo if the system has a configured IP. In some applications, it is desirable to bind to 0.0.0.0 and not wait for WiFi/DHCP to complete before setting up the OPC server:
```
       If hints.ai_flags includes the AI_ADDRCONFIG flag, then IPv4
       addresses are returned in the list pointed to by res only if the
       local system has at least one IPv4 address configured, and IPv6
       addresses are returned only if the local system has at least one
       IPv6 address configured.  The loopback address is not considered
       for this case as valid as a configured address. This flag is
       useful on, for example, IPv4-only systems, to ensure that
       getaddrinfo() does not return IPv6 socket addresses that would
       always fail in connect(2) or bind(2).
```

I wish an alternative solution to deal with CAN interfaces could be found.

## Background Information / Reproduction Steps

I added some logging to document the behavior: https://github.com/Chronos-Inc/open62541/commit/4b95ac7171c434b638eeb133c58ef40d2b98fbdb

Log (A) and (B) show the current behavior, Log (C) shows how it works with `AI_ADDRCONFIG` removed

#### (A) AI_ADDRCONFIG active, WiFI is setup before OPC, IPv4 socket gets bound ✅
`getaddrinfo() flags = AI_ADDRCONFIG (32) | AI_PASSIVE (1) = 33`
```
Mar 24 15:05:02 INF network   Started network service ...
Mar 24 15:05:03 INF config    [wlan0] has dynamic IP
Mar 24 15:05:04 INF config    [wlan0] WiFi SSID: [FraxNet] security: wpa-psk
Mar 24 15:05:05 INF network   [nm] wlan0: connecting (prepare)
Mar 24 15:05:05 INF network   [nm] wlan0: connecting (configuring)
Mar 24 15:05:05 INF network   [nm] wlan0: connecting (need authentication)
Mar 24 15:05:05 INF network   [nm] wlan0: connecting (prepare)
Mar 24 15:05:05 INF network   [nm] wlan0: connecting (configuring)
Mar 24 15:05:05 INF network   [nm] wlan0: connecting (getting IP configuration)
Mar 24 15:05:06 INF network   [nm] wlan0: connecting (checking IP connectivity)
Mar 24 15:05:06 INF network   [nm] wlan0: connecting (starting secondary connections)
Mar 24 15:05:06 INF network   [nm] wlan0: connected
Mar 24 15:05:06 Starting opc server on port 4840
Mar 24 15:05:06   info/network        Calling getaddrinfo(NULL, 4840, family: 0, socktype: 1, flags: 33)
Mar 24 15:05:06   info/network        Setting up socket: addr: 0.0.0.0, ai_family: 2, res: 0
Mar 24 15:05:06   info/network        Setting up socket: addr: ::, ai_family: 10, res: 0
Mar 24 15:05:06   info/network        TCP network layer listening on opc.tcp://logger:4840/
```

#### (B) AI_ADDRCONFIG active, WiFI DHCP is slow and completes after OPC, IPv4 socket DOES NOT gets bound ❌
`getaddrinfo() flags = AI_ADDRCONFIG (32) | AI_PASSIVE (1) = 33`
```
Mar 24 15:08:42 INF network   Started network service ...
Mar 24 15:08:43 INF config    [wlan0] has dynamic IP
Mar 24 15:08:44 INF config    [wlan0] WiFi SSID: [FraxNet] security: wpa-psk
Mar 24 15:08:45 INF network   [nm] wlan0: connecting (prepare)
Mar 24 15:08:45 INF network   [nm] wlan0: connecting (configuring)
Mar 24 15:08:45 INF network   [nm] wlan0: connecting (need authentication)
Mar 24 15:08:45 INF network   [nm] wlan0: connecting (prepare)
Mar 24 15:08:45 INF network   [nm] wlan0: connecting (configuring)
Mar 24 15:08:45 INF network   [nm] wlan0: connecting (getting IP configuration)
Mar 24 15:08:46 Starting opc server on port 4840
Mar 24 15:08:46    info/network        Calling getaddrinfo(NULL, 4840, family: 0, socktype: 1, flags: 33)
Mar 24 15:08:46    info/network        Setting up socket: addr: ::, ai_family: 10, res: 0
Mar 24 15:08:46    info/network        TCP network layer listening on opc.tcp://logger:4840/
Mar 24 15:08:52 INF network   [nm] wlan0: connecting (checking IP connectivity)
Mar 24 15:08:52 INF network   [nm] wlan0: connecting (starting secondary connections)
Mar 24 15:08:52 INF network   [nm] wlan0: connected
```

#### (C) AI_ADDRCONFIG disabled, WiFI DHCP is slow and completes after OPC, IPv4 socket gets bound ✅
`getaddrinfo() flags = AI_PASSIVE (1) = 1`
```
Mar 24 15:13:22 INF network   Started network service ...
Mar 24 15:13:23 INF config    [wlan0] has dynamic IP
Mar 24 15:13:24 INF config    [wlan0] WiFi SSID: [FraxNet] security: wpa-psk
Mar 24 15:13:25 INF network   [nm] wlan0: connecting (prepare)
Mar 24 15:13:25 INF network   [nm] wlan0: connecting (configuring)
Mar 24 15:13:25 INF network   [nm] wlan0: connecting (need authentication)
Mar 24 15:13:25 INF network   [nm] wlan0: connecting (prepare)
Mar 24 15:13:25 INF network   [nm] wlan0: connecting (configuring)
Mar 24 15:13:25 INF network   [nm] wlan0: connecting (getting IP configuration)
Mar 24 15:13:26 Starting opc server on port 4840
Mar 24 15:13:26    info/network        Calling getaddrinfo(NULL, 4840, family: 0, socktype: 1, flags: 1)
Mar 24 15:13:26    info/network        Setting up socket: addr: 0.0.0.0, ai_family: 2, res: 0
Mar 24 15:13:26    info/network        Setting up socket: addr: ::, ai_family: 10, res: 0
Mar 24 15:13:26    info/network        TCP network layer listening on opc.tcp://logger:4840/
Mar 24 15:13:29 INF network   [nm] wlan0: connecting (checking IP connectivity)
Mar 24 15:13:29 INF network   [nm] wlan0: connecting (starting secondary connections)
Mar 24 15:13:29 INF network   [nm] wlan0: connected
```

## Checklist

Please provide the following information:

 - [X] open62541 Version (release number or git tag): 1.3.5
 - [ ] Other OPC UA SDKs used (client or server): -
 - [X] Operating system: Linux 4.19
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
This seems to introduce blocking behavior.
In the logs you wait three seconds for the ipv4 socket to appear.
What about a system where IPv4 is never configured.
We should not block indefinitely.

Another option would be to allow for the networklayer to restart at runtime.

I see you are on the stable 1.3 release.
The change could break some applications and should go on master.

Please have a look at the new "EventLoop" model for networking.
The implementation on master already allows to separately start/stop the TCP "EventSource".

**Comment by dbeinder** [comment]
@jpfr 
> This seems to introduce blocking behavior. In the logs you wait three seconds for the IPv4 socket to appear. What about a system where IPv4 is never configured. We should not block indefinitely.

Which call do you think could block with the `AI_ADDRCONFIG` flag removed? In my example, there is no blocking, the OPC server gets bound instantly to 0.0.0.0:4840.
In my second+third example, the WiFi is slow, and it takes 3 seconds for the WiFi interface to acquire an IP, but these are network manager logs and don't cause blocking in this library.

`getaddrinfo()` can only block if we try to bind our server to a hostname that is not known and needs a DNS lookup first. To me this seems an extremly non-standard use. Usually, if we supply a hostname instead of NULL, it would be the devices own hostname, which gets resolved instantly without DNS lookup.
However, the `AI_ADDRCONFIG` flag has no effect on this behviour anyway. The only effect of the flag is quoted in my original post above.

Binding a listening socket should always be a non-blocking operation as well.

As far as I can tell, the only change would be this:
`getaddrinfo()` can now return the IPv6 wildcard address even on systems that lack IPv6 support. On those systems, open62541 should be compiled without `UA_IPV6` anyway. But even if the developer missed this, there would be no functional change, since the setup function will succeed as long as it binds at least one socket (binding the IPv4 socket will still succeed):
https://github.com/open62541/open62541/blob/master/arch/eventloop_posix_tcp.c#L547-L558
In such a case, there will be an additional warning logged, that will show the failure to bind an IPv6 socket. I believe this is actually helpful, notifying the developer to compile open62541 without `UA_IPV6`.

The change in #3940 was only done because:
a) there, the user had a CANbus interface which always fails to bind AND
b) at the time, the setup code was different and TCP setup only succeeded if ALL sockets were bound successfully:
https://github.com/open62541/open62541/pull/3940/files#diff-3a63b2828397b362938c502e14c1e64e6088620f5f30f41d49256d82c35ddea9R434

Since the setup logic is now different, I believe this change should be reverted. The CANbus user will see an additional warning. They can avoid this warning by binding to the local hostname instead of NULL.

If you agree, I'll create a PR for the master branch.

**Comment by dbeinder** [comment]
It would not block open62541, it simply allows it open a listening socket on the wildcard IP (0.0.0.0). This should work instantly, even when the device doesn't have an IP yet. This should not cause any blocks in the library code. Once the interface gets an IP, the open62541 server will reachable from outside. My point is that when I bind the open62541 socket on the wildcard IP, it shouldn't be necessary to re-initalize open62541 if the network interface goes down for a few seconds, or changes IP.
