### ISSUE TITLE
How do I add custom attributes for a Variable Node?

### ISSUE THREAD

**Issue by serega1103** [open62541/open62541#5729]
## Description
Hello!

How do I add custom attributes to a VariableNode?
Can I change the composition of the attributes of the VariableNode in the direction of increase?

I want there to be other attributes besides "Value" that I will change from the database, as I am changing "Value" now.

And what additional infrastructure will have to be modified for this (new functions, structures)?

Thanks for the answer!

## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUA_NAMESPACE_ZERO=FULL -DUA_ENABLE_AMALGAMATION=ON -G "Visual Studio 17 2022" -A Win32 -S .. -B "build32"
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 1.2
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Windows 11
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by serega1103** [comment]
That is, I want my attributes to be in addition to the standard attributes ("BrowseName", "DisplayName", "Description", "WriteMask", "Value"), for example: "StatusColor", "ValidAlm", "TransmitterType", "LinearType".

**Comment by jpfr** [comment]
Is this some kind of research into OPC UA extensions?
The attributes are predefined for each node class.
And no client will be able to read your custom attributes.

I think what you want to have is an object-node.
That references variable "child nodes" for StatusColor, ValidAlm, and so on.

**Comment by NoelGraf** [comment]
@serega1103 can the issue be closed?
