### ISSUE TITLE
Hololens 2 Support

### ISSUE THREAD

**Issue by ffreality** [open62541/open62541#5736]
I need to use open62541 with Hololens 2.
It has Snapdragon 850 but its not Android or vanilla Windows. It called as Windows Holographic OS. It is based on Windows 10 but it supports UWP not Win32

So, is there any suggestion about platform selection to build ?

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
We use very little of the win32 API.
From what I see here, the socket api is available also for UWP apps:
https://learn.microsoft.com/en-us/uwp/win32-and-com/win32-apis

Try the win32 platform first.
Once we have visibility for the remaining problems we can find workarounds.
