### ISSUE TITLE
OPC-UA Device Integration XML creates invalid C-code

### ISSUE THREAD

**Issue by truschival** [open62541/open62541#578]
The XML-Namspace compiler ``generate_open62541CCode.py`` creates incorrect C-Code for the the xml specification Device Integration (DI) companion specification [https://opcfoundation.org/UADevices/1.1/Opc.Ua.Di.NodeSet2.xml] 

The XML defines nodes with  BrowseName ``1:&lt;MethodIdentifier&gt;`` and  ``<DisplayName>&lt;MethodIdentifier&gt;</DisplayName>``. (IMHO a quite shady cornercase) 
The script turns this into the macro `` #define UA_NS1ID_<METHODIDENTIFIER> 6018 `` which obviously is not correct C-Code.

**Comment by jpfr** [comment]
Good find.
Imho we can just filter out any characters besides [a-z0-9_].

@ichrispa Any strong opinions in that regard?

**Comment by Stasik0** [comment]
Or maybe be a bit paranoic and use the html encoded symbols like &gt; -> _GT_ or smth similar?

**Comment by truschival** [comment]
@jpfr I would not just filter them out (the identifier could become empty) but substitute with another ASCII symbol
@Stasik0  Since it is not in visible to the (end-) user I don't think it is _necessary _to come up with a list of specific meaningful substitutions like ``_GT_``. The problem is we would need a (quite long) list for all kinds of UTF symbols that are AFAIK valid XML.... But you have a point, the resulting name would be unique. 
That said, the situation is not as easy as it looked.... a possible solution is for every new node, create a name like today, if it contains a "forbidden character" substitute the forbidden characters with a ``_`` if the resulting symbol is already in the list of known node substitute it with something else...?

**Comment by truschival** [comment]
The developer will notice that the nodes have been renamed, I guess we should issue a warning during generation

**Comment by Stasik0** [comment]
Maybe just encode all utf8? http://stackoverflow.com/a/2365444a

**Comment by jpfr** [comment]
It's a starting point. `<` is still ASCII.

**Comment by ichrispa** [comment]
I am not sure how to handle these "special" cases. The aliases are there to assist with the C Code and make it a bit more readable. Having weird unicode or C patterns in browseNames is a weird case.

I would just shrug and remove them... otherwise yes for filtering during the print (which will generate the next problem: someone will complain about duplicate names).
