### ISSUE TITLE
Created Session remains in memory until the maxSessionTimeout expires on unexpected termination of the connection from the client.

### ISSUE THREAD

**Issue by engycz** [open62541/open62541#5809]
## Description
Created Session remains in memory until the maxSessionTimeout expires on unexpected termination of the connection from the client. The Session is only detached from SecureChannel. Session holds its Monitored items until the maxSessionTimeout expires, which default value is 60 minutes. On large systems, it's not a problem but on embedded systems, it consumes a significant part of the memory.

Shouldn't the associated sessions be removed when removing SecureChannel? Do we need to keep them in memory until the maxSessionTimeout expires?

**Comment by mlang-de** [comment]
May this helps you to understand the desired behavior.

https://reference.opcfoundation.org/Core/Part4/v104/docs/5.5 

> Once a Client has established a Session it may wish to access the Session from a different SecureChannel. The Client can do this by validating the new SecureChannel with the ActivateSession Service described in 5.6.3. 

> Each SecureChannel exists until it is explicitly closed or until the last token has expired and the overlap period has elapsed. A Server application should limit the number of SecureChannels. To protect against misbehaving Clients and denial of service attacks, the Server shall close the oldest SecureChannel that has no Session assigned before reaching the maximum number of supported SecureChannels.

https://reference.opcfoundation.org/Core/Part4/v104/docs/5.6

> Sessions are created to be independent of the underlying communications connection. Therefore, if a communications connection fails, the Session is not immediately affected. The exact mechanism to recover from an underlying communication connection error depends on the SecureChannel mapping as described in OPC 10000-6.

**Comment by engycz** [comment]
Okay, I understand.
