### ISSUE TITLE
X.509 certificate auth wrong security policy

### ISSUE THREAD

**Issue by Maddin-619** [open62541/open62541#5828]
While checking the auth token signature it is read in a comment that if found the security policy specifiyed by the token policy is used. But here always the channel security policy is used:
https://github.com/open62541/open62541/blob/1b7e2b5d669661c568fda5577ee92011a029cf75/src/server/ua_services_session.c#L784

There is a [PR](https://github.com/open62541/open62541/pull/5422) that fixes the Bug merged into the master brunch. But this commit never lands on the release branch. 

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 1.3.6
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [x] Critical issue

**Comment by V-Strassheim** [comment]
Hi Martin, looks like the change didn't make it into release 1.3.6.
But it is included on the branch for release 1.4:
https://github.com/open62541/open62541/blob/c72e52ac067ffa4af8a36f5bb6cd86b655ed2bec/src/server/ua_services_session.c#L783

Is the info enough to close the issue?
