### ISSUE TITLE
Put client connection into the config (change API before 0.2?)

### ISSUE THREAD

**Issue by jpfr** [open62541/open62541#583]
Hey there,

According to issue #567, I'd like to get comments on whether to make this breaking change before 0.2:

All the client connectivity functions take a connection function pointer as input.
```c
typedef UA_Connection (*UA_ConnectClientConnection)(UA_ConnectionConfig localConf,
                                                    const char *endpointUrl,
                                                    UA_Logger logger);

UA_StatusCode UA_EXPORT
UA_Client_connect(UA_Client *client, UA_ConnectClientConnection connFunc, const char *endpointUrl);
```

I'd like to put the connFunc pointer into the client config instead.
The two main reasons for this are:
- Most people will only use the standard TCP implementation.
So this pointer is a messy detail these users should not be forced to deal with.
- There is little reason to change the connection pointer between connections. It seems more logical to attach it to the client.

**Comment by HolgerJeromin** [comment]
Looks good to me

**Comment by FlorianPalm** [comment]
I am good with it. I think there is more to fix within the connection structure. To me it is quite confusing that we manage a localConf and a remoteConf (sendBufferSize/recvBufferSize on both sides).

**Comment by jpfr** [comment]
Related PR #585.

**Comment by ichrispa** [comment]
Yes, please make the connFunc vanish from connect - I think its counter-intuitiv in this context...

**Comment by jpfr** [comment]
#585 merged.
