### ISSUE TITLE
build failure 

### ISSUE THREAD

**Issue by wgm20096420** [open62541/open62541#5843]
E:\projects\cProject\open62541\build>cmake .. -G "MinGW Makefiles"
-- The C compiler identification is GNU 8.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/applications/qt/Tools/mingw810_32/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Python3: D:/applications/python3/python.exe (found version "3.11.4") found components:  Interpreter
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.35.1.windows.2")
......

E:\projects\cProject\open62541\build>cmake --build . --config Release
......

[ 90%] Building C object CMakeFiles/open62541-plugins.dir/arch/eventloop_posix_tcp.c.obj
E:\projects\cProject\open62541\arch\eventloop_posix_tcp.c: In function 'TCP_sendWithConnection':
E:\projects\cProject\open62541\arch\eventloop_posix_tcp.c:619:19: error: storage size of 'tmp_poll_fd' isn't known
     struct pollfd tmp_poll_fd;
                   ^~~~~~~~~~~
In file included from E:/projects/cProject/open62541/build/src_generated/open62541/config.h:560,
                 from E:\projects\cProject\open62541\arch\eventloop_posix.h:12,
                 from E:\projects\cProject\open62541\arch\eventloop_posix_tcp.c:9:
E:/projects/cProject/open62541/arch/win32/ua_architecture.h:76:20: error: 'POLLWRNORM' undeclared (first use in this function)
 #define UA_POLLOUT POLLWRNORM
                    ^~~~~~~~~~
E:/projects/cProject/open62541/arch/win32/ua_architecture.h:76:20: note: in definition of macro 'UA_POLLOUT'
 #define UA_POLLOUT POLLWRNORM
                    ^~~~~~~~~~
E:/projects/cProject/open62541/arch/win32/ua_architecture.h:76:20: note: each undeclared identifier is reported only once for each function it appears in
 #define UA_POLLOUT POLLWRNORM
                    ^~~~~~~~~~
E:/projects/cProject/open62541/arch/win32/ua_architecture.h:76:20: note: in definition of macro 'UA_POLLOUT'
 #define UA_POLLOUT POLLWRNORM
                    ^~~~~~~~~~
E:/projects/cProject/open62541/arch/win32/ua_architecture.h:87:35: error: implicit declaration of function 'WSAPoll'; did you mean 'WSANtohl'? [-Werror=implicit-function-declaration]
 #define UA_poll(fds,nfds,timeout) WSAPoll((LPWSAPOLLFD)fds, nfds, timeout)
                                   ^~~~~~~
E:/projects/cProject/open62541/arch/win32/ua_architecture.h:87:35: note: in definition of macro 'UA_poll'
 #define UA_poll(fds,nfds,timeout) WSAPoll((LPWSAPOLLFD)fds, nfds, timeout)
                                   ^~~~~~~
E:/projects/cProject/open62541/arch/win32/ua_architecture.h:87:35: error: nested extern declaration of 'WSAPoll' [-Werror=nested-externs]
 #define UA_poll(fds,nfds,timeout) WSAPoll((LPWSAPOLLFD)fds, nfds, timeout)
                                   ^~~~~~~
E:/projects/cProject/open62541/arch/win32/ua_architecture.h:87:35: note: in definition of macro 'UA_poll'
 #define UA_poll(fds,nfds,timeout) WSAPoll((LPWSAPOLLFD)fds, nfds, timeout)
                                   ^~~~~~~
E:/projects/cProject/open62541/arch/win32/ua_architecture.h:87:44: error: 'LPWSAPOLLFD' undeclared (first use in this function); did you mean 'LPWSABUF'?
 #define UA_poll(fds,nfds,timeout) WSAPoll((LPWSAPOLLFD)fds, nfds, timeout)
                                            ^~~~~~~~~~~
E:/projects/cProject/open62541/arch/win32/ua_architecture.h:87:44: note: in definition of macro 'UA_poll'
 #define UA_poll(fds,nfds,timeout) WSAPoll((LPWSAPOLLFD)fds, nfds, timeout)
                                            ^~~~~~~~~~~
E:\projects\cProject\open62541\arch\eventloop_posix_tcp.c:619:19: error: unused variable 'tmp_poll_fd' [-Werror=unused-variable]
     struct pollfd tmp_poll_fd;
                   ^~~~~~~~~~~
E:\projects\cProject\open62541\arch\eventloop_posix_tcp.c: At top level:
cc1.exe: error: unrecognized command line option '-Wno-static-in-inline' [-Werror]
cc1.exe: all warnings being treated as errors

**Comment by g-tardy** [comment]
hello there, I had the same issue when trying to compile version 1.4.x.

Was someone able to solve it, and how did they achieve it? Thanks!
