### ISSUE TITLE
How to transfer sensor data (fast): Subscription (sample rate) vs. PubSub?

### ISSUE THREAD

**Issue by Rehcsif** [open62541/open62541#5873]
## Description
I want to transmit measurement data from a sensor via OPC UA. I wonder which transfer method fits best. I have a measurement value which is updated at 10 kHz (applications with up to 100 kHz could be possible).

## Background Information
The idea was to either create a subscription with samplerate 100 us and queue size 1000 (publish rate 100ms). However, it does not seem to be suitable to use subscriptions for such high data rates? The Server-Config states, that sampling intervals below 5ms are not possible. This would be far away from the intended 100 us. 
https://github.com/open62541/open62541/blob/258d6ad8472e879a19c8eb36779d2f77e6d90f27/include/open62541/server.h#L308

There is a [issue](https://github.com/open62541/open62541/issues/5759) mentioning that a lower `samplingIntervalLimits` is possible, but I don't know if it's realistic to reach 100 us or less?
Should such values then instead rather be transmitted via PubSub?

Thanks for clarification!

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): v1.3.6
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

## Related issues
- https://github.com/open62541/open62541/issues/5759

**Comment by jpfr** [comment]
Try to vary the sampling interval (MonitoredItem) independent from the publishing interval (Subscription). You will end up with many samples transmitted with a single packet, that saves a lot of resources.

if you need even more speed, try PubSub with the real-time fast path enabled. But there you will end up with one sample per publishing interval. On top of that, you could define a backend that fills up an array value with samples. And transmit that with a single publish.

**Comment by jpfr** [comment]
If the sample rate shall be 100us, that is 10kHz, and your platform does updates at 1.3khz, then you have to consider two bottlenecks:

- Malloc requires about 300 CPU cycles if you store each sample individually (which the subscription algorithm does)
- Making a lookup of a node in the information model has a similar computational requirement. Depending a bit on the size of the information model.

With an array to store multiple measurements and the PubSub fastpath you can get rid of both.
