### ISSUE TITLE
Example Code in Current Document  "Creating object instances" not  work

### ISSUE THREAD

**Issue by YangXinyu** [open62541/open62541#589]
When i run  the example in current document "create object instances" , it shows errors:

Undefined symbols for architecture x86_64:
  "_UA_Server_addInstanceOf", referenced from:
      _main in myServer-a6d8c6.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

And i can not find the method: UA_Server_addInstanceOf() in the document and code ....

i have run the example code to compile XML Namespaces and it works fine, but the "create object instance" can not work. 

Can somebody tell me , how to create a object instance use open62541?

Thank you !

**Comment by ichrispa** [comment]
Hi @YangXinyu,

the document references a highlevel function that was removed. A partial reimplementation is now part of addObjectNode - by handing it a typedefinition nodeId, the instantiation will take place automatically. Just use addObjectNode instead.

I will remove the given tutorial page in due course - sorry for the inconvinience.

Best regards,

ichrispa
