### ISSUE TITLE
Decoding Error on Valid ReadResponse

### ISSUE THREAD

**Issue by wbitesi** [open62541/open62541#5911]
## Description

BadDecodingError on valid server (ReadResponse) response.

## Background Information / Reproduction Steps

I have attached the program to generate the error (decode_timestamp_neither.cpp) The log output is attached in error.log

The error occurs because all DataValues in the response are completely empty.
If at least the server timestamp is included (decode_timestamp_neither.cpp) the message gets decoded correctly.
A wireshark dump is attached. The first part is without decoding error (timestamps are included) the second part is with empty DataValues with the BadDecodingError.

The piece of code that is responsible for getting the decoding error is in function

static status
Array_decodeBinary(void *UA_RESTRICT *UA_RESTRICT dst, size_t *out_length,
                   const UA_DataType *type, Ctx *ctx) {

....

    /* Filter out arrays that can obviously not be decoded, because the message
     * is too small for the array length. This prevents the allocation of very
     * long arrays for bogus messages.*/
    size_t length = (size_t)signed_length;
    if(ctx->pos + ((type->memSize * length) / 32) > ctx->end)
        return UA_STATUSCODE_BADDECODINGERROR;

I have no idea what this piece of code should achieve, but it does not work properly in this case.

```bash
cmake -DUA_NAMESPACE_ZERO=FULL
```

## Checklist

Please provide the following information:

 - [X] open62541 Version (release number or git tag): 1.2.2 and 1.2.7
 - [X] Other OPC UA SDKs used (client or server): UaCppServer 1.7.7
 - [X] Operating system: Windows and Linux
 - [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [x] Wireshark network dump attached
 - [X] Self-contained code example attached
 - [X] Critical issue
[BadDecodingError.zip](https://github.com/open62541/open62541/files/12216351/BadDecodingError.zip)

**Comment by jpfr** [comment]
Right. We will fix that.
This code prevents memory exhaustian.
Otherwise somebody could say "I have this one billion element array" which is in this 500 byte-long message.
So we check that the relation between message length and array size is reasonable.

It appears you ran into an edge case that was not covered.
UA_DataValue internally is 80 byte long. But can be expressed in only one byte in the message.

The fix for 1.2 is in #5917 and will be front-ported to 1.3, 1.4 and master.
