### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by tpiat** [open62541/open62541#593]
I have download zip file, 
```
cmake.exe .. -G "MinGW Makefiles" -DUA_BUILD_EXAMPLESERVER=1 -DUA_BUILD_EXAMPLECLIENT=1 -DUA_ENABLE_AMALGAMATION=1 -DUA_ENABLE_SUBSCRIPTIONS=1
mingw32-make.exe
```
And then I have error.
E:\opcua\open62541-master.25\build\open62541.c:2710: error: redefinition of typedef 'UA_Subscription'
E:\opcua\open62541-master.25\build\open62541.c:2003: note: previous declaration of 'UA_Subscription' was here

UA_Subscription declared twice.
Line 2004
```
struct UA_Subscription;
typedef struct UA_Subscription UA_Subscription;
```
and  next
```
typedef struct UA_Subscription {
....
} UA_Subscription;
```
I must use gcc 4.4.0.
In 4.6.2 it compiled successfully.

If remove line 
typedef struct UA_Subscription UA_Subscription;
and change all "UA_Subscription" to "struct UA_Subscription" I have no errors.

Probably need change order of file in make script.

PS. opne62541.c compiled without errors when dowloaded from http://open62541.org/releases/77cc480499.zip, UA_ENABLE_SUBSCRIPTIONS not defined.

**Comment by Stasik0** [comment]
which release do you use? 77cc480499?
