### ISSUE TITLE
UaExpert complains about invalid datatype for NodeClass

### ISSUE THREAD

**Issue by NetoLe** [open62541/open62541#595]
Hello,

since the latest updates I have a problem which is that UaExpert complains about the Type of the NodeClass.

![nodeclass](https://cloud.githubusercontent.com/assets/16148176/14816351/a3e3b09c-0bb0-11e6-80e7-9b498e29091f.PNG)
that doesn't influence the functionality of the server but seems a bit not correct.

**Comment by Kruno313** [comment]
Same here.
I build it for the first time and tought it's normal.
Also amalgamated build do not work, and the demo server.c uses UA_ServerNetworkLayerTCP() with thre parameters. Had to make changes in it and build and against .so library.

**Comment by Stasik0** [comment]
I though, 1cb82777b578f3273d35251b2552e88c288955d9 was supposed to fix it?

**Comment by Kruno313** [comment]
I'm not sure what is affected with that change.
I pulled my source with 'git clone https://github.com/acplt/open62541'  as
described here:
http://open62541.org/doc/current/tutorial_server_firstSteps.html#prerequisites
and compiled it as described in the next chapter of the same link.
The demo server source in
http://open62541.org/doc/current/tutorial_server_firstSteps.html#creating-your-first-server
does not compile without two small changes and than, it has this issue.

2016-04-26 15:02 GMT+02:00 Sten Grüner <notifications@github.com>:

**Comment by Stasik0** [comment]
when did you pull it? which version of uaexpert do you use?

**Comment by Stasik0** [comment]
okay, I can confirm it

**Comment by Kruno313** [comment]
I pulled it last week, thursday or friday.
I'l try it again.

2016-04-26 15:18 GMT+02:00 Sten Grüner <notifications@github.com>:

**Comment by Kruno313** [comment]
It works fine now!
Just buildt it fresh and it's perfect.
Thanks

2016-04-26 15:21 GMT+02:00 krunoslav ostrouska <
krunoslav.ostrouska@gmail.com>:

**Comment by Stasik0** [comment]
@NetoLe can you confirm it?

**Comment by Stasik0** [comment]
@Kruno313 nice to hear it

**Comment by ichrispa** [comment]
I can also confirm that @jpfrs fix has corrected this problem.

**Comment by NetoLe** [comment]
confirmed. thanks :)
