### ISSUE TITLE
Tools directory of installed library is wrong

### ISSUE THREAD

**Issue by ccvca** [open62541/open62541#5956]
## Description
In https://github.com/open62541/open62541/commit/7547a8a9dc0b64eaf7a568305d82a78da6a6a6a1#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL25
`set(open62541_TOOLS_DIR "${PROJECT_SOURCE_DIR}/tools")` moved from `CMakeLists.txt` to `/tools/cmake/macros_public.cmake`. 

https://github.com/open62541/open62541/blob/bd994c1609478e6cf2732b3671c55ab459cc8974/tools/cmake/macros_public.cmake#L1
When importing the library with `find_package(open62541 REQUIRED)` this results in a tools directory like this: `/home/user/UmatiServerDev/open62541_update/Sample-Server/tools`.

Then an error like this appears:
```
gmake[5]: *** Keine Regel vorhanden, um das Ziel „../../tools/nodeset_compiler/nodeset_compiler.py“, 
  benötigt von „../../src_generated/namespace_irdi_generated.c“, zu erstellen.  Schluss.
```

The path is correctly set in the Config-Script here:
https://github.com/open62541/open62541/blob/bd994c1609478e6cf2732b3671c55ab459cc8974/tools/cmake/open62541Config.cmake.in#L5

```
set (open62541_TOOLS_DIR ${PACKAGE_PREFIX_DIR}/share/open62541/tools CACHE PATH "Path to the directory that contains the tooling of the stack")
```

but as the macros are included, the wrong path is used later on.

## Possible fixes

- Move `set (open62541_TOOLS_DIR ...` to CMakeLists.txt again
- Check if open62541_TOOLS_DIR is already set before setting the 'fallback' `${PROJECT_SOURCE_DIR}/tools`

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): bd994c1609478e6cf2732b3671c55ab459cc8974
 - [x] Operating system: Debian
 - [x] Critical issue

**Comment by GoetzGoerisch** [comment]
@jpfr could you please have a look?

**Comment by jpfr** [comment]
I prefer option No. 2
