### ISSUE TITLE
TRANSPORT_PROFILE_URI in the MQTT examples are wrong

### ISSUE THREAD

**Issue by tukotech** [open62541/open62541#5990]
## Background Information / Reproduction Steps
Build with examples on. Then run open62541/build/bin/examples/tutorial_pubsub_mqtt_publish. This was tested on Ubuntu 23.04. 

Used CMake options:
```bash
cmake -DUA_NAMESPACE_ZERO=FULL -DUA_MULTITHREADING=100 -DCMAKE_BUILD_TYPE=Debug -DUA_ENABLE_PUBSUB=ON -DUA_BUILD_EXAMPLES=ON -DUA_ENABLE_MQTT=ON -DUA_ENABLE_PUBSUB_MONITORING=ON -DUA_LOGLEVEL=100 -DUA_ENABLE_JSON_ENCODING=ON -DUA_ENABLE_PUBSUB_INFORMATIONMODEL=ON ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): master and v1.3.6
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Ubuntu 23.04
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

This is the same issue as #5977 - but I wanted to fix this. I will be submitting a PR soon.

**Comment by jpfr** [comment]
@tukotech 
Great, looking forward to the PR.
