### ISSUE TITLE
endiannes problem with gcc

### ISSUE THREAD

**Issue by NetoLe** [open62541/open62541#600]
Well this is not directly related to the stack. 
I am using an ARM device with little endian order and compile with gcc 4.5.1. (none of the OS mentioned is true for me) 
But it gives me the warning that it is using the slow integer variants, which shouldn't be. 
I checked the flags with:
```
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
# warning little endian order
#if defined(__BYTE_ORDER__) && defined(__ORDER_LITTLE_ENDIAN__)
# warning both defined
#endif
#else
# warning big endian order
#endif
```

first gets true, but second doesn't. So just " little endian order" is put out. that's weird. 
Well by knowing what architecture I am using I can simply define the overlayables true. But it would be good to know, why this fails.

**Comment by jpfr** [comment]
The C99 standard specifies at §6.10.1 ¶3:
> After all replacements due to macro expansion and the defined unary operator have been performed, all remaining identifiers are replaced with the pp-number 0.

Probably `__BYTE_ORDER__` and `ORDER_LITTLE_ENDIAN` are both undefined in your compiler...
