### ISSUE TITLE
The server is writeable 

### ISSUE THREAD

**Issue by NetoLe** [open62541/open62541#601]
Well, hit the enter key by accident, sorry.

So I can write anything on the server. Even the Server-specific nodes that surely never should be changed can be rewritten with a simple client (UaExpert in this case), even the start time of the server and the profile URIs.

I found some "writeMask" points in the Stack, and the spec tells about the WriteMask for the attributes at two points:

> The WriteMask Attribute is a 32-bit unsigned integer with the structure defined in Table 3. If the bit is set to 0, it means the Attribute is not writable, if it is set to 1, it means it is writable. If a Node does not support a specific Attribute, the corresponding bit has to be set to 0.

- Part 3, p. 14 
So UaExpert tells me the whole WriteMask is 0, which means it should not be writeable.

> Optionally the WriteMask Attribute can be provided. If the WriteMask Attribute is provided, it shall set all Attributes to not writable that are not said to be vendor-specific.

- Part 5, p.4

So how can I prevent a Client from rewriting the Nodes in the server, without deactivating the whole write-Service? (that's what I've done before)

**Comment by jpfr** [comment]
Security and access control is not implemented so far.
You can just add checks for the writeMask/userWriteMask, accessLevel/userAccessLevel, and so on in ua_services_attributes.c.

We have not done this so far for a simple reason. Currently we have a fixed userWriteMask integer in the node. But access control should take different users into accounts.

We will probably add an access control plugin API in the mid-term future. The plugin offers a callback that returns access rights **for the current user**. And you can write your own implementation that queries the Windows domain, Unix PAM, and so on.

But that will not happen prior to 0.2.
