### ISSUE TITLE
QUESTION: Can the NodeSet compiler compile PubSub nodes

### ISSUE THREAD

**Issue by MarkoMuc** [open62541/open62541#6020]
## Question

Can the NodeSet Compiler compile XML NodeSets with PubSub Nodes (e.g. PubSubConnectionsType)?

**Comment by AsishGanesh1** [comment]
Yes. NodeSet compiler can compile XML Nodesets with PubSub Nodes.
Set UA_NAMESPACE_ZERO cmake configuration FULL to compile PubSub nodes.

**Comment by MarkoMuc** [comment]
Thank you for answering my question, have a great day.
