### ISSUE TITLE
[CMake] deprecated syntax

### ISSUE THREAD

**Issue by OgreTransporter** [open62541/open62541#6141]
https://github.com/open62541/open62541/blob/08d2cbeca26683732721d29c768cfb535e20cc73/tools/cmake/open62541Config.cmake.in#L9

https://cmake.org/cmake/help/latest/module/FindPythonInterp.html
> FindPythonInterp
> ----------------
> 
> .. versionchanged:: 3.27
>   This module is available only if policy :policy:`CMP0148` is not set to ``NEW``.
> 
> .. deprecated:: 3.12
> 
>   Use :module:`FindPython3`, :module:`FindPython2` or :module:`FindPython` instead.

There is no module for `PythonInterp` anymore. The syntax must be as follows:

```
find_dependency(Python3 COMPONENTS Interpreter REQUIRED)
```

**Comment by jeroendoggen** [comment]
Can be closed. (fixed: https://github.com/open62541/open62541/commit/151aecc03c256a68c38dbdef58f3a7e74c6865f1)
