### ISSUE TITLE
linux 64 bit Server by UACTT server test issue

### ISSUE THREAD

**Issue by ilike28** [open62541/open62541#615]
Does v0.2 linux sdk pass all of the uactt test now @@?
I got the following issue when I test the linux opc-ua server which in the virtual box(Ubuntu 16.04).

![a](https://cloud.githubusercontent.com/assets/19503973/15448060/35290d78-1f88-11e6-97ea-1a85a9103907.png)

**Comment by Stasik0** [comment]
Not yet, we are working on it.
