### ISSUE TITLE
incorrect ArrayDimensions for scalar values

### ISSUE THREAD

**Issue by csmucsi** [open62541/open62541#6150]
## Description

According to the OPC UA specification part 5.3
	
_If the ValueRank does not identify an array of a specific dimension (i.e. ValueRank <= 0) the ArrayDimensions can either be set to null or the Attribute is missing. This behaviour is server-specific._

see https://reference.opcfoundation.org/Core/Part5/v104/docs/5.3

When I compile and run the provided server example, ArrayDimensions contains UInt32[-1] which is probably incorrect.

## Background Information / Reproduction Steps

Compile and run the default example "server.cpp" and observe ArrayDimensions of any scalar value in a client e.g. UAExpert.

The problem seems to be in the function called "readWithNode"

```
 case UA_ATTRIBUTEID_ARRAYDIMENSIONS:
        CHECK_NODECLASS(UA_NODECLASS_VARIABLE | UA_NODECLASS_VARIABLETYPE);
        retval = UA_Variant_setArrayCopy(&v->value, node->variableTypeNode.arrayDimensions,
                                         node->variableTypeNode.arrayDimensionsSize,
                                         &UA_TYPES[UA_TYPES_UINT32]);
        break;

```
Possible fix: make sure to return an empty variant when valueRank is negative, e.g.:
```
    case UA_ATTRIBUTEID_ARRAYDIMENSIONS:
        CHECK_NODECLASS(UA_NODECLASS_VARIABLE | UA_NODECLASS_VARIABLETYPE);
        if (node->variableTypeNode.valueRank >= 0) {
          // old code - only when valueRank is not negative
          retval = UA_Variant_setArrayCopy(&v->value, node->variableTypeNode.arrayDimensions,
                                         node->variableTypeNode.arrayDimensionsSize,
                                         &UA_TYPES[UA_TYPES_UINT32]);
        } else {
          retval = UA_STATUSCODE_GOOD;
          // FIX: should return a null
          UA_Variant_clear(&v->value); 
        }
        break;
```

Used CMake options:

none

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 1.3.8
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Ubuntu
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

![bug](https://github.com/open62541/open62541/assets/9932151/02d67554-eb53-4a2c-9d9b-902187c87f98)

![bugFixed](https://github.com/open62541/open62541/assets/9932151/2f02253d-435a-496e-824e-c93a4f659ccf)

**Comment by jpfr** [comment]
Empty arrays in opc UA can have two types of length. Zero or -1.

-1 is for null arrays that don’t even have a length.

this behavior is tested with the CB conformance testing tools. And we are passing.
