### ISSUE TITLE
Creating Subscription to Rockwell Factory Talk OPCUA Server results in BadTooManyPublishRequests

### ISSUE THREAD

**Issue by pemartin2** [open62541/open62541#6156]
## Description
I am connecting with an open62541 client to a  Rockwell Factory Talk server. I try to create a subscription to Rockwell OPCUA server using basically the client_subscription_loop sample (https://github.com/open62541/open62541/blob/v1.3.9/examples/client_subscription_loop.c, see used code here https://paste2.org/7keJydhB)). At the moment of creating a subscription I get an warning message in the client "The ServiceResult has the StatusCode BadTooManyPublishRequests" " Received a ServiceFault response. Too many publishrequest, reduce outStandingPublishRequests to [x]". Except this, subscription seems to work fine in general. 

If I understand correctly from here (https://github.com/FreeOpcUa/python-opcua/discussions/1430) this is in the first way a server issue. However, as can be seen from the client log open62541 sends ~10 PublishRequests in ~12ms...

Is there any way I can influence this warning from client-side? I tried to play around with `UA_Client_Subscription.publishingInterval` and     `UA_Double samplingInterval`. Anything else which I could do from client-side to omit this?

## Background Information / Reproduction Steps

Run the slightly modified code from client_subscription_loop sample (https://paste2.org/7keJydhB)

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 1.3.9
 - [x] Other OPC UA SDKs used (client or server): Rockwell Factory Talk Linx Gateway, V 6.31.00
 - [x] Operating system: Win 10
 - [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [x] Wireshark network dump attached: https://filebin.net/6lfojgn3nddzs1hv
 - [client] Self-contained code example attached: Client-side: https://paste2.org/7keJydhB
 - [ ] Critical issue

**Comment by jpfr** [comment]
This is normal behavior.
The clients sends a configurable initial amount of publish requests.
When that is already too much, it will reduce the number of publish requests that can be in flight.

the server should always have a few publish requests outstanding. So he cans answer immediately when notifications shall be sent out.

**Comment by pemartin2** [comment]
Ok. I did not know those warnings were expected. Thank you very much.

**Comment by pemartin2** [comment]
Just for reference if someone else has the same issue. The respective parameter related to this is `outStandingPublishRequests` in `UA_ClientConfig`.
