### ISSUE TITLE
linux 64 bit Server Subscription issue - v0.2

### ISSUE THREAD

**Issue by ilike28** [open62541/open62541#616]
After first connect to the linux server , I used opc foundation DA client monitor the "current time" node.
I change the Subscription Intervaltime to 5000ms.
It work!
But I want to change the Intervaltime  to the other , it not work.
Even if I re-open the Server and Client, it Intervaltime  still keep in 5000 ms @@! 

![b](https://cloud.githubusercontent.com/assets/19503973/15449430/48c38cd2-1fb0-11e6-9dc8-45c2bc52ec48.png)

**Comment by jpfr** [comment]
Does it work for you now?

**Comment by ilike28** [comment]
no~~ 
But I re-download the sdk file and re-build.
Never appeared this problem~
