### ISSUE TITLE
UA_Client_connect - getendpoint problem - sdk v0.2

### ISSUE THREAD

**Issue by ilike28** [open62541/open62541#617]
I use client in the ubuntu of virtual box and open a opc foundation server on the win 7.

The server address is opc.tcp://pc20140604c:62541/Quickstarts/ReferenceServer.
I can ping pc20140604c in the ubuntu .
But ,when I use UA_Client_connect function which  show the "GetEndpointRequest fail" durning the connect state !

Does anyone know how to fix this problem??

Thanks~~

![a1](https://cloud.githubusercontent.com/assets/19503973/15510915/0699d11e-220c-11e6-8f42-0e964dede474.png)

**Comment by Stasik0** [comment]
hey, could you post a link to the server you are using?

**Comment by jpfr** [comment]
I just pushed a patch to 0.2 so that more statuscodes are logged for the client.

@ilike28 Can you just redo your tests with the current 0.2 branch and post the logs?
My guess is that the server allows encrypted connections only.

**Comment by ilike28** [comment]
I got the following statecode by the new v0.2 SDK 

![default](https://cloud.githubusercontent.com/assets/19503973/15645753/e6c26574-268c-11e6-9542-afffe79617ce.png)

**Comment by Stasik0** [comment]
@ilike28 it seems to be our bug, getting endpoints should be possible without encryption, i will look into it

**Comment by Stasik0** [comment]
@ilike28 please try it now, we had a problem with the local config missmatch

**Comment by ilike28** [comment]
It can work now !!
Thank you very~~~~~ much ^^!

![default](https://cloud.githubusercontent.com/assets/19503973/15660132/4b3a5ea8-270a-11e6-832c-07201e52fea2.png)
