### ISSUE TITLE
UA_Client  - UACTT -Server test -initializes.js problem - sdk v0.2

### ISSUE THREAD

**Issue by ilike28** [open62541/open62541#620]
The UACTT Server test run the initializes.js  before all of the test case.
And it got the following issue.
Read.Response.ResponseHeader.ServiceResult is Bad: BadInternalError(0x80020000)

Does anyone know how to fix this problem??

Thanks~~

![default](https://cloud.githubusercontent.com/assets/19503973/15661500/8514c1ee-271a-11e6-9c2e-e554b8a56152.png)

**Comment by ilike28** [comment]
update the fail point @@~
Does anyone get the same issue during CTT Server test?

![c1](https://cloud.githubusercontent.com/assets/19503973/15712059/5e07b6ae-2843-11e6-8929-74668c75bbba.png)

![c2](https://cloud.githubusercontent.com/assets/19503973/15712062/61623afe-2843-11e6-8c71-c9f5aa92d5c5.png)

**Comment by Stasik0** [comment]
@ilike28 this is what i see here with the latest commit c1d7abf7de77bdd5928ea846513ef45058f8bf72

![screenshot from 2016-06-01 17 28 44](https://cloud.githubusercontent.com/assets/469170/15715606/61b0339a-281f-11e6-9fad-0a3144515b10.png)

Which CTT version are you using?

**Comment by ilike28** [comment]
I use version 1.2.336.256.
And download the CTT test Project from : https://github.com/open62541/open62541-ctt.
@@

**Comment by ilike28** [comment]
I upload a video to show my building and testing step~ 
https://drive.google.com/file/d/0B5VqbFqMszDhYzljcnFITktuRDg/view?usp=sharing

**Comment by jpfr** [comment]
Fixed in commit 6d65901096afc79b9e7ff1835c2a4a95481638e0.
The generated namespace contains variants that are never given any content.
Those are handled correctly now.

**Comment by ilike28** [comment]
@jpfr 
Thanks ^^
