### ISSUE TITLE
Writing to OPC UA server nodes from an MQTT Broker

### ISSUE THREAD

**Issue by tedwad** [open62541/open62541#6212]
## Description

I have some basic questions about the interaction between OPC UA PubSub and MQTT. I have created an OPC UA server using a custom information model. I also have data being published as a list of strings to a remote Mosquitto broker at test.mosquitto.org:1883. I want to parse through the data from the MQTT broker and publish the values into specific nodes of the OPC UA server. In this way, my MQTT broker would act as a publisher and my OPC UA server as a subscriber. 

My questions are, 
1. Can a OPC UA PubSub server subscribe to a remote MQTT broker?
2. If so, does the broker have to be receiving data from another OPC UA Server, or can the data come from any source?
3. If the described approach is feasible, how can I get data from the broker into the nodes of my information model? 

I saw in this [post](https://github.com/open62541/open62541/issues/4215) that someone was able to publish to the mosquitto broker from their OPC UA server, is it possible to do the same in reverse?

## Background Information / Reproduction Steps
I tried combining the steps from the tutorial_pubsub_mqtt_subscribe.c example and the custom information model guide from the documentation, and ended up with the following [main.c](https://github.com/open62541/open62541/files/13845083/main.txt) file. Although the file compiles fine, I end up with the following output:

![Screenshot from 2024-01-05 01-26-15](https://github.com/open62541/open62541/assets/89061708/6274a062-c3a6-4240-845f-bc4cf951ca13)

I am not sure if I am approaching this problem correctly. I would very much appreciate if someone could point me in the right direction if there is a better way to do this!

Used CMake options:

```bash
cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo  -DUA_NAMESPACE_ZERO=FULL -DUA_ENABLE_PUBSUB=ON -DUA_ENABLE_PUBSUB_INFORMATIONMODEL=ON ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): master
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Ubuntu 20.04.5
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
You should add MQTT support to the build flags.
This all works…. But: the messages on MQTT need to be OPC UA PubSub messages, not just any MQTT.
If you look at our internal MQTT API in /include/open62541/plugins/eventloop.h you might have an easier time spinning up your own MQTT client, atttached to the EventLoop of the OPC UA server, and process the incoming data in your own callback method. There you can write the data to the nodes.

**Comment by tedwad** [comment]
Would you suggest using the mqtt-c library to create the MQTT client and attaching it to the EventLoop of the server? Or is creating the MQTT client possible using only the definitions from including the eventloop.h header file?

**Comment by jpfr** [comment]
The MQTT-C library was wrapped to be used for our PubSub subsystem.
You only need the definitions from eventloop.h to use it.

**Comment by jpfr** [comment]
This is the internal creation of a MQTT subscriber for PubSub:
https://github.com/open62541/open62541/blob/aa98741b4f9dacd89bceb36cbd5846b1a40e8b1f/src/pubsub/ua_pubsub_eventloop.c#L892

**Comment by tedwad** [comment]
I managed to get my application working by following your suggestion, thank you for all the help!
