### ISSUE TITLE
C#怎么调用

### ISSUE THREAD

**Issue by aligarduo** [open62541/open62541#6222]
你好！请问 C# 该如何调用呢？

**Comment by jpfr** [comment]
The majority here does not speak Chinese…
Please use a translation tool like DeepL.

that gives:
> Hello! How should I call this in C#?

this is a genera l question best answers via Google.
https://stackoverflow.com/questions/11425202/is-it-possible-to-call-a-c-function-from-c-net#:~:text=You%20can%20directly%20call%20C,wraps%20around%20a%20C%20dll.&text=Now%20in%20the%20Linker%20branch,to%20the%20C%23%20project%20root.
