### ISSUE TITLE
[Question] open62541 linux v0.2 client - subscription/monitoritem

### ISSUE THREAD

**Issue by ilike28** [open62541/open62541#626]
I saw the open62541 server has the Modify subscription feature.
But I don't see any modify function in the src/client/ua_client_highlevel_subscriptions.c .
just see the following function :+1: 

UA_Client_Subscriptions_new
UA_Client_Subscriptions_remove
UA_Client_Subscriptions_addMonitoredItem
UA_Client_Subscriptions_removeMonitoredItem
UA_Client_processPublishResponse
UA_Client_Subscriptions_manuallySendPublishRequest

Does the client have the modify subscription/monitoritem feature??

Thanks.

**Comment by jpfr** [comment]
Yes. There is no "highlevel" convenience function.
But you can just use the raw service: https://github.com/open62541/open62541/blob/0.2/include/ua_client.h#L279
