### ISSUE TITLE
PubSub: Sending NULL values in dataSetMessages with rawData field encoding crashes the application

### ISSUE THREAD

**Issue by MichalTyndel** [open62541/open62541#6260]
## Description

Variables with NULL values can be created (even if the dataType is not baseDataType). For PubSub messages with variant field encoding this is no issue, since empty variants can be sent. If we try to send message with rawData field encoding encoder crashes.

## Background Information / Reproduction Steps

[rawDataCrash.txt](https://github.com/open62541/open62541/files/14124308/rawDataCrash.txt)  
Attached is example code (c file saved as txt...), that can be used to reproduce this crash. It creates DataSetWriter -> DataSetReader pair that exchanges a single variable using UDP over localhost. When the program is run with "dynamic" argument it works fine, when run with "fixed" argument the program crashes.

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): v1.4.0-rc2-162-gcc806cb47
 - [x] Self-contained code example attached

**Comment by jpfr** [comment]
Thanks for providing the reproducer. Fixed in #6283.
This now generates an error when we try to do a RAW encoding when there is no value.
The code only worked with master.
But the fix is done for 1.4 already.
