### ISSUE TITLE
Default log level changed with refactoring commit

### ISSUE THREAD

**Issue by keba-estr** [open62541/open62541#6290]
The default log level change with commit 0271f505799a7a44cc99da06277071d2cdbdf5e6 ("refactor(server): Only use logging-pointer instead of inline structure")

In ua_config_default.c the logger was previously initialized with UA_Log_Stdout_withLevel(UA_LOGLEVEL_INFO), which was changed to UA_Log_Stdout.
@jpfr: What is the reason for the change?

 - [X] open62541 Version (release number or git tag): 1.4-rc2

**Comment by jpfr** [comment]
Changed back to the old default in #6293.
We have put the logging plugin on the heap.
Because we kept pointers to it in other plugins. And this got ugly when the configuration was moved "into" the server.
