### ISSUE TITLE
Client Connect/Disconnect

### ISSUE THREAD

**Issue by TorbenD** [open62541/open62541#631]
- If the client wants to disconnect, the state of the client stays still the same. Therefore you cannot connect again. 
- Furthermore the sockets should be freed
- If there is a connection between the client and the server and i want to connect to another server, the function only returns a Good-Status instead of checking if this is the same server (should there be the option to connect to more than one server? if not, then there must be a Error-Status with the information that the client first have to disconnect)

**Comment by Stasik0** [comment]
*does calling "UA_Client_reset" after disconnect help?
*are the sockets not freed? should be done here https://github.com/open62541/open62541/blob/0.2/src/client/ua_client.c#L543
*as far as I see, you should use another UA_Client object to connect to another server
