### ISSUE TITLE
Question: Is it possible to get variable type during browse request?

### ISSUE THREAD

**Issue by ivan-ushakov** [open62541/open62541#6312]
I use `UA_Client_Service_browse` to get all variables available on server. I also need to know variable data type. Is it possible to know this type without reading variable by node id?

**Comment by basyskom-jvoe** [comment]
The ReferenceDescription struct returned by the Browse service only contains the node ID of the type definition for object and variable nodes.
If your VariableType doesn't have a fixed data type, you'll have to read the DataType attribute of the variable node.
