### ISSUE TITLE
`UA_Client_run_iterate()` possibly not thread-safe?

### ISSUE THREAD

**Issue by sgoll** [open62541/open62541#6364]
## Description

The function `UA_Client_run_iterate()` is marked with `UA_THREADSAFE`, indicating that it can safely be called concurrently with other calls to it and other functions on the same `UA_Client` instance.

However, the first call inside that function is to `__UA_Client_startup()` which in turn seems to assume that the client mutex has already been locked outside that function:

https://github.com/open62541/open62541/blob/0bd65af85b49c29b626ef8163e1b22d6f1427737/src/client/ua_client.c#L1023-L1024

Inside that function is what looks like a possible race condition with `client->houseKeepingCallbackId`. When this is checked by two concurrent calls, they might register the cyclic callback twice.

What is the reason why `UA_Client_run_iterate()` can still be regarded as being thread-safe?

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): master branch, commit 0bd65af85b49c29b626ef8163e1b22d6f1427737
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Good find. This is now changed in #6379.
It wasn't super-critical, as the function mostly called into the EventLoop.
Which takes its own lock internally.

But, since client-internal state is changed, taking the client lock is the correct way.
