### ISSUE TITLE
Version 1.4 not buildable with debian buster

### ISSUE THREAD

**Issue by keba-estr** [open62541/open62541#6395]
## Description

libopen62541 needs at least libmbedtls-dev (>= 2.28.0) in the control-template. Debian buster only has version 2.16.0-1.

Dependency to libmbedtls is only done for libmbedtls14, not libmbedtls12 and libmbedtls10 any more

Due to Commit: 9e0b766fbba73be8d703b6ccbfdeec5bfd200b48 (PR #6369)

## Checklist

Please provide the following information:

 - [X] open62541 Version (release number or git tag): 1.4
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by keba-estr** [comment]
@jpfr: Why is debian buster not supported any more?

**Comment by jpfr** [comment]
You are right. Buster is two versions behind Debian stable.
But it still receives Long-Term-Support.
The dependency can be reduced to older versions of mbedTLS.

**Comment by keba-estr** [comment]
Compilable for debian buster with libmbedtls-dev (>= 2.16.0) and dependency to libmbedtls12 | libmbedtls14

**Comment by jpfr** [comment]
Fixed on 1.4.
