### ISSUE TITLE
Error comunicación OPC UA Cliente S7 TiaPortal V16

### ISSUE THREAD

**Issue by Bieitokalvo** [open62541/open62541#6398]
Hola,

quiero comunicar OPC UA Server de Robotino View, es de open62541, con un cliente de S7 1500 Tia Portal V16.

Creado el Cliente OPC UA en S7 me indica error de conexión con OPC UA Server de Robotino 4 por Error 8005:0000.
Dos opciones:
- Causa dirección del servidor: NO PUES LO VEO.
- Tamaño bufer permitido: el cliente de la CPU S7-1500 proporciona 8192 bytes. ¿El servidor acepta este valor?

¿Conoces la solución?

Saludos

## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Sorry, but this is an international project.
English is standard.

The AI translators are quit good now.
Please reopen when we can interact with you.
