### ISSUE TITLE
Version 1.4 not linkable with debian linux

### ISSUE THREAD

**Issue by keba-estr** [open62541/open62541#6400]
## Description
Linking the open62541 does not work any more on linux systems, as the files libopen62541.so (and libopen62541.a, not relevant for dynamic linking) have been removed from the dev debian package.

Changed in commit https://github.com/open62541/open62541/commit/9e0b766fbba73be8d703b6ccbfdeec5bfd200b48 (PR https://github.com/open62541/open62541/pull/6369)

## Checklist

Please provide the following information:

 - [X] open62541 Version (release number or git tag): 1.4
 - [X] Operating system: Debian Linux

**Comment by jpfr** [comment]
I checked locally and it works.
1. Create the debian build environment with /tools/prepare_packaging.py
2. Build with dpkg-buildpackage -B

The generated package does contain the .so file.

**Comment by jpfr** [comment]
The .so is now in the libopen62541 package.
The libopen62541-dev package depends on that.

So other packages can use our library without having to install the headers.
