### ISSUE TITLE
Error building nodesetloader in Open62541 library version 1.4.0.

### ISSUE THREAD

**Issue by xydan83** [open62541/open62541#6401]
## Description
Hi!
I'm having trouble building the new Open62541 1.4.0 version along with nodesetloader. Please see the screenshot below.

![image](https://github.com/open62541/open62541/assets/86729310/c2ab7157-2e0f-4def-a1c8-7fe9b3ba465e)

I noticed the same errors in the git autobuild system.
![image](https://github.com/open62541/open62541/assets/86729310/fbcd2404-9fac-4b9b-8451-d8dd2a77f3d1)

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 1.4.0
 - [x] Operating system: Linux Ubuntu 22.04

**Comment by paddor** [comment]
+1

**Comment by matkonnerth** [comment]
here is the fix: https://github.com/open62541/open62541-nodeset-loader/pull/257

**Comment by keba-estr** [comment]
Is the update of the open62541-nodeset-loader done automatically on the open62541 1.4 (or rather 1.4.1 hotfix) branch or do we need a PR?

**Comment by matkonnerth** [comment]
PR is needed

**Comment by keba-estr** [comment]
@jpfr: Please start an update with dependabot[bot] (however this works)

**Comment by GoetzGoerisch** [comment]
Here you go: #6422

**Comment by matkonnerth** [comment]
Is this issue resolved?

**Comment by paddor** [comment]
I think it is

**Comment by keba-estr** [comment]
@jpfr: please close
