### ISSUE TITLE
Possible null pointer access in UA_parseEndpointUrl

### ISSUE THREAD

**Issue by keba-estr** [open62541/open62541#6435]
## Description
UA_parseEndpointUrl is called with outPort equal to NULL in src/pubsub/ua_pubsub_eventloop.c line 408, but outPort is not checked before access in src/ua_util.c line 145.

Or is there a special use case for ETH that inhibits the use of a port?

## Checklist

Please provide the following information:

 - [X] open62541 Version (release number or git tag): 1.4

**Comment by jpfr** [comment]
No, ETH cannot have a port. Ports are a TCP or UDP thing.
It appears that for ETH the parsing returns before accessing the outPort pointer.
https://github.com/open62541/open62541/blob/043af7d279778eceed82d83fc2737a04acaa2389/src/util/ua_util.c#L165
