### ISSUE TITLE
Increasing delay of UA_DateTime_Now() on embedded device 

### ISSUE THREAD

**Issue by llukic** [open62541/open62541#6439]
Due to gettimeofday() having some shortcomings, I suppose using clock_gettime() for UA_DateTime_Now().

"POSIX.1-2008 marks gettimeofday() as obsolete,
       recommending the use of [clock_gettime(2)](https://man7.org/linux/man-pages/man2/clock_gettime.2.html) instead."

"The time returned by gettimeofday() is affected by discontinuous
       jumps in the system time (e.g., if the system administrator
       manually changes the system time).  If you need a monotonically
       increasing clock, see [clock_gettime(2)](https://man7.org/linux/man-pages/man2/clock_gettime.2.html)."

 - [x] Operating system: embedded linux

**Comment by jpfr** [comment]
We also have UA_DateTime_nowMonotonic().
Why can't you use that?
