### ISSUE TITLE
somewhat inconsistent naming for data type APIs and other APIs

### ISSUE THREAD

**Issue by RolfKal** [open62541/open62541#6446]
While trying to use the library I had a bit of trouble understanding the various functions to construct, initialize, clean and delete the various data types. At the same time there seems to be some inconsistency.

My understanding so far is:

<type>_new() will allocate a new memory area for the type and initialize it to default values 
<type>_init() will initialize it to default values (e.g. NULL pointers and 0 numeric values)
<type>_clear() iteratively deallocates all the content of a variable but does not reinitialize the values
<type>_delete() will iteratively deallocate al the content of a variable and then the variable itself

Then there are some APIs such as UA_ServerConfig_clean() that seems to be a bit of a mix of the _clear() API and for some of the values contained therein also an _init() but not all of them.

The buildInfo, applicationDescription, mdnsConfig, mdnsInterfaceIP, and mdnsIpAddressList only seems to get cleared (deallocated) but not reinitialized to a NULL value.

The remaining members however all are reset to 0 after deallocating them.

On further investigation it seems that despite the documentation for UA_clear() claiming that it will not reinitialize the content of the variable to default values, it actually does a memset() to reset the contents all to 0. So all the <type>_clear() APIs/macros actually seem to do a full initialization after deleting the content.

So why would the  UA_ServerConfig_clean() be called _clean() instead of _clear() like other datatypes?
Shouldn't the remark for UA_clear() be changed to correctly indicate that it will actually reset the contents of the variable to 0?

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 1.4
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Windows, but not important
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
That is a good point.
Let's fix that on master. This can also be done with small macro definitions.
Initially we should keep the original API around and mark it as UA_DEPRECATED.
