### ISSUE TITLE
using malloc, free etc.

### ISSUE THREAD

**Issue by NetoLe** [open62541/open62541#645]
Hello! I liked your idea of mapping the Allocation-functions to system-specific functions.

But it seems that newest commits don't use this functionality. I saw at least 2 mallocs which are no UA_malloc in the latest commits. That broke my server, sure it is fast to fix, but I would recommend to stay with the original idea. As well I would say you should use them as well in the tcp_networklayer etc. because I'm sure that many people use this component as well (so for me).

best regards

**Comment by FlorianPalm** [comment]
The system depended funcitons were accidently introduced. I think @Stasik0 is fixing it atm.

**Comment by Stasik0** [comment]
@NetoLe is it this commit that you mean? https://github.com/open62541/open62541/commit/984342b057440a91fe7686ee1eea4c9d9cc4eb8a or are there some more mallocs that are used outside of the tests?

**Comment by NetoLe** [comment]
yes those are the ones I needed to fix. But I didn't watch the whole code to be honest.

**Comment by Stasik0** [comment]
i will change it back asap, happened by an accident as @FlorianPalm correctly noticed

**Comment by jpfr** [comment]
The changes in ua_types.h should be reverted.
The difference between `UA_STRING` and `UA_STRING_ALLOC` is precisely that `UA_STRING` does not allocate memory. And `UA_STRING_ALLOC` uses the internal malloc as @NetoLe requested.

@ichrispa Please use `UA_STRING_ALLOC` if you C++-compiler doesn't like the pointer magic.
