### ISSUE TITLE
Path not found in open62541Config.cmake

### ISSUE THREAD

**Issue by keba-estr** [open62541/open62541#6481]
## Description
Due to commit 6091b1865f87acf3285b45b06c38d740cab40cd5 the path usr/share/open62541/ua-nodeset is not available any more. Yet the cmake file open62541Config.cmake checks this path.
Therefore the compilation of this cmake file fails.

There are also additional references to this directory in open62541Macros.cmake.

## Checklist

Please provide the following information:

 - [X] open62541 Version (release number or git tag): 1.4.1
 - [X] Critical issue

**Comment by keba-estr** [comment]
Line in open62541Config.cmake:
set_and_check(UA_NODESET_DIR @PACKAGE_open62541_install_nodeset_dir@ CACHE PATH "Path to the directory that contains the OPC UA schema repository")

@jpfr: What is the correct solution? Should the check be deleted or should the path be replaced?

**Comment by jpfr** [comment]
You are right.
The reduced nodeset (used to build the library) is in usr/share/open62541/schema.

**Comment by keba-estr** [comment]
@jpfr Could you please create a pull request? I don't understand how '@PACKAGE_open62541_install_nodeset_dir@' is resolved or which would be the correct path variable here.

**Comment by keba-estr** [comment]
I will try out usr/share/open62541/schema in CMakeLists.txt to see if other errors occur.

**Comment by keba-estr** [comment]
For the compile option UA_NAMESPACE_ZERO = "FULL" the file ${UA_NODESET_DIR}/Schema/Opc.Ua.NodeSet2.xml is still referenced in CMakeLists.txt and open62541Macros.cmake, but not installed to the tools package any more.

**Comment by keba-estr** [comment]
Created PR #6483

**Comment by keba-estr** [comment]
Resolved with PR #6483
