### ISSUE TITLE
Errors compiling with Cygwin

### ISSUE THREAD

**Issue by cercata** [open62541/open62541#6511]
I don't know if you intend to support Cygwin, if not, just close this, and I'll try to find workarounds.

First I have a compilation error because SO_REUSEPORT is not defined.
I was able to continue compiling adding this line to CMakeLists.txt:
`add_definitions(-DSO_REUSEPORT=SO_REUSEADDR)`

Then when trying to compile eventloop_posix_udp.c, the type "struct ip_mreqn" is not available

**Comment by jpfr** [comment]
Yes, we want to support Cygwin.
I would #ifdef the offending code instead of working with compiler flags.
You can send a patch and/or suggest a way to include Cygwin in our CI pipeline.
