### ISSUE TITLE
enable generation of monitoreditems with somes "BADxxx"

### ISSUE THREAD

**Issue by StalderT** [open62541/open62541#657]
That would be great to enable generation of monitoreditems with some "BADxxx"

see https://github.com/open62541/open62541/commit/db0c995daa2e2e0847b127fff3ddf597110a9e06 comments

I suggest : 

UA_STATUSCODE_BADRESOURCEUNAVAILABLE 
UA_STATUSCODE_BADCOMMUNICATIONERROR
UA_STATUSCODE_BADWAITINGFORINITIALDATA

**Comment by Stasik0** [comment]
is there something in the standard?
@jpfr cannot we use some "own" statuscodes that do not colliede with ua ones?

**Comment by jpfr** [comment]
@Stasik0 We could indeed. But it will be really hard to ensure that nonstandard codes don't leak out to clients.

Here's the table from part 4. There are some reserved bits currently unused.
![statuscodes](https://cloud.githubusercontent.com/assets/1726411/16413145/63bacfee-3d30-11e6-93f6-c08b185af1e0.png)

**Comment by Stasik0** [comment]
Or just to rework the function to use a distinct return value.
