### ISSUE TITLE
UA_Client_readNodeClassAttribute_async() callback always return  BADINTERNALERROR

### ISSUE THREAD

**Issue by xcouzch** [open62541/open62541#6574]
Good Day,

Has anyone here tried to use UA_Client_readNodeClassAttribute_async() properly? When I use it, I always receive a BADINTERNALERROR. However, when I try other asynchronous read methods like UA_Client_readValueAttribute_async() and UA_Client_readDescriptionAttribute_async(), the callback status is good.

Note: I’ve tried to use the same nodeID on those three asynchronous methods, but only the nodeclass callback returns a BADINTERNALERROR.

**Comment by jpfr** [comment]
The fix comes via ##6605.
