### ISSUE TITLE
CMake: Configuration fails when requiring component FullNamespace

### ISSUE THREAD

**Issue by vkb** [open62541/open62541#6597]
## Description

I have an issue with the cmake configuration when buildung mit FullNamespace since _v1.4.1_ and still existing within _v1.4.2_:

When setting the define UA_NAMESPACE_ZERO to "FULL", the cmake command "find_package(open62541 REQUIRED COMPONENTS FullNamespace)" fails:

> -- UA_NAMESPACE_ZERO="FULL"
> CMake Error at CMakeLists.txt:23 (find_package):
>   Found package configuration file:
> 
>     /usr/local/lib/cmake/open62541/open62541Config.cmake
> 
>   but it set open62541_FOUND to FALSE so package "open62541" is considered to
>   be NOT FOUND.
> 
> 
> -- Configuring incomplete, errors occurred!

## Background Information / Reproduction Steps

The Installation of open62541 library on the system is done as follows:

> mkdir build && \\
> cd build/ && \\
> cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release \\
>                               -DBUILD_SHARED_LIBS=ON \\
>                               -DUA_NAMESPACE_ZERO=FULL \\
>                               -DUA_ENABLE_HISTORIZING=ON \\
>                               -DUA_ENABLE_SUBSCRIPTIONS_EVENTS=ON \\
>                               -S .. -B . && \\
> make -j4 && \\
> sudo make install

It can then be easily reproduced utilizing the examples folder of open62541:

> cd open62541/examples
> mkdir build
> cd build
> cmake -DUA_NAMESPACE_ZERO=FULL ..

The configuration then leads to the error shown above.

## Checklist

Please provide the following information:

 - [X] open62541 Version (release number or git tag): v1.4.2
 - [ ] Other OPC UA SDKs used (client or server): -/-
 - [X] Operating system: Ubuntu 22.04
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Remove the `COMPONENTS FullNamespace` part.
We no longer expose components via the CMake target.
