### ISSUE TITLE
pkg-config error

### ISSUE THREAD

**Issue by fantomsam** [open62541/open62541#6619]
## Description
The pkg-config give the following error:
```bash
Package m was not found in the pkg-config search path.
Perhaps you should add the directory containing `m.pc'
to the PKG_CONFIG_PATH environment variable
Package 'm', required by 'open62541', not found
Package 'rt', required by 'open62541', not found
```

I have notice this error, may related with the line: "Requires.private: m, rt" in the open62541.pc.in file. 
I don't know if anyone else have notice anything similar.

Please can y make a modification or guide me how to properly do compilation.

Thanks in advance.

## Background Information / Reproduction Steps

Used CMake options:

```bash
cmake -D BUILD_SHARED_LIBS=ON
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): d52ca9b
 - [ ] Other OPC UA SDKs used (client or server): 
 -  [x] Operating system: GNU
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
This should be solved with the new v1.4.3 release and on the master branch.
Please confirm.
