### ISSUE TITLE
[PubSub] Typo in setETHHeader(...) function causes nothing to be sent with the pubsub-eth-uadp profile

### ISSUE THREAD

**Issue by Bubeck-ISW** [open62541/open62541#6623]
## Description

when PubSub runs with eth-uadp profile, the network header is not set correctly due to a typo in the function “setETHHeader(...)” in “arch/eventloop_posix/eventloop_posix_eth.c”. This results in the frame not being sent with UA_sendto(), as the destination and source addresses are always the same. 

In [line 187](https://github.com/open62541/open62541/blob/master/arch/eventloop_posix/eventloop_posix_eth.c#L187) destAddr is used for both the destination and the source address part of the header.
```
memcpy(&buf[pos], destAddr, ETHER_ADDR_LEN);
```
have to be changed to
```
memcpy(&buf[pos], sourceAddr, ETHER_ADDR_LEN);
```
in order to set the header correctly.

## Background Information / Reproduction Steps

Used with the example "examples/pubsub/tutorial_pubsub_publish.c":
```
build/bin/examples/tutorial_pubsub_publish opc.eth://FF-FF-FF-FF-FF-FF eth0
```

Used CMake options:

```bash
cmake -DUA_ENABLE_PUBSUB=ON -DUA_ENABLE_MALLOC_SINGLETON=ON -DUA_NAMESPACE_ZERO=FULL -DUA_BUILD_EXAMPLES=ON ..
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): version: v1.4.3-507-g06e60e3ce / git commit: [06e60e3](https://github.com/open62541/open62541/tree/06e60e3ce76baaea97bc9e0f7b06cbe750980d27)
 - [x] Operating system: tested under Linux Debian 11 (Armv7) and Ubuntu 22.04.3 LTS (Intel i7-8550U, Win10-WSL)
 - [x] Critical issue: Yes

**Comment by jpfr** [comment]
Thanks. Fixed via #6624.
