### ISSUE TITLE
pthread and rt problem on Android

### ISSUE THREAD

**Issue by ffreality** [open62541/open62541#6663]
## Background Information / Reproduction Steps

As I mention on my encryption related problem,
https://github.com/open62541/open62541/issues/6657

I made these changes to build open62541 for Android with Android NDK toolchain.
1. commented out `-lpthread` and `-lrt` libraries on `CMakeLists.txt`
2. commented out `<bits/stdio_lim.h>` in `ua_securitypolicy_filestore.c` **(stdio already has this include)**
3. Add `set(ANDROID_PLATFORM 24)` to `CMakeLists.txt` 
Because `<ifaddrs.h>` (used by `freeifaddrs` and `getifaddrs`) and `epoll_create1` came with `NDK level 24`
4. set cross compile toolchain on cmake as `NDK 25.1.8937393 android.toolchain.cmake`
5. set platform type as Posix

I can build open62541, integrate it to Unreal Engine, package and run it.
But if I use same `UA_Client*` for two operations in different thread at the same time (for example read a node value and historical access. I use call historical access in another thread because I don't want to block main thread), I get `art_sigsegv_fault` crash like below.

![Screenshot (107)](https://github.com/user-attachments/assets/32528888-114e-4b62-9215-617aee20e752)

## Used CMake options:

```
USED NDK TOOLCHAIN = NDK 25.1.8937393 on Android Studio 2024.1.1 Patch 2 Koala on Ubuntu 24.04 LTS

-DUA_ENABLE_ENCRYPTION_TPM2:STRING="OFF" 
-DCMAKE_INSTALL_LIBEXECDIR:PATH="libexec" 
-DUA_ENABLE_DISCOVERY:BOOL="1" 
-DUA_LOGLEVEL:STRING="100" 
-DUA_ARCHITECTURE:STRING="posix" 
-DUA_NAMESPACE_ZERO:STRING="FULL" 
-DCMAKE_INSTALL_SYSCONFDIR:PATH="etc" 
-DUA_ENABLE_PUBSUB_MONITORING:BOOL="1" 
-DUA_AMALGAMATION_MULTIARCH:BOOL="1" 
-DCMAKE_INSTALL_INFODIR:PATH="" 
-DUA_ENABLE_PUBSUB_ENCRYPTION:BOOL="1" 
-DUA_ENABLE_PUBSUB:BOOL="1"
-DUA_ENABLE_AMALGAMATION:BOOL="1" 
-DUA_ENABLE_DISCOVERY_MULTICAST:BOOL="1" 
-DUA_MULTITHREADING:STRING="100" 
-DCMAKE_INSTALL_SHAREDSTATEDIR:PATH="com" 
-DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" 
-DCMAKE_INSTALL_BINDIR:PATH="bin" 
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): v1.4.4 release
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Development Platform = Ubuntu 24.04 LTS / Target Platform = Android
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by ffreality** [comment]
I have a temporary solution like this.

```
UA_ReadResponse ReadResponse;
UA_ReadResponse_init(&ReadResponse);
ReadResponse = UA_Client_Service_read(In_Client, ValueReadRequest);
		
if (!ReadResponse.results)
{
	return false;
}
```

**Comment by jpfr** [comment]
Please make this a separate issue each.
And wheee you have local fixes, PR are appreciated to speed things up.
