### ISSUE TITLE
Build PDF documentation for releases

### ISSUE THREAD

**Issue by jpfr** [open62541/open62541#667]
Sphinx is generating nice-looking PDFs with the doc_latex make target.

Here's a recent build:
http://www.pdf-archive.com/2016/07/06/open62541/

We should include PDF documentation with the release zips.
Who knows the internals of the release process? @Stasik0 ?

Adding the documentation to the webpage can be done manually once 0.2 is out.
Also, we should stop updating the html documentation on the homepage automatically after 0.2 happens.

**Comment by Stasik0** [comment]
docs are already only pushed on updates of 0.2 branch https://github.com/open62541/open62541/blob/0.2/.travis.yml#L96
is the pdf file already generated automatically?

**Comment by jpfr** [comment]
> is the pdf file already generated automatically?

No. But should be doable. apt-get texlive and a few lines of script.

**Comment by jpfr** [comment]
implemented on 0.2
