### ISSUE TITLE
Create SBOM file during release process

### ISSUE THREAD

**Issue by finger42** [open62541/open62541#6764]
## Description

I am using this Git repository as submodule in my project.
To get my specific released version I switch to an spcific Tag or Branch.

Then I like to generate my own "Top Level" SBOM file (cyclonedx format) which contains all
used components. For this I use the https://github.com/CycloneDX/cyclonedx-python-lib
in my own python script.

To do this I like to merge / integrate the SBOM file from open62541 which should contain the actual
version / Tag.

## Ideas:
- Using some Github Actions to generate SBOMs
- Put the SBOM to the released Branch
- Put it also to the Release tar/zip files
- Maybe this information is already there for the deb files?
- My favorite format would be cyclonedx but SPDX would also be great
  - Otherwise I could convert it on my side from SPDX to cyclonedx
- Maybe both formats are required in future for CRA or other laws?
- I am using the "Top Level" cyclonedx SBOM with depenceytrack ( https://dependencytrack.org/ )
  to monitor all of my components. For this it would also be really nice when the SBOM contains the right PURL

E.g.

`   
{
      "bom-ref": "BomRef.6894591892306213.20718498437121546",
      "cpe": "cpe:2.3:a:open62541:open62541:1.3.6:*:*:*:*:*:*:*",
      "licenses": [ {  "license": {  "id": "MPL-2.0" }} ],
      "name": "open62541",
      "purl": "pkg:generic/open62541@v1.3.6?download_url=https://github.com/open62541/open62541/archive/refs/tags/v1.3.6.tar.gz",
      "type": "library",
      "version": "v1.3.6"
    }
`

- CPE is important to match the version against the NIST database
- purl could be helpful for other databases like Github sec. , OSV (https://osv.dev/) and other commercial databases
- licenses could help to clarify the Open Source scanners, may be...

 
- Alternatives:
  - I could parse some config files / header files for the version
  - Adding some other files like simple version.txt file to this repo
  - Adding more config files like: https://github.com/ETLCPP/etl/blob/master/library.json 
  - Using Github Actions:
    https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/.github/workflows/auto-release.yml#L79
    and: 
    https://github.com/FreeRTOS/CI-CD-Github-Actions/tree/main/sbom-generator
    
It would be really great if this project contains and manage its own SBOM file !

**Comment by jpfr** [comment]
SBOM files are already made available with the Enterprise Services package.
https://www.open62541.org/doc/open62541_product_sheet_web.pdf
