### ISSUE TITLE
Memory leak from Array_decodeBinary()

### ISSUE THREAD

**Issue by electro-logic** [open62541/open62541#6790]
According to a memory snapshot comparison in Visual Studio there is a memory leak in the message processing routing

![callstack](https://github.com/user-attachments/assets/5350c68d-16df-4c84-a9fe-bae0b2047f5a)

Seems that the UA_calloc() highlighted is never released by the caller function. I'm using v1.4.6, can a library developer dig into this?

Update:
Seems that processMSGResponse()  is not calling UA_clear(response) in the cleanup and it's an user duty

**Comment by keba-estr** [comment]
It seems that the function processMSGResponse only clears the decoded buffer if the internal pointer &asyncResponse is used.
Can you check in your process dump if inside the function processMSGResponse the variable ac->syncResponse is set? If it is set, the owner of this buffer in the AsyncServiceCall is responsible for calling UA_clear.

**Comment by electro-logic** [comment]
Issue was in user calling code. Thanks for the support.
