### ISSUE TITLE
[API Design] Why UA_NodeId is always by value?

### ISSUE THREAD

**Issue by electro-logic** [open62541/open62541#6799]
I have a question about the API design of the library.

Almost all high level functions have a signature like this:

static UA_INLINE UA_StatusCode UA_Client_readValueAttribute(UA_Client *client, const UA_NodeId nodeId, UA_Variant *outValue) {
    return __UA_Client_readAttribute(client, &nodeId, UA_ATTRIBUTEID_VALUE, outValue, &UA_TYPES[UA_TYPES_VARIANT]);
}

where nodeId (24 bytes in memory) is almost always copied on the stack and then the address is passed to an inner function.

Why nodeId is not a reference value so that we can save memory and time?

**Comment by jpfr** [comment]
It allows to define the nodeids in place.
Eg using the UA_NODEID_NUMERIC macro.

**Comment by mlang-de** [comment]
UA_NODEID_NUMERIC also requires 24 bytes in stack.

**Comment by electro-logic** [comment]
Would be great to have an UA_Client_readValueAttribute overload with a nodeId by reference for embedded system that are trying to fit small microcontrollers

**Comment by mlang-de** [comment]
If then this needs to apply to the whole public api (Server and Client).

**Comment by electro-logic** [comment]
In C it's a bit tricky because overloads can't have the same signature and pointers are not taken into account, so it's not possible to have

```
void Func(int x);
void Func(int *x);
```

So a bigger API redesign is required to implement this proposal
