### ISSUE TITLE
[BUG, QUESTION ] NULL values

### ISSUE THREAD

**Issue by electro-logic** [open62541/open62541#6801]
When reading a value, how is possible to discriminate an EMPTY value from a NULL value?

Let' take as an example UA_ByteString. According to the specification https://reference.opcfoundation.org/Core/Part6/v104/docs/5.2.2.7 If the length of the byte string is −1 then the byte string is ‘null’.

But UA_BYTESTRING_NULL is defined as a zero length ByteString:

const UA_ByteString UA_BYTESTRING_NULL = {0, NULL};
https://github.com/open62541/open62541/blob/4562ed893841ee9dd85a76c939651a1c5151698c/src/ua_types.c#L38C7-L38C21

Note: UA_ByteString.length is defined as uint32 so storing -1 requires more changes.

Same apply to UA_String where we have:

The length in bytes is encoded as [Int32](https://reference.opcfoundation.org/search/25?t=Int32). A value of −1 is used to indicate a ‘null’ string. (https://reference.opcfoundation.org/Core/Part6/v104/docs/5.2.2.4)

But then

const UA_String UA_STRING_NULL = {0, NULL};

UA_Boolean UA_String_isEmpty(const UA_String *s) {
    return (s->length == 0 || s->data == NULL);
}
https://github.com/open62541/open62541/blob/4562ed893841ee9dd85a76c939651a1c5151698c/src/ua_types.c#L139

Other types may be affected by similar considerations.

**Comment by jpfr** [comment]
See the types.h.
Empty strings have a special sentinel pointer and also length zero.
