### ISSUE TITLE
Building Library with MinGW not working

### ISSUE THREAD

**Issue by Knuckleblade** [open62541/open62541#6804]
- [ ] open62541 Version (release number or git tag): 1.4.6

 - [ ] Operating system: Windows 10

![1](https://github.com/user-attachments/assets/1fd62b1c-7f1b-450c-baf8-4f22428e7ea0)
![2](https://github.com/user-attachments/assets/78dc9346-70ea-474e-97a2-fab64c21e9d8)
![3](https://github.com/user-attachments/assets/739c6914-4433-4057-87fd-4acd3641000e)

According to the screen shots above, building the library with MinGW does not seem to work despite what is written in the manual. Paths are defined, also the path to the compiler, yet the error occurs in CMake. I thereby surmise that either the implementation to build with MinGW is faulty, or not implemented at all.

**Comment by Knuckleblade** [comment]
@ccvca  Thank you for the advice. Can I assume that the correct compiler to build the library would be gcc.exe form MinGW? This sadly isnt specified in the manual. If so, then I apologize for opening an issue unrelated to open62541, and this issue can be considered as closed.

**Comment by ccvca** [comment]
Yes, `gcc.exe` is correct. but there are more settings to do. Maybe have a look here and try to compile with a minimal example: https://www.lotushints.com/2023/11/setting-up-cmake-with-mingw-on-windows/

CMake should find all the settings by it's own as soon as the right geneator ist selected.

**Comment by Knuckleblade** [comment]
Not an Issue of Open62541
