### ISSUE TITLE
Building of tools/ua-cli fails at linking stage when building for Windows with open62541 set to be build as shared library

### ISSUE THREAD

**Issue by RolfKal** [open62541/open62541#6824]
## Description

In Commit 0abb95b from October 29, custom logging was added to the tools/ua-cli/ua.c file. This depends on deps/mp_printf.c which is a non-exported function in the open62541 library. This produces a link error when compiling the library with tools under Windows, when open62541 is configured to compile as shared library.

Build error:
ua.obj : error LNK2019: unresolved external symbol _mp_vsnprintf referenced in function _UA_Client_Service_read

## Background Information / Reproduction Steps

Under Windows, an executable can't link to functions that are not explicitly exported from a shared library.  Following solutions are possible:
- ua-cli needs to separately link to mp_printf.obj from the library build tree
- the mp_vsnprintf() function needs to be exported from the library
- a different way of allowing to do UA_Logger functionality to stderr needs to be added to the existing stdout logger
- the custom logging to stderr is abandoned and instead the existing stdout logger is used
- disallow building of tools/ua-cli under Windows when building the library as shared library

Used CMake options:

BUILD_SHARED_LIBS = True
UA_BUILD_TOOLS = True

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): Commit f18fa90 in master
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Windows
 - [x] Compiler: MS Visual Studio 2015
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Fixed via #6842.
