### ISSUE TITLE
shared library probably not being generated despite activated option

### ISSUE THREAD

**Issue by Knuckleblade** [open62541/open62541#6828]
- [x] open62541 Version (release number or git tag): 1.4.6

 - [x] Operating system: Windows 10

Good evening everyone. I successfully built the Open62541 library with CMake. Sadly, there is an issue. According to the manual, there is an option to build a shared library:
![grafik](https://github.com/user-attachments/assets/16dd54a5-ee7b-4c89-8c21-42b4abaf0325)

i did exactly that:
![grafik](https://github.com/user-attachments/assets/11cd1b5b-cce0-4f75-8dea-ca467ca2dc2d)

sadly I cannot find the .dll or .so file in my build directory. Can someone tell me where the shared library file is normally generated? or is this a bug?

**Comment by RolfKal** [comment]
With latest master branch, CMake 3.29.3 UI, and Visual Studio 2017 I get the DLL and other build artefacts inside the <build>/bin directory. Did you run the Visual Studio project or what build toolchain are you using?

**Comment by Knuckleblade** [comment]
I m using MinGW. Interesting, sadly my /bin folder stays empty.

**Comment by Knuckleblade** [comment]
Resolved for now. I managed to build the library completely meanwhile, but still cannot find the shared library. But i suspect its my incompetence rather than a bug.
