### ISSUE TITLE
Unable to build a static library with 1.4.6

### ISSUE THREAD

**Issue by ernstblechaPT** [open62541/open62541#6829]
## Description
After upgrading from 1.3.4 to 1.4.6 I no longer get a static library ( `open62541.a`). All I can find is a dynamic library (`open62541.dll` and `open62541.dll.a`) in the `bin` directory of my build directory.

It looks like the following change has changed the build to be `SHARED` independent of the setting of `BUILD_SHARED_LIBS`: https://github.com/open62541/open62541/commit/dc0c061cb5a80436f985092df5e076b15a36b38b#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR1332

## Background Information / Reproduction Steps
Used CMake options:

```bash
cmake -DUA_ARCHITECTURE:STRING="win32" -DBUILD_SHARED_LIBS:BOOL="0" -DUA_ENABLE_AMALGAMATION:BOOL="1" -DUA_NAMESPACE_ZERO:STRING="FULL" 
```

## Checklist

Please provide the following information:

 - [X] open62541 Version (release number or git tag): 1.4.6
 - [X] Operating system: Windows 10

**Comment by jpfr** [comment]
Fixed via #6840.
