### ISSUE TITLE
Multiple .h files are not being generated by CMake when MinGW package is chosen as compiler

### ISSUE THREAD

**Issue by Knuckleblade** [open62541/open62541#6833]
- [ ] open62541 Version (release number or git tag): 1.4.6
 - [ ] Operating system: Windows 10

Very sorry for still bothering you, but I am starting to think that building with CMake with MinGW as compiler is not properly implemented in general. 

Finding the right compiler works. and files are generated in my output directory. I do have errors though, but since its just about missing version numbers, I assume its irrelevant:
![grafik](https://github.com/user-attachments/assets/bfa6e71b-4097-4e76-8acc-1ce61c3c4725)

Sadly though, i have multiple issues with Cmake +MinGW simply not generating a ton of .h files necessary for using this library! After trying to piece together multiple missing parts using scraps from the amalgamated .h file from version 1.3.6 (absolutly wrong, i know), I have to conclude that this is futile! Please fix/complete the implementation of  Cmake build with MinGW!

**Comment by jpfr** [comment]
The red error message is not a problem.
It just means that you are working not in a git clone (but probably downloaded the zip file with the source).
Then the git metadata cannot be used to detect the version number.
But that is not a problem.

The .h files get generated once you do the actual build.
But it looks good from the screenshot.

**Comment by Knuckleblade** [comment]
Yeah, I dont get any other errors. Interestingly, my build folder does contain a configuration.h file, but I shockingly found out now it  is the only .h file that was generated. Everything else is missing.  The shared library is also not being created even though i chose the option to do so.

**Comment by RolfKal** [comment]
I'm not familiar with the MinGW build tool chain, but are you simply pushing the Generate button and expecting the MinGW tool chain to be magically invoked? It may work like that in MinGW, but under Visual Studio you then have to start the actual project file and start the compilation yourself. I would suppose that under MinGW you may also have to invoke the actual make command (possibly on the command line) to get the whole generation magic started. The CMake GUI tool is most likely just generating the actual makefiles for your toolchain but not invoking your toolchain.
