### ISSUE TITLE
DataValue parsing incorrect when source picoseconds or server pico seconds present. 

### ISSUE THREAD

**Issue by prateekbansal** [open62541/open62541#686]
I tried to parse `DataValue` using this data:

```
// { 0x3F,
//                           0x01, 0x00, // Variant Value
//                           0x64, 0x00, 0x00, 0x00, // StatusCode = 100
//                           0x00, 0x64, 0xDF, 0x3E, 0x6E, 0xDB, 0x52, 0x06, // sourceTimestamp = 455667778865554432
//                           0xE0, 0x15, //  sourcePicoSeconds = 5600
//                           0x00, 0x64, 0x69, 0x9C, 0xE6, 0x20, 0xB6, 0x07, // serverTimestamp = 555667778865554432
//                           0xA8, 0x16 //  serverPicoSeconds = 5800
// }
```
However, the output that I get is:
```
  {"hasServerPicoseconds":true,"hasServerTimestamp":true
  ,"hasSourcePicoseconds":true,"hasSourceTimestamp":true,"hasStatus":true
  ,"hasValue":true,"serverPicoseconds":999
  ,"serverTimestamp":2370754230320371200,"sourcePicoseconds":999
  ,"sourceTimestamp":455667778865554432,"status":100,"value":false}
```

The `sourceTimeStamp` field is parsed correctly, but any field after and including sourcePicoSeconds is incorrect.

**Comment by Stasik0** [comment]
Hi, where does the binary data coming from?

**Comment by prateekbansal** [comment]
This data is from my unit test and could possibly be incorrect. I based my
unit tests off specification at
http://www.commsvr.com/UAModelDesigner/html/7f816c6d-3aa2-4f38-9992-16d892e6fe4a.htm#DataValue

**Comment by prateekbansal** [comment]
Part of the issue is fixed. However, there is one more issue: The value of `serverPicoseconds` and `sourcePicoseconds` is capped at 999. As per http://www.commsvr.com/UAModelDesigner/html/7f816c6d-3aa2-4f38-9992-16d892e6fe4a.htm#DataValue, the value could be max 9999.

As per latest run of the test, this is the output that I get:
```
{"hasServerPicoseconds":true,"hasServerTimestamp":true
  ,"hasSourcePicoseconds":true,"hasSourceTimestamp":true,"hasStatus":true
  ,"hasValue":true,"serverPicoseconds":999,"serverTimestamp":555667778865554432
  ,"sourcePicoseconds":999,"sourceTimestamp":455667778865554432,"status":100
  ,"value":false}
```

**Comment by prateekbansal** [comment]
Opened issue #692 to track this further.
