### ISSUE TITLE
[Feature] Add Check and LibXml2 to deps folder

### ISSUE THREAD

**Issue by electro-logic** [open62541/open62541#6870]
Check (https://github.com/libcheck/check) is used for unit testing.

LibXml2 (https://github.com/GNOME/libxml2) is used for nodesetloader.

Why not adding them to the deps folder when unit tests / nodesetloader are compiled?

Note: latest release of libxml2 is not compiling, I tried an old version (v2.9 from 2022) and seems fine.

**Comment by jpfr** [comment]
Both of these libraries are widely available in the package managers.
And we make to custom modifications to them.
So there is no need to internalize them.

**Comment by electro-logic** [comment]
The main issue is that installing the latest version is not working, adding the latest working version to the documentation may be enough.

**Comment by jpfr** [comment]
> The main issue is that installing the latest version is not working.

The installation is not working or we do not compile against that version?
The installation not working must be a more general problem.
Both libraries are very widely used.

**Comment by electro-logic** [comment]
Latest version of libxml2 is not compiling because sax.h is removed. Now they have sax2.
I had to rollback to v2.9 (2022) to compile.
