### ISSUE TITLE
[Bug] UA_CreateCertificate implementation missing in v1.4 when using Mbed TLS

### ISSUE THREAD

**Issue by electro-logic** [open62541/open62541#6874]
Implementation (create_certificate.c) is missing from the v1.4 branch, is this by design ?
I found the implementation in the master branch: https://github.com/open62541/open62541/blob/master/plugins/crypto/mbedtls/create_certificate.c

**Comment by jpfr** [comment]
Not by design. We just have not gotten around to doing it.
PR are welcome.

**Comment by electro-logic** [comment]
Thanks to let me know, maybe this is an useful info that can added to https://github.com/open62541/open62541/blob/master/FEATURES.md (ex. a new row "Create Certificate" under Encryption with a partial check mark)

**Comment by ccvca** [comment]
The current master has the code, looks like this was implemented after the 1.4 feature freeze.
https://github.com/open62541/open62541/pull/6145

It was originally missing, because mbedTLS did not support the required x509 fields in the past.

**Comment by jpfr** [comment]
Thanks @ccvca.
Closing this.

**Comment by GoetzGoerisch** [comment]
WIP #6882 

FYI @electro-logic

**Comment by electro-logic** [comment]
Thanks very much to backporting it to v1.4
