### ISSUE TITLE
DataValue source picoseconds or server pico seconds capped at 999. 

### ISSUE THREAD

**Issue by prateekbansal** [open62541/open62541#692]
Relates to: issue #686:

Part of the original issue is fixed. However, there is one more related issue: The value of serverPicoseconds and sourcePicoseconds is capped at 999. As per http://www.commsvr.com/UAModelDesigner/html/7f816c6d-3aa2-4f38-9992-16d892e6fe4a.htm#DataValue, the value could be max 9999.

As per latest run of the test, this is the output that I get:

{"hasServerPicoseconds":true,"hasServerTimestamp":true
  ,"hasSourcePicoseconds":true,"hasSourceTimestamp":true,"hasStatus":true
  ,"hasValue":true,"serverPicoseconds":999,"serverTimestamp":555667778865554432
  ,"sourcePicoseconds":999,"sourceTimestamp":455667778865554432,"status":100
  ,"value":false}

**Comment by jpfr** [comment]
One character.
The unbeatable record for the smallest bugfix.
