### ISSUE TITLE
[BUG] UA_Variant_isEmpty not checking UA_EMPTY_ARRAY_SENTINEL

### ISSUE THREAD

**Issue by electro-logic** [open62541/open62541#6923]
The following code is not correctly detecting an empty variant array of StatusCode

```
    UA_Variant var;    
    var.type = &UA_TYPES[UA_TYPES_STATUSCODE];
    var.storageType = UA_VARIANT_DATA;
    var.arrayLength = 0;
    var.data = UA_EMPTY_ARRAY_SENTINEL;   //0x01
    var.arrayDimensions = 0;
    var.arrayDimensionsSize = 0;
    bool isEmpty = UA_Variant_isEmpty(&var);
```

UaExpert is showing the node as an empty array of StatusCode.

Seems that UA_EMPTY_ARRAY_SENTINEL is not correctly checked.

https://github.com/open62541/open62541/blob/9968c1926374299f53fa22b83258cd9170eef1f5/include/open62541/types.h#L787

**Comment by Tassenpudding** [comment]
Afaik the UA_EMPTY_ARRAY_SENTINEL is used to represent an empty array.

A UA_Variant can hold an empty array.
The Variant itself is then not empty because it is holding an Array.
