### ISSUE TITLE
connection with a certificate

### ISSUE THREAD

**Issue by lesslefou** [open62541/open62541#6987]
## Description
I created a c++ project that write and read variables values to my PLC through the OPCUA communication. It work perfectly with no contraint for the connection. 

Npw I want to secure the connection using a certificate. I am new to this kind of things and quite lost. I did a lot of researches on this repository and on other forums but it did not help. 

Actually I try to compile the last release version (V1.4.8) with the following command in the build folder I created: 
`cmake --DUA_ENABLE_AMALGAMATION=ON --DUA_ENABLE_ENCRYPTION=ON ..`
or 
`cmake --DUA_ENABLE_AMALGAMATION=ON --DUA_ENABLE_ENCRYPTION=OPENSSL ..`

and then I did `make -sj12` and move the open62541.h .c file into my project.. 

I got a lot of error like these one 
```bash
/usr/bin/ld: open62541.c:(.text+0x56554): undefined reference to `mbedtls_pk_free'
/usr/bin/ld: open62541.c:(.text+0x565ca): undefined reference to `mbedtls_pk_free'
/usr/bin/ld: CMakeFiles/tool_opcua_link.dir/src/open62541.c.o: in function `mbedtls_hmac':
open62541.c:(.text+0x4e0e8): undefined reference to `mbedtls_md_hmac_finish'
/usr/bin/ld: CMakeFiles/tool_opcua_link.dir/src/open62541.c.o: in function `asym_decrypt_sp_basic128rsa15.cold':
open62541.c:(.text.unlikely+0x11): undefined reference to `mbedtls_rsa_set_padding'
/usr/bin/ld: CMakeFiles/tool_opcua_link.dir/src/open62541.c.o: in function `asym_encrypt_sp_basic128rsa15.cold':
open62541.c:(.text.unlikely+0x102): undefined reference to `mbedtls_rsa_set_padding'
/usr/bin/ld: CMakeFiles/tool_opcua_link.dir/src/open62541.c.o: in function `mbedtls_decrypt_rsaOaep.cold':
open62541.c:(.text.unlikely+0x1a0): undefined reference to `mbedtls_rsa_set_padding'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
```

I have check that the libmbedtls-dev was install. 
What did I do wrong ? 

In the mean time, I have some problems in understanding what I need to add do my code before the connect function in order to use this certificate. 

Thanks you for your help !

## Background Information / Reproduction Steps

Used CMake options:

```bash
`cmake --DUA_ENABLE_AMALGAMATION=ON --DUA_ENABLE_ENCRYPTION=ON ..`
```
or 

```bash
`cmake --DUA_ENABLE_AMALGAMATION=ON --DUA_ENABLE_ENCRYPTION=OPENSSL ..`
```

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag): V1.4.8
 - [ ] Other OPC UA SDKs used (client or server): client
 - [ ] Operating system: Linux
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
You still need to link against mbedtls.
Just installing it is not enough.
We have a lot of examples for how to use encryption.

reopen this if required.

**Comment by lesslefou** [comment]
I took the liberty of posting an “Issus” because, despite the example on the repository, I can't get my project to work or understand what I'm doing. 

When you speak about link the mbedtls library, what do you mean exactly , 

I try to add the following lines in my CMakeLists.txt but it is still not working
`
find_library(MBEDX509_LIBRARY mbedx509 REQUIRED)
find_library(MBEDCRYPTO_LIBRARY mbedcrypto REQUIRED)
find_library(MBEDTLS_LIBRARY mbedtls REQUIRED)
include_directories( /usr/include/mbedtls )
target_link_libraries(cm_opcua  ${MBEDX509_LIBRARY}  ${MBEDTLS_LIBRARY}  ${MBEDCRYPTO_LIBRARY})
`

everytime I uncomment the following lines

`
add_executable(test_opcua_link src/LinkOpcua.cpp src/open62541.c tests/test_linkOpcua.cpp )
ament_target_dependencies(test_opcua_link "rclcpp" "cm_base")
` I got the same probleme

**Comment by jpfr** [comment]
Lisa,

You need to link your test_opcua_link application against the mbedTLS
libraries.
Add target_link_libraries(test_opcua_link ...) to your CMake when you add
the new executable.

Regards, Julius

Am Do., 2. Jan. 2025 um 15:39 Uhr schrieb Lisa_Duterte <
***@***.***>:
