### ISSUE TITLE
UA_Server_addMethodNode is not working when the parent node has a string id

### ISSUE THREAD

**Issue by markusgraube** [open62541/open62541#715]
When you want to add a method node with `UA_Server_addMethodNode` below a parent node that has a string node id, the method node won't be created.

See also my minimal example under: https://github.com/markusgraube/open62541/blob/issue_add_method_string_id_parent/examples/server_method.c

The first call in line 86 does not work since it uses a string node id as parent.
The second call in line 94 works with a numeric node id for the parent.

**Comment by jpfr** [comment]
Is this separate from #717?

**Comment by markusgraube** [comment]
@jpfr Yes, it is.
#715 is about the c function in open62541
#717 is about the namespace compiler

**Comment by jpfr** [comment]
fixed in a4bead3

**Comment by markusgraube** [comment]
Perfect. Works for me.
@jpfr Thank you.
