### ISSUE TITLE
Problem with python-opcua library

### ISSUE THREAD

**Issue by destogl** [open62541/open62541#726]
Hi guys,

can one of you check FreeOpcUa/python-opcua#247. You will probably immediately see the error.

Thanks!

**Comment by Stasik0** [comment]
if(ci->messageSizeSoFar + offset > connection->remoteConf.maxMessageSize)
        ci->errorCode = UA_STATUSCODE_BADRESPONSETOOLARGE;
    if(++ci->chunksSoFar > connection->remoteConf.maxChunkCount && connection->remoteConf.maxChunkCount > 0)
ci->errorCode = UA_STATUSCODE_BADRESPONSETOOLARGE;

these are the only places where server drops this error

**Comment by Stasik0** [comment]
@destogl Shouldn't the client adjust its parameters to server's config?

**Comment by jpfr** [comment]
Fixed. maxChunkCount 0 -> accept any number of chunks
