### ISSUE TITLE
[Client] Browse / Search  nodes by theire types

### ISSUE THREAD

**Issue by maljac** [open62541/open62541#733]
Hello, 

this is not a bug but more a general question how to do this with open62541:

I have several hundred objects that are all in the same server and share the same (custom) object type. How can I find all objects that share the same object type? Think of a SQL query: `SELECT nodeid FROM root_node WHERE object_type = 'ns=foo;i=bar'`. Since they are not located under the same root node but distributed in sub- and sub-sub-nodes, I can not just choose the root nood and browse the node.

Is this supported by the standard spec or is it only possible when I create a reference manually (on node instanciation) between the object type and the object?

**Comment by jpfr** [comment]
OPC UA defines a `query` service for that purpose. open62541 has not implemented that service so far.

There is a TypeDefinitionOf/HasTypeDefinition reference pair between every object and its type. At least when you provide the type-nodeid during instantiation.

So you can just
- use the `browse` service to get a list of all instances of the object type
- do a second `browse` for the sub-nodes in the relevant folder
- take the intersection of the returned sets of nodeids

**Comment by jpfr** [comment]
Please reopen if the question is still unresolved.
