### ISSUE TITLE
[Question] about UA_ENABLE_MULTITHREADING

### ISSUE THREAD

**Issue by ilike28** [open62541/open62541#737]
I have 1 client and 1 server

When client read server node , server will get the data from the device.
It maybe cost 15 sec Sometime.
I can not read the other node because server doesn't have any response during that 15 sec.
Could UA_ENABLE_MULTITHREADING=ON fix this problem??

or could you please tell me which case must be use UA_ENABLE_MULTITHREADING=ON? 

(1)
client A ->   server -> device

(2)
client A <-   server <-after 15 sec- device

Thanks ^^.

**Comment by jpfr** [comment]
Please reopen if still relevant.
