### ISSUE TITLE
[build problem] source code v0.2 - sample code

### ISSUE THREAD

**Issue by ilike28** [open62541/open62541#742]
Hello~
I can not produce the sample code in the v0.2 sdk today download.

opcua@opcua-VirtualBox:~/bbb/open62541-0.2$ sudo cmake -DBUILD_EXAMPLECLIENT=On -DBUILD_EXAMPLESERVER=On -DUA_BUILD_EXAMPLE=On -DUA_ENABLE_SUBSCRIPTIONS=On
-- The C compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.11") 
-- Found Git: /usr/bin/git (found version "2.7.4") 
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
-- Git failed (not a repo, or no tags). Build will not contain git revision info.
-- Git version: commit id unknown
-- CMAKE_BUILD_TYPE not given; setting to 'Debug'
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_EXAMPLECLIENT
    BUILD_EXAMPLESERVER
    UA_BUILD_EXAMPLE

-- Build files have been written to: /home/opcua/bbb/open62541-0.2
opcua@opcua-VirtualBox:~/bbb/open62541-0.2$ sudo make
[  2%] Generating src_generated/ua_nodeids.h
[  5%] Generating src_generated/ua_types_generated.c, src_generated/ua_types_generated.h, src_generated/ua_types_generated_handling.h, src_generated/ua_types_generated_encoding_binary.h
[  8%] Generating src_generated/ua_transport_generated.c, src_generated/ua_transport_generated.h, src_generated/ua_transport_generated_handling.h, src_generated/ua_transport_generated_encoding_binary.h
Scanning dependencies of target open62541-object
[ 10%] Building C object CMakeFiles/open62541-object.dir/src/ua_types.c.o
[ 13%] Building C object CMakeFiles/open62541-object.dir/src/ua_types_encoding_binary.c.o
[ 16%] Building C object CMakeFiles/open62541-object.dir/src_generated/ua_types_generated.c.o
[ 18%] Building C object CMakeFiles/open62541-object.dir/src_generated/ua_transport_generated.c.o
[ 21%] Building C object CMakeFiles/open62541-object.dir/src/ua_connection.c.o
[ 24%] Building C object CMakeFiles/open62541-object.dir/src/ua_securechannel.c.o
[ 27%] Building C object CMakeFiles/open62541-object.dir/src/ua_session.c.o
[ 29%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_server.c.o
[ 32%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_server_binary.c.o
[ 35%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_nodes.c.o
[ 37%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_server_worker.c.o
[ 40%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_securechannel_manager.c.o
[ 43%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_session_manager.c.o
[ 45%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_services_discovery.c.o
[ 48%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_services_securechannel.c.o
[ 51%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_services_session.c.o
[ 54%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_services_attribute.c.o
[ 56%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_services_nodemanagement.c.o
[ 59%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_services_view.c.o
[ 62%] Building C object CMakeFiles/open62541-object.dir/src/client/ua_client.c.o
[ 64%] Building C object CMakeFiles/open62541-object.dir/src/client/ua_client_highlevel.c.o
[ 67%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_nodestore.c.o
[ 70%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_nodestore_concurrent.c.o
[ 72%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_services_call.c.o
[ 75%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_subscription.c.o
[ 78%] Building C object CMakeFiles/open62541-object.dir/src/server/ua_services_subscription.c.o
[ 81%] Building C object CMakeFiles/open62541-object.dir/src/client/ua_client_highlevel_subscriptions.c.o
[ 83%] Building C object CMakeFiles/open62541-object.dir/plugins/ua_network_tcp.c.o
[ 86%] Building C object CMakeFiles/open62541-object.dir/plugins/ua_clock.c.o
[ 89%] Building C object CMakeFiles/open62541-object.dir/plugins/ua_log_stdout.c.o
[ 91%] Building C object CMakeFiles/open62541-object.dir/plugins/ua_config_standard.c.o
[ 94%] Building C object CMakeFiles/open62541-object.dir/deps/libc_time.c.o
[ 97%] Building C object CMakeFiles/open62541-object.dir/deps/pcg_basic.c.o
[ 97%] Built target open62541-object
Scanning dependencies of target open62541
[100%] Linking C static library libopen62541.a
[100%] Built target open62541

**Comment by Stasik0** [comment]
the flags changed a bit, please use

-DUA_BUILD_EXAMPLES=ON
-DUA_BUILD_EXAMPLESERVER=On
-DUA_BUILD_EXAMPLECLIENT=On
