### ISSUE TITLE
Bug in UA_Server_addMethodNode?

### ISSUE THREAD

**Issue by cbelyaev** [open62541/open62541#755]
Consider the following piece of code in `server/ua_services_nodemanagement.c`: 

```
861:    UA_AddNodesItem_deleteMembers(&item);
862:    UA_MethodAttributes_deleteMembers(&attrCopy);
863:
864:    UA_RCU_LOCK();
865:    Service_AddNodes_existing(server, &adminSession, (UA_Node*)node, &item.parentNodeId.nodeId,
866: &item.referenceTypeId, &item.typeDefinition.nodeId, NULL, &result);

```
If `item.parentNodeId.nodeId` (copied from `parentNodeId`) has `identifierType == string`, then line 861 destroys this nodeId and in line 865 we have a invalid parent's nodeId.

Is this a bug or I missed something?

**Comment by FlorianPalm** [comment]
related to #715?
