### ISSUE TITLE
Reconnect client (Question)

### ISSUE THREAD

**Issue by SvenManier** [open62541/open62541#758]
What is the best way to reconnect a disconnected client? Do I really need to build a complete new client?

**Comment by Stasik0** [comment]
UA_Client_reset ?

**Comment by SvenManier** [comment]
Does this also reconnect or do I have to connect again before?

**Comment by Stasik0** [comment]
oh no, sorry i misunderstood you, probably there is no better way to
reconnect ATM :(

**Comment by SvenManier** [comment]
Too bad, thanks

**Comment by Stasik0** [comment]
there is an "API wishes" issue somewhere - so its a good place to write

**Comment by jpfr** [comment]
This should become easy once we have an event loop in the client (same as the server).
As @Stasik0 mentioned, this is post 0.2.

**Comment by HolgerJeromin** [comment]
API wishes are here: #710
