### ISSUE TITLE
Assigning minus sign to uint32_t variables breaks compilation in VS2013

### ISSUE THREAD

**Issue by xwaffelx** [open62541/open62541#776]
Hello.
I tried to compile the library in Visual Studio 2013 and got following error:
```error C4146: Einem vorzeichenlosen Typ wurde ein unärer Minus-Operator zugewiesen. Das Ergebnis ist weiterhin vorzeichenlos.``` on line 22373:
```
22372:  uint32_t rot = (uint32_t)(oldstate >> 59u);
22373:  return (xorshifted >> rot) | (xorshifted << ((-rot) & 31));
```
here ```rot``` is defined as uint32_t which triggers error, and on line 22402:
```
uint32_t threshold = -bound % bound;
```
here ```bound``` is a variable defined in the function signature as uint32_t.

Simple casting to int32_t in both cases did the trick and library compiled. Example server and client worked as expected after that. However, I'm not sure if it is a good fix.
I could create a PR if so.

**Comment by jpfr** [comment]
Hey @xwaffelx ,

this was fixed 2 months ago in the 0.2 branch.
https://github.com/open62541/open62541/blob/0.2/deps/pcg_basic.c#L39

You can use a nightly build of the single-file release as a drop-in replacement:
http://open62541.org/releases/
