### ISSUE TITLE
[Question] Serialization

### ISSUE THREAD

**Issue by SvenManier** [open62541/open62541#784]
Is there any way to serialize the data Im getting when I read a Node from the Server? I know there is a ua_copy function but it doesnt seem like to create a serializable structure which can be saved to a file.

**Comment by jpfr** [comment]
There is ua_encodeBinary.
https://github.com/open62541/open62541/blob/0.2/src/ua_types_encoding_binary.h

However, that is considered an internal function. So the API is not stable.

**Comment by SvenManier** [comment]
Thank you, Ill have a look at that
