### ISSUE TITLE
How to embed client in to a server for server to server architecture

### ISSUE THREAD

**Issue by tijo40** [open62541/open62541#797]

**Comment by FlorianPalm** [comment]
Depends on the specific use case. A simple case could be: create a method node on the server which creates an opc ua client (client api) to read a variblenode value etc. on another server.

**Comment by tijo40** [comment]
Hello FlorianPalm,

I have created 2 embedded servers. I was able to connect both servers through OPC UA expert method call.  It worked fine.

If each server runs on different applications, how can I connect both servers without using OPC UA expert

**Comment by tijo40** [comment]
Hello FlorianPalm, 

I was able to create embedded servers & client with QT threads. It is running perfectly.
