### ISSUE TITLE
Add features table to webpage

### ISSUE THREAD

**Issue by Pro** [open62541/open62541#810]
What is your opinion about adding a table on the main webpage listing all the supported and non-supported features of open62541?

Additionally it may include information about the supported service sets, server profiles, multithreading support, ...

Currently it's not that easy for beginners to see what is supported and what not.

**Comment by jpfr** [comment]
👍 

I can add a list of supported conformance units from the CTT.

We could take the list form node-opcua as the starting point:
https://github.com/node-opcua/node-opcua

**Comment by Pro** [comment]
Uh, nice! node-opcua has exactly what I meant.
So probably it's also best to include the table into the README.md or a separate markup file to keep it consistent with the corresponding branch/code-base. Then on the webpage we may just include this file from current main branch.

I'll create a PR for the first draft.

**Comment by Pro** [comment]
@jpfr I created the PR. You can directly push to my branch
