### ISSUE TITLE
Remove #define NULL from namespace compiler

### ISSUE THREAD

**Issue by Pro** [open62541/open62541#845]
@ichrispa  currently, the namespace compiler adds
`#define NULL ((void *)0)`

https://github.com/open62541/open62541/blob/0.2/tools/pyUANamespace/ua_namespace.py#L655

Is this really necessary?

It causes the compiler to throw warnings because NULL is already defined in string.h which is included in ua_config.h

**Comment by ichrispa** [comment]
hmmm... I vaguely remember adding it for a reason. There was a construct UA_NULL, which was then removed or replaced for NULL. After that, some Compiler did not want to run properly without having NULL defined.

What about just wrapping it in ifndef?

**Comment by ichrispa** [comment]
002cecd should fix the warnings for you @Pro.

**Comment by Pro** [comment]
@ichrispa i think it's better if it is after the `#include "open62541.h"`

So change
```
header.append('  #ifndef NULL')
header.append('    #define NULL ((void *)0)')
header.append('  #endif NULL')
header.append('  #include "open62541.h"')
```
to
```
header.append('  #include "open62541.h"')
header.append('  #ifndef NULL')
header.append('    #define NULL ((void *)0)')
header.append('  #endif NULL')
```

Otherwise this definition of NULL may collide with some other definitions in open62541.h and its included headers

**Comment by ichrispa** [comment]
Done :)
