### ISSUE TITLE
UaModeler variable :BadWaitingForInitialData?

### ISSUE THREAD

**Issue by xty19** [open62541/open62541#862]
i use xml to generate c code .
but when i use UaExpert to see the variables . 
none of them can be seen.
Statuscode : BadWaitingForInitialData
why
i just use the cmake command:
cmake -DCMAKE_BUILD_TYPE=Debug -DUA_ENABLE_METHODCALLS=On \
        -BUILD_EXAMPLECLIENT=On -BUILD_EXAMPLESERVER=On \
        -DUA_ENABLE_GENERATE_NAMESPACE0=On ../

**Comment by xty19** [comment]
@Pro 
@jpfr 
i dont know why?
because it can work just now just after i use the cmake command above.

**Comment by caspervanzoest** [comment]
Do you mean you are using XML to generate the nodes?
Have you tried those examples:
[https://github.com/open62541/open62541/blob/master/examples/server_nodeset.xml](https://github.com/open62541/open62541/blob/master/examples/server_nodeset.xml)
[https://github.com/open62541/open62541/blob/master/examples/server_nodeset.c](https://github.com/open62541/open62541/blob/master/examples/server_nodeset.c)

Let me know if you need a look at your code.

**Comment by xty19** [comment]
@caspervanzoest 
thanks i made it.
just because the TypeDefinition ,
i choose the **BaseVariableType** instead of **Property Type**  and solve the problem

**Comment by caspervanzoest** [comment]
Nice.

Could you do me a big favor, by helping me on issue [#864](https://github.com/open62541/open62541/issues/864)

Could you try the Prosys client on your server, and tell me if you are able to connect?

Thank you in advance!
