### ISSUE TITLE
ConnectionErrorApiReconnect

### ISSUE THREAD

**Issue by StalderT** [open62541/open62541#871]
Hello,

The latest commit  https://github.com/open62541/open62541/commit/23a6e70ce5832aac526bbe3b13c7454bb97c892f cause ConnectionErrorApiReconnect with UaExpert : 

![capture](https://cloud.githubusercontent.com/assets/13799456/19837078/80a5d002-9eb2-11e6-9fe0-c3a1c4a986c3.JPG)

**Comment by jpfr** [comment]
reverted until we have a solution
