### ISSUE TITLE
when will support the feature "SOAP-HTTP WS-SC UA Binary"

### ISSUE THREAD

**Issue by truthlz** [open62541/open62541#876]
I want to know when will the team support the feature "SOAP-HTTP WS-SC UA Binary" ?
thank you for your answer.

**Comment by jpfr** [comment]
It's not on the roadmap.
So unless somebody steps forward with a strong motivation, it will probably never happen.

Besides, there are not many advantages to using SOAP-HTTP over the binary protocol.

**Comment by truthlz** [comment]
ok, I know the situation. and thank you for your answer.
