### ISSUE TITLE
cant connect Siemens Server 

### ISSUE THREAD

**Issue by xty19** [open62541/open62541#879]
I connect Siemens 840D opc ua server.
it can be connected via UA expert ,but cant via my code.
question is:
1.the program stuck at   **client->connection = client->config.connectionFunc(UA_ConnectionConfig_standard, endpointUrl, client->config.logger);**
2. could you please tell me how print the logger? i cant print it, thank you.

ps:this mac is not good to use ,i cant use markdown ,so pardon me

**Comment by xty19** [comment]
<img width="1145" alt="2016-11-05 5 25 43" src="https://cloud.githubusercontent.com/assets/9359167/20029071/400d8722-a37d-11e6-8634-2a58f9dae003.png">

**Comment by xty19** [comment]
I can connect the siemens device ! :laughing: 
just change the UA_ClientCOnfig_standard !

`const UA_EXPORT UA_ClientConfig UA_ClientConfig_standard =
{
.timeout = 5000,
.secureChannelLifeTime = 600000,
.logger = Logger_Stdout,
.localConnectionConfig =
{
//original setting
/*.protocolVersion = 0,
.sendBufferSize = 65536,
.recvBufferSize = 65536,
.maxMessageSize = 65536,
.maxChunkCount = 1*/
- //changed

setting

.protocolVersion = 0,
.sendBufferSize = 16384,
.recvBufferSize = 16384,
.maxMessageSize = 65536,
.maxChunkCount = 0 },
.connectionFunc = UA_ClientConnectionTCP
};`

**Comment by Stasik0** [comment]
We need to handle it automatically. Could you give us a trace of errored connection?

**Comment by xty19** [comment]
@Stasik0  it is my pleasure to give you them info,but i am a green hand,i dont konw how to get the info ,such as the logger and the shark software, would you please tell me how to use them and i can provide you the info. :smiley:

**Comment by Stasik0** [comment]
Have a look in projects wiki

**Comment by xty19** [comment]
@Stasik0  i am from China, the network cant visit wiki,google,youtube ect.  website :sob:

**Comment by HolgerJeromin** [comment]
@xty19 Stasik did not wrote wikipedia but project wiki :-)
https://github.com/open62541/open62541/wiki/Capturing-traffic-with-Wireshark

**Comment by xty19** [comment]
@HolgerJeromin thanks , i will read the page now, and do some work
