### ISSUE TITLE
Subscription issue when request over 600 items.

### ISSUE THREAD

**Issue by JinGuoGe** [open62541/open62541#889]
1) subscription issue
I requested monitoring request over 600 items. But  get timeout response.
But success when request less 600 items. 
I am using only open62541.h/open62541.c source file for creating opc server and opc client.

2) multithread issue
When I enable multithreading  in open62541.h,  even mornitoring  request for one item doesn't work.
     #define UA_ENABLE_MULTITHREADING

**Comment by jpfr** [comment]
Hey @JinGuoGe ,

can you try with a recent nightly build from here?
http://open62541.org/releases/
Handling of repeated jobs improved quite a bit recently.

I will look into the multithreading issue.

If the issue persists, can you provide debug logging output so we can pinpoint the issue cause?
https://github.com/open62541/open62541/wiki/Writing-Good-Issue-Reports

Best regards,
Julius

**Comment by JinGuoGe** [comment]
Hi, Julius.
Thanks for your solution.
When I used updated version from releases, it works well. 
Really thanks. 
And If multithreading issue is solved, it will be great help.

Best regards.
GuoGe Jin

**Comment by TianDaGe** [comment]
Hi did you solve multithreading issue?

**Comment by jpfr** [comment]
I fixed an issue and multithreading now works for me.

However, we have no enough tests to declare multithreading "bug-free".
I just marked it as an experimental feature.
