### ISSUE TITLE
BADTYPEMISMATCH in UA_Server_writeAccessLevel()

### ISSUE THREAD

**Issue by jmrahm** [open62541/open62541#896]
Hey guys,

there is a type missmatch between your function definition in UA_Server_writeAccessLevel and the switch-case statement in CopyAttributeIntoNode().

In function UA_Server_writeAccessLevel you want a UA_UInt32 acessLevel, but in CopyAttributeIntoNode() you check for a BYTE type. 

Some code to compare....
` UA_Server_writeAccessLevel(UA_Server *server, const UA_NodeId nodeId, const UA_UInt32 accessLevel) {}`

From CopyAttributeIntoNode():
`case UA_ATTRIBUTEID_ACCESSLEVEL:
        CHECK_NODECLASS_WRITE(UA_NODECLASS_VARIABLE);
        CHECK_DATATYPE_SCALAR(BYTE);
        ((UA_VariableNode*)node)->accessLevel = *(const UA_Byte*)value;
        break;`

I would be glad if you fix it.

**Comment by jpfr** [comment]
done
