### ISSUE TITLE
Wrong coverage percentage reported

### ISSUE THREAD

**Issue by jpfr** [open62541/open62541#904]
Coveralls is currently reporting a ~28% test coverage.
That can't be. We were at ~75% some weeks ago.

Anybody with knowledge on coveralls that can triage the issue?

**Comment by Stasik0** [comment]
the problem started with this build https://travis-ci.org/open62541/open62541/jobs/176633572#L2856 while here https://travis-ci.org/open62541/open62541/jobs/175648912#L997 it was alrite. So the tests are never linked and never executed. Was the build environment updated? Check updated? Something else?

**Comment by jpfr** [comment]
fixed
