### ISSUE TITLE
Event support in the client

### ISSUE THREAD

**Issue by jpfr** [open62541/open62541#905]
As Requested here:
https://groups.google.com/forum/#!topic/open62541/sHGkoEMb-1M

See also the description of the solution approach in the mailing list disscussion.

This is up for grabs. Feel free to do something about a feature you are missing. 😄

**Comment by fmeerkoetter** [comment]
I am currently trying to pick up from where the google groups discussion stopped.

**Comment by Stasik0** [comment]
@jpfr what would be a nice roadmap for events? Maybe to get away from internal polling for subscriptions to an alternative triggerUpdate mechanism?

**Comment by fmeerkoetter** [comment]
My current status is that i have something that is somewhat working. My next step would be to clean it up and to create a WIP-MR so we can have a discussion about the patchset.

**Comment by Pro** [comment]
PR #1161

**Comment by Pro** [comment]
Added with #1161
