### ISSUE TITLE
[Question] about sending binary data between opcserver and opcclient.

### ISSUE THREAD

**Issue by JinGuoGe** [open62541/open62541#908]
Hi,
For example , I am going to send binary file content from opcclient to opcserver.
But there is not node type for binary data, so I can not create node for binary data.
How can I implement this other than encrypting file contents by base64?
Looking forward your solution.
Thanks.

**Comment by jpfr** [comment]
Just create a variable node that contains a ByteString value.
ByteStrings can hold any string and also null entries. Base64 is not needed.

If your file is really big. Say, hundreds of megabyte, there is a mechanism that exposes filesystem-like operations (open / seek / read / write / close / ...). But I guess you won't need that.

**Comment by JinGuoGe** [comment]
thanks for your solution.
