### ISSUE TITLE
Amalgamation: Cannot encode some unicode character

### ISSUE THREAD

**Issue by miraenator** [open62541/open62541#909]
Hi,

for both branches master and v0.2-rc2:

**compilation fails** in ''tools/amalgamate.py''

fails on (amalgamation of) file ''src/server/ua_server_worker.c''

with the following error:

```
 File "/open62541-0.2-rc2/tools/amalgamate.py", line 69, in <module>
    file.write(line)
UnicodeEncodeError: 'ascii' codec can't encode character '\xea' in position 8: ordinal not in range(128)
CMakeFiles/open62541-object.dir/build.make:109: recipe for target 'open62541.c' failed
make[2]: *** [open62541.c] Error 1
make[1]: *** [CMakeFiles/open62541-object.dir/all] Error 2
make: *** [all] Error 2
```
**Problem**: Comment (author name) in the ua_server_worker.c contains character that cannot be converted using ascii codec, utf-8 must be used.

***

**Solution**: specify output encoding (was ascii):
```
diff amalgamate_old.py amalgamate.py 
5a6
> import codecs
25c26
< file = io.open(args.outfile, 'w')
---
> file = codecs.open(args.outfile, 'w', 'utf-8')
```
***
**Environment**: Docker (FROM deb:jessie, x86_64)
```
FROM debian:jessie
RUN apt-get clean && apt-get update && apt-get install -y  --no-install-recommends \
	build-essential gcc cmake \
	python3 \
	liburcu-dev \
	wget ca-certificates

ENV RELEASE 0.2-rc2

RUN wget "https://github.com/open62541/open62541/archive/${RELEASE}.tar.gz" -O - | \
	tar zxC /

WORKDIR /open62541-${RELEASE}

RUN mkdir build && cd build && \
	cmake \
		-D UA_BUILD_EXAMPLES=ON \
		-D UA_ENABLE_AMALGAMATION=ON \
		-D UA_ENABLE_MULTITHREADING=ON \
```

**Comment by jpfr** [comment]
hey @miraenator,

I exchanged the utf8 character instead of adjusting the python script.

Lately, people have reported to use open62541 with ~10 year old compilers.
Using utf8 in code might bring up a few quite subtle bugs. So le't's stick to ascii in the first place.

Anyway, thanks for reporting this!
