### ISSUE TITLE
ubuntu 12.04LTS cant complie

### ISSUE THREAD

**Issue by xty19** [open62541/open62541#913]
OS ubuntu 12.04 LTS
OS type 64-bit
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
cmake version 3.3.2
i use command to compile `gcc -std=c99 open62541.c read_xml_xx2.c -o read_xml_xx2`

log `/tmp/ccAx2fYL.o:In function "UA_DateTime_nowMonotonic":`
log `(.text+0x39e5):undefined reference to "clock_gettime"`
log `collect2: ld returned 1 exit status``

and i cant compile simple server and client code.

**Comment by nikita158** [comment]
@xty19 
try add `-lrt` to gcc arguments

**Comment by xty19** [comment]
@nikita158 
thanks ,but it still has the problem 
:sob:

**Comment by jpfr** [comment]
Did you put `-lrt` after the .c files that need it?
http://stackoverflow.com/questions/2418157/ubuntu-linux-c-error-undefined-reference-to-clock-gettime-and-clock-settim

**Comment by xty19** [comment]
@jpfr  thanks it work  i put -lrt behind .c files  and it work!
