### ISSUE TITLE
UA_Server_addDataSourceVariableNode ignores access attributes

### ISSUE THREAD

**Issue by Wedmer** [open62541/open62541#929]
Hi.
Found that accessLevel, userAccessLevel, minimumSamplingInterval are not set for variable node created by UA_Server_addDataSourceVariableNode. 

To reproduce just compile server.c from examples and check "current time" node.

Can be easily fixed by using copyVariableNodeAttributes instead of copyCommonVariableAttributes.

**Comment by jpfr** [comment]
Thanks @Wedmer.
Fixed in commit ba009d1.
