### ISSUE TITLE
bug in ua_client_highlevel.c?

### ISSUE THREAD

**Issue by maaroo99** [open62541/open62541#930]
hi,
i am a newbie - I was playing with project, but find out that high level api __UA_Client_readAttribute was returning values only under some circumstances ?

Found this in  open62541/src/client/ua_client_highlevel.c

function __UA_Client_readAttribute 
```
 if(res->hasStatus != UA_STATUSCODE_GOOD)
     retval = res->hasStatus;
```

shouldn't it be this ?

```
     if(res->hasStatus == UA_TRUE)
         retval = res->status;
```

**Comment by jpfr** [comment]
Thanks for reporting.
Fixed.
