### ISSUE TITLE
Wrong use of pthread condition in server worker implementation

### ISSUE THREAD

**Issue by janitza-luwe** [open62541/open62541#949]
Description
===========
When starting the server in multithreading mode with more than 1 Thread, it happens that the server can not be killed, because only one worker thread is signaled.

Background Information / Reproduction Steps
===========================================
Reason is a wrong useage of pthread conditions. Currently each worker creates its own mutex to access the servers condition variable _server->dispatchQueue_condition_ (us_server_worker.c, workerLoop()). According to [PThread documentation](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_timedwait.html) this leads to a undefined effect:

> When a thread waits on a condition variable, having specified a particular mutex to either the pthread_cond_timedwait() or the pthread_cond_wait() operation, a dynamic binding is formed between that mutex and condition variable that remains in effect as long as at least one thread is blocked on the condition variable. **During this time, the effect of an attempt by any thread to wait on that condition variable using a different mutex is undefined.**

So for correct useage, all workers should use the same mutex to access the condition var.

Here is a patch for current master: [fix_pthread_condition_access.patch.txt](https://github.com/open62541/open62541/files/731899/fix_pthread_condition_access.patch.txt)

Checklist
=========

 - [ ] open62541 Version (release number or git tag): all versions (current master 94e9a6e)

**Comment by jpfr** [comment]
Applied and merged in 51d04c438bf30955140c1bbfa3dd7535a3f2c00b.
Much obliged for the patch.
