### ISSUE TITLE
Callback on registering server - minor change to do

### ISSUE THREAD

**Issue by XB32Z** [open62541/open62541#950]
Hi all!

I was using the registerServerCallback in an application. I was planing to use the isOnline of the object passed in the callback to detect if the server is being registered or deregistered and I noticed that it was always marked as connected. 

To overcome this I changed in process_RegisterServer (ua_services_discovery.c: 774 and 814) to `server->registerServerCallback(requestServer, server->registerServerCallbackData); ` which sends the actual server status rather than the last one saved. 
@Pro 

I hope I'm right, 
Thx for all your work

Checklist
=========
Please provide the following information:

 - [ feature_mdns] open62541 Version (release number or git tag):

**Comment by Pro** [comment]
Thanks!
Fixed https://github.com/open62541/open62541/commit/a76639c9d4cc91b51e3a425e878cd996cbea5ed1
