### ISSUE TITLE
How to generate server_static.

### ISSUE THREAD

**Issue by panhenry** [open62541/open62541#957]
Hi All,

 I download the 0.2 version to build the server. I can get server, server_datasource, server_method and   server_variable…

But I did not see the server_static. 
Do you know how to generate server_static?   I tried to modify CMakeList.txt but still cannot generate server_static. 

Thanks for your help,
Henry

**Comment by jpfr** [comment]
*static* is not a type if server but a way to compile servers that do not need an external library but have the entire SDK in the executable file.
In 0.2, all examples are compiled as static executables by default.
