### ISSUE TITLE
DataSourceCallback - UA_String

### ISSUE THREAD

**Issue by jrnh58** [open62541/open62541#958]
Hey guys,

i'm trying to use a DataSourceCallback for a UA_String variable.
The following Code is my readString and my writeString callback.
When i write a new string via UAExpert and read it again, the string shifts in memory after a incomprehensible number of readings (can be directly or changes after reading the string 10 times).

As you can see in "Pic1", changed the content of my string from "UNIT" to "CELCIUS". After reading this 3 times it changes to "en_US", which is the language tag for the description or the displayName of my Node.

What can be the issue in this connection?

![pic1 - kopie](https://cloud.githubusercontent.com/assets/25682556/22820725/52545c20-ef78-11e6-8625-492e3a4fd563.jpg)

```C
UA_StatusCode readString(void *handle, const UA_NodeId nodeid, UA_Boolean sourceTimeStamp,
	const UA_NumericRange *range, UA_DataValue *dataValue)
{	
	dataValue->hasValue = true;
	UA_Variant_setScalarCopy(&dataValue->value, (UA_String*)handle, &UA_TYPES[UA_TYPES_STRING]);
	UA_LOG_INFO(logger, UA_LOGCATEGORY_USERLAND, "Node read %i, read value is: %*s ",  nodeid.identifier.numeric, *(UA_String*)handle);
	return UA_STATUSCODE_GOOD;
}

UA_StatusCode writeString(void *handle, const UA_NodeId nodeid,
	const UA_Variant *data, const UA_NumericRange *range)
{
	if (UA_Variant_isScalar(data) && data->type == &UA_TYPES[UA_TYPES_STRING] && data->data) {
		*(UA_String*)handle = *(UA_String*)data->data;
	}
	UA_LOG_INFO(logger, UA_LOGCATEGORY_USERLAND, "Node written %i, written value is: %*s", nodeid.identifier.numeric, *(UA_String*)handle);
	return UA_STATUSCODE_GOOD;
}
```

**Comment by jpfr** [comment]
You need to copy the string in writeString.
The SDK cannot not know whether you use the variant in writeString.
So it is assumed that you do not modify it and we can free the value afterwards.
