### ISSUE TITLE
Documentation: Set DataType

### ISSUE THREAD

**Issue by Grimlex** [open62541/open62541#966]
Hey guys,

first of all I would like to apologize for my pretty stupid question. But I can't find anything in the documentation which helps me with my problem.

I'm using the latest release from http://open62541.org/.

I expected to get an INT32 variable from the following code:

```c
    /* Add a variable node */
    /* 1) Define the node attributes */
    UA_VariableAttributes attr;
    UA_VariableAttributes_init(&attr);
    attr.displayName = UA_LOCALIZEDTEXT("en_US", "the answer");
    UA_Int32 myInteger = 42;
    UA_Variant_setScalar(&attr.value, &myInteger, &UA_TYPES[UA_TYPES_INT32]);

    /* 2) Define where the node shall be added with which browsename */
    UA_NodeId newNodeId = UA_NODEID_STRING(1, "the.answer");
    UA_NodeId parentNodeId = UA_NODEID_NUMERIC(0, UA_NS0ID_OBJECTSFOLDER);
    UA_NodeId parentReferenceNodeId = UA_NODEID_NUMERIC(0, UA_NS0ID_ORGANIZES);
    UA_NodeId variableType = UA_NODEID_NULL; /* take the default variable type */
    UA_QualifiedName browseName = UA_QUALIFIEDNAME(1, "the answer");

    /* 3) Add the node */
    UA_Server_addVariableNode(server, newNodeId, parentNodeId, parentReferenceNodeId,
                              browseName, variableType, attr, NULL, NULL);
```

But somehow I get a BaseDataType instead of a Int32:
![image](https://cloud.githubusercontent.com/assets/25812672/23060754/6275f47e-f4ff-11e6-8cb4-cb87a246b4d1.png)

What am I doing wrong?

**Comment by jpfr** [comment]
Hello @Grimlex ,

the datatype is a constraint on the value.
BaseDataType allows you to put any type of value (including int32) in the variable.

To set the constraint, just set
```c
attr.dataType = UA_TYPES[UA_TYPES_INT32].typeId;
```
before add the node.
