### ISSUE TITLE
Can you help with generating bindings for Golang?

### ISSUE THREAD

**Issue by happierall** [open62541/open62541#967]
I have some discussion [this](https://github.com/xlab/c-for-go/issues/20#issuecomment-280549371) about it.

1. include file not found: stdbool.h
2. open62541.h:1654:5: undefined: __builtin_object_size
3. open62541.h:1654:5: undefined: __builtin___memset_chk

Can you help?

**Comment by jpfr** [comment]
The issue was fixed in the c-for-go project.

**Comment by gedw99** [comment]
@jpfr I know c for go reasonably well.
Can you point me to the code generation file that c for go uses ?

**Comment by jpfr** [comment]
No idea. I closed this issue since it was reported as solved in the c-for-go project.

**Comment by gedw99** [comment]
Thanks.

I found it in few minutes ago.
Will try to do a bringup and make a repo for it. Let me know if your
interested in adding it to your list of wrappers.

**Comment by rtmaster** [comment]
hi @gedw99 can you kindly share how you were able to convert to Golang the library? Thanks!

**Comment by gedw99** [comment]
I used this:

https://github.com/xlab/c-for-go

It's used for lots of similar requirements and the developer behind it is
very helpful.

I only did a quick test that it works.
I never had time to check the whole API.

I can probably help later.

**Comment by gedw99** [comment]
Am really sorry but i dont have it anymore. I did a quikc 5 minute test and
then stopped when i saw it work.

The guy that is behind the cForGO code is really awesome and i am sure he
will help you if you let him knwo the code.
Best thing is to put up a git hub repo and let me and him knwo and we can
all work on it together.

Is that ok ?
