### ISSUE TITLE
UA client can not link to UA server

### ISSUE THREAD

**Issue by ruikai** [open62541/open62541#987]
Description
===========
i use the order gcc -std=c99 my_server.c open62541.c -o test ;
and it generate test;
then  ./test;
and it is display the server is run ,and the Port number is 4840;
then i use the UAexpert to connect with it;
it shows could not connect to server:BadTimeout;

especially, i run it in the cortex-a8(linux) it is run ok;
but i run it in the cortex-a5,it shows the problem :Badtimeout

Background Information / Reproduction Steps
===========================================

See here for the kinds of information we need to reproduce the bug and how to obtain it:
https://github.com/open62541/open62541/wiki/Writing-Good-Issue-Reports

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version (release number or git tag):
 - [x] Other OPC UA SDKs used (client or server): 
 - [x] Operating system:
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
Hello @ruikai ,

can you enable logging and post the output? See the wiki page on writing good issue reports for details.

Furthermore, are you able to handshake with the TCP port at all? For example via telnet...

**Comment by ruikai** [comment]
![111](https://cloud.githubusercontent.com/assets/20692705/23887796/e54dc14c-08be-11e7-926e-8e097bb00e95.PNG)
Above is running server in cortex-a5,and it shows ok;
and then i use the UAexpert to connect with it;
and the output is below:
![222](https://cloud.githubusercontent.com/assets/20692705/23887890/7b36e9b8-08bf-11e7-9f34-babfc08584d5.PNG)
i do not know what is wrong whit it,and i run the server in PC and cortex-a8 is OK,and UAexpert connect is ok；
thank you;

**Comment by jpfr** [comment]
Hello @ruikai ,

I traced the steps in the code.
The error occurs because the `validTill` timestamp of the session is in the past.
That's funny, because the timestamp is set to `UA_DateTime_nowMonotonic() + session->timeout` when the session is created (right before the activation).

Can you have a look at your implementation of UA_DateTime_nowMonotonic?
Just add some additional log information to the important places.

**Comment by ruikai** [comment]
hello  @jpfr :

         thank you for you help,that is the problem,in the function UA_DateTime_nowMonotonic,there is a clock_gettime,when i Compile the project，i shoule add -lrt, and now ,it is works OK,Thanks very much；

**Comment by ruikai** [comment]
hello @jpfr:
          
           another question, i use the server_variable.c open62541.c and open62541.h,and compile them with       
gcc -std=c99 -lrt server_variable.c open62541.c -o test,and now it is run OK,and  i use UAexpert to connect with it,and the picture is like below:
![test](https://cloud.githubusercontent.com/assets/20692705/23980282/c5a53a9c-0a39-11e7-8490-3516fceeacd6.PNG)
it is ok,but the value always be 42,my question is I want to see dynamic data changes，how can i do with it,thanks

**Comment by jpfr** [comment]
Hello @ruikai ,

you already see dynamic data changes.
There is a variable /Objects/Server/ServerStatus/CurrentTime. If you add that to the data access view, you should see the changes.

Otherwise, you might have subscriptions disabled in the build settings.
