### ISSUE TITLE
plugins/ua_network_tcp incorrect test after select()

### ISSUE THREAD

**Issue by asthomas** [open62541/open62541#999]
Description
===========

In ServerNetworkLayerTCP_getJobs there is a call to select() with this code:

```
    UA_Int32 resultsize = select(highestfd+1, &fdset, NULL, &errset, &tmptv);
    if(resultsize < 0) {
        *jobs = NULL;
        return 0;
    }
```

The test for resultsize should be
```
   if(resultsize <= 0)
```
A zero return indicates that no FD is set.  Some implementations of select() do not modify fdset if they return a zero.

Checklist
=========
Please provide the following information:

 - [ ] open62541 Version (release number or git tag):  0.2
 - [ ] Operating system:  ThreadX

**Comment by jpfr** [comment]
Fixed. Thanks for reporting this.
